/* collectors/pivot/table/hp3_maritime.c -- batch 18: maritime
 *
 * Every row here names a machine-readable endpoint that was proof-of-life
 * verified before it was written: fetched over the wire by
 * collectors/verify_feeds.py, parsed in its declared mode, and confirmed to
 * yield at least one real record. Rows whose endpoint answered but produced
 * an empty result set were rejected rather than shipped -- a source that is
 * structurally guaranteed to emit nothing on every run is the exact failure
 * the no-fabrication rule exists to prevent.
 *
 * The observed shape and record count for each row are recorded in
 * docs/verified-sources-batch18.tsv; the candidates that failed are kept as
 * data in docs/rejected-sources-batch18.tsv rather than silently dropped.
 *
 * Generated by tools/gen_hp_batch.py from
 * docs/candidate-sources-batch18.maritime.txt. Edit the manifest, not this file.
 */
#include "lib/hpengine.h"

static const hp_source HP3_MARITIME[] = {
  { .id = "DIGITRAFFIC_TRAINS", .name = "Fintraffic — train composition and schedule",
    .name_ja = "フィンランド 列車編成",
    .category = "transport", .portal = "https://www.digitraffic.fi",
    .record_type = "train-schedule",
    .tags = "\"transport\",\"rail\",\"train\",\"finland\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://rata.digitraffic.fi/api/v1/trains/latest/1",
    .id_keys = "trainNumber",
    .interval = 21600,
    .title_keys = "trainType,commuterLineID",
    .description = "Train records with the operator, category, every timetable row "
      "with scheduled and actual times per station, cancellations and "
      "the cause codes for delay. Cause codes attribute a delay to "
      "infrastructure, rolling stock or operations" },

  { .id = "OVERPASS_PORT_INDUSTRIAL", .name = "Overpass - industrial port facilities",
    .name_ja = "Overpass 工業港湾施設",
    .category = "maritime", .portal = "https://overpass-api.de",
    .record_type = "port",
    .tags = "\"maritime\",\"port\",\"infrastructure\",\"geo\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://overpass-api.de/api/interpreter?data=%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3Bnwr%5B%22industrial%22%3D%22port%22%5D%2851.3%2C-0.5%2C51.7%2C0.3%29%3Bout%20center%20100%3B",
    .headers = { "User-Agent: JapanOSINT-research/1.0 (+https://github.com/)" },
    .array_path = "elements",
    .interval = 86400,
    .description = "Port and harbour facilities as mapped in OpenStreetMap with "
      "operator, berth structure and the industrial classification. "
      "Community mapping of port infrastructure covers terminals whose "
      "operators publish nothing" },

  { .id = "OVERPASS_HELIPAD", .name = "Overpass — helipads and helicopter landing sites",
    .name_ja = "Overpass ヘリポート",
    .category = "aviation", .portal = "https://overpass-api.de",
    .record_type = "helipad",
    .tags = "\"aviation\",\"helipad\",\"osm\",\"geo\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://overpass-api.de/api/interpreter?data=%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3Bnwr%5B%22aeroway%22%3D%22helipad%22%5D%2851.0%2C-1.0%2C52.0%2C0.5%29%3Bout%20center%20100%3B",
    .headers = { "User-Agent: JapanOSINT-research/1.0 (+https://github.com/)" },
    .array_path = "elements",
    .interval = 86400,
    .description = "Helicopter landing sites with operator and surface, including "
      "hospital, corporate, offshore and military pads. Helipads mark "
      "the points at which a site is reachable without a runway, which "
      "matters for remote or restricted facilities" },

  { .id = "OPENFLIGHTS_AIRLINES", .name = "OpenFlights — airline registry",
    .name_ja = "OpenFlights 航空会社一覧",
    .category = "aviation", .portal = "https://openflights.org",
    .record_type = "airline",
    .tags = "\"aviation\",\"airline\",\"operator\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://raw.githubusercontent.com/jpatokal/openflights/master/data/airlines.dat",
    .csv_no_header = 1,
    .id_keys = "col0",
    .interval = 21600,
    .title_keys = "col1",
    .description = "Airlines with IATA and ICAO codes, callsign, country and active "
      "status. The ICAO code and callsign are what link a radio "
      "transmission or a flight plan to a named operating company" },

  { .id = "NOAA_CO_OPS_WATERLEVEL", .name = "NOAA CO-OPS — observed water levels",
    .name_ja = "NOAA 実測潮位",
    .category = "maritime", .portal = "https://tidesandcurrents.noaa.gov",
    .record_type = "water-level",
    .tags = "\"ocean\",\"tides\",\"noaa\",\"observation\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?date=latest&station=8454000&product=water_level&datum=MLLW&units=metric&time_zone=gmt&format=json",
    .array_path = "data",
    .id_keys = "t",
    .interval = 21600,
    .title_keys = "t",
    .description = "Observed water level at a US tide station with the measurement "
      "time, quality flags and sigma. Water-level stations at ports are "
      "the ground truth behind a storm-surge or tsunami claim" },

  { .id = "NOAA_CO_OPS_CURRENTS", .name = "NOAA CO-OPS — tidal current predictions",
    .name_ja = "NOAA 潮流予測",
    .category = "maritime", .portal = "https://tidesandcurrents.noaa.gov",
    .record_type = "current-observation",
    .tags = "\"ocean\",\"currents\",\"noaa\",\"observation\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?date=latest&station=cb0102&product=currents_predictions&units=metric&time_zone=gmt&format=json",
    .array_path = "current_predictions.cp",
    .id_keys = "Time",
    .interval = 21600,
    .title_keys = "Time",
    .description = "Predicted tidal current speed and direction at monitored "
      "channels. Current strength in a narrow channel determines the "
      "transit window for deep-draught vessels, which constrains when a "
      "large ship can move" },

  { .id = "NOAA_NDBC_STATIONS", .name = "NOAA NDBC — ocean observation buoys",
    .name_ja = "NOAA 海洋観測ブイ",
    .category = "maritime", .portal = "https://www.ndbc.noaa.gov",
    .record_type = "ocean-buoy",
    .tags = "\"ocean\",\"buoy\",\"noaa\",\"observation\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations.json?type=currentpredictions",
    .array_path = "stations",
    .interval = 21600,
    .lat_key = "lat",
    .lon_key = "lng",
    .description = "The network of monitored current-prediction stations with "
      "coordinates and identifiers. A geolocated inventory of the "
      "marine observation infrastructure whose data underpins "
      "navigation warnings" },
};

HP_REGISTER_TABLE(HP3_MARITIME)
