/* collectors/pivot/table/hp3b21_foodhygiene.c -- batch 21: foodhygiene
 *
 * Every row here names a machine-readable endpoint that was proof-of-life
 * verified before it was written: fetched over the wire by
 * collectors/verify_feeds.py, parsed in its declared mode, and confirmed to
 * yield at least one real record. Rows whose endpoint answered but produced
 * an empty result set were rejected rather than shipped -- a source that is
 * structurally guaranteed to emit nothing on every run is the exact failure
 * the no-fabrication rule exists to prevent.
 *
 * The observed shape and record count for each row are recorded in
 * docs/verified-sources-batch21.tsv; the candidates that failed are kept as
 * data in docs/rejected-sources-batch21.tsv rather than silently dropped.
 *
 * Generated by tools/gen_hp_batch.py from
 * docs/candidate-sources-batch21.foodhygiene.txt. Edit the manifest, not this file.
 */
#include "lib/hpengine.h"

static const hp_source HP3B21_FOODHYGIENE[] = {
  { .id = "FSA_AUTHORITIES", .name = "FSA FHRS - local authorities",
    .name_ja = "英国食品衛生 自治体一覧",
    .category = "health", .portal = "https://ratings.food.gov.uk",
    .record_type = "regulator-record",
    .tags = "\"uk\",\"food-safety\",\"fhrs\",\"local-authority\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.ratings.food.gov.uk/Authorities",
    .headers = { "x-api-version: 2" },
    .array_path = "authorities",
    .id_keys = "LocalAuthorityId",
    .interval = 604800,
    .link_keys = "Url",
    .title_keys = "Name",
    .description = "Every UK local authority that runs the Food Hygiene Rating "
      "Scheme with its authority id and code the friendly name the "
      "region the scheme type the email address the web site and the "
      "URL of the authority's own data extract. This is the register of "
      "the 380-odd bodies that actually inspect food businesses in the "
      "United Kingdom and the id it returns keys the establishment "
      "queries below" },

  { .id = "FSA_AUTHORITIES_BASIC", .name = "FSA FHRS - local authority establishment counts",
    .name_ja = "英国食品衛生 自治体別件数",
    .category = "health", .portal = "https://ratings.food.gov.uk",
    .record_type = "regulator-record",
    .tags = "\"uk\",\"food-safety\",\"fhrs\",\"local-authority\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.ratings.food.gov.uk/Authorities/basic",
    .headers = { "x-api-version: 2" },
    .array_path = "authorities",
    .id_keys = "LocalAuthorityId",
    .interval = 604800,
    .title_keys = "Name",
    .description = "The same authority list reduced to id code name scheme type and "
      "the count of establishments each one currently holds. The "
      "establishment count is the denominator for every rate computed "
      "from this scheme and it moves when an authority stops inspecting "
      "- a falling count is a signal about the regulator rather than "
      "about the businesses" },

  { .id = "FSA_ESTABLISHMENT_BY_ADDRESS", .name = "FSA FHRS - establishments by address",
    .name_ja = "英国食品衛生 住所検索",
    .category = "health", .portal = "https://ratings.food.gov.uk",
    .record_type = "inspection-record",
    .tags = "\"uk\",\"food-safety\",\"fhrs\",\"inspection\",\"establishment\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.ratings.food.gov.uk/Establishments?address={q}&pageSize=100",
    .headers = { "x-api-version: 2" },
    .array_path = "establishments",
    .date_keys = "RatingDate",
    .id_keys = "FHRSID",
    .lat_key = "geocode.latitude",
    .lon_key = "geocode.longitude",
    .page_param = "pageNumber",
    .title_keys = "BusinessName",
    .description = "Every inspected food business whose address matches the search "
      "text with the trading name the business type the full postal "
      "address the geocoded coordinates the hygiene rating the date of "
      "the last inspection and the three component scores - hygiene "
      "standards structural compliance and confidence in management. "
      "The component scores are what a rating hides: a business can "
      "hold a 4 on the strength of two good scores while confidence in "
      "management is failing" },

  { .id = "FSA_ESTABLISHMENT_BY_AUTHORITY", .name = "FSA FHRS - establishments by local authority",
    .name_ja = "英国食品衛生 自治体別施設",
    .category = "health", .portal = "https://ratings.food.gov.uk",
    .record_type = "inspection-record",
    .tags = "\"uk\",\"food-safety\",\"fhrs\",\"inspection\",\"local-authority\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.ratings.food.gov.uk/Establishments?localAuthorityId={qd}&pageSize=100",
    .headers = { "x-api-version: 2" },
    .array_path = "establishments",
    .date_keys = "RatingDate",
    .id_keys = "FHRSID",
    .lat_key = "geocode.latitude",
    .lon_key = "geocode.longitude",
    .page_param = "pageNumber",
    .title_keys = "BusinessName",
    .description = "The complete inspected food estate of one local authority - "
      "every restaurant takeaway school kitchen care home caterer "
      "manufacturer and retailer it is responsible for with rating date "
      "and component scores. This is the enumeration that turns the "
      "scheme from a lookup into a corpus and it is the only way to ask "
      "what an entire council's food estate looks like" },

  { .id = "FSA_ESTABLISHMENT_BY_BUSINESS_TYPE", .name = "FSA FHRS - establishments by business type",
    .name_ja = "英国食品衛生 業種別施設",
    .category = "health", .portal = "https://ratings.food.gov.uk",
    .record_type = "inspection-record",
    .tags = "\"uk\",\"food-safety\",\"fhrs\",\"inspection\",\"sector\"",
    .mode = HP_JSON, .want = HP_NUMERIC, .free_tier = 1,
    .url = "https://api.ratings.food.gov.uk/Establishments?businessTypeId={qd}&pageSize=100",
    .headers = { "x-api-version: 2" },
    .array_path = "establishments",
    .date_keys = "RatingDate",
    .id_keys = "FHRSID",
    .lat_key = "geocode.latitude",
    .lon_key = "geocode.longitude",
    .page_param = "pageNumber",
    .title_keys = "BusinessName",
    .description = "Every inspected establishment of one business type nationwide - "
      "hospitals and care homes school and college caterers importers "
      "and exporters manufacturers mobile caterers and the rest. Asking "
      "the scheme by sector rather than by place is how a systemic "
      "failure in one kind of operation becomes visible" },

  { .id = "FSA_ESTABLISHMENT_ZERO_RATED", .name = "FSA FHRS - establishments rated zero",
    .name_ja = "英国食品衛生 評価0の施設",
    .category = "health", .portal = "https://ratings.food.gov.uk",
    .record_type = "inspection-record",
    .tags = "\"uk\",\"food-safety\",\"fhrs\",\"inspection\",\"noncompliance\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.ratings.food.gov.uk/Establishments?ratingKey=fhrs_0_en-gb&pageSize=100",
    .headers = { "x-api-version: 2" },
    .array_path = "establishments",
    .date_keys = "RatingDate",
    .id_keys = "FHRSID",
    .interval = 86400,
    .lat_key = "geocode.latitude",
    .lon_key = "geocode.longitude",
    .page_param = "pageNumber",
    .title_keys = "BusinessName",
    .description = "Every food business in England Wales and Northern Ireland "
      "currently holding a hygiene rating of zero - urgent improvement "
      "necessary - with its name address inspecting authority "
      "inspection date and component scores. A nationwide standing list "
      "of the worst-performing food premises in the country refreshed "
      "as ratings change" },

  { .id = "FSA_BUSINESS_TYPES", .name = "FSA FHRS - business type register",
    .name_ja = "英国食品衛生 業種コード表",
    .category = "health", .portal = "https://ratings.food.gov.uk",
    .record_type = "reference-record",
    .tags = "\"uk\",\"food-safety\",\"fhrs\",\"reference\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.ratings.food.gov.uk/BusinessTypes/basic",
    .headers = { "x-api-version: 2" },
    .array_path = "businessTypes",
    .id_keys = "BusinessTypeId",
    .interval = 2592000,
    .title_keys = "BusinessTypeName",
    .description = "The controlled list of business types the scheme classifies "
      "establishments under with the numeric id each one is queried by. "
      "This is the key set for the sector query above - without it that "
      "endpoint takes an integer nobody can guess" },

  { .id = "FSA_SCORE_DESCRIPTORS", .name = "FSA FHRS - score descriptor register",
    .name_ja = "英国食品衛生 スコア説明表",
    .category = "health", .portal = "https://ratings.food.gov.uk",
    .record_type = "reference-record",
    .tags = "\"uk\",\"food-safety\",\"fhrs\",\"reference\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.ratings.food.gov.uk/ScoreDescriptors",
    .headers = { "x-api-version: 2" },
    .array_path = "scoreDescriptors",
    .id_keys = "Id",
    .interval = 2592000,
    .title_keys = "Description",
    .description = "What each numeric component score actually means for each of the "
      "three inspection dimensions - hygiene structural and confidence "
      "in management - in the words the FSA uses. The establishment "
      "records carry raw integers and this is the only thing that turns "
      "a score of 20 in confidence-in-management into a finding rather "
      "than a number" },

  { .id = "FSA_REGIONS", .name = "FSA FHRS - region register",
    .name_ja = "英国食品衛生 地域区分表",
    .category = "health", .portal = "https://ratings.food.gov.uk",
    .record_type = "reference-record",
    .tags = "\"uk\",\"food-safety\",\"fhrs\",\"reference\",\"geography\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.ratings.food.gov.uk/Regions",
    .headers = { "x-api-version: 2" },
    .array_path = "regions",
    .id_keys = "id",
    .interval = 2592000,
    .title_keys = "name",
    .description = "The regions the scheme groups local authorities into with their "
      "codes. The join that lets authority-level and "
      "establishment-level results roll up to a comparable geography "
      "across the four UK nations which use two different rating "
      "schemes" },
};

HP_REGISTER_TABLE(HP3B21_FOODHYGIENE)
