/* collectors/pivot/table/hp3b32_jptelemetry.c -- batch 32: live Japanese traffic, power, transit and road telemetry
 *
 * Every row here names a machine-readable endpoint that was proof-of-life
 * verified before it was written: fetched over the wire by
 * collectors/verify_feeds.py, parsed in its declared mode, and confirmed to
 * yield at least one real record. Rows whose endpoint answered but produced
 * an empty result set were rejected rather than shipped -- a source that is
 * structurally guaranteed to emit nothing on every run is the exact failure
 * the no-fabrication rule exists to prevent.
 *
 * The observed shape and record count for each row are recorded in
 * docs/verified-sources-batch32.tsv; the candidates that failed are kept as
 * data in docs/rejected-sources-batch32.tsv rather than silently dropped.
 *
 * Generated by tools/gen_hp_batch.py from
 * docs/candidate-sources-batch32.jptelemetry.txt — scaffolded from it ONCE.
 * This file is the maintained copy from here on: repairs carry the live counts
 * that justify them, which the manifest has nowhere to put. Regenerating over
 * it reverts them, so the generator refuses to without --force. See CLAUDE.md,
 * "Batch tooling".
 */
#include "lib/hpengine.h"

static const hp_source HP3B32_JPTELEMETRY[] = {
  { .id = "JO32_TEL_JARTIC_LOOP_5MIN_EAST", .name = "MLIT permanent traffic counters, 5-minute volumes, eastern Japan "
      "(lon >= 137.5)",
    .name_ja = "国交省 常時観測交通量 5分間交通量 東日本（直近45分）",
    .category = "infrastructure", .portal = "https://www.jartic-open-traffic.org/",
    .record_type = "traffic-count",
    .tags = "\"japan\",\"traffic\",\"road\",\"telemetry\",\"mlit\",\"jartic\",\"5-minute\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.jartic-open-traffic.org/geoserver?service=WFS&version=2.0.0&request=GetFeature&typeNames=t_travospublic_measure_5m&srsName=EPSG:4326&outputFormat=application/json&exceptions=application/json&cql_filter=%E6%99%82%E9%96%93%E3%82%B3%E3%83%BC%E3%83%89%20%3E%3D%20dateFormat%28%27yyyyMMddHHmm%27%2C%20dateParse%28%27yyyyMMddHHmmZ%27%2C%20Concatenate%28dateFormat%28%27yyyyMMddHHmm%27%2C%20now%28%29%29%2C%20%27-0815%27%29%29%29%20AND%20BBOX%28%E3%82%B8%E3%82%AA%E3%83%A1%E3%83%88%E3%83%AA%2C137.5%2C20%2C154%2C46%2C%27EPSG%3A4326%27%29",
    .array_path = "features",
    .date_keys = "properties.時間コード",
    .id_keys = "properties.常時観測点コード+properties.時間コード",
    .interval = 600,
    .lat_key = "geometry.coordinates.0.1",
    .lon_key = "geometry.coordinates.0.0",
    .timeout_ms = 60000,
    .title_keys = "properties.常時観測点コード",
    .description = "WFS GeoJSON of the loop/ultrasonic permanent counters on "
      "national highways and expressways east of 137.5E (Hokkaido, "
      "Tohoku, Kanto, eastern Hokuriku/Chubu). Fetched 2026-09-30 13:04 "
      "JST: 3,876 features = 6 five-minute slices 12:20-12:45 x 646 "
      "counters, each with 地方整備局等番号, 常時観測点コード, 観測年月日, 時間帯, up/down "
      "small/large/unclassified vehicle counts and "
      "power/loop/ultrasonic/missing flags, MultiPoint lon/lat. The "
      "layer refuses a request without cql_filter and the gateway caps "
      "a response at 6 MB with no paging, so the filter is relative to "
      "the server clock: GeoServer now() is UTC, and re-parsing its "
      "yyyyMMddHHmm string with a -08:15 zone gives JST minus 45 "
      "minutes, i.e. each run asks for the last 45 minutes and needs no "
      "date token. Data lag about 20 min. 常時観測点コード+時間コード unique over "
      "all 3,876." },

  { .id = "JO32_TEL_JARTIC_LOOP_5MIN_WEST", .name = "MLIT permanent traffic counters, 5-minute volumes, western Japan "
      "(lon <= 137.5)",
    .name_ja = "国交省 常時観測交通量 5分間交通量 西日本（直近45分）",
    .category = "infrastructure", .portal = "https://www.jartic-open-traffic.org/",
    .record_type = "traffic-count",
    .tags = "\"japan\",\"traffic\",\"road\",\"telemetry\",\"mlit\",\"jartic\",\"5-minute\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.jartic-open-traffic.org/geoserver?service=WFS&version=2.0.0&request=GetFeature&typeNames=t_travospublic_measure_5m&srsName=EPSG:4326&outputFormat=application/json&exceptions=application/json&cql_filter=%E6%99%82%E9%96%93%E3%82%B3%E3%83%BC%E3%83%89%20%3E%3D%20dateFormat%28%27yyyyMMddHHmm%27%2C%20dateParse%28%27yyyyMMddHHmmZ%27%2C%20Concatenate%28dateFormat%28%27yyyyMMddHHmm%27%2C%20now%28%29%29%2C%20%27-0815%27%29%29%29%20AND%20BBOX%28%E3%82%B8%E3%82%AA%E3%83%A1%E3%83%88%E3%83%AA%2C122%2C20%2C137.5%2C46%2C%27EPSG%3A4326%27%29",
    .array_path = "features",
    .date_keys = "properties.時間コード",
    .id_keys = "properties.常時観測点コード+properties.時間コード",
    .interval = 600,
    .lat_key = "geometry.coordinates.0.1",
    .lon_key = "geometry.coordinates.0.0",
    .timeout_ms = 60000,
    .title_keys = "properties.常時観測点コード",
    .description = "Same layer west of 137.5E (western Hokuriku/Chubu, Kinki, "
      "Chugoku, Shikoku, Kyushu, Okinawa). Fetched 2026-09-30 13:04 "
      "JST: 2,250 features = 6 slices 12:20-12:45 x 375 counters (89 "
      "Kyushu 606, 86 Kinki 462, 88 Shikoku 396 ...), fields as the "
      "eastern row. The layer refuses a request without cql_filter and "
      "the gateway caps a response at 6 MB with no paging, so the "
      "filter is relative to the server clock: GeoServer now() is UTC, "
      "and re-parsing its yyyyMMddHHmm string with a -08:15 zone gives "
      "JST minus 45 minutes, i.e. each run asks for the last 45 minutes "
      "and needs no date token. 常時観測点コード+時間コード unique over all 2,250." },

  { .id = "JO32_TEL_JARTIC_CCTV_5MIN_EAST", .name = "MLIT CCTV image-recognition traffic counts, 5-minute, eastern "
      "Japan (lon >= 137.5)",
    .name_ja = "国交省 CCTV画像解析交通量 5分間 東日本（直近45分）",
    .category = "infrastructure", .portal = "https://www.jartic-open-traffic.org/",
    .record_type = "traffic-count",
    .tags = "\"japan\",\"traffic\",\"road\",\"telemetry\",\"mlit\",\"jartic\",\"cctv\",\"5-minute\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.jartic-open-traffic.org/geoserver?service=WFS&version=2.0.0&request=GetFeature&typeNames=t_travospublic_measure_5m_img&srsName=EPSG:4326&outputFormat=application/json&exceptions=application/json&cql_filter=%E6%99%82%E9%96%93%E3%82%B3%E3%83%BC%E3%83%89%20%3E%3D%20dateFormat%28%27yyyyMMddHHmm%27%2C%20dateParse%28%27yyyyMMddHHmmZ%27%2C%20Concatenate%28dateFormat%28%27yyyyMMddHHmm%27%2C%20now%28%29%29%2C%20%27-0815%27%29%29%29%20AND%20BBOX%28%E3%82%B8%E3%82%AA%E3%83%A1%E3%83%88%E3%83%AA%2C137.5%2C20%2C154%2C46%2C%27EPSG%3A4326%27%29",
    .array_path = "features",
    .date_keys = "properties.時間コード",
    .id_keys = "properties.常時観測点コード+properties.時間コード",
    .interval = 600,
    .lat_key = "geometry.coordinates.0.1",
    .lon_key = "geometry.coordinates.0.0",
    .timeout_ms = 60000,
    .title_keys = "properties.常時観測点コード",
    .description = "Traffic volumes measured by image recognition on MLIT road CCTV "
      "cameras east of 137.5E. Fetched 2026-09-30 13:04 JST: 1,955 "
      "features = 5 slices 12:20-12:40 x 391 cameras (81 Hokkaido 1,000 "
      "...), each with up/down total/small/large/unclassified counts "
      "and ten camera-health flags (preset position, weather-degraded "
      "image, low light, incident, server/decoding/analysis failures). "
      "The layer refuses a request without cql_filter and the gateway "
      "caps a response at 6 MB with no paging, so the filter is "
      "relative to the server clock: GeoServer now() is UTC, and "
      "re-parsing its yyyyMMddHHmm string with a -08:15 zone gives JST "
      "minus 45 minutes, i.e. each run asks for the last 45 minutes and "
      "needs no date token. This layer lags about 25 min. "
      "常時観測点コード+時間コード unique over all 1,955." },

  { .id = "JO32_TEL_JARTIC_CCTV_5MIN_WEST", .name = "MLIT CCTV image-recognition traffic counts, 5-minute, western "
      "Japan (lon <= 137.5)",
    .name_ja = "国交省 CCTV画像解析交通量 5分間 西日本（直近45分）",
    .category = "infrastructure", .portal = "https://www.jartic-open-traffic.org/",
    .record_type = "traffic-count",
    .tags = "\"japan\",\"traffic\",\"road\",\"telemetry\",\"mlit\",\"jartic\",\"cctv\",\"5-minute\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.jartic-open-traffic.org/geoserver?service=WFS&version=2.0.0&request=GetFeature&typeNames=t_travospublic_measure_5m_img&srsName=EPSG:4326&outputFormat=application/json&exceptions=application/json&cql_filter=%E6%99%82%E9%96%93%E3%82%B3%E3%83%BC%E3%83%89%20%3E%3D%20dateFormat%28%27yyyyMMddHHmm%27%2C%20dateParse%28%27yyyyMMddHHmmZ%27%2C%20Concatenate%28dateFormat%28%27yyyyMMddHHmm%27%2C%20now%28%29%29%2C%20%27-0815%27%29%29%29%20AND%20BBOX%28%E3%82%B8%E3%82%AA%E3%83%A1%E3%83%88%E3%83%AA%2C122%2C20%2C137.5%2C46%2C%27EPSG%3A4326%27%29",
    .array_path = "features",
    .date_keys = "properties.時間コード",
    .id_keys = "properties.常時観測点コード+properties.時間コード",
    .interval = 600,
    .lat_key = "geometry.coordinates.0.1",
    .lon_key = "geometry.coordinates.0.0",
    .timeout_ms = 60000,
    .title_keys = "properties.常時観測点コード",
    .description = "Same CCTV layer west of 137.5E. Fetched 2026-09-30 13:04 JST: "
      "2,965 features = 5 slices 12:20-12:40 x 593 cameras (89 Kyushu "
      "995, 86 Kinki 555, 87 Chugoku 410 ...), fields as the eastern "
      "row. The layer refuses a request without cql_filter and the "
      "gateway caps a response at 6 MB with no paging, so the filter is "
      "relative to the server clock: GeoServer now() is UTC, and "
      "re-parsing its yyyyMMddHHmm string with a -08:15 zone gives JST "
      "minus 45 minutes, i.e. each run asks for the last 45 minutes and "
      "needs no date token. 常時観測点コード+時間コード unique over all 2,965." },

  { .id = "JO32_TEL_JARTIC_LOOP_1H", .name = "MLIT permanent traffic counters, hourly volumes (rolling 4-hour "
      "window)",
    .name_ja = "国交省 常時観測交通量 1時間交通量（直近4時間）",
    .category = "infrastructure", .portal = "https://www.jartic-open-traffic.org/",
    .record_type = "traffic-count",
    .tags = "\"japan\",\"traffic\",\"road\",\"telemetry\",\"mlit\",\"jartic\",\"hourly\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.jartic-open-traffic.org/geoserver?service=WFS&version=2.0.0&request=GetFeature&typeNames=t_travospublic_measure_1h&srsName=EPSG:4326&outputFormat=application/json&exceptions=application/json&cql_filter=%E6%99%82%E9%96%93%E3%82%B3%E3%83%BC%E3%83%89%20%3E%3D%20dateFormat%28%27yyyyMMddHHmm%27%2C%20dateParse%28%27yyyyMMddHHmmZ%27%2C%20Concatenate%28dateFormat%28%27yyyyMMddHHmm%27%2C%20now%28%29%29%2C%20%27-0500%27%29%29%29",
    .array_path = "features",
    .date_keys = "properties.時間コード",
    .id_keys = "properties.常時観測点コード+properties.時間コード",
    .interval = 3600,
    .lat_key = "geometry.coordinates.0.1",
    .lon_key = "geometry.coordinates.0.0",
    .timeout_ms = 60000,
    .title_keys = "properties.常時観測点コード",
    .description = "Hourly aggregates of the permanent counters, all Japan in one "
      "request. Fetched 2026-09-30 13:04 JST: 2,141 features = hours "
      "10:00 (1,071 counters) and 11:00 (1,070) across all ten regional "
      "bureaus (82 Tohoku 493, 81 Hokkaido 446 ... 90 Okinawa 12), with "
      "up/down small/large counts and fault flags. The cql_filter keeps "
      "時間コード >= JST now minus 4 h, computed server-side from now() (UTC "
      "re-parsed with a -05:00 zone). An hour appears about 80 minutes "
      "after it starts. 常時観測点コード+時間コード unique over all 2,141." },

  { .id = "JO32_TEL_JARTIC_CCTV_1H", .name = "MLIT CCTV image-recognition traffic counts, hourly (rolling "
      "4-hour window)",
    .name_ja = "国交省 CCTV画像解析交通量 1時間交通量（直近4時間）",
    .category = "infrastructure", .portal = "https://www.jartic-open-traffic.org/",
    .record_type = "traffic-count",
    .tags = "\"japan\",\"traffic\",\"road\",\"telemetry\",\"mlit\",\"jartic\",\"cctv\",\"hourly\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.jartic-open-traffic.org/geoserver?service=WFS&version=2.0.0&request=GetFeature&typeNames=t_travospublic_measure_1h_img&srsName=EPSG:4326&outputFormat=application/json&exceptions=application/json&cql_filter=%E6%99%82%E9%96%93%E3%82%B3%E3%83%BC%E3%83%89%20%3E%3D%20dateFormat%28%27yyyyMMddHHmm%27%2C%20dateParse%28%27yyyyMMddHHmmZ%27%2C%20Concatenate%28dateFormat%28%27yyyyMMddHHmm%27%2C%20now%28%29%29%2C%20%27-0500%27%29%29%29",
    .array_path = "features",
    .date_keys = "properties.時間コード",
    .id_keys = "properties.常時観測点コード+properties.時間コード",
    .interval = 3600,
    .lat_key = "geometry.coordinates.0.1",
    .lon_key = "geometry.coordinates.0.0",
    .timeout_ms = 60000,
    .title_keys = "properties.常時観測点コード",
    .description = "Hourly CCTV-derived volumes, all Japan. Fetched 2026-09-30 13:04 "
      "JST: 1,968 features = 984 camera points x hours 10:00 and 11:00 "
      "(81 Hokkaido 400, 89 Kyushu 398, 86 Kinki 222 ...), each with "
      "up/down total/small/large/unclassified counts and a 5-minute-gap "
      "flag per direction. Same server-side 4-hour window as the "
      "loop-counter hourly row. 常時観測点コード+時間コード unique over all 1,968." },

  { .id = "JO32_TEL_DOCOMO_BIKESHARE_STATUS", .name = "DOCOMO Bike Share nationwide GBFS station status",
    .name_ja = "ドコモ・バイクシェア 全国 GBFS ステーション状況",
    .category = "transport", .portal = "https://ckan.odpt.org/dataset/c_bikeshare_gbfs-d-nationwide-bikeshare",
    .record_type = "bikeshare-station-status",
    .tags = "\"japan\",\"bikeshare\",\"gbfs\",\"docomo\",\"mobility\",\"telemetry\",\"odpt\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api-public.odpt.org/api/v4/gbfs/docomo-cycle/station_status.json",
    .array_path = "data.stations",
    .date_keys = "last_reported",
    .id_keys = "station_id+last_reported",
    .interval = 3600,
    .title_keys = "station_id",
    .description = "GBFS 2.3 station_status for the nationwide docomo-cycle system "
      "(ttl 60 s). Fetched 2026-09-30 12:37 JST: 6,139 stations with "
      "station_id, num_bikes_available, num_docks_available, "
      "is_installed/is_renting/is_returning and last_reported (epoch, "
      "one value for the whole snapshot). The tree reads this system's "
      "station_information (cycling_ports.c) but not its status. Keyed "
      "station_id+last_reported so each run stores a fresh availability "
      "snapshot; 6,139 distinct keys on the page." },

  { .id = "JO32_TEL_TOEI_BUS_POSITIONS", .name = "Toei Bus live vehicle positions (ODPT public API)",
    .name_ja = "都営バス 運行中バス位置（ODPT公開API）",
    .category = "transport", .portal = "https://ckan.odpt.org/",
    .record_type = "bus-position",
    .tags = "\"japan\",\"bus\",\"tokyo\",\"toei\",\"odpt\",\"realtime\",\"telemetry\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api-public.odpt.org/api/v4/odpt:Bus?odpt:operator=odpt.Operator:Toei",
    .date_keys = "odpt:fromBusstopPoleTime,dc:date",
    .id_keys = "owl:sameAs+odpt:fromBusstopPoleTime",
    .interval = 600,
    .title_keys = "odpt:note,owl:sameAs",
    .description = "Keyless ODPT public endpoint listing every Toei bus currently in "
      "service. Fetched 2026-09-30 12:39 JST: 490 buses on 115 routes, "
      "each with owl:sameAs (route.pattern.trip.vehicle), "
      "odpt:busNumber, odpt:busroute, odpt:note (route and destination "
      "text), from/to/starting/terminal bus-stop poles, "
      "odpt:fromBusstopPoleTime and dc:date. Keyed "
      "owl:sameAs+odpt:fromBusstopPoleTime so a record is one bus "
      "passing one stop; 490 distinct keys on the page. The upstream "
      "answers [] outside Toei service hours (measured 02:35 JST "
      "2026-10-02 for both the bus and train endpoints); that is an "
      "honest empty, not a dead endpoint." },

  { .id = "JO32_TEL_TOEI_TRAIN_POSITIONS", .name = "Toei Subway and Arakawa Line live train positions (ODPT public "
      "API)",
    .name_ja = "都営地下鉄・都電 列車走行位置（ODPT公開API）",
    .category = "transport", .portal = "https://ckan.odpt.org/",
    .record_type = "train-position",
    .tags = "\"japan\",\"rail\",\"subway\",\"tokyo\",\"toei\",\"odpt\",\"realtime\",\"telemetry\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api-public.odpt.org/api/v4/odpt:Train?odpt:operator=odpt.Operator:Toei",
    .date_keys = "dc:date",
    .id_keys = "owl:sameAs+dc:date",
    .interval = 900,
    .title_keys = "owl:sameAs",
    .description = "Keyless ODPT public endpoint of every Toei train in service. "
      "Fetched 2026-09-30 12:39 JST: 94 trains (Oedo 30, Arakawa 18, "
      "Mita 17, Asakusa 15, Shinjuku 14; 69 stopped at a station, 25 "
      "between stations) with odpt:trainNumber, trainType, "
      "railDirection, fromStation/toStation, origin/destination "
      "stations (incl. through-running to other operators), odpt:delay "
      "seconds and dc:date. Keyed owl:sameAs+dc:date, one position "
      "snapshot per train per run; 94 distinct. The upstream answers [] "
      "outside Toei service hours (measured 02:35 JST 2026-10-02 for "
      "both the bus and train endpoints); that is an honest empty, not "
      "a dead endpoint." },

  { .id = "JO32_TEL_TEPCO_DEMAND_5MIN", .name = "TEPCO Power Grid today's 5-minute demand and solar output",
    .name_ja = "東京電力パワーグリッド でんき予報 当日5分間隔実績",
    .category = "infrastructure", .portal = "https://www.tepco.co.jp/forecast/",
    .record_type = "power-demand",
    .tags = "\"japan\",\"electricity\",\"tepco\",\"grid\",\"demand\",\"solar\",\"telemetry\",\"5-minute\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.tepco.co.jp/forecast/html/images/juyo-d1-j.csv",
    .charset = "shift_jis",
    .csv_skip_lines = 54,
    .date_keys = "DATE",
    .id_keys = "DATE+TIME",
    .interval = 1800,
    .title_keys = "DATE+TIME",
    .description = "Static always-today でんき予報 CSV (cp932, updated every 5 min; "
      "2026/9/30 12:20 UPDATE when fetched). This row reads its last "
      "section, which starts on physical line 55: 288 rows DATE, TIME, "
      "当日実績(５分間隔値)(万kW), 太陽光発電実績(５分間隔値)(万kW), 太陽光発電量(電力使用量に対する割合)(%) "
      "for 00:00-23:55, 150 of them filled at fetch time and the rest "
      "empty placeholders the next runs fill in. The peak-supply "
      "summary and the 24-row hourly forecast/usage-rate/supply block "
      "above line 55 are NOT read by this row (the engine takes one "
      "header per CSV). DATE+TIME unique over 288 rows." },

  { .id = "JO32_TEL_CHUBU_GRID_ACTUAL_30MIN", .name = "Chubu Electric Power Grid area supply-demand actuals (30-minute, "
      "today)",
    .name_ja = "中部電力パワーグリッド 系統情報 エリア需給実績（当日30分値）",
    .category = "infrastructure", .portal = "https://powergrid.chuden.co.jp/denkiyoho/",
    .record_type = "power-supply-demand",
    .tags = "\"japan\",\"electricity\",\"chubu\",\"grid\",\"demand\",\"generation\",\"renewables\",\"telemetry\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://powergrid.chuden.co.jp/denki_yoho_content_data/keito_jisseki_cepco003.csv",
    .charset = "shift_jis",
    .csv_skip_lines = 2,
    .date_keys = "日付",
    .id_keys = "日付+時間コマ",
    .interval = 1800,
    .title_keys = "日付+時間帯_自",
    .description = "cp932 CSV rewritten through the day (file stamp 2026/09/30 "
      "12:27:17 when fetched). Two banner lines, then 48 half-hour rows "
      "日付, 時間コマ, 時間帯_自, 時間帯_至, エリア総需要量, エリア総発電量, エリア風力・太陽光発電量 in kWh; "
      "slot 24 (11:30-12:00) read 8,161,000 demand / 7,280,000 "
      "generation / 3,461,000 wind+solar, later slots empty until "
      "observed. 日付+時間コマ unique over 48." },

  { .id = "JO32_TEL_SHIKOKU_GRID_ACTUAL_30MIN", .name = "Shikoku Electric Power Transmission area supply-demand actuals "
      "(30-minute, today)",
    .name_ja = "四国電力送配電 エリア需給実績（当日30分値）",
    .category = "infrastructure", .portal = "https://www.yonden.co.jp/nw/denkiyoho/index.html",
    .record_type = "power-supply-demand",
    .tags = "\"japan\",\"electricity\",\"shikoku\",\"yonden\",\"grid\",\"demand\",\"generation\",\"renewables\",\"telemetry\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.yonden.co.jp/nw/denkiyoho/supply_demand/csv/jisseki_today.csv",
    .charset = "shift_jis",
    .csv_skip_lines = 2,
    .date_keys = "日付",
    .id_keys = "日付+時間コマ",
    .interval = 1800,
    .title_keys = "日付+時間帯_自",
    .description = "Static always-today cp932 CSV (stamp 20260930 12:14:37 when "
      "fetched): two banner lines, then 48 half-hour rows 日付, 時間コマ, "
      "時間帯_自/至, エリア総需要量, エリア総発電量, エリア風力・太陽光発電量 (kWh). Slot 24 "
      "(11:30-12:00) read 1,473,000 demand / 2,259,000 generation / "
      "1,160,000 wind+solar; unobserved slots are empty. 日付+時間コマ unique "
      "over 48. The registered yonden row is the juyo_08 demand file, a "
      "different dataset." },

  { .id = "JO32_TEL_CHUBU_AREA_DEMAND_2016_2019", .name = "Chubu Electric area hourly demand history FY2016-FY2018",
    .name_ja = "中部電力パワーグリッド エリア需要実績 1時間値（2016-2019）",
    .category = "infrastructure", .portal = "https://powergrid.chuden.co.jp/denkiyoho/",
    .record_type = "power-demand",
    .tags = "\"japan\",\"electricity\",\"chubu\",\"grid\",\"demand\",\"history\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://powergrid.chuden.co.jp/denki_yoho_content_data/areajuyo_current.csv",
    .charset = "shift_jis",
    .date_keys = "DATE",
    .id_keys = "DATE+TIME",
    .interval = 604800,
    .title_keys = "DATE+TIME",
    .description = "Despite its name this file is a frozen archive: 26,280 hourly "
      "rows DATE, TIME, 実績(万kW) from 2016/04/01 00:00 to 2019/03/31 "
      "23:00 (last row 1256 万kW), cp932, one header line. It is still "
      "served from the live でんき予報 data directory and nothing else in "
      "the tree carries this hourly history. DATE+TIME unique over all "
      "26,280 rows; weekly re-fetch only." },

  { .id = "JO32_TEL_JARTIC_ROAD_NOTICES", .name = "JARTIC road-traffic ticker notices (closures, night closures, "
      "regulations)",
    .name_ja = "日本道路交通情報センター テロップ 道路交通お知らせ",
    .category = "infrastructure", .portal = "https://www.jartic.or.jp/",
    .record_type = "road-notice",
    .tags = "\"japan\",\"road\",\"traffic\",\"closure\",\"jartic\",\"expressway\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.jartic.or.jp/d/telop/normal.json",
    .array_path = "records",
    .id_keys = "id",
    .interval = 3600,
    .link_keys = "link",
    .title_keys = "text",
    .description = "JSON feeding the jartic.or.jp ticker: 37 records when fetched "
      "2026-09-30, each id, text (e.g. 今治小松道 夜間通行止), operator link "
      "(NEXCO/MLIT pages), term [start, end] as YYYYMMDDHHMM and "
      "display order, plus a target map of which prefecture/area codes "
      "show which id. Mostly current and scheduled "
      "expressway/national-road closures; a few standing safety "
      "messages. id unique over 37." },

  { .id = "JO32_TEL_JARTIC_ROADWORK_TOPICS", .name = "JARTIC road-works and regulation topics",
    .name_ja = "日本道路交通情報センター トピックス（工事・規制）",
    .category = "infrastructure", .portal = "https://www.jartic.or.jp/",
    .record_type = "road-notice",
    .tags = "\"japan\",\"road\",\"roadworks\",\"jartic\",\"mlit\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.jartic.or.jp/d/telop/topics.json",
    .array_path = "records",
    .id_keys = "id",
    .interval = 3600,
    .link_keys = "link",
    .title_keys = "text",
    .description = "Second ticker list on jartic.or.jp: 25 records when fetched "
      "2026-09-30, each id, category, text (e.g. 国道21号 岐阜市 立体工事 車線規制 "
      "2026/10/5-10/24), link to the road administrator's page and term "
      "[start, end], with a per-area target map. Different ids from the "
      "notices row (road works and long-term regulations rather than "
      "closures). id unique over 25." },

  { .id = "JO32_TEL_NEXCO_EAST_TRAFFIC_RSS", .name = "NEXCO East (Drive Plaza) traffic notices RSS",
    .name_ja = "ドラぷら（NEXCO東日本）交通お知らせ RSS",
    .category = "infrastructure", .portal = "https://www.driveplaza.com/traffic/",
    .record_type = "road-notice",
    .tags = "\"japan\",\"road\",\"expressway\",\"nexco\",\"closure\",\"rss\"",
    .mode = HP_XML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.driveplaza.com/cms/news/traffic.xml",
    .array_path = "channel.item",
    .date_keys = "pubDate",
    .id_keys = "guid,link",
    .interval = 3600,
    .link_keys = "link",
    .title_keys = "title",
    .description = "RSS 2.0 of NEXCO East traffic notices: 100 items when fetched "
      "2026-09-30 (newest 2026-09-29 19:06, oldest 2025-08-04), each "
      "title, link (press page or emergency PDF), author and pubDate - "
      "night closures, ramp closures, emergency closures such as 常磐道 "
      "南相馬IC-相馬IC. guid unique over 100. Distinct from the registered "
      "e-nexco newly.xml (general news)." },

  { .id = "JO32_TEL_HANSHIN_EXPWY_CLOSURES", .name = "Hanshin Expressway closure and lane-restriction works notices",
    .name_ja = "阪神高速 通行止め・車線規制工事のお知らせ",
    .category = "infrastructure", .portal = "https://www.hanshin-exp.co.jp/drivers/",
    .record_type = "road-closure",
    .tags = "\"japan\",\"road\",\"expressway\",\"hanshin\",\"closure\",\"roadworks\",\"osaka\",\"kobe\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.hanshin-exp.co.jp/drivers/douro/include/driver_entry_list.json",
    .date_keys = "s,d_t",
    .id_keys = "id",
    .interval = 3600,
    .link_keys = "l",
    .title_keys = "t",
    .description = "JSON list behind hanshin-exp.co.jp/drivers (first of the two "
      "files named in driver_entry_json_list.json). Fetched 2026-09-30: "
      "50 notices posted 2025-03-10 to 2026-09-25, each id, posted date "
      "d_t, start s and end e (ISO), title t, route number r and name "
      "rn, place a (entrances/JCTs), work type w (e.g. 伸縮継手取替工事), "
      "restriction i (夜間通行止め 30, 終日通行止め 11, 車線規制 4 ...), human period p "
      "and PDF link l. id unique over 50." },

  { .id = "JO32_TEL_YAMANASHI_ROAD_REGULATIONS", .name = "Yamanashi Prefecture road regulation RSS (prefecture-managed "
      "national and prefectural roads)",
    .name_ja = "山梨県道路規制情報 RSS",
    .category = "infrastructure", .portal = "https://www.pref.yamanashi.jp/dourokisei/",
    .record_type = "road-closure",
    .tags = "\"japan\",\"road\",\"closure\",\"yamanashi\",\"prefecture\",\"rss\"",
    .mode = HP_XML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.pref.yamanashi.jp/dourokisei/kisei.xml",
    .array_path = "channel.item",
    .date_keys = "pubDate",
    .id_keys = "dk:kisei_id,link",
    .interval = 1800,
    .latlon_key = "dk:geo.dk:center",
    .link_keys = "link",
    .title_keys = "title",
    .description = "RSS 2.0 with a dk: namespace (lastBuildDate 2026-09-30 13:09 "
      "JST): 21 items - 10 規制中, 6 規制解除予定, 4 規制解除済み, 1 情報変更あり - each "
      "title (road class, route number and name), link "
      "kisei_info.php?id=, pubDate, dk:geo (center lat,lon, icon point, "
      "encoded polyline) and dk:detail (kisei_id, section start/end, "
      "length, 区分, 内容 e.g. 全面通行止, 原因 e.g. 雨量規制, start/end time, detour, "
      "administrator and office phone). kisei_id unique over 21, newest "
      "item 2026-09-30 10:30, oldest 2025-09-26." },

  { .id = "JO32_TEL_FUKUSHIMA_ROAD_WORKS_CLOSURES", .name = "Fukushima Prefecture road closures for construction works",
    .name_ja = "福島県道路通行規制情報（工事による規制）",
    .category = "infrastructure", .portal = "http://www.pref.fukushima.jp/douro/kisei/kisei-list.htm",
    .record_type = "road-closure",
    .tags = "\"japan\",\"road\",\"closure\",\"roadworks\",\"fukushima\",\"prefecture\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "http://www.pref.fukushima.jp/douro/kisei/json/listKOUJI.json",
    .date_keys = "kiseistartdate",
    .id_keys = "kanrinum",
    .interval = 3600,
    .title_keys = "rosenmei,sectionstart",
    .description = "JSON behind the prefecture's 通行規制一覧 page (kisei-list.js loads "
      "four lists). Fetched 2026-09-30: 25 works-related regulations on "
      "prefecture-managed national and prefectural roads, each kanrinum "
      "(management number), dorosyu (国/県), rosenmei, "
      "sectionstart/sectionend (place names), encho (km), kiseikbn "
      "(全面通行止, 大型通行止 ...), kiseiriyu, kiseistartdate/kiseienddate, the "
      "responsible civil-engineering office and phone, and remarks. "
      "kanrinum unique over 25." },

  { .id = "JO32_TEL_FUKUSHIMA_ROAD_DISASTER_CLOSURES", .name = "Fukushima Prefecture road closures caused by disasters",
    .name_ja = "福島県道路通行規制情報（災害による規制）",
    .category = "infrastructure", .portal = "http://www.pref.fukushima.jp/douro/kisei/kisei-list.htm",
    .record_type = "road-closure",
    .tags = "\"japan\",\"road\",\"closure\",\"disaster\",\"fukushima\",\"prefecture\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "http://www.pref.fukushima.jp/douro/kisei/json/listSAIGAI.json",
    .date_keys = "kiseistartdate",
    .id_keys = "kanrinum",
    .interval = 3600,
    .title_keys = "rosenmei,sectionstart",
    .description = "Second list from the same page: 14 disaster regulations "
      "(earthquake, landslide, flood damage) when fetched 2026-09-30, "
      "same fields as the works list - e.g. 22B0200048 浪江国見線 伊達崎橋 大型通行止 "
      "since 2022/04/02 地震のため, end 当分の間. kanrinum unique over 14 and "
      "disjoint from the works list." },

  { .id = "JO32_TEL_GIFU_ROAD_REGULATIONS", .name = "Gifu Prefecture road regulations (closures, alternating one-way, "
      "lane reductions)",
    .name_ja = "岐阜県 道路規制情報（規制一覧）",
    .category = "infrastructure", .portal = "https://douro.pref.gifu.lg.jp/",
    .record_type = "road-regulation",
    .tags = "\"japan\",\"road\",\"gifu\",\"prefecture\",\"closure\",\"roadworks\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://douro.pref.gifu.lg.jp/api/getRegulation",
    .array_path = "vals",
    .date_keys = "startDate",
    .id_keys = "id",
    .interval = 1800,
    .lat_key = "latitude",
    .lon_key = "longitude",
    .title_keys = "routeName,startPoint",
    .description = "JSON API behind douro.pref.gifu.lg.jp (岐阜県 道の情報), found in the "
      "site's _app.js (fetch of "
      "https://douro.pref.gifu.lg.jp/api/<name>), keyless GET, records "
      "under vals. Fetched 2026-09-30 13:15 JST: 748 current and "
      "scheduled regulations on prefecture-managed roads, each id, "
      "latitude/longitude, area, office, routeNo/routeName, "
      "startPoint/endPoint, distance (km), startDate/endDate "
      "(YYYYMMDDhhmm), content (片側交互通行 472, その他 108, 全面通行止 93, 車線減少 "
      "75), reason (工事 707, その他 37, 災害 4), direction, time windows, "
      "remarks and photo lists. id unique over 748 (regManageNo is not: "
      "744 distinct)." },

  { .id = "JO32_TEL_GIFU_ROAD_RAIN", .name = "Gifu Prefecture road rain gauges - live readings and closure "
      "status",
    .name_ja = "岐阜県 道路雨量計 現況（事前通行規制区間）",
    .category = "infrastructure", .portal = "https://douro.pref.gifu.lg.jp/",
    .record_type = "rain-gauge-reading",
    .tags = "\"japan\",\"road\",\"gifu\",\"prefecture\",\"rain\",\"telemetry\",\"road-weather\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://douro.pref.gifu.lg.jp/api/getRain",
    .array_path = "vals",
    .id_keys = "id",
    .interval = 900,
    .title_keys = "id",
    .description = "JSON API behind douro.pref.gifu.lg.jp (岐阜県 道の情報), found in the "
      "site's _app.js (fetch of "
      "https://douro.pref.gifu.lg.jp/api/<name>), keyless GET, records "
      "under vals. Fetched 2026-09-30 13:15 JST: 74 gauges that govern "
      "the prefecture's rainfall-triggered pre-emptive road closures, "
      "each id, status (降雨開始 at 2 gauges, blank otherwise), kind/icon, "
      "totalRain, 1hourRain, 2hourRain and closure flags (reg_flg, "
      "reg_dt). Station names, route sections, coordinates and "
      "alert/stop thresholds are in the gauge master row. id unique "
      "over 74, keyed on id so each run refreshes the current reading." },

  { .id = "JO32_TEL_GIFU_ROAD_FREEZE", .name = "Gifu Prefecture road-surface freeze sensors - live readings",
    .name_ja = "岐阜県 路面凍結センサー 現況",
    .category = "infrastructure", .portal = "https://douro.pref.gifu.lg.jp/",
    .record_type = "road-surface-reading",
    .tags = "\"japan\",\"road\",\"gifu\",\"prefecture\",\"road-weather\",\"freeze\",\"winter\",\"telemetry\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://douro.pref.gifu.lg.jp/api/getFreeze",
    .array_path = "vals",
    .date_keys = "ts",
    .id_keys = "id",
    .interval = 1800,
    .title_keys = "id",
    .description = "JSON API behind douro.pref.gifu.lg.jp (岐阜県 道の情報), found in the "
      "site's _app.js (fetch of "
      "https://douro.pref.gifu.lg.jp/api/<name>), keyless GET, records "
      "under vals. Fetched 2026-09-30 13:15 JST: 130 sensors, each id, "
      "ts (202609301300 for 120 of them), kind/icon, air temperature, "
      "road_temperature and a graph path. All readings were null at "
      "fetch time (the sensors report in the winter season), so today "
      "the rows carry station status only. Names, routes and "
      "coordinates are in the freeze-sensor master row. id unique over "
      "130." },

  { .id = "JO32_TEL_GIFU_ROAD_SNOW", .name = "Gifu Prefecture road snow gauges - live readings",
    .name_ja = "岐阜県 道路積雪計 現況",
    .category = "infrastructure", .portal = "https://douro.pref.gifu.lg.jp/",
    .record_type = "snow-gauge-reading",
    .tags = "\"japan\",\"road\",\"gifu\",\"prefecture\",\"snow\",\"winter\",\"telemetry\",\"road-weather\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://douro.pref.gifu.lg.jp/api/getSnow",
    .array_path = "vals",
    .date_keys = "ts",
    .id_keys = "id",
    .interval = 1800,
    .title_keys = "id",
    .description = "JSON API behind douro.pref.gifu.lg.jp (岐阜県 道の情報), found in the "
      "site's _app.js (fetch of "
      "https://douro.pref.gifu.lg.jp/api/<name>), keyless GET, records "
      "under vals. Fetched 2026-09-30 13:15 JST: 86 gauges, all stamped "
      "ts 202609301300, each id, kind/icon, snow (depth), fallsnow, "
      "temperature and a graph path. Values were null at fetch time "
      "(snow season has not started). 43 of the 86 ids appear in the "
      "snow-gauge master. id unique over 86." },

  { .id = "JO32_TEL_GIFU_UNDERPASS_FLOOD", .name = "Gifu Prefecture underpass flood sensors - live status and camera "
      "frames",
    .name_ja = "岐阜県 アンダーパス冠水情報 現況",
    .category = "infrastructure", .portal = "https://douro.pref.gifu.lg.jp/",
    .record_type = "underpass-flood-status",
    .tags = "\"japan\",\"road\",\"gifu\",\"prefecture\",\"flood\",\"underpass\",\"iot\",\"telemetry\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://douro.pref.gifu.lg.jp/api/getUnderpath",
    .array_path = "vals",
    .id_keys = "id",
    .interval = 900,
    .title_keys = "id",
    .description = "JSON API behind douro.pref.gifu.lg.jp (岐阜県 道の情報), found in the "
      "site's _app.js (fetch of "
      "https://douro.pref.gifu.lg.jp/api/<name>), keyless GET, records "
      "under vals. Fetched 2026-09-30 13:15 JST: 19 underpass "
      "monitoring points, each id, status (all 19 read 欠測 at fetch "
      "time), kind/icon, closure flags and one or two camera frames "
      "with ts (202609301310), caption (e.g. 北側/南側) and image path. "
      "Names, routes and the railway each underpass crosses are in the "
      "underpass master row. id unique over 19." },
};

HP_REGISTER_TABLE(HP3B32_JPTELEMETRY)
