/* collectors/pivot/table/hp3b19_iana.c -- batch 19: iana
 *
 * Every row here names a machine-readable endpoint that was proof-of-life
 * verified before it was written: fetched over the wire by
 * collectors/verify_feeds.py, parsed in its declared mode, and confirmed to
 * yield at least one real record. Rows whose endpoint answered but produced
 * an empty result set were rejected rather than shipped -- a source that is
 * structurally guaranteed to emit nothing on every run is the exact failure
 * the no-fabrication rule exists to prevent.
 *
 * The observed shape and record count for each row are recorded in
 * docs/verified-sources-batch19.tsv; the candidates that failed are kept as
 * data in docs/rejected-sources-batch19.tsv rather than silently dropped.
 *
 * Generated by tools/gen_hp_batch.py from
 * docs/candidate-sources-batch19.iana.txt. Edit the manifest, not this file.
 */
#include "lib/hpengine.h"

static const hp_source HP3B19_IANA[] = {
  { .id = "IANA_AS_NUMBERS", .name = "IANA — autonomous system number allocations",
    .name_ja = "IANA AS番号割当",
    .category = "infrastructure", .portal = "https://www.iana.org",
    .record_type = "asn-allocation",
    .tags = "\"iana\",\"bgp\",\"asn\",\"reference\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.iana.org/assignments/as-numbers/as-numbers-1.csv",
    .interval = 86400,
    .description = "The top-level allocation of AS number blocks to the regional "
      "internet registries, with the WHOIS and RDAP service for each "
      "and the allocation date. The first step in resolving any AS "
      "number to the registry that can describe it" },

  { .id = "IANA_IPV4_SPACE", .name = "IANA — IPv4 address space allocations",
    .name_ja = "IANA IPv4アドレス空間割当",
    .category = "infrastructure", .portal = "https://www.iana.org",
    .record_type = "address-allocation",
    .tags = "\"iana\",\"ip\",\"allocation\",\"reference\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.iana.org/assignments/ipv4-address-space/ipv4-address-space.csv",
    .interval = 86400,
    .description = "Every /8 of IPv4 space with its designation, the registry "
      "responsible, the allocation date and status. Identifies "
      "reserved, special-purpose and legacy blocks, which is how an "
      "address that should never appear in routing is recognised" },

  { .id = "IANA_MEDIA_TYPES", .name = "IANA — registered media types (application)",
    .name_ja = "IANA メディアタイプ登録",
    .category = "infrastructure", .portal = "https://www.iana.org",
    .record_type = "media-type",
    .tags = "\"iana\",\"protocol\",\"mime\",\"reference\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.iana.org/assignments/media-types/application.csv",
    .interval = 21600,
    .description = "Registered application media types with the registration "
      "template and the defining specification. The reference for "
      "deciding whether a Content-Type seen on the wire is standard, "
      "vendor-specific or fabricated" },

  { .id = "IANA_LANGUAGE_SUBTAGS", .name = "IANA — language subtag registry",
    .name_ja = "IANA 言語サブタグ登録",
    .category = "reference", .portal = "https://www.iana.org",
    .record_type = "language-subtag",
    .tags = "\"iana\",\"language\",\"locale\",\"reference\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry",
    .csv_no_header = 1,
    .interval = 86400,
    .description = "The authoritative registry of language, script, region and "
      "variant subtags with their descriptions, added dates and any "
      "deprecation. Needed to interpret the language tags that every "
      "multilingual source in this registry carries" },

  { .id = "MCC_MNC_TABLE", .name = "Mobile country and network code table",
    .name_ja = "MCC/MNC 対応表",
    .category = "telecom", .portal = "https://github.com",
    .record_type = "mobile-network-code",
    .tags = "\"telecom\",\"mobile\",\"mcc\",\"mnc\",\"sigint\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://raw.githubusercontent.com/musalbas/mcc-mnc-table/master/mcc-mnc-table.json",
    .interval = 21600,
    .title_keys = "network",
    .description = "Mobile Country Code and Mobile Network Code pairs mapped to the "
      "operator, country, ISO code and network name. An MCC/MNC pair is "
      "what a handset broadcasts and what appears in cell-site and "
      "roaming records, so this is the table that turns a raw network "
      "identifier into a named carrier in a named country" },

  { .id = "RIPE_DELEGATED_STATS", .name = "RIPE NCC — delegated resource statistics",
    .name_ja = "RIPE NCC 資源委譲統計",
    .category = "infrastructure", .portal = "https://www.ripe.net",
    .record_type = "resource-delegation",
    .tags = "\"rir\",\"ripe\",\"allocation\",\"bgp\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://ftp.ripe.net/pub/stats/ripencc/delegated-ripencc-latest",
    .csv_no_header = 1,
    .interval = 86400,
    .description = "Every IPv4 range, IPv6 range and AS number RIPE NCC has "
      "delegated, with the recipient country, the allocation date and "
      "the status. Published daily by the registry itself, this is the "
      "ground truth for which country an internet resource is "
      "registered to — and it covers Russia, Iran and Turkey" },
};

HP_REGISTER_TABLE(HP3B19_IANA)
