/* collectors/pivot/table/hp3b34_ndjson.c -- batch 34: newline-delimited-JSON feeds, reachable only since HP_NDJSON
 *
 * Every row here names a machine-readable endpoint that was proof-of-life
 * verified before it was written: fetched over the wire by
 * collectors/verify_feeds.py, parsed in its declared mode, and confirmed to
 * yield at least one real record. Rows whose endpoint answered but produced
 * an empty result set were rejected rather than shipped -- a source that is
 * structurally guaranteed to emit nothing on every run is the exact failure
 * the no-fabrication rule exists to prevent.
 *
 * The observed shape and record count for each row are recorded in
 * docs/verified-sources-batch34.tsv; the candidates that failed are kept as
 * data in docs/rejected-sources-batch34.tsv rather than silently dropped.
 *
 * Generated by tools/gen_hp_batch.py from
 * docs/candidate-sources-batch34.ndjson.txt — scaffolded from it ONCE.
 * This file is the maintained copy from here on: repairs carry the live counts
 * that justify them, which the manifest has nowhere to put. Regenerating over
 * it reverts them, so the generator refuses to without --force. See CLAUDE.md,
 * "Batch tooling".
 */
#include "lib/hpengine.h"

static const hp_source HP3B34_NDJSON[] = {
  { .id = "GO_MODULE_INDEX", .name = "Go module index — the global module publish stream",
    .category = "cyber", .portal = "https://index.golang.org",
    .record_type = "go-module-version",
    .tags = "\"supplychain\",\"package-registry\",\"go\",\"golang\",\"release-feed\",\"firehose\"",
    .mode = HP_NDJSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://index.golang.org/index?since={ago:7200}&limit=2000",
    .array_path = ".",
    .date_keys = "Timestamp",
    .id_keys = "Path+Version",
    .interval = 3600,
    .next_path = "$last.Timestamp",
    .next_tmpl = "https://index.golang.org/index?since={v}&limit=2000",
    .page_max = 20,
    .title_keys = "Path",
    .description = "Every module version ever published to the Go module ecosystem, "
      "in publication order: Path, Version and Timestamp, 2,000 per "
      "page from 2019-04-10 onward. This is the only complete, "
      "authoritative record of what has been published to Go — there is "
      "no search API that answers it — and because it is ordered by "
      "publication it is the feed a newly registered typosquat, a "
      "resurrected abandoned module path, or a burst of releases from "
      "one account appears in. Paged by a `since` cursor taken from the "
      "LAST record of each page, which is why it needs "
      "next_path=$last.Timestamp, and ANCHORED with since={ago:7200} "
      "because the index is append-only from 2019-04-10 with no reverse "
      "order and no `latest`: without the anchor the row walks forward "
      "from 2019 on every run, emits 40,000 records an hour and never "
      "reaches today. The cursor is INCLUSIVE — page N's last record is "
      "byte-identical to page N+1's first, verified live — so one "
      "record per page boundary collapses at the sink, which is correct "
      "dedupe of a genuine repeat." },
};

HP_REGISTER_TABLE(HP3B34_NDJSON)
