/* collectors/pivot/table/hp3b35_strings.c -- batch 35: endpoints whose records are bare JSON strings
 *
 * WHY THIS TABLE EXISTS — it is a correction, and the correction is the point.
 *
 * docs/rejected-sources-batch34.tsv ruled all four of these endpoints out on
 * the reasoning that an array of bare JSON STRINGS cannot be a record set,
 * because lib/hpengine.c counts a bare scalar in a JSON array as an `empty`
 * slot. That reading was wrong. The `empty` path is for a NULL, a number or
 * an EMPTY string — the trailing newline of a CSV, which is what the comment
 * there is actually about — and hp_json_flat() has always mapped a string
 * WITH CONTENT to {"value": "<the string>"}. So `title_keys=value` and
 * `id_keys=value` is the whole of what a string-array row needs.
 *
 * Four live sources were written off on a capability claim read out of a
 * comment instead of measured. The measurement takes one command:
 *
 *   MCR_IMAGE_CATALOG            emitted 3851 of 3851    stored 3851
 *   NUGET_PACKAGE_VERSIONS_FLAT  emitted 86 of 86        stored 86
 *   PUBDEV_ALL_PACKAGE_NAMES     emitted 91388 of 91388  stored 91388
 *
 * Every row here was fetched live with curl on 2026-10-05, probed with
 * tools/probe_hp_batch.py --check-filter, and then run through the real binary
 * for the emitted-and-stored numbers above. docs/verified-sources-batch35.tsv
 * carries the probe output verbatim.
 *
 * Two row-level details worth keeping:
 *
 *   * NUGET_PACKAGE_VERSIONS_FLAT uses {ql}, not {q}. The NuGet flat container
 *     is case-sensitive and serves lowercase ids only, so an entity pivot that
 *     did not lower-case would 404 on "Newtonsoft.Json" while working for
 *     "newtonsoft.json".
 *   * PUBDEV_ALL_PACKAGE_NAMES declares an Accept-Encoding header. pub.dev
 *     answers a client that does not accept gzip with HTTP 406 NotAcceptable
 *     and no data at all, which is a refusal the probe would otherwise record
 *     as a dead endpoint.
 *
 * Generated by tools/gen_hp_batch.py from
 * docs/candidate-sources-batch35.strings.txt — scaffolded from it ONCE.
 * This file is the maintained copy from here on: repairs carry the live counts
 * that justify them, which the manifest has nowhere to put. Regenerating over
 * it reverts them, so the generator refuses to without --force. See CLAUDE.md,
 * "Batch tooling".
 */
#include "lib/hpengine.h"

static const hp_source HP3B35_STRINGS[] = {
  { .id = "MCR_IMAGE_CATALOG", .name = "Microsoft Container Registry — the full repository catalogue",
    .category = "cyber", .portal = "https://mcr.microsoft.com",
    .record_type = "container-repository",
    .tags = "\"supplychain\",\"package-registry\",\"container\",\"oci\",\"microsoft\",\"namespace\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://mcr.microsoft.com/v2/_catalog",
    .array_path = "repositories",
    .id_keys = "value",
    .interval = 86400,
    .title_keys = "value",
    .description = "Every container repository Microsoft publishes, read from the "
      "registry's own OCI catalogue endpoint: 162 KB of repository "
      "paths on 2026-10-05, from azure-sentinel/solutions/* and "
      "acc/samples/* through the dotnet, windows and sql-server images "
      "most Microsoft-stack containers are built FROM. There is no "
      "search UI for this and no other machine-readable list of it. "
      "Anonymous and keyless, unlike Docker Hub's and AWS ECR Public's "
      "equivalents." },

  { .id = "NUGET_PACKAGE_VERSIONS_FLAT", .name = "NuGet — the flat version list for a package",
    .category = "cyber", .portal = "https://www.nuget.org",
    .record_type = "nuget-package-version",
    .tags = "\"supplychain\",\"package-registry\",\"dotnet\",\"nuget\",\"release-history\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.nuget.org/v3-flatcontainer/{ql}/index.json",
    .array_path = "versions",
    .id_keys = "value",
    .title_keys = "value",
    .description = "Every version of the package as the restore protocol itself sees "
      "it, in the order NuGet resolves them — 86 versions for "
      "newtonsoft.json. This is the list a `dotnet restore` actually "
      "consults, and it differs from the registration index in one way "
      "that matters: it is the flattened, authoritative set with no "
      "catalog-page envelope, so a version present here is installable. "
      "The path segment is lower-cased ({ql}) because the flat "
      "container is case-sensitive and only serves lowercase ids." },

  { .id = "PACKAGIST_ALL_PACKAGE_NAMES", .name = "Packagist — the complete Composer package namespace",
    .category = "cyber", .portal = "https://packagist.org",
    .record_type = "php-package",
    .tags = "\"supplychain\",\"package-registry\",\"php\",\"composer\",\"packagist\",\"namespace\",\"typosquat\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://packagist.org/packages/list.json",
    .array_path = "packageNames",
    .id_keys = "value",
    .interval = 604800,
    .title_keys = "value",
    .description = "Every package name on Packagist in one document — 12.2 MB "
      "holding 470,134 vendor/package names on 2026-10-04, which "
      "Packagist's own statistics endpoint confirms as the registry "
      "total. This is the denominator a PHP typosquat question needs "
      "and the index the per-package rows in batch 33 hop out of: "
      "whether a vendor/name is taken, and what sits one edit away from "
      "it. Measured 2026-10-05: 464,521 emitted, 464,521 stored, 2 m 56 s "
      "and 1.13 GB of database per pass at 2.43 KB per record, which is "
      "why it runs weekly." },

  { .id = "PUBDEV_ALL_PACKAGE_NAMES", .name = "pub.dev — the complete package namespace as names",
    .category = "cyber", .portal = "https://pub.dev",
    .record_type = "dart-package",
    .tags = "\"supplychain\",\"package-registry\",\"dart\",\"flutter\",\"pubdev\",\"namespace\",\"typosquat\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://pub.dev/api/package-names",
    .headers = { "Accept-Encoding: gzip" },
    .array_path = "packages",
    .id_keys = "value",
    .interval = 86400,
    .next_path = "nextUrl",
    .page_max = 4,
    .title_keys = "value",
    .description = "Every package name on pub.dev, 91,325 of them on 2026-10-04, in "
      "440 KB gzipped — the same namespace PUBDEV_ALL_PACKAGES walks in "
      "914 paged requests, in one. Both are kept deliberately: this row "
      "is the cheap complete denominator for a name question, the paged "
      "one carries each package's full latest release and pubspec. The "
      "endpoint REFUSES a client that does not accept gzip (HTTP 406 "
      "NotAcceptable), which is why the row declares the header." },
};

HP_REGISTER_TABLE(HP3B35_STRINGS)
