/* collectors/pivot/table/hp3b19_media.c -- batch 19: media
 *
 * Every row here names a machine-readable endpoint that was proof-of-life
 * verified before it was written: fetched over the wire by
 * collectors/verify_feeds.py, parsed in its declared mode, and confirmed to
 * yield at least one real record. Rows whose endpoint answered but produced
 * an empty result set were rejected rather than shipped -- a source that is
 * structurally guaranteed to emit nothing on every run is the exact failure
 * the no-fabrication rule exists to prevent.
 *
 * The observed shape and record count for each row are recorded in
 * docs/verified-sources-batch19.tsv; the candidates that failed are kept as
 * data in docs/rejected-sources-batch19.tsv rather than silently dropped.
 *
 * Generated by tools/gen_hp_batch.py from
 * docs/candidate-sources-batch19.media.txt. Edit the manifest, not this file.
 */
#include "lib/hpengine.h"

static const hp_source HP3B19_MEDIA[] = {
  { .id = "FOI_ASKTHEEU", .name = "AskTheEU — FOI requests to EU institutions",
    .name_ja = "AskTheEU EU機関情報公開請求",
    .category = "government", .portal = "https://www.asktheeu.org",
    .record_type = "foi-request",
    .tags = "\"foi\",\"transparency\",\"eu\",\"government\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.asktheeu.org/feed/search/{q}.json",
    .description = "Freedom-of-information requests made to EU institutions and "
      "agencies through the AskTheEU platform, with the requesting "
      "person, the body addressed, the request text, every event in the "
      "exchange and the institution's response. Requests to Frontex, "
      "Europol and the Commission's directorates are all here, and the "
      "response text is frequently the only public account of an "
      "internal decision" },

  { .id = "FOI_FRAGDENSTAAT_DE", .name = "FragDenStaat — German FOI requests",
    .name_ja = "FragDenStaat ドイツ情報公開請求",
    .category = "government", .portal = "https://fragdenstaat.de",
    .record_type = "foi-request",
    .tags = "\"foi\",\"transparency\",\"germany\",\"government\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://fragdenstaat.de/api/v1/request/?limit=50",
    .array_path = "objects",
    .interval = 21600,
    .next_path = "meta.next",
    .description = "German freedom-of-information requests with the public body "
      "addressed, the request and response text, the legal basis "
      "invoked, the resolution status and any refusal grounds. "
      "Germany's federal and Länder bodies both appear, and refusal "
      "grounds are recorded as structured codes rather than prose" },

  { .id = "FOI_FRAGDENSTAAT_AT", .name = "FragDenStaat.at — Austrian FOI requests",
    .name_ja = "FragDenStaat.at オーストリア情報公開請求",
    .category = "government", .portal = "https://fragdenstaat.at",
    .record_type = "foi-request",
    .tags = "\"foi\",\"transparency\",\"austria\",\"government\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://fragdenstaat.at/api/v1/request/?limit=50",
    .array_path = "objects",
    .interval = 21600,
    .next_path = "meta.next",
    .description = "Austrian freedom-of-information requests on the same Froide "
      "platform, with the addressed authority, request and response "
      "text, status and jurisdiction. Austria's transparency regime "
      "changed materially in 2025 and this is the record of what is "
      "being asked under it" },

  { .id = "FOI_IMAMOPRAVOZNATI_HR", .name = "Imamo pravo znati — Croatian FOI requests",
    .name_ja = "クロアチア情報公開請求",
    .category = "government", .portal = "https://imamopravoznati.org",
    .record_type = "foi-request",
    .tags = "\"foi\",\"transparency\",\"croatia\",\"government\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://imamopravoznati.org/feed/search/{q}.json",
    .description = "Croatian freedom-of-information requests with the public body, "
      "the request text, the full event history and the response. "
      "Croatia's public bodies include the state asset manager and the "
      "port authorities, and contract-related requests here surface "
      "documents that appear nowhere else" },

  { .id = "FOI_INFOPROVSECHNY_CZ", .name = "Informace pro všechny — Czech FOI requests",
    .name_ja = "チェコ情報公開請求",
    .category = "government", .portal = "https://www.infoprovsechny.cz",
    .record_type = "foi-request",
    .tags = "\"foi\",\"transparency\",\"czechia\",\"government\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.infoprovsechny.cz/feed/search/{q}.json",
    .description = "Czech freedom-of-information requests with the addressed "
      "authority, request and response text and the event chain. Runs "
      "on Alaveteli, so the record shape matches the other national "
      "instances and the corpus is directly comparable across countries" },

  { .id = "FOI_KIMITTUD_HU", .name = "KiMitTud — Hungarian FOI requests",
    .name_ja = "ハンガリー情報公開請求",
    .category = "government", .portal = "https://kimittud.hu",
    .record_type = "foi-request",
    .tags = "\"foi\",\"transparency\",\"hungary\",\"government\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://kimittud.hu/feed/search/{q}.json",
    .description = "Hungarian freedom-of-information requests and responses. Hungary "
      "has narrowed FOI access repeatedly since 2016, which makes the "
      "refusal pattern in this corpus a measurable record of how access "
      "has changed" },

  { .id = "ARCHIVE_ORG_ADVANCED", .name = "Internet Archive — advanced item search",
    .name_ja = "Internet Archive 詳細検索",
    .category = "archive", .portal = "https://archive.org",
    .record_type = "archived-item",
    .tags = "\"archive\",\"internetarchive\",\"search\",\"web\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://archive.org/advancedsearch.php?q={q}&fl%5B%5D=identifier&fl%5B%5D=title&fl%5B%5D=date&fl%5B%5D=creator&fl%5B%5D=collection&rows=100&output=json",
    .array_path = "response.docs",
    .page_param = "page",
    .page_start = 1,
    .description = "Structured search across every item the Internet Archive holds — "
      "not just web captures but uploaded documents, broadcasts, "
      "software and government publications — returning the identifier, "
      "title, creator, date and collection of each. The identifier "
      "resolves to the item's full metadata and files" },

  { .id = "WIKIMEDIA_FEATURED_FEED", .name = "Wikimedia — daily featured and most-read feed",
    .name_ja = "Wikimedia 日次注目記事",
    .category = "media", .portal = "https://api.wikimedia.org",
    .record_type = "attention-record",
    .tags = "\"media\",\"wikipedia\",\"attention\",\"reference\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.wikimedia.org/feed/v1/wikipedia/en/featured/2024/01/15",
    .array_path = "mostread.articles",
    .interval = 21600,
    .description = "The featured article, most-read articles with their view counts, "
      "picture of the day and the news items linked from the main page "
      "for a given date. The most-read list is a dated, quantified "
      "record of collective attention that can be replayed for any past "
      "day" },
};

HP_REGISTER_TABLE(HP3B19_MEDIA)
