/* collectors/pivot/table/hp3b33_socratacat.c -- batch 33: socratacat
 *
 * NOT PROOF-OF-LIFE VERIFIED. This is the deliberate exception, and it is
 * stated here rather than in a note someone has to find: the session that
 * authored batch 33 had no outbound HTTPS (the environment's network policy
 * allowed only Anthropic APIs, package registries and GitHub), so NO row in
 * this file was fetched over the wire. There is no docs/verified-sources-batch33.tsv
 * and no rejects file, because nothing was probed to pass or fail.
 *
 * What IS established, and why these rows are candidates rather than guesses:
 *   - every host is proven reachable by a DIFFERENT row already in this tree
 *     that uses the same host and the same API base path;
 *   - the endpoint path, its query parameters, its paging and its response
 *     envelope are fixed by a published specification (the CKAN Action API,
 *     the FDSN web service spec, the Socrata Discovery API) rather than
 *     inferred from a page;
 *   - batch_exclusions.py --bin reports 0 id or endpoint collisions against
 *     the registry's 18,170 sources, and the reachability (rule 3) and
 *     pagination audits are clean.
 *
 * So treat each row as REGISTERED, NOT PROVEN. Rules 4, 4b and 4d — fetching
 * is not emitting, emitting is not storing, answering is not answering the
 * question — are unmeasured here. The first session with egress should run:
 *     python3 tools/audit_registry_emit.py --bin ./bin/japanosint \
 *             --match JO33_ --jobs 6 --timeout 220 --out b33.tsv
 *     python3 tools/probe_hp_batch.py docs/candidate-sources-batch33.*.txt \
 *             --check-filter
 * and retire whatever comes back EMITS_NOTHING, COLLISION or FILTER_IGNORED.
 * Unlike batch 31, the manifests exist, so those tools can be pointed at this
 * batch directly.
 *
 * The engine cannot fabricate: a moved or reshaped endpoint yields an honest
 * empty, never an invented record. An unmeasured row is a coverage gap.
 *
 * Generated by tools/gen_hp_batch.py from
 * docs/candidate-sources-batch33.socratacat.txt — scaffolded from it ONCE.
 * This file is the maintained copy from here on: repairs carry the live counts
 * that justify them, which the manifest has nowhere to put. Regenerating over
 * it reverts them, so the generator refuses to without --force. See CLAUDE.md,
 * "Batch tooling".
 */
#include "lib/hpengine.h"

static const hp_source HP3B33_SOCRATACAT[] = {
  { .id = "JO33_SOCCAT_ANALISI_TRANSPARENCIACATALUNYA_CAT", .name = "analisi.transparenciacatalunya.cat — dataset catalogue search "
      "(Socrata Discovery)",
    .name_ja = "analisi.transparenciacatalunya.cat データセット検索（Socrata）",
    .category = "government", .portal = "https://analisi.transparenciacatalunya.cat",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"catalonia\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://analisi.transparenciacatalunya.cat/api/catalog/v1?q={q}&domains=analisi.transparenciacatalunya.cat&search_context=analisi.transparenciacatalunya.cat&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_COS_DATA_SEATTLE_GOV", .name = "cos-data.seattle.gov — dataset catalogue search (Socrata "
      "Discovery)",
    .name_ja = "cos-data.seattle.gov データセット検索（Socrata）",
    .category = "government", .portal = "https://cos-data.seattle.gov",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"usa\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://cos-data.seattle.gov/api/catalog/v1?q={q}&domains=cos-data.seattle.gov&search_context=cos-data.seattle.gov&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_DATA_BRLA_GOV", .name = "data.brla.gov — dataset catalogue search (Socrata Discovery)",
    .name_ja = "data.brla.gov データセット検索（Socrata）",
    .category = "government", .portal = "https://data.brla.gov",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"usa\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://data.brla.gov/api/catalog/v1?q={q}&domains=data.brla.gov&search_context=data.brla.gov&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_DATA_CALGARY_CA", .name = "data.calgary.ca — dataset catalogue search (Socrata Discovery)",
    .name_ja = "data.calgary.ca データセット検索（Socrata）",
    .category = "government", .portal = "https://data.calgary.ca",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"canada\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://data.calgary.ca/api/catalog/v1?q={q}&domains=data.calgary.ca&search_context=data.calgary.ca&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_DATA_CITYOFGAINESVILLE_ORG", .name = "data.cityofgainesville.org — dataset catalogue search (Socrata "
      "Discovery)",
    .name_ja = "data.cityofgainesville.org データセット検索（Socrata）",
    .category = "government", .portal = "https://data.cityofgainesville.org",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"ngo\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://data.cityofgainesville.org/api/catalog/v1?q={q}&domains=data.cityofgainesville.org&search_context=data.cityofgainesville.org&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_DATA_EDMONTON_CA", .name = "data.edmonton.ca — dataset catalogue search (Socrata Discovery)",
    .name_ja = "data.edmonton.ca データセット検索（Socrata）",
    .category = "government", .portal = "https://data.edmonton.ca",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"canada\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://data.edmonton.ca/api/catalog/v1?q={q}&domains=data.edmonton.ca&search_context=data.edmonton.ca&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_DATA_MESAAZ_GOV", .name = "data.mesaaz.gov — dataset catalogue search (Socrata Discovery)",
    .name_ja = "data.mesaaz.gov データセット検索（Socrata）",
    .category = "government", .portal = "https://data.mesaaz.gov",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"usa\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://data.mesaaz.gov/api/catalog/v1?q={q}&domains=data.mesaaz.gov&search_context=data.mesaaz.gov&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_DATA_NORFOLK_GOV", .name = "data.norfolk.gov — dataset catalogue search (Socrata Discovery)",
    .name_ja = "data.norfolk.gov データセット検索（Socrata）",
    .category = "government", .portal = "https://data.norfolk.gov",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"usa\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://data.norfolk.gov/api/catalog/v1?q={q}&domains=data.norfolk.gov&search_context=data.norfolk.gov&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_DATA_NOVASCOTIA_CA", .name = "data.novascotia.ca — dataset catalogue search (Socrata "
      "Discovery)",
    .name_ja = "data.novascotia.ca データセット検索（Socrata）",
    .category = "government", .portal = "https://data.novascotia.ca",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"canada\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://data.novascotia.ca/api/catalog/v1?q={q}&domains=data.novascotia.ca&search_context=data.novascotia.ca&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_DATA_PRINCEGEORGESCOUNTYMD_GOV", .name = "data.princegeorgescountymd.gov — dataset catalogue search "
      "(Socrata Discovery)",
    .name_ja = "data.princegeorgescountymd.gov データセット検索（Socrata）",
    .category = "government", .portal = "https://data.princegeorgescountymd.gov",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"usa\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://data.princegeorgescountymd.gov/api/catalog/v1?q={q}&domains=data.princegeorgescountymd.gov&search_context=data.princegeorgescountymd.gov&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_DATA_SANDIEGOCOUNTY_GOV", .name = "data.sandiegocounty.gov — dataset catalogue search (Socrata "
      "Discovery)",
    .name_ja = "data.sandiegocounty.gov データセット検索（Socrata）",
    .category = "government", .portal = "https://data.sandiegocounty.gov",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"usa\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://data.sandiegocounty.gov/api/catalog/v1?q={q}&domains=data.sandiegocounty.gov&search_context=data.sandiegocounty.gov&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_DATA_SCCGOV_ORG", .name = "data.sccgov.org — dataset catalogue search (Socrata Discovery)",
    .name_ja = "data.sccgov.org データセット検索（Socrata）",
    .category = "government", .portal = "https://data.sccgov.org",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"ngo\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://data.sccgov.org/api/catalog/v1?q={q}&domains=data.sccgov.org&search_context=data.sccgov.org&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_DATA_SFGOV_ORG", .name = "data.sfgov.org — dataset catalogue search (Socrata Discovery)",
    .name_ja = "data.sfgov.org データセット検索（Socrata）",
    .category = "government", .portal = "https://data.sfgov.org",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"ngo\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://data.sfgov.org/api/catalog/v1?q={q}&domains=data.sfgov.org&search_context=data.sfgov.org&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_DATA_USAID_GOV", .name = "data.usaid.gov — dataset catalogue search (Socrata Discovery)",
    .name_ja = "data.usaid.gov データセット検索（Socrata）",
    .category = "government", .portal = "https://data.usaid.gov",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"usa\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://data.usaid.gov/api/catalog/v1?q={q}&domains=data.usaid.gov&search_context=data.usaid.gov&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_DATA_VERMONT_GOV", .name = "data.vermont.gov — dataset catalogue search (Socrata Discovery)",
    .name_ja = "data.vermont.gov データセット検索（Socrata）",
    .category = "government", .portal = "https://data.vermont.gov",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"usa\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://data.vermont.gov/api/catalog/v1?q={q}&domains=data.vermont.gov&search_context=data.vermont.gov&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_DATA_WINNIPEG_CA", .name = "data.winnipeg.ca — dataset catalogue search (Socrata Discovery)",
    .name_ja = "data.winnipeg.ca データセット検索（Socrata）",
    .category = "government", .portal = "https://data.winnipeg.ca",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"canada\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://data.winnipeg.ca/api/catalog/v1?q={q}&domains=data.winnipeg.ca&search_context=data.winnipeg.ca&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_DATAHUB_AUSTINTEXAS_GOV", .name = "datahub.austintexas.gov — dataset catalogue search (Socrata "
      "Discovery)",
    .name_ja = "datahub.austintexas.gov データセット検索（Socrata）",
    .category = "government", .portal = "https://datahub.austintexas.gov",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"usa\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://datahub.austintexas.gov/api/catalog/v1?q={q}&domains=datahub.austintexas.gov&search_context=datahub.austintexas.gov&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_DATAHUB_TRANSPORTATION_GOV", .name = "datahub.transportation.gov — dataset catalogue search (Socrata "
      "Discovery)",
    .name_ja = "datahub.transportation.gov データセット検索（Socrata）",
    .category = "government", .portal = "https://datahub.transportation.gov",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"usa\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://datahub.transportation.gov/api/catalog/v1?q={q}&domains=datahub.transportation.gov&search_context=datahub.transportation.gov&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_HICSCDATA_HAWAII_GOV", .name = "hicscdata.hawaii.gov — dataset catalogue search (Socrata "
      "Discovery)",
    .name_ja = "hicscdata.hawaii.gov データセット検索（Socrata）",
    .category = "government", .portal = "https://hicscdata.hawaii.gov",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"usa\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://hicscdata.hawaii.gov/api/catalog/v1?q={q}&domains=hicscdata.hawaii.gov&search_context=hicscdata.hawaii.gov&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_ILLINOIS_EDP_DATA_SOCRATA_COM", .name = "illinois-edp.data.socrata.com — dataset catalogue search "
      "(Socrata Discovery)",
    .name_ja = "illinois-edp.data.socrata.com データセット検索（Socrata）",
    .category = "government", .portal = "https://illinois-edp.data.socrata.com",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"com\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://illinois-edp.data.socrata.com/api/catalog/v1?q={q}&domains=illinois-edp.data.socrata.com&search_context=illinois-edp.data.socrata.com&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_OPENDATA_RDW_NL", .name = "opendata.rdw.nl — dataset catalogue search (Socrata Discovery)",
    .name_ja = "opendata.rdw.nl データセット検索（Socrata）",
    .category = "government", .portal = "https://opendata.rdw.nl",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"netherlands\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://opendata.rdw.nl/api/catalog/v1?q={q}&domains=opendata.rdw.nl&search_context=opendata.rdw.nl&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_PUBLICREPORTING_CFTC_GOV", .name = "publicreporting.cftc.gov — dataset catalogue search (Socrata "
      "Discovery)",
    .name_ja = "publicreporting.cftc.gov データセット検索（Socrata）",
    .category = "government", .portal = "https://publicreporting.cftc.gov",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"usa\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://publicreporting.cftc.gov/api/catalog/v1?q={q}&domains=publicreporting.cftc.gov&search_context=publicreporting.cftc.gov&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_SHAREFULTON_FULTONCOUNTYGA_GOV", .name = "sharefulton.fultoncountyga.gov — dataset catalogue search "
      "(Socrata Discovery)",
    .name_ja = "sharefulton.fultoncountyga.gov データセット検索（Socrata）",
    .category = "government", .portal = "https://sharefulton.fultoncountyga.gov",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"usa\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://sharefulton.fultoncountyga.gov/api/catalog/v1?q={q}&domains=sharefulton.fultoncountyga.gov&search_context=sharefulton.fultoncountyga.gov&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },

  { .id = "JO33_SOCCAT_WWW_DATI_FRIULIVENEZIAGIULIA_IT", .name = "www.dati.friuliveneziagiulia.it — dataset catalogue search "
      "(Socrata Discovery)",
    .name_ja = "www.dati.friuliveneziagiulia.it データセット検索（Socrata）",
    .category = "government", .portal = "https://www.dati.friuliveneziagiulia.it",
    .record_type = "dataset",
    .tags = "\"socrata\",\"open-data\",\"catalog\",\"dataset\",\"italy\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.dati.friuliveneziagiulia.it/api/catalog/v1?q={q}&domains=www.dati.friuliveneziagiulia.it&search_context=www.dati.friuliveneziagiulia.it&limit=100",
    .array_path = "results",
    .body_keys = "resource.description",
    .date_keys = "resource.updatedAt",
    .id_keys = "resource.id",
    .link_keys = "permalink",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 100,
    .timeout_ms = 60000,
    .title_keys = "resource.name,resource.description",
    .description = "UNPROBED. The Socrata Discovery API scoped to this domain: given "
      "an entity it returns every dataset on that portal whose metadata "
      "mentions it, with the dataset name, description, owning "
      "department, category, update time and permalink. This is the "
      "pivot that answers \"which of this government's datasets mention "
      "X\" before spending a request on any single dataset. The domain "
      "is proven Socrata by existing wired /resource/<4x4> rows; the "
      "catalog path, its q filter and its limit/offset paging are fixed "
      "by the Socrata Discovery API." },
};

HP_REGISTER_TABLE(HP3B33_SOCRATACAT)
