/* collectors/pivot/table/hp3b32_supplychain.c -- batch 32: software supply-chain and package-registry intelligence, cross-ecosystem
 *
 * WHY THIS BEAT. The tree already carried package registries, but almost
 * entirely as NAME SEARCH: "find me packages matching X". The three questions
 * a supply-chain investigation actually asks were missing in every ecosystem:
 * who can publish this thing (owners, teams, maintainer email); what has it
 * published, when, and by whom (per-version history with the publishing
 * account and the artefact hash); and what breaks if that account is taken
 * over (reverse dependencies, namespace listings, the whole namespace as a
 * denominator). Every row here answers one of those three.
 *
 * VERIFICATION STATUS -- this batch is MEASURED, not merely probed. The
 * environment it was authored in reaches package-registry hosts (and only
 * those), so all four gates ran against the live upstreams on 2026-10-04:
 *
 *   tools/probe_hp_batch.py --check-filter   43/43 PASS, no FILTER_IGNORED
 *   tools/audit_batch_emit.py                every row OK, emitted == available
 *   ./bin/japanosint --run <id> <entity>     emitted vs stored, per pivot row
 *   tools/audit_registry_emit.py             the scheduled rows, against a
 *                                            fresh copy of a warm template DB
 *
 * Every record count and field list in the row descriptions is what the body
 * actually held at that moment, and docs/verified-sources-batch32.tsv carries
 * the probe output verbatim. What did NOT survive is kept as data in
 * docs/rejected-sources-batch32.tsv -- the two rows dropped after measurement
 * and the candidate families the engine or the egress policy ruled out.
 *
 * Four rows were WRONG when first written and are right because they were
 * measured; the defect in each was invisible to probe-and-count:
 *
 *   * The three hex.pm rows and the three RubyGems array rows answer with a
 *     BARE ROOT ARRAY. Left to discovery the engine takes the densest array
 *     of objects, which on hex.pm is a package's own `releases` list (133)
 *     and not the root (100): HEXPM_RECENT_UPDATES emitted 9,643 records
 *     across 60 pages that hold 6,000, keyed on a field the release entries
 *     do not carry, 2,881 of them collapsing at the sink. `array_path = "."`
 *     is the root (see lib/hpengine.h) and took it to 6,000 of 6,000 stored.
 *   * NUGET_REGISTRATION_INDEX declared `array_path = items`, which is the
 *     catalog PAGES: 2 records of 189 KB and 219 KB with all 86 versions
 *     flattened into them as items.0.*, items.1.*. `items.items` crosses the
 *     page array (hp_path_multi) and gives 86 version records.
 *   * JSR_PACKAGE_META uses {Q}, not {q}: {q} percent-encodes the slash in
 *     `scope/name` and jsr.io answers /@std%2Fpath/meta.json with HTTP 400.
 *     Maven Central and proxy.golang.org both normalise %2F back, which is
 *     why the other two slash-bearing pivots here work with {q}.
 *
 * One COLLISION verdict is upstream, not ours, and is left alone:
 * RUBYGEMS_LATEST_GEMS emits 50 and stores 32 because rubygems.org repeats
 * the same gem several times in that feed -- checked field by field, the
 * repeats are byte-identical (rphonetic 0.1.0 appears 6 times, zxing_ffi
 * 7, corvus_json_schema 8), so no key can separate them and collapsing them
 * is real dedupe. Do not "fix" it by widening id_keys.
 *
 * crates.io is paced at 1100 ms in core/hostgate.c. Its crawler policy is one
 * request per second and it enforces it: a 4-worker sweep was 429'd part-way
 * through a reverse_dependencies walk, and a later single run of the same row
 * was 429'd on its first request while the window was still hot.
 *
 * Generated by tools/gen_hp_batch.py from
 * docs/candidate-sources-batch32.supplychain.txt — scaffolded from it ONCE.
 * This file is the maintained copy from here on: repairs carry the live counts
 * that justify them, which the manifest has nowhere to put. Regenerating over
 * it reverts them, so the generator refuses to without --force. See CLAUDE.md,
 * "Batch tooling".
 */
#include "lib/hpengine.h"

static const hp_source HP3B32_SUPPLYCHAIN[] = {
  { .id = "CRATESIO_CRATE_VERSIONS", .name = "crates.io — every published version of a crate",
    .category = "cyber", .portal = "https://crates.io",
    .record_type = "crate-version",
    .tags = "\"supplychain\",\"package-registry\",\"rust\",\"crates-io\",\"release-history\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://crates.io/api/v1/crates/{q}/versions",
    .array_path = "versions",
    .date_keys = "created_at",
    .id_keys = "crate+num",
    .title_keys = "num",
    .description = "One record per published version of the crate (316 for serde on "
      "2026-10-04). Each carries num, created_at and updated_at, "
      "downloads, yanked plus yank_message, crate_size, checksum, "
      "license, edition, rust_version, bin_names, has_lib, lib_links, "
      "the feature map, repository/homepage/documentation URLs, "
      "audit_actions (who published or yanked it and when) and "
      "published_by (the crates.io account that pushed it). "
      "published_by + audit_actions is the publication-provenance trail "
      "a supply-chain compromise shows up in: a release pushed by an "
      "account that never published before." },

  { .id = "CRATESIO_CRATE_OWNERS", .name = "crates.io — user accounts that own a crate",
    .category = "cyber", .portal = "https://crates.io",
    .record_type = "package-owner",
    .tags = "\"supplychain\",\"package-registry\",\"rust\",\"crates-io\",\"attribution\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://crates.io/api/v1/crates/{q}/owners",
    .array_path = "users",
    .id_keys = "id",
    .title_keys = "login,name",
    .description = "The individual accounts with publish rights on the crate: "
      "crates.io id, login, display name, the GitHub profile URL, "
      "avatar, and github_username_matches (whether the linked GitHub "
      "login still matches — a false there means the GitHub account was "
      "renamed or taken over, which is exactly the signal a hijack "
      "leaves behind). Two owners for serde." },

  { .id = "CRATESIO_CRATE_OWNER_TEAMS", .name = "crates.io — GitHub teams that own a crate",
    .category = "cyber", .portal = "https://crates.io",
    .record_type = "package-owner",
    .tags = "\"supplychain\",\"package-registry\",\"rust\",\"crates-io\",\"attribution\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://crates.io/api/v1/crates/{q}/owner_team",
    .array_path = "teams",
    .id_keys = "id",
    .title_keys = "login,name",
    .description = "The GitHub TEAMS holding publish rights, which the user-owner "
      "endpoint does not list: id, login in github:org:team form "
      "(github:serde-rs:publish), display name, the org URL and avatar. "
      "Team ownership means publish rights follow GitHub team "
      "membership, so the crate's effective publisher set is whoever is "
      "in that team today — not visible from the crate page." },

  { .id = "CRATESIO_CRATE_REVDEPS", .name = "crates.io — reverse dependencies of a crate",
    .category = "cyber", .portal = "https://crates.io",
    .record_type = "package-dependency",
    .tags = "\"supplychain\",\"package-registry\",\"rust\",\"crates-io\",\"dependency-graph\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://crates.io/api/v1/crates/{q}/reverse_dependencies?per_page=100",
    .array_path = "dependencies",
    .id_keys = "id",
    .page_max = 200,
    .page_param = "page",
    .title_keys = "crate_id",
    .description = "Everything in the Rust ecosystem that depends on this crate: one "
      "record per dependent version with its own id, version_id, the "
      "semver requirement string, optional and default_features flags, "
      "the requested feature list, target cfg, kind (normal/build/dev) "
      "and the dependent's download count. meta.total was 127,327 for "
      "serde on 2026-10-04 — the blast radius of a compromise in that "
      "one crate, enumerated." },

  { .id = "CRATESIO_CRATE_DOWNLOAD_SERIES", .name = "crates.io — per-version daily download series for a crate",
    .category = "cyber", .portal = "https://crates.io",
    .record_type = "package-download-series",
    .tags = "\"supplychain\",\"package-registry\",\"rust\",\"crates-io\",\"telemetry\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://crates.io/api/v1/crates/{q}/downloads",
    .array_path = "version_downloads",
    .date_keys = "date",
    .id_keys = "version+date",
    .title_keys = "date",
    .description = "A daily download count per crate VERSION, 439 records for serde "
      "covering the last 90 days. Fields: version (the numeric version "
      "id), downloads, date. A version that suddenly acquires downloads "
      "long after being superseded, or a brand-new version spiking on "
      "day one, is visible here and nowhere else in the API." },

  { .id = "CRATESIO_RECENT_UPDATES", .name = "crates.io — most recently updated crates",
    .category = "cyber", .portal = "https://crates.io",
    .record_type = "crate",
    .tags = "\"supplychain\",\"package-registry\",\"rust\",\"crates-io\",\"release-feed\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://crates.io/api/v1/crates?sort=recent-updates&per_page=100",
    .array_path = "crates",
    .date_keys = "updated_at",
    .id_keys = "id",
    .interval = 3600,
    .page_max = 40,
    .page_param = "page",
    .title_keys = "name",
    .description = "The publish firehose ordered by last update: name, created_at "
      "and updated_at, total and recent downloads, num_versions, "
      "default/max/newest/max_stable version, yanked flag, description, "
      "homepage, documentation and repository. meta.total 345,158 "
      "crates. Watching this is how you see a dormant crate suddenly "
      "publishing again." },

  { .id = "CRATESIO_NEW_CRATES", .name = "crates.io — newly created crates",
    .category = "cyber", .portal = "https://crates.io",
    .record_type = "crate",
    .tags = "\"supplychain\",\"package-registry\",\"rust\",\"crates-io\",\"release-feed\",\"typosquat\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://crates.io/api/v1/crates?sort=new&per_page=100",
    .array_path = "crates",
    .date_keys = "created_at",
    .id_keys = "id",
    .interval = 3600,
    .page_max = 40,
    .page_param = "page",
    .title_keys = "name",
    .description = "Crates ordered by creation date — the registration feed rather "
      "than the release feed. Same full record as the update feed "
      "(created_at, downloads, num_versions, repository, description). "
      "A newly registered name one character from a popular crate is "
      "the typosquat signal, and it is only visible in creation order." },

  { .id = "CRATESIO_TOP_DOWNLOADS", .name = "crates.io — crates ranked by total downloads",
    .category = "cyber", .portal = "https://crates.io",
    .record_type = "crate",
    .tags = "\"supplychain\",\"package-registry\",\"rust\",\"crates-io\",\"dependency-graph\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://crates.io/api/v1/crates?sort=downloads&per_page=100",
    .array_path = "crates",
    .id_keys = "id",
    .interval = 86400,
    .page_max = 100,
    .page_param = "page",
    .title_keys = "name",
    .description = "The Rust ecosystem ranked by total downloads, which is the "
      "ranked list of what a single compromised publish would reach. "
      "Same record as the other crate listings: downloads and "
      "recent_downloads, num_versions, newest and max_stable version, "
      "repository and documentation URLs." },

  { .id = "CRATESIO_KEYWORDS", .name = "crates.io — the whole keyword vocabulary",
    .category = "cyber", .portal = "https://crates.io",
    .record_type = "package-keyword",
    .tags = "\"supplychain\",\"package-registry\",\"rust\",\"crates-io\",\"taxonomy\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://crates.io/api/v1/keywords?per_page=100",
    .array_path = "keywords",
    .date_keys = "created_at",
    .id_keys = "id",
    .interval = 86400,
    .page_max = 600,
    .page_param = "page",
    .title_keys = "keyword",
    .description = "Every keyword publishers have attached to a crate, with "
      "created_at (when it first appeared) and crates_cnt (how many "
      "crates carry it). meta.total 58,604 on 2026-10-04. The whole "
      "self-declared topic vocabulary of the Rust ecosystem, which is "
      "what you search when you need to find every crate in a problem "
      "domain rather than by name." },

  { .id = "CRATESIO_CATEGORIES", .name = "crates.io — curated crate categories",
    .category = "cyber", .portal = "https://crates.io",
    .record_type = "package-category",
    .tags = "\"supplychain\",\"package-registry\",\"rust\",\"crates-io\",\"taxonomy\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://crates.io/api/v1/categories?per_page=100",
    .array_path = "categories",
    .id_keys = "id",
    .interval = 86400,
    .title_keys = "category",
    .description = "The 58 curated categories (meta.total 58, so one page holds all "
      "of them): slug, display name, prose description, created_at and "
      "crates_cnt. Unlike keywords these are maintained rather than "
      "publisher-declared, so they are the stable axis for asking 'what "
      "is the Rust cryptography surface'." },

  { .id = "RUBYGEMS_OWNER_GEMS", .name = "RubyGems — every gem owned by one account",
    .category = "cyber", .portal = "https://rubygems.org",
    .record_type = "gem",
    .tags = "\"supplychain\",\"package-registry\",\"ruby\",\"rubygems\",\"attribution\",\"maintainer-pivot\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://rubygems.org/api/v1/owners/{q}/gems.json",
    .array_path = ".",
    .date_keys = "version_created_at",
    .id_keys = "name",
    .title_keys = "name",
    .description = "The maintainer pivot: given a RubyGems handle, every gem that "
      "account can publish, each as the full gem record (downloads, "
      "current version, authors, licenses, yanked flag, sha, and the "
      "complete URI block). 191 gems for tenderlove on 2026-10-04. This "
      "is the blast radius of one compromised RubyGems account, and the "
      "API answers it directly — a missing or renamed handle returns "
      "HTTP 404, never a wrong list." },

  { .id = "RUBYGEMS_JUST_UPDATED", .name = "RubyGems — gems updated most recently",
    .category = "cyber", .portal = "https://rubygems.org",
    .record_type = "gem",
    .tags = "\"supplychain\",\"package-registry\",\"ruby\",\"rubygems\",\"release-feed\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://rubygems.org/api/v1/activity/just_updated.json",
    .array_path = ".",
    .date_keys = "version_created_at",
    .id_keys = "name+version",
    .interval = 1800,
    .title_keys = "name",
    .description = "The RubyGems update firehose: the most recently pushed versions, "
      "each as a complete gem record — name, new version and "
      "version_created_at, platform, authors, licenses, yanked flag, "
      "sha, and every project/source/changelog/funding URI. A new "
      "version of a widely-installed gem appears here before any "
      "advisory does." },

  { .id = "RUBYGEMS_LATEST_GEMS", .name = "RubyGems — newly published gems",
    .category = "cyber", .portal = "https://rubygems.org",
    .record_type = "gem",
    .tags = "\"supplychain\",\"package-registry\",\"ruby\",\"rubygems\",\"release-feed\",\"typosquat\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://rubygems.org/api/v1/activity/latest.json",
    .array_path = ".",
    .date_keys = "version_created_at",
    .id_keys = "name+version",
    .interval = 1800,
    .title_keys = "name",
    .description = "Gems whose FIRST version was just published, which is a "
      "different set from just_updated and the one typosquats land in. "
      "Same complete gem record: authors, licenses, sha, homepage and "
      "source_code URIs, downloads." },

  { .id = "HEXPM_PACKAGE_OWNERS", .name = "Hex.pm — accounts that own an Elixir/Erlang package",
    .category = "cyber", .portal = "https://hex.pm",
    .record_type = "package-owner",
    .tags = "\"supplychain\",\"package-registry\",\"elixir\",\"erlang\",\"hex\",\"attribution\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://hex.pm/api/packages/{q}/owners",
    .array_path = ".",
    .date_keys = "inserted_at",
    .id_keys = "username",
    .title_keys = "username,full_name",
    .description = "Who can publish this package: username, full_name, the account's "
      "EMAIL ADDRESS in clear, the ownership level (full or "
      "maintainer), the account's API URL, inserted_at and updated_at, "
      "and any linked handles. Five owners for phoenix. Hex publishes "
      "maintainer email addresses, which makes this a direct "
      "person-to-package attribution source rather than a handle-only "
      "one." },

  { .id = "HEXPM_USER_PACKAGES", .name = "Hex.pm — every package one account can publish",
    .category = "cyber", .portal = "https://hex.pm",
    .record_type = "package",
    .tags = "\"supplychain\",\"package-registry\",\"elixir\",\"erlang\",\"hex\",\"attribution\",\"maintainer-pivot\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://hex.pm/api/users/{q}",
    .array_path = "packages",
    .id_keys = "name",
    .title_keys = "name",
    .description = "The maintainer pivot for Hex: one record per package the account "
      "owns, with the package name, its API URL, its human page and the "
      "repository it lives in. 54 packages for josevalim. The response "
      "envelope also carries the account's own email in clear, "
      "full_name and inserted_at, which are NOT emitted here because "
      "the records are the packages — HEXPM_PACKAGE_OWNERS is the row "
      "that emits an account identity as a record, and the two compose: "
      "owners of a package, then packages of an owner." },

  { .id = "HEXPM_RECENT_UPDATES", .name = "Hex.pm — packages ordered by last update",
    .category = "cyber", .portal = "https://hex.pm",
    .record_type = "package",
    .tags = "\"supplychain\",\"package-registry\",\"elixir\",\"erlang\",\"hex\",\"release-feed\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://hex.pm/api/packages?sort=updated_at",
    .array_path = ".",
    .date_keys = "updated_at",
    .id_keys = "name",
    .interval = 3600,
    .page_max = 60,
    .page_param = "page",
    .title_keys = "name",
    .description = "The Hex release firehose, 100 packages per page ordered by "
      "updated_at. Each record carries name, html_url and "
      "docs_html_url, inserted_at and updated_at, latest_version and "
      "latest_stable_version, the full releases[] list with each "
      "version and its own URL, downloads (all/recent/week/day), "
      "retirements (versions the maintainer withdrew and why), the "
      "repository it lives in, and meta{} with the description, licence "
      "list, declared maintainers and every project link the publisher "
      "supplied." },

  { .id = "NPM_MAINTAINER_PACKAGES", .name = "npm registry — every package a maintainer can publish",
    .category = "cyber", .portal = "https://www.npmjs.com",
    .record_type = "npm-package",
    .tags = "\"supplychain\",\"package-registry\",\"javascript\",\"npm\",\"attribution\",\"maintainer-pivot\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://registry.npmjs.org/-/v1/search?text=maintainer:{q}&size=250",
    .array_path = "objects",
    .date_keys = "package.date",
    .id_keys = "package.name+package.version",
    .page_max = 40,
    .page_param = "from",
    .page_size = 250,
    .page_zero_based = 1,
    .title_keys = "package.name",
    .description = "The npm maintainer pivot. The registry's own search honours a "
      "maintainer: qualifier, so one handle returns the packages that "
      "account publishes — 250 per page for sindresorhus. Each record "
      "carries package{name, version, description, keywords, date, "
      "links{npm,homepage,repository,bugs}, author, "
      "publisher{username,email}, maintainers[]}, the dependents count, "
      "weekly and monthly downloads, and the "
      "quality/popularity/maintenance score breakdown. publisher.email "
      "and maintainers[].email are real addresses." },

  { .id = "NPM_KEYWORD_PACKAGES", .name = "npm registry — packages carrying one keyword",
    .category = "cyber", .portal = "https://www.npmjs.com",
    .record_type = "npm-package",
    .tags = "\"supplychain\",\"package-registry\",\"javascript\",\"npm\",\"taxonomy\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://registry.npmjs.org/-/v1/search?text=keywords:{q}&size=250",
    .array_path = "objects",
    .date_keys = "package.date",
    .id_keys = "package.name+package.version",
    .page_max = 40,
    .page_param = "from",
    .page_size = 250,
    .page_zero_based = 1,
    .title_keys = "package.name",
    .description = "The same full search record as the maintainer pivot, selected by "
      "the publisher-declared keyword rather than by account. Asking "
      "the registry for keywords:cve returns the packages whose authors "
      "claim to work on CVE data — a self-declared capability list. "
      "Each record carries the package manifest summary, links, "
      "publisher and maintainer identities with email addresses, "
      "dependents count and download figures." },

  { .id = "NPM_DIST_TAGS", .name = "npm registry — the dist-tags a package publishes",
    .category = "cyber", .portal = "https://www.npmjs.com",
    .record_type = "npm-dist-tag",
    .tags = "\"supplychain\",\"package-registry\",\"javascript\",\"npm\",\"release-integrity\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://registry.npmjs.org/-/package/{q}/dist-tags",
    .id_keys = "latest",
    .title_keys = "latest",
    .description = "The tag-to-version map an npm install actually resolves through: "
      "latest, next, beta and any maintainer-defined tag. express "
      "returns latest 5.2.1 and latest-4 4.22.3. This is the smallest "
      "request that answers what version the world is being handed "
      "right now, and a tag silently repointed at an older or "
      "unexpected version is a published-state change that the version "
      "list alone does not show." },

  { .id = "PUBDEV_PACKAGE_VERSIONS", .name = "pub.dev — every published version of a Dart/Flutter package",
    .category = "cyber", .portal = "https://pub.dev",
    .record_type = "dart-package-version",
    .tags = "\"supplychain\",\"package-registry\",\"dart\",\"flutter\",\"pubdev\",\"release-history\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://pub.dev/api/packages/{q}",
    .array_path = "versions",
    .date_keys = "published",
    .id_keys = "pubspec.name+version",
    .title_keys = "version",
    .description = "One record per published version (130 for package:http): the "
      "version string, published timestamp, archive_url, archive_sha256 "
      "(the integrity hash of the actual tarball), and the COMPLETE "
      "pubspec as declared at that version — name, description, "
      "homepage and repository and issue_tracker URLs, environment SDK "
      "constraints, and the full dependencies and dev_dependencies "
      "maps. A per-version dependency history with a content hash on "
      "each release." },

  { .id = "PUBDEV_SEARCH", .name = "pub.dev — package name search",
    .category = "cyber", .portal = "https://pub.dev",
    .record_type = "dart-package",
    .tags = "\"supplychain\",\"package-registry\",\"dart\",\"flutter\",\"pubdev\",\"discovery\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://pub.dev/api/search?q={q}",
    .array_path = "packages",
    .id_keys = "package",
    .page_max = 30,
    .page_param = "page",
    .title_keys = "package",
    .description = "pub.dev's own search, returning the matching package names in "
      "relevance order. Deliberately thin (one name per record) — it is "
      "the index into PUBDEV_PACKAGE_VERSIONS and "
      "PUBDEV_PACKAGE_METRICS, which is how a query term becomes a set "
      "of packages to pull in full." },

  { .id = "PUBDEV_ALL_PACKAGES", .name = "pub.dev — the complete package namespace",
    .category = "cyber", .portal = "https://pub.dev",
    .record_type = "dart-package",
    .tags = "\"supplychain\",\"package-registry\",\"dart\",\"flutter\",\"pubdev\",\"namespace\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://pub.dev/api/packages",
    .array_path = "packages",
    .date_keys = "latest.published",
    .id_keys = "name",
    .interval = 86400,
    .next_path = "next_url",
    /* 1000, not the manifest's original 700. 700 pages is 70,000 records and
     * that is exactly what the first measured run emitted — the ceiling, not
     * the end of the namespace. pub.dev's own /api/package-names (which needs
     * an Accept-Encoding: gzip or it answers 406) declares 91,325 packages
     * with nextUrl null, so 700 pages was dropping ~21,000 of them behind a
     * truncation notice. 1000 covers 100,000 and leaves headroom. */
    .page_max = 1000,
    .title_keys = "name",
    .description = "Every package on pub.dev, 100 per page, each with its name and "
      "its complete latest release — version, archive_url, "
      "archive_sha256, published timestamp and the whole pubspec "
      "(description, repository, homepage, SDK constraints, dependency "
      "maps). The server publishes its own next_url, so the walk "
      "follows the upstream's evidence rather than guessed page "
      "arithmetic. The full Dart/Flutter namespace is the denominator a "
      "typosquat search needs — 91,325 packages on 2026-10-04, counted "
      "from pub.dev's own /api/package-names." },

  { .id = "PUBDEV_RECENT_ATOM", .name = "pub.dev — recently published packages (Atom)",
    .category = "cyber", .portal = "https://pub.dev",
    .record_type = "dart-package-release",
    .tags = "\"supplychain\",\"package-registry\",\"dart\",\"flutter\",\"pubdev\",\"release-feed\"",
    .mode = HP_XML, .want = HP_ANY, .free_tier = 1,
    .url = "https://pub.dev/feed.atom",
    .array_path = "entry",
    .date_keys = "updated",
    .id_keys = "id",
    .interval = 1800,
    .title_keys = "title",
    .description = "pub.dev's own Atom feed of recent publishes: one entry per "
      "release with its id, title (package and version), updated "
      "timestamp, author and the rendered changelog/description "
      "content. The lowest-latency view of what is being pushed to Dart "
      "and Flutter users." },

  { .id = "DOCKERHUB_NAMESPACE_REPOS", .name = "Docker Hub — every repository in one namespace",
    .category = "cyber", .portal = "https://hub.docker.com",
    .record_type = "container-repository",
    .tags = "\"supplychain\",\"package-registry\",\"container\",\"docker\",\"oci\",\"namespace-pivot\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://hub.docker.com/v2/repositories/{q}/?page_size=100",
    .array_path = "results",
    .date_keys = "last_updated",
    .id_keys = "namespace+name",
    .next_path = "next",
    .page_max = 2,
    .title_keys = "name",
    .description = "Given an organisation or user namespace, every container "
      "repository it publishes: name, namespace, repository_type, "
      "status and status_description (which is how an archived or "
      "deprecated publisher shows up), description, is_private, "
      "star_count, pull_count, date_registered, last_updated and "
      "last_modified, storage_size, declared categories, media_types "
      "and content_types, and the source. 276 repositories for bitnami. "
      "The namespace-level view of a container publisher that the "
      "per-image tag endpoint cannot give." },

  { .id = "DOCKERHUB_OFFICIAL_IMAGES", .name = "Docker Hub — the official (library) image set",
    .category = "cyber", .portal = "https://hub.docker.com",
    .record_type = "container-repository",
    .tags = "\"supplychain\",\"package-registry\",\"container\",\"docker\",\"oci\",\"baseline\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://hub.docker.com/v2/repositories/library/?page_size=100",
    .array_path = "results",
    .date_keys = "last_updated",
    .id_keys = "namespace+name",
    .interval = 86400,
    .next_path = "next",
    .page_max = 2,
    .title_keys = "name",
    .description = "The 181 Docker Official Images — the curated base layers most of "
      "the world's containers are built FROM. Same full repository "
      "record as any namespace (pull_count, star_count, last_updated, "
      "date_registered, storage_size, categories, status), which makes "
      "this the baseline set to diff an unknown base image against." },

  { .id = "PACKAGIST_PACKAGE_ADVISORIES", .name = "Packagist — security advisories for one Composer package",
    .category = "cyber", .portal = "https://packagist.org",
    .record_type = "security-advisory",
    .tags = "\"supplychain\",\"package-registry\",\"php\",\"composer\",\"packagist\",\"vulnerability\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://packagist.org/api/security-advisories/?packages%5B%5D={q}",
    .date_keys = "reportedAt",
    .id_keys = "advisoryId",
    .title_keys = "title",
    .description = "Every known advisory against the named Composer package: "
      "advisoryId (PKSA-...), packageName, title, link, cve (often null "
      "where no CVE was ever assigned, which is the point), "
      "affectedVersions as a semver range, severity, reportedAt, the "
      "composerRepository it applies to, the originating source, and "
      "sources[] cross-referencing the same issue in GitHub (GHSA) and "
      "FriendsOfPHP. PHP advisories frequently exist here with no CVE "
      "at all, so a CVE-only pipeline never sees them." },

  { .id = "PACKAGIST_RELEASES_RSS", .name = "Packagist — new releases feed",
    .category = "cyber", .portal = "https://packagist.org",
    .record_type = "php-package-release",
    .tags = "\"supplychain\",\"package-registry\",\"php\",\"composer\",\"packagist\",\"release-feed\"",
    .mode = HP_XML, .want = HP_ANY, .free_tier = 1,
    .url = "https://packagist.org/feeds/releases.rss",
    .array_path = "item",
    .date_keys = "pubDate",
    .id_keys = "guid,link,title",
    .interval = 1800,
    .title_keys = "title",
    .description = "Packagist's own release firehose: one item per published version "
      "with title (vendor/package and version), link, description, "
      "pubDate and the Dublin Core creator. The lowest-latency view of "
      "what the PHP ecosystem is publishing." },

  { .id = "PACKAGIST_PACKAGE_RSS", .name = "Packagist — release feed for one package",
    .category = "cyber", .portal = "https://packagist.org",
    .record_type = "php-package-release",
    .tags = "\"supplychain\",\"package-registry\",\"php\",\"composer\",\"packagist\",\"release-history\"",
    .mode = HP_XML, .want = HP_ANY, .free_tier = 1,
    .url = "https://packagist.org/feeds/package.{q}.rss",
    .array_path = "item",
    .date_keys = "pubDate",
    .id_keys = "guid,link,title",
    .title_keys = "title",
    .description = "The per-package release history as RSS: one item per version "
      "with title, link, description, pubDate and creator. A vendor "
      "name alone returns HTTP 404 rather than a wrong feed, so the row "
      "answers about the package asked for or not at all." },

  { .id = "PACKAGIST_POPULAR", .name = "Packagist — most-installed Composer packages",
    .category = "cyber", .portal = "https://packagist.org",
    .record_type = "php-package",
    .tags = "\"supplychain\",\"package-registry\",\"php\",\"composer\",\"packagist\",\"dependency-graph\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://packagist.org/explore/popular.json?per_page=100",
    .array_path = "packages",
    .id_keys = "name",
    .interval = 86400,
    .page_max = 30,
    .page_param = "page",
    .title_keys = "name",
    .description = "Composer packages ranked by installs: name, description, the "
      "Packagist URL, total downloads and favers (stars). Packagist's "
      "own statistics endpoint put the registry at 470,134 packages and "
      "202.9 billion downloads on 2026-10-04, so the head of this list "
      "is the set whose compromise would reach the most PHP "
      "deployments." },

  { .id = "PYPI_SIMPLE_PROJECT_FILES", .name = "PyPI — every distribution file for one project (PEP 503 index)",
    .category = "cyber", .portal = "https://pypi.org",
    .record_type = "python-distribution-file",
    .tags = "\"supplychain\",\"package-registry\",\"python\",\"pypi\",\"release-integrity\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://pypi.org/simple/{q}/",
    .description = "The PEP 503 simple index for a project: one anchor per uploaded "
      "FILE — every sdist and every wheel of every version ever "
      "published, each href carrying the SHA-256 fragment of that exact "
      "artefact, plus data-requires-python, data-dist-info-metadata, "
      "data-core-metadata and data-yanked (with the maintainer's yank "
      "reason) as attributes. This is the artefact-level record "
      "installers actually resolve against, and it includes files that "
      "the JSON project API's current release view no longer surfaces." },

  { .id = "PYPI_RECENT_UPDATES_RSS", .name = "PyPI — recently updated projects",
    .category = "cyber", .portal = "https://pypi.org",
    .record_type = "python-package-release",
    .tags = "\"supplychain\",\"package-registry\",\"python\",\"pypi\",\"release-feed\"",
    .mode = HP_XML, .want = HP_ANY, .free_tier = 1,
    .url = "https://pypi.org/rss/updates.xml",
    .array_path = "item",
    .date_keys = "pubDate",
    .id_keys = "guid,link,title",
    .interval = 1800,
    .title_keys = "title",
    .description = "PyPI's update feed: one item per release of an EXISTING project, "
      "with title (name and version), link, description, author and "
      "pubDate. Distinct from the new-packages feed already in the "
      "registry — this is the one a hijacked maintainer account shows "
      "up in, because a hijack publishes a new version of something "
      "that already has installs." },

  { .id = "PYPI_PROJECT_RELEASES_RSS", .name = "PyPI — release feed for one project",
    .category = "cyber", .portal = "https://pypi.org",
    .record_type = "python-package-release",
    .tags = "\"supplychain\",\"package-registry\",\"python\",\"pypi\",\"release-history\"",
    .mode = HP_XML, .want = HP_ANY, .free_tier = 1,
    .url = "https://pypi.org/rss/project/{q}/releases.xml",
    .array_path = "item",
    .date_keys = "pubDate",
    .id_keys = "guid,link,title",
    .title_keys = "title",
    .description = "The per-project release feed: one item per version with title, "
      "link, description, author and pubDate. A project that does not "
      "exist returns HTTP 404, so the feed is about the project asked "
      "for or nothing — and the author field is the uploading identity "
      "as PyPI recorded it at that release." },

  { .id = "MAVENCENTRAL_ARTIFACT_METADATA", .name = "Maven Central — published version list for a groupId/artifactId",
    .category = "cyber", .portal = "https://repo1.maven.org/maven2",
    .record_type = "maven-artifact-version",
    .tags = "\"supplychain\",\"package-registry\",\"java\",\"maven\",\"maven-central\",\"release-history\"",
    .mode = HP_XML, .want = HP_ANY, .free_tier = 1,
    .url = "https://repo1.maven.org/maven2/{q}/maven-metadata.xml",
    .array_path = "versioning",
    .date_keys = "lastUpdated",
    .id_keys = "artifactId+lastUpdated,lastUpdated",
    .title_keys = "latest,release",
    .description = "The repository's own maven-metadata.xml for an artefact path: "
      "groupId, artifactId, the latest and release versions, "
      "lastUpdated, and the complete <versions> list of everything ever "
      "published under that coordinate. Read straight off "
      "repo1.maven.org, so it is what a Maven build actually resolves "
      "against rather than what a search index has indexed." },

  { .id = "MAVENCENTRAL_PATH_LISTING", .name = "Maven Central — directory listing under a repository path",
    .category = "cyber", .portal = "https://repo1.maven.org/maven2",
    .record_type = "maven-repository-path",
    .tags = "\"supplychain\",\"package-registry\",\"java\",\"maven\",\"maven-central\",\"namespace\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://repo1.maven.org/maven2/{q}/",
    .description = "Maven Central serves a real directory listing for every path: "
      "given a groupId as a path, every artifactId beneath it, and "
      "given an artifactId, every version directory plus the actual "
      "jar, pom, sources, javadoc and signature files with their sizes "
      "and upload timestamps. This is how you enumerate a Java "
      "publisher's whole output without a search index deciding what is "
      "worth indexing." },

  { .id = "HACKAGE_RECENT_RSS", .name = "Hackage — recently uploaded Haskell packages",
    .category = "cyber", .portal = "https://hackage.haskell.org",
    .record_type = "haskell-package-release",
    .tags = "\"supplychain\",\"package-registry\",\"haskell\",\"hackage\",\"release-feed\"",
    .mode = HP_XML, .want = HP_ANY, .free_tier = 1,
    .url = "https://hackage.haskell.org/packages/recent.rss",
    .array_path = "item",
    .date_keys = "pubDate",
    .id_keys = "guid,link,title",
    .interval = 3600,
    .title_keys = "title",
    .description = "Hackage's upload feed: one item per package version with title "
      "(name and version), link to the package page, the uploading "
      "account in the description, and pubDate. Hackage names the "
      "uploader in every item, so this is a release feed with "
      "attribution already attached." },

  { .id = "HACKAGE_ALL_PACKAGES", .name = "Hackage — the complete Haskell package namespace",
    .category = "cyber", .portal = "https://hackage.haskell.org",
    .record_type = "haskell-package",
    .tags = "\"supplychain\",\"package-registry\",\"haskell\",\"hackage\",\"namespace\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://hackage.haskell.org/packages/",
    /* Measured on the live page 2026-10-04: 27,695 raw anchors, 19,521
     * distinct after the engine dedupes on the resolved link. 26,444 of the
     * raw anchors are /package/ links — each package is listed once per
     * category it declares, which is why there are more anchors than packages
     * — and the remaining 1,249 are the category and tag pages those
     * groupings link to, i.e. navigation back into this same index. Without
     * href_must those 1,249 stored as record_type "haskell-package", which is
     * a wrong claim about what the record is. They are not dropped data: they
     * are links to the page we already fetched. */
    .href_must = "/package/",
    .interval = 86400,
    .description = "Hackage's full package index as one 3.2 MB document: every "
      "package name on the registry, linked to its page and grouped "
      "under the category tags its authors declared. The complete "
      "namespace, which is what you need to decide whether a name is "
      "unclaimed, newly claimed, or one character from something "
      "established. Measured 2026-10-04: 27,695 anchors on the page, "
      "26,444 of them /package/ links (a package appears once per "
      "category it declares) and 1,249 category/tag pages pointing back "
      "into this same index, which href_must excludes." },

  { .id = "GOPROXY_MODULE_LATEST", .name = "Go module proxy — latest version and its VCS origin",
    .category = "cyber", .portal = "https://proxy.golang.org",
    .record_type = "go-module-version",
    .tags = "\"supplychain\",\"package-registry\",\"go\",\"golang\",\"goproxy\",\"provenance\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://proxy.golang.org/{q}/@latest",
    .date_keys = "Time",
    .id_keys = "Origin.URL+Version,Origin.Hash,Version",
    .title_keys = "Version",
    .description = "What the Go module proxy will currently serve as a module's "
      "latest version, with the proof of where it came from: Version, "
      "Time, and Origin{VCS, URL, Ref, Hash} — the exact git ref and "
      "commit hash the proxy resolved that version from. The commit "
      "hash is the link between a published module version and a "
      "specific commit in a specific repository, which is the one field "
      "that makes a Go release independently verifiable." },

  { .id = "NUGET_REGISTRATION_INDEX", .name = "NuGet — every published version of a package, with the "
      "registry's own commit trail",
    .category = "cyber", .portal = "https://www.nuget.org",
    .record_type = "nuget-package-version",
    .tags = "\"supplychain\",\"package-registry\",\"dotnet\",\"nuget\",\"release-history\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://api.nuget.org/v3/registration5-semver1/{q}/index.json",
    .array_path = "items.items",
    .date_keys = "catalogEntry.published",
    .id_keys = "catalogEntry.id+catalogEntry.version",
    .title_keys = "catalogEntry.id,catalogEntry.version",
    .description = "One record per published version, read from the uncompressed "
      "SemVer1 registration index: catalogEntry.id and version, "
      "published, authors, description, title and summary, tags, "
      "projectUrl, iconUrl, licenseExpression and licenseUrl, "
      "requireLicenseAcceptance, minClientVersion, the listed flag (an "
      "unlisted version is still installable but hidden from search — a "
      "quiet withdrawal), and packageContent, the actual .nupkg URL. "
      "Each entry also carries the registry's own commitId and "
      "commitTimeStamp, which is when that version entered the index "
      "rather than when its author claims it was built." },

  { .id = "JSR_PACKAGE_META", .name = "JSR — package version index",
    .category = "cyber", .portal = "https://jsr.io",
    .record_type = "jsr-package",
    .tags = "\"supplychain\",\"package-registry\",\"javascript\",\"typescript\",\"deno\",\"jsr\",\"release-history\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://jsr.io/@{Q}/meta.json",
    .id_keys = "scope+name+latest",
    .title_keys = "name",
    .description = "JSR's own package metadata: scope, name, the current latest "
      "version, and the complete versions map with each version's "
      "createdAt and its yanked flag. JSR is the registry Deno and "
      "modern TypeScript resolve through, and it is absent from this "
      "tree entirely — so every JSR scope is currently invisible. The "
      "token is {Q} (raw), not {q}: {q} percent-encodes the slash in "
      "scope/name and jsr.io answers /@std%2Fpath/meta.json with HTTP "
      "400. Maven Central and proxy.golang.org both normalise %2F back "
      "to a slash, which is why the two other slash-bearing pivots in "
      "this beat work with {q} — jsr.io does not, and that was measured "
      "both ways." },

  { .id = "JSR_NPM_COMPAT_PACKUMENT", .name = "JSR — npm-compatibility packument for a JSR package",
    .category = "cyber", .portal = "https://npm.jsr.io",
    .record_type = "jsr-package",
    .tags = "\"supplychain\",\"package-registry\",\"javascript\",\"typescript\",\"deno\",\"jsr\",\"release-history\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://npm.jsr.io/@jsr/{q}",
    .id_keys = "name",
    .title_keys = "name",
    .description = "JSR republishes every package through an npm-compatible "
      "endpoint, and the packument there is far richer than meta.json: "
      "name, description, dist-tags, the full versions map with each "
      "version's dependencies, exports map, and dist{tarball, shasum, "
      "integrity}, plus the time map giving the publication timestamp "
      "of every version. The scope and name are joined with a double "
      "underscore (@std/path becomes std__path)." },

  { .id = "PYPI_SIMPLE_INDEX", .name = "PyPI — the complete project namespace (PEP 503 root index)",
    .category = "cyber", .portal = "https://pypi.org",
    .record_type = "python-package",
    .tags = "\"supplychain\",\"package-registry\",\"python\",\"pypi\",\"namespace\",\"typosquat\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://pypi.org/simple/",
    /* WEEKLY, not daily, and that is a measurement rather than a guess. This
     * is the largest single document in the registry: 46.7 MB holding 904,857
     * project anchors, which the engine reads and stores completely — there is
     * no truncation and no discard. A COMPLETE pass was measured end to end:
     *
     *   [hp:PYPI_SIMPLE_INDEX] emitted 904059 of 904059 available across 1 page(s)
     *   [sched] PYPI_SIMPLE_INDEX run rc=0 records=904059 6818250ms stored=904059
     *
     * 904,059 emitted, 904,059 stored, no uid collision, 1 h 54 m of wall
     * clock and 2,269,962,240 bytes of database — 2.51 KB per record. (A
     * separate fetch of the same URL four hours earlier held 904,857
     * anchors; the namespace moves continuously, and the run's own
     * emitted-of-available is the number that matters: it used every anchor
     * it was given.) Every other namespace row in this
     * beat is an order of magnitude smaller (pub.dev 91,326, Hackage 19,515).
     * Daily was the manifest's original value and would have put that cost on
     * every deployment once a day for a namespace that grows by a few hundred
     * names in that time. The per-project hops — PYPI_SIMPLE_PROJECT_FILES
     * and PYPI_PROJECT_RELEASES_RSS — are the targeted reads, and
     * PYPI_RECENT_UPDATES_RSS is the low-latency change feed; this row is the
     * denominator, which only has to be fresh to the week. */
    .interval = 604800,
    .description = "Every project name on PyPI in one PEP 503 document — 46.7 MB of "
      "anchors on 2026-10-04, one per registered project, each linking "
      "to that project's own file index. This is the denominator every "
      "Python typosquat question needs: whether a name is taken, when "
      "it appeared, and what else sits one edit away from it. No search "
      "API gives the whole namespace, and the per-project rows in this "
      "beat (PYPI_SIMPLE_PROJECT_FILES, PYPI_PROJECT_RELEASES_RSS) are "
      "the hops out of it. 904,857 anchors measured in the fetched body; "
      "the engine stores every one it is given: a complete pass measured "
      "904,059 emitted and 904,059 stored with no collision, 1 h 54 m of "
      "wall clock and 2.27 GB of database at 2.51 KB per record — which "
      "is why this row runs weekly rather than daily." },

  { .id = "HEXPM_NEW_PACKAGES", .name = "Hex.pm — newly registered packages",
    .category = "cyber", .portal = "https://hex.pm",
    .record_type = "package",
    .tags = "\"supplychain\",\"package-registry\",\"elixir\",\"erlang\",\"hex\",\"release-feed\",\"typosquat\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://hex.pm/api/packages?sort=inserted_at",
    .array_path = ".",
    .date_keys = "inserted_at",
    .id_keys = "name",
    .interval = 3600,
    .page_max = 60,
    .page_param = "page",
    .title_keys = "name",
    .description = "Hex ordered by inserted_at — first registration rather than last "
      "update, which is the order a typosquat appears in. Each record "
      "is the full package document: name, html_url and docs_html_url, "
      "inserted_at and updated_at, latest_version and "
      "latest_stable_version, the whole releases[] list, downloads "
      "broken down by all/recent/week/day, retirements, the repository, "
      "and meta{} with the description, licences, declared maintainers "
      "and every publisher-supplied link." },

  { .id = "PACKAGIST_VENDOR_RSS", .name = "Packagist — release feed for one vendor",
    .category = "cyber", .portal = "https://packagist.org",
    .record_type = "php-package-release",
    .tags = "\"supplychain\",\"package-registry\",\"php\",\"composer\",\"packagist\",\"vendor-pivot\"",
    .mode = HP_XML, .want = HP_ANY, .free_tier = 1,
    .url = "https://packagist.org/feeds/vendor.{q}.rss",
    .array_path = "item",
    .date_keys = "pubDate",
    .id_keys = "guid,link,title",
    .title_keys = "title",
    .description = "Every release by one Composer VENDOR, not one package: title "
      "(vendor/package and version), link, description, pubDate and the "
      "Dublin Core creator, for all of that organisation's packages in "
      "one feed. This is the organisation-level publish history — what "
      "a vendor shipped, in order — which neither the per-package feed "
      "nor the global release firehose can answer. Note the shape: "
      "packagist.org/feeds/vendor/<name>.rss is HTTP 404 and "
      "vendor.<name>.rss is the live form (both measured)." },
};

HP_REGISTER_TABLE(HP3B32_SUPPLYCHAIN)
