/* collectors/pivot/table/hp3b30_jpcam.c -- batch 30: jpcam
 *
 * Every row here names a machine-readable endpoint that was proof-of-life
 * verified before it was written: fetched over the wire by
 * collectors/verify_feeds.py, parsed in its declared mode, and confirmed to
 * yield at least one real record. Rows whose endpoint answered but produced
 * an empty result set were rejected rather than shipped -- a source that is
 * structurally guaranteed to emit nothing on every run is the exact failure
 * the no-fabrication rule exists to prevent.
 *
 * The observed shape and record count for each row are recorded in
 * docs/verified-sources-batch30.tsv; the candidates that failed are kept as
 * data in docs/rejected-sources-batch30.tsv rather than silently dropped.
 *
 * Generated by tools/gen_hp_batch.py from
 * docs/candidate-sources-batch30.jpcam.txt — scaffolded from it ONCE.
 * This file is the maintained copy from here on: repairs carry the live counts
 * that justify them, which the manifest has nowhere to put. Regenerating over
 * it reverts them, so the generator refuses to without --force. See CLAUDE.md,
 * "Batch tooling".
 */
#include "lib/hpengine.h"

static const hp_source HP3B30_JPCAM[] = {
  { .id = "JO30_CAM_FUKUI_MICHIJOHO_CAMERAS", .name = "Fukui Prefecture Michi-joho Net Fukui — road camera inventory "
      "(JSON)",
    .name_ja = "福井県 みち情報ネットふくい — 道路カメラ一覧（JSON）",
    .category = "webcam", .portal = "https://www.hozen.pref.fukui.lg.jp/hozen/yuki/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"fukui\",\"prefecture\",\"snow\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.hozen.pref.fukui.lg.jp/hozen/yuki/sp/assets/jsons/cameras.json",
    .body_keys = "address",
    .id_keys = "id",
    .interval = 3600,
    .lat_key = "map.icons.0.lat",
    .lon_key = "map.icons.0.lng",
    .timeout_ms = 60000,
    .title_keys = "name",
    .description = "The JSON the Fukui road-preservation SPA loads: a 254 KB "
      "top-level array of 310 camera objects (fetched 2026-09-20, "
      "Last-Modified the same day). Each carries id, name, rname, "
      "category, area, organize (managing office), route, address and a "
      "map.icons list whose first element holds lat/lng and the "
      "still-image path. One record per prefecture-managed road camera "
      "with coordinates." },

  { .id = "JO30_CAM_GIFU_KASEN_CAMERAS", .name = "Gifu Prefecture River Disaster Information — live camera index",
    .name_ja = "岐阜県 川の防災情報 — ライブカメラ一覧",
    .category = "webcam", .portal = "https://www.kasen.pref.gifu.lg.jp/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"gifu\",\"prefecture\",\"disaster\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.kasen.pref.gifu.lg.jp/h/CameraIndex.html",
    .href_must = "_S.html",
    .interval = 3600,
    .description = "Server-rendered index of 138 prefectural river cameras, each "
      "anchor text the river and site name (長良川 芥見, 境川 馬橋 ...) linking "
      "to CameraNNN_S.html which holds the current still. Page "
      "regenerated every few minutes (Last-Modified 2026-09-20 11:23 "
      "UTC at fetch). All 138 anchors carry text, so all 138 emit." },

  { .id = "JO30_CAM_TENRYU_UPPER_RIVER", .name = "MLIT Tenryu River Upper Reaches Office — river live camera list",
    .name_ja = "国土交通省 天竜川上流河川事務所 — ライブカメラ一覧",
    .category = "webcam", .portal = "https://www.cbr.mlit.go.jp/tenjyo/cctv/pc/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"nagano\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.cbr.mlit.go.jp/tenjyo/cctv/pc/list.php",
    .href_must = "detail.php?cameraId=",
    .interval = 3600,
    .description = "List view of the office's CCTV network: 62 distinct "
      "detail.php?cameraId= anchors, each labelled with an index and "
      "site name (1 横川川合流点, 3 伊那富水位観測所 ...). Fetched 2026-09-20, 20 KB "
      "UTF-8 PHP page. Every anchor has text, so 62 records." },

  { .id = "JO30_CAM_TOCHIGI_ROADCCTV", .name = "Tochigi Prefecture road live cameras — camera location list",
    .name_ja = "栃木県 道路ライブカメラ（撮影位置一覧）",
    .category = "webcam", .portal = "https://www.kendo.pref.tochigi.lg.jp/roadinfo/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"tochigi\",\"prefecture\",\"underpass\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.kendo.pref.tochigi.lg.jp/roadcctv/m/menu.html",
    .charset = "shift_jis",
    .href_must = "Portable/",
    .interval = 3600,
    .description = "Shift_JIS mobile menu listing 59 prefectural road cameras "
      "(underpasses and snow points) as ../Portable/NNN_1.htm anchors; "
      "51 carry a site name (宮の内アンダー, 簗瀬アンダー（水戸街道） ...), 8 are "
      "image-only and are dropped by the engine. Last-Modified "
      "2021-03-19 but the Portable pages serve current stills." },

  { .id = "JO30_CAM_KORIYAMA_ROAD_ALL", .name = "MLIT Koriyama National Highway Office — all road live cameras",
    .name_ja = "国土交通省 郡山国道事務所 — すべてのライブカメラ",
    .category = "webcam", .portal = "http://www.thr.mlit.go.jp/koriyama/inform/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"mlit\",\"fukushima\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "http://www.thr.mlit.go.jp/koriyama/inform/index1.html",
    .href_must = "jpeg=",
    .interval = 3600,
    .description = "Single page with 45 anchors straight to the still image on "
      "roadcctv.thr.mlit.go.jp (jpeg?jpeg=775_C00951_l.jpg ...), each "
      "labelled with location and direction (栃福橋 東京方向, 小田川 東京方向 ...). "
      "Fetched 2026-09-20, 27 KB. All 45 labelled." },

  { .id = "JO30_CAM_IIDA_ROAD", .name = "MLIT Iida National Highway Office — road status live cameras",
    .name_ja = "国土交通省 飯田国道事務所 — 道路状況ライブカメラ",
    .category = "webcam", .portal = "https://www.cbr.mlit.go.jp/iikoku/info/live/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"mlit\",\"nagano\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.cbr.mlit.go.jp/iikoku/info/live/index.php",
    .href_must = "cmr=",
    .interval = 3600,
    .description = "PHP index (index.html meta-refreshes here) with 37 distinct "
      "live_area19.html?cmr=CNNN anchors; 31 carry the site name (片平橋, "
      "贄川駅前, 桃岡登坂 ...), 6 are map hot-spots without text and are "
      "dropped. Fetched 2026-09-20, 32 KB." },

  { .id = "JO30_CAM_SAKATA_RIVER", .name = "MLIT Sakata River and National Highway Office — river live "
      "cameras",
    .name_ja = "国土交通省 酒田河川国道事務所 — 河川ライブカメラ",
    .category = "webcam", .portal = "https://www.thr.mlit.go.jp/sakata/river/livecam/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"yamagata\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.thr.mlit.go.jp/sakata/river/livecam/",
    .href_must = "rivercam/",
    .interval = 3600,
    .description = "Mogami-gawa camera list: 22 anchors into "
      "www2.thr.mlit.go.jp/Bumon/J76301/rivercam/cam_23FNNNNN.html, 17 "
      "labelled (最上川河口, 出羽大橋(スワンパーク), 両羽橋 ...), 5 image-only and "
      "dropped. Page Last-Modified 2026-06-02; stills refresh every 10 "
      "minutes per the page text." },

  { .id = "JO30_CAM_YAMAGATA_ROAD", .name = "MLIT Yamagata River and National Highway Office — road live "
      "cameras",
    .name_ja = "国土交通省 山形河川国道事務所 — 道路のライブカメラ",
    .category = "webcam", .portal = "https://www.thr.mlit.go.jp/yamagata/camera-road/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"mlit\",\"yamagata\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.thr.mlit.go.jp/yamagata/camera-road/s-map-13n.html",
    .href_must = "ycam/data/",
    .interval = 3600,
    .description = "Route 13 / 47 / 112 camera map with 19 anchors into "
      "www2.thr.mlit.go.jp/yamagata/ycam/data/NNNNN.html; 15 labelled "
      "(東根宮崎, 村山大橋（南）...), 4 popup-only and dropped. Fetched "
      "2026-09-20, 29 KB." },

  { .id = "JO30_CAM_SAGA_KOKUDO_CCTV", .name = "MLIT Saga National Highway Office — road live cameras",
    .name_ja = "国土交通省 佐賀国道事務所 — 佐賀国道ライブカメラ",
    .category = "webcam", .portal = "https://www.qsr.mlit.go.jp/sakoku/bousai_doro/camera/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"mlit\",\"saga\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.qsr.mlit.go.jp/sakoku/bousai_doro/camera/",
    .href_must = "cctv/",
    .interval = 3600,
    .description = "29 distinct anchors straight to the still "
      "(sakoku/bousai/data/img/cctv/S0NNNN.jpg); 28 labelled through "
      "the img alt (神埼市神埼町 神埼橋 下 国道34号(19k400) ...) plus one text "
      "anchor, so all 29 emit. Page Last-Modified 2026-08-27, 26 KB." },

  { .id = "JO30_CAM_SANRIKU_ROAD", .name = "MLIT Sanriku National Highway Office — Sanriku road live cameras",
    .name_ja = "国土交通省 三陸国道事務所 — 三陸の道路ライブカメラ",
    .category = "webcam", .portal = "http://www.thr.mlit.go.jp/bumon/j73501/gazou/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"mlit\",\"iwate\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "http://www.thr.mlit.go.jp/bumon/j73501/gazou/list.html",
    .href_must = "live_",
    .interval = 3600,
    .description = "25 distinct live_NN.html anchors, each an image anchor whose alt "
      "is the generic カメラ画像, so all 25 emit but with identical titles — "
      "the camera name sits in a sibling text anchor the engine dedupes "
      "onto the same link. Page Last-Modified 2023-03-29, stills "
      "current." },

  { .id = "JO30_CAM_TAKASAKI_RIVER", .name = "MLIT Takasaki River and National Highway Office — river live "
      "cameras",
    .name_ja = "国土交通省 高崎河川国道事務所 — ライブカメラ映像（河川）",
    .category = "webcam", .portal = "https://www.ktr.mlit.go.jp/takasaki/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"gunma\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.ktr.mlit.go.jp/takasaki/takasaki_index020.html",
    .href_must = "takasaki/takasaki00",
    .interval = 3600,
    .description = "10 labelled anchors to per-camera pages takasaki004NN.html "
      "(市役所屋上（烏川・碓氷川）, 城南（烏川）, 寺尾（烏川）...). Last-Modified 2026-01-14. "
      "All 10 emit." },

  { .id = "JO30_CAM_TAKASAKI_ROAD", .name = "MLIT Takasaki River and National Highway Office — road live "
      "cameras",
    .name_ja = "国土交通省 高崎河川国道事務所 — ライブカメラ映像（道路）",
    .category = "webcam", .portal = "https://www.ktr.mlit.go.jp/takasaki/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"mlit\",\"gunma\",\"mikuni\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.ktr.mlit.go.jp/takasaki/takasaki_index009.html",
    .href_must = "takasaki/takasaki00",
    .interval = 3600,
    .description = "9 labelled anchors to Route 17 Mikuni Pass and Karasu-gawa "
      "cameras (新三国トンネル新潟県側（立岩橋）, 法師大橋 ...). Last-Modified 2026-01-14. "
      "All 9 emit." },

  { .id = "JO30_CAM_KANTO_TONE_UPPER_CCTV", .name = "MLIT Kanto Regional Bureau — Tone River upper reaches real-time "
      "camera links",
    .name_ja = "国土交通省 関東地方整備局 — 川のリアルタイム映像（利根川上流）",
    .category = "webcam", .portal = "https://www.ktr.mlit.go.jp/river/bousai/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"tone\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.ktr.mlit.go.jp/river/bousai/river_bousai00000080.html",
    .href_must = "camview.htm",
    .interval = 3600,
    .description = "8 labelled anchors to tonejo/cctv/camview.htm whose query string "
      "carries the camera id and its latitude/longitude (cam1 36.2647 "
      "139.1978 八斗島水位観測所 ...). Last-Modified 2026-09-18. Small but the "
      "only server-rendered list of these gauges' cameras." },

  { .id = "JO30_CAM_SHIZUOKA_FUJI_DOBOKU", .name = "Shizuoka Prefecture Fuji Civil Engineering Office — live cameras",
    .name_ja = "静岡県 富士土木ライブカメラ",
    .category = "webcam", .portal = "http://fujilive.pref.shizuoka.jp/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"shizuoka\",\"prefecture\",\"fuji\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "http://fujilive.pref.shizuoka.jp/",
    .href_must = "cam_",
    .interval = 3600,
    .description = "8 labelled anchors straight to the still "
      "(fuji/01_nehara/cam_nehara.jpg ...), each named by route and "
      "site ((主)富士宮鳴沢線 根原, 富士宮口二合目, 白糸の滝 ...). Fetched 2026-09-20; "
      "images carry a timestamp overlay." },

  { .id = "JO30_CAM_SHIZUOKA_ATAMI_DOBOKU", .name = "Shizuoka Prefecture Atami Civil Engineering Office — live "
      "cameras",
    .name_ja = "静岡県 熱海土木事務所ライブカメラ",
    .category = "webcam", .portal = "http://izu-e.pref.shizuoka.jp/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"shizuoka\",\"prefecture\",\"izu\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "http://izu-e.pref.shizuoka.jp/",
    .href_must = "cam_",
    .interval = 3600,
    .description = "9 labelled anchors to Route 135 and prefectural-road stills "
      "((国)135号 上多賀１(熱海方面), 宇佐美, 笹尻 ...). Same static-page family as "
      "fujilive; fetched 2026-09-20." },

  { .id = "JO30_CAM_SHIZUOKA_SHIMODA_DOBOKU", .name = "Shizuoka Prefecture Shimoda Civil Engineering Office — Michinami "
      "live cameras",
    .name_ja = "静岡県 下田土木 みちなみライブカメラ",
    .category = "webcam", .portal = "http://izu-s.pref.shizuoka.jp/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"shizuoka\",\"prefecture\",\"izu\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "http://izu-s.pref.shizuoka.jp/",
    .href_must = "cam_",
    .interval = 3600,
    .description = "14 labelled anchors to Route 135/136 stills on the south Izu "
      "coast ((国)135号 東伊豆町大川, 河津町浜, 下田市一丁目 ...). Fetched 2026-09-20." },

  { .id = "JO30_CAM_SHIZUOKA_NUMAZU_SNOW", .name = "Shizuoka Prefecture Numazu snow live cameras",
    .name_ja = "静岡県 沼津雪ライブカメラ",
    .category = "webcam", .portal = "http://snowlive.pref.shizuoka.jp/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"shizuoka\",\"prefecture\",\"snow\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "http://snowlive.pref.shizuoka.jp/",
    .href_must = "cam_",
    .interval = 3600,
    .description = "15 labelled anchors to mountain-pass stills ((国)136号 船原, 亀石峠, "
      "(国)469号 十里木, 天城 ...). Fetched 2026-09-20." },

  { .id = "JO30_CAM_HIROSHIMA_CITY_ROAD", .name = "Hiroshima City — road information live cameras",
    .name_ja = "広島市 道路情報ライブカメラ",
    .category = "webcam", .portal = "https://www.city.hiroshima.lg.jp/living/doro-kotsu-kasen/1021384/1026405/1039463.html",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"hiroshima\",\"municipal\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.city.hiroshima.lg.jp/living/doro-kotsu-kasen/1021384/1026405/1039463.html",
    .href_must = "kouiki-nw.jp/device/",
    .interval = 3600,
    .description = "29 labelled anchors to the city's camera host "
      "kouiki-nw.jp/device/?id=NN&token=... (大塚西三丁目, 小田JRアンダー, "
      "大古谷トンネル(上り) ...); stills refresh every 10 minutes per the page. "
      "Fetched 2026-09-20, 61 KB." },

  { .id = "JO30_CAM_GUNMA_ROAD_YOUTUBE", .name = "Gunma Prefecture road live cameras (YouTube live streams)",
    .name_ja = "群馬県 ぐんまの道路ライブカメラ",
    .category = "webcam", .portal = "https://www.pref.gunma.jp/page/610085.html",
    .record_type = "camera-stream",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"gunma\",\"prefecture\",\"youtube\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.pref.gunma.jp/page/610085.html",
    .href_must = "youtube.com/live/",
    .interval = 3600,
    .description = "54 labelled anchors, one per intersection camera, each to a "
      "youtube.com/live/ID stream ((主)前橋館林線 木工団地入口交差点, 駒形跨線橋 ...). "
      "Last-Modified 2026-09-19. Stream URLs rather than stills." },

  { .id = "JO30_CAM_KITASYUTO_R298_SNOW", .name = "MLIT Kita-Shuto National Highway Office — Route 298 snow "
      "monitoring cameras",
    .name_ja = "国土交通省 北首都国道事務所 — R298降雪監視カメラ",
    .category = "webcam", .portal = "https://www.ktr.mlit.go.jp/kitasyuto/public/CCTV.html",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"mlit\",\"saitama\",\"snow\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.ktr.mlit.go.jp/kitasyuto/public/CCTV_L.html",
    .charset = "shift_jis",
    .href_must = "CAM_",
    .interval = 3600,
    .description = "Shift_JIS frame page listing 26 CAM_*.html camera pages with "
      "labelled text (幸魂大橋, 辻アンダー, 芝アンダー ...). Last-Modified "
      "2024-06-05. All 26 emit." },

  { .id = "JO30_CAM_JMA_VOLCANO_CAMERAS", .name = "JMA volcano monitoring cameras — camera selection list",
    .name_ja = "気象庁 火山監視カメラ画像 — カメラ選択一覧",
    .category = "webcam", .portal = "https://www.data.jma.go.jp/vois/data/obs/volcam/volcam.php",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"volcano\",\"jma\",\"disaster\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.data.jma.go.jp/vois/data/obs/volcam/volcam.php",
    .href_must = "VC=",
    .interval = 3600,
    .description = "The selector page behind every JMA volcano camera: 95 labelled "
      "anchors ./volcam.php?VC=NNNNN (アトサヌプリ 北東山麓, 雌阿寒岳 上徹別, 富士山 萩原, 桜島 "
      "牛根 ...). Each target page shows the latest still "
      "(camera/314_82008084/20260920191800.jpg at fetch). All 95 emit." },

  { .id = "JO30_CAM_CHIBA_RIVER_CAMERAS", .name = "Chiba Prefecture river monitoring cameras — list with Kawabou "
      "links",
    .name_ja = "千葉県 河川監視カメラ一覧",
    .category = "webcam", .portal = "https://www.pref.chiba.lg.jp/kakan/h20-suibou/kasencamera.html",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"chiba\",\"prefecture\",\"kawabou\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.pref.chiba.lg.jp/kakan/h20-suibou/kasencamera.html",
    .href_must = "scamId=",
    .interval = 86400,
    .description = "100 distinct anchors, 98 labelled (都川（中央区矢作町）, 村田川（緑区越智町）...), "
      "each to the MLIT Kawabou map with the camera's scamId, sysCamId "
      "and centre lat/lon in the query string. Last-Modified "
      "2026-08-08. The most complete list of Chiba's simple river "
      "cameras." },

  { .id = "JO30_CAM_OITA_RIVER_CAMERAS", .name = "Oita Prefecture river disaster information — monitoring camera "
      "list",
    .name_ja = "大分県 河川防災情報 — 監視カメラ情報一覧",
    .category = "webcam", .portal = "https://river.pref.oita.jp/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"oita\",\"prefecture\",\"disaster\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://river.pref.oita.jp/mobile/servlet/mobile.ServletBousaiMobileOnline?sv=5&dk=15",
    .charset = "shift_jis",
    .href_must = "sv=4",
    .interval = 3600,
    .description = "Shift_JIS mobile list of 153 camera anchors (sv=4 detail pages), "
      "145 labelled by bridge or site (蛎瀬橋, 自見大橋, 桜洲橋 ...). Fetched "
      "2026-09-20, 25 KB, no bot wall. The largest single prefectural "
      "river-camera list found." },

  { .id = "JO30_CAM_KAGOSHIMA_PREF_LIVE_LIST", .name = "Kagoshima Prefecture — live cameras in the prefecture (link "
      "list)",
    .name_ja = "鹿児島県 県内のライブカメラ一覧",
    .category = "webcam", .portal = "https://www.pref.kagoshima.jp/bosai/saigai/live.html",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"volcano\",\"river\",\"kagoshima\",\"prefecture\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.pref.kagoshima.jp/bosai/saigai/live.html",
    .href_must = "bousai",
    .interval = 86400,
    .description = "75 labelled anchors: 56 prefectural river/volcano cameras on "
      "doboku-bousai.pref.kagoshima.jp (大浪池(霧島市)から見た霧島山 ...), 11 Osumi "
      "office Sakurajima sabo cameras (黒神川１号ダム上流左岸 ...), plus portal "
      "links. The prefecture's own camera host sits behind an Incapsula "
      "wall, so this list page is the reachable inventory. "
      "Last-Modified 2026-04-11." },

  { .id = "JO30_CAM_HAMADA_RIVER_VIEW", .name = "MLIT Hamada River and National Highway Office — river camera "
      "viewer list",
    .name_ja = "国土交通省 浜田河川国道事務所 — 浜田河川映像",
    .category = "webcam", .portal = "http://www.cgr.mlit.go.jp/hamada/r_view/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"shimane\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "http://www.cgr.mlit.go.jp/hamada/r_view/main.php",
    .href_must = "viewer.php?cid=",
    .interval = 3600,
    .description = "17 cameras listed twice (an image anchor and a text anchor per "
      "viewer.php?cid=N); the 17 text anchors are labelled (川平水位観測所, "
      "江の川取水場, 下の原排水樋門 ...). Fetched 2026-09-20 after the index "
      "redirect. The text anchors hrefs carry a leading space in the "
      "source, and the engine run 2026-09-21 (emitted 17, stored 17) "
      "kept it: stored links read r_view/ ./viewer.php?cid=N — the href "
      "needs whitespace trimming engine-side." },

  { .id = "JO30_CAM_KAGAWA_KASEN_CAMERAS", .name = "Kagawa Prefecture river monitoring cameras",
    .name_ja = "香川県 河川監視カメラ",
    .category = "webcam", .portal = "http://kasencamera.pref.kagawa.lg.jp/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"kagawa\",\"prefecture\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "http://kasencamera.pref.kagawa.lg.jp/",
    .href_must = "/index/detail/",
    .interval = 3600,
    .description = "18 /index/detail/N.html anchors, 14 labelled through the img alt "
      "(与田山, 弁天橋, 井戸川橋 ...), 4 without alt are dropped. Fetched "
      "2026-09-20, 29 KB. The prefecture's xlsx export of the same list "
      "answers HTTP 500." },

  { .id = "JO30_CAM_TOKUSHIMA_LIVECAM_INVENTORY", .name = "Tokushima Prefecture open data — live camera inventory (CSV)",
    .name_ja = "徳島県オープンデータ ライブカメラ等一覧",
    .category = "webcam", .portal = "https://opendata.pref.tokushima.lg.jp/dataset/35.html",
    .record_type = "camera-location",
    .tags = "\"japan\",\"webcam\",\"camera\",\"tokushima\",\"prefecture\",\"opendata\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://opendata.pref.tokushima.lg.jp/dataset/35/resource/13739/%E3%83%A9%E3%82%A4%E3%83%96%E3%82%AB%E3%83%A1%E3%83%A9%E7%AD%89%E4%B8%80%E8%A6%A7%EF%BC%88202211%EF%BC%89.csv",
    .body_keys = "備考",
    .csv_skip_lines = 1,
    .id_keys = "ID",
    .interval = 604800,
    .lat_key = "緯度",
    .link_keys = "ＵＲＬ",
    .lon_key = "経度",
    .title_keys = "名称",
    .description = "56 KB CSV dated 2022-11-16 (Last-Modified 2022-11-24): 166 "
      "camera rows after a one-line banner, columns ID, 名称, 設置元, "
      "住所（設置場所）, 緯度, 経度, ＵＲＬ, 備考, その他URL, 出典元, 出典元URL. Every camera in "
      "Tokushima the prefecture could identify — MLIT, prefecture, "
      "municipalities and private — with coordinates and the "
      "image/stream URL." },

  { .id = "JO30_CAM_AICHI_KASEN_CAMERAS", .name = "Aichi Prefecture River Disaster Information — river monitoring "
      "camera list",
    .name_ja = "愛知県 川の防災情報 — 河川監視カメラ一覧",
    .category = "webcam", .portal = "https://www.kasen-aichi.jp/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"aichi\",\"prefecture\",\"disaster\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.kasen-aichi.jp/sp/CameraList.html",
    .href_must = "CameraImage_",
    .interval = 3600,
    .description = "Smartphone list page regenerated every few minutes "
      "(Last-Modified 2026-09-20 11:42 UTC): 84 "
      "CameraImage_N_NNNNNN.html anchors, every one labelled with "
      "address and river/site (名古屋市中川区下之一色町字三角地内 新川下之一色 ...). All 84 "
      "emit." },

  { .id = "JO30_CAM_AOMORI_KASENSABO_CAMERAS", .name = "Aomori Prefecture River and Sabo Information System — river "
      "monitoring cameras (all areas)",
    .name_ja = "青森県河川砂防情報提供システム — 河川監視カメラ（全域）",
    .category = "webcam", .portal = "https://www.kasensabo.bousai.pref.aomori.jp/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"aomori\",\"prefecture\",\"disaster\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.kasensabo.bousai.pref.aomori.jp/smart/servlet/bousaiweb.servletBousaiContents?style=itv_area&dk=15&it=1&nw=1&mp=1&fn=0&no=0&sv=3&ga=0&gk=4",
    .charset = "shift_jis",
    .href_must = "&sn=",
    .interval = 3600,
    .description = "The all-areas (fn=0) servlet view, Shift_JIS: 126 distinct "
      "camera anchors (style=itv and sn=N), 102 labelled by site "
      "(駒込川合流点付近, 筒井小学校付近, 横内川合流点付近 ...), 24 image-only and dropped. "
      "The seven per-area views (fn=1..7) sum to the same set. Fetched "
      "2026-09-20." },

  { .id = "JO30_CAM_KANAGAWA_SUIBOU_CAM_YOKOHAMA", .name = "Kanagawa Prefecture rainfall and water-level information — "
      "camera list, Yokohama area",
    .name_ja = "神奈川県雨量水位情報 — カメラ一覧（横浜）",
    .category = "webcam", .portal = "https://www.pref.kanagawa.jp/sys/suibou/web_general/suibou_joho/html/camera/list/p20101_11.html",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"kanagawa\",\"prefecture\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.pref.kanagawa.jp/sys/suibou/web_general/suibou_joho/html/camera/list/p20101_11.html",
    .href_must = "/camera/detail/",
    .interval = 3600,
    .description = "Area list of the prefectural river-camera system: 20 labelled "
      "anchors into html/camera/detail/ (早淵川 鍛冶橋付近, 大熊川 大竹上橋付近, 帷子川 "
      "宮崎橋付近 ...); stills refresh about every 2 minutes per the system. "
      "Regenerated at fetch (Last-Modified 2026-09-20). The seven area "
      "pages p20101_11..17 partition the whole network." },

  { .id = "JO30_CAM_KANAGAWA_SUIBOU_CAM_KAWASAKI", .name = "Kanagawa Prefecture rainfall and water-level information — "
      "camera list, Kawasaki area",
    .name_ja = "神奈川県雨量水位情報 — カメラ一覧（川崎）",
    .category = "webcam", .portal = "https://www.pref.kanagawa.jp/sys/suibou/web_general/suibou_joho/html/camera/list/p20101_12.html",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"kanagawa\",\"prefecture\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.pref.kanagawa.jp/sys/suibou/web_general/suibou_joho/html/camera/list/p20101_12.html",
    .href_must = "/camera/detail/",
    .interval = 3600,
    .description = "Kawasaki area page of the same system: 12 labelled camera "
      "anchors into html/camera/detail/. Fetched 2026-09-20." },

  { .id = "JO30_CAM_KANAGAWA_SUIBOU_CAM_SHONAN", .name = "Kanagawa Prefecture rainfall and water-level information — "
      "camera list, Shonan area",
    .name_ja = "神奈川県雨量水位情報 — カメラ一覧（湘南）",
    .category = "webcam", .portal = "https://www.pref.kanagawa.jp/sys/suibou/web_general/suibou_joho/html/camera/list/p20101_13.html",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"kanagawa\",\"prefecture\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.pref.kanagawa.jp/sys/suibou/web_general/suibou_joho/html/camera/list/p20101_13.html",
    .href_must = "/camera/detail/",
    .interval = 3600,
    .description = "Shonan area page: 35 labelled camera anchors into "
      "html/camera/detail/, the largest of the seven areas. Fetched "
      "2026-09-20." },

  { .id = "JO30_CAM_KANAGAWA_SUIBOU_CAM_MIURA", .name = "Kanagawa Prefecture rainfall and water-level information — "
      "camera list, Miura Peninsula",
    .name_ja = "神奈川県雨量水位情報 — カメラ一覧（三浦半島）",
    .category = "webcam", .portal = "https://www.pref.kanagawa.jp/sys/suibou/web_general/suibou_joho/html/camera/list/p20101_14.html",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"kanagawa\",\"prefecture\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.pref.kanagawa.jp/sys/suibou/web_general/suibou_joho/html/camera/list/p20101_14.html",
    .href_must = "/camera/detail/",
    .interval = 3600,
    .description = "Miura Peninsula area page: 9 labelled camera anchors into "
      "html/camera/detail/. Fetched 2026-09-20." },

  { .id = "JO30_CAM_KANAGAWA_SUIBOU_CAM_SAGAMIHARA", .name = "Kanagawa Prefecture rainfall and water-level information — "
      "camera list, Sagamihara area",
    .name_ja = "神奈川県雨量水位情報 — カメラ一覧（相模原）",
    .category = "webcam", .portal = "https://www.pref.kanagawa.jp/sys/suibou/web_general/suibou_joho/html/camera/list/p20101_15.html",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"kanagawa\",\"prefecture\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.pref.kanagawa.jp/sys/suibou/web_general/suibou_joho/html/camera/list/p20101_15.html",
    .href_must = "/camera/detail/",
    .interval = 3600,
    .description = "Sagamihara area page: 9 labelled camera anchors into "
      "html/camera/detail/. Fetched 2026-09-20." },

  { .id = "JO30_CAM_KANAGAWA_SUIBOU_CAM_KENO", .name = "Kanagawa Prefecture rainfall and water-level information — "
      "camera list, Ken-o area",
    .name_ja = "神奈川県雨量水位情報 — カメラ一覧（県央）",
    .category = "webcam", .portal = "https://www.pref.kanagawa.jp/sys/suibou/web_general/suibou_joho/html/camera/list/p20101_16.html",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"kanagawa\",\"prefecture\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.pref.kanagawa.jp/sys/suibou/web_general/suibou_joho/html/camera/list/p20101_16.html",
    .href_must = "/camera/detail/",
    .interval = 3600,
    .description = "Ken-o area page: 19 labelled camera anchors into "
      "html/camera/detail/ (玉川 玉川橋付近, 細田川 森の里付近 ...). Fetched "
      "2026-09-20." },

  { .id = "JO30_CAM_KANAGAWA_SUIBOU_CAM_ASHIGARA", .name = "Kanagawa Prefecture rainfall and water-level information — "
      "camera list, Ashigara-kami area",
    .name_ja = "神奈川県雨量水位情報 — カメラ一覧（足柄上）",
    .category = "webcam", .portal = "https://www.pref.kanagawa.jp/sys/suibou/web_general/suibou_joho/html/camera/list/p20101_17.html",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"kanagawa\",\"prefecture\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.pref.kanagawa.jp/sys/suibou/web_general/suibou_joho/html/camera/list/p20101_17.html",
    .href_must = "/camera/detail/",
    .interval = 3600,
    .description = "Ashigara-kami area page: 16 labelled camera anchors into "
      "html/camera/detail/. Fetched 2026-09-20." },

  { .id = "JO30_CAM_HIGASHIURA_TOWN_RIVER", .name = "Higashiura Town (Aichi) — river monitoring cameras",
    .name_ja = "愛知県東浦町 河川監視カメラ",
    .category = "webcam", .portal = "https://www.river.town.aichi-higashiura.lg.jp/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"aichi\",\"municipal\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.river.town.aichi-higashiura.lg.jp/",
    .href_must = "action=",
    .interval = 3600,
    .description = "Town-run camera site: 12 labelled ?page=list&action=NAME "
      "anchors, one per bridge camera (豆搗川・豆搗橋, 蕨橋, 正戸橋 ...). Fetched "
      "2026-09-20, 25 KB. Small but every camera the town operates." },

  { .id = "JO30_CAM_FUKUYAMA_ASHIDA_RIVER", .name = "MLIT Fukuyama River Office — Ashida River system live cameras",
    .name_ja = "国土交通省 福山河川事務所 — 芦田川水系ライブカメラ",
    .category = "webcam", .portal = "https://www.cgr.mlit.go.jp/fukuyama/live/river/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"hiroshima\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.cgr.mlit.go.jp/fukuyama/live/river/",
    .href_must = "select.php?id=",
    .interval = 3600,
    .description = "PHP index with 40 select.php?id=N anchors, 39 labelled by site "
      "(阿字川合流部, 矢野原水位観測所, 矢野原水位観測所（量水板拡大表示）...); the page states stills "
      "refresh every 10 minutes. Fetched 2026-09-20, 11 KB." },

  { .id = "JO30_CAM_EDOGAWA_LIVE_MOBILE", .name = "MLIT Edogawa River Office — Edogawa live image list (mobile)",
    .name_ja = "国土交通省 江戸川河川事務所 — ライブ画像(江戸川)",
    .category = "webcam", .portal = "https://www.ktr.mlit.go.jp/edogawa/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"edogawa\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.ktr.mlit.go.jp/edogawa/m/live/index.htm",
    .href_must = "p_",
    .interval = 3600,
    .description = "Mobile index of 22 p_NAME.htm camera pages, all labelled with "
      "municipality and site (野田市関宿三軒家 関宿城, 幸手市西関宿, 春日部市下吉妻 ...). "
      "Last-Modified 2021-05-26; target pages serve current stills. All "
      "22 emit." },

  { .id = "JO30_CAM_KEIHIN_TAMAGAWA", .name = "MLIT Keihin River Office — Tama River live cameras",
    .name_ja = "国土交通省 京浜河川事務所 — ライブカメラ(多摩川)",
    .category = "webcam", .portal = "https://www.ktr.mlit.go.jp/keihin/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"tokyo\",\"kawabou\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.ktr.mlit.go.jp/keihin/keihin01457.html",
    .href_must = "scamId=",
    .interval = 86400,
    .description = "31 labelled anchors, one per Tama River camera "
      "(1.多摩川河口水位観測所(川崎市川崎区殿町) ...), each to the MLIT Kawabou map "
      "carrying scamId, sysCamId and centre lat/lon. Last-Modified "
      "2025-09-09." },

  { .id = "JO30_CAM_KEIHIN_TSURUMIGAWA", .name = "MLIT Keihin River Office — Tsurumi River live cameras",
    .name_ja = "国土交通省 京浜河川事務所 — ライブカメラ(鶴見川)",
    .category = "webcam", .portal = "https://www.ktr.mlit.go.jp/keihin/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"kanagawa\",\"kawabou\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.ktr.mlit.go.jp/keihin/keihin01458.html",
    .href_must = "scamId=",
    .interval = 86400,
    .description = "11 labelled anchors, one per Tsurumi River camera "
      "(1.鶴見川橋上流(横浜市鶴見区鶴見中央2丁目) ...), each to the Kawabou map with "
      "scamId and centre lat/lon. Last-Modified 2025-01-14." },

  { .id = "JO30_CAM_OKAYAMA_RIVER_CAMERAS", .name = "Okayama Prefecture river monitoring cameras (River Division "
      "list)",
    .name_ja = "岡山県の河川監視カメラ（河川課）",
    .category = "webcam", .portal = "https://www.pref.okayama.jp/page/670433.html",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"okayama\",\"prefecture\",\"kawabou\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.pref.okayama.jp/page/670433.html",
    .href_must = "scamId=",
    .interval = 86400,
    .description = "77 labelled anchors (旭川／岡山市北区 ...), one per prefectural river "
      "camera, each to the Kawabou map with scamId, sysCamId and centre "
      "lat/lon. Last-Modified 2026-09-20, 56 KB." },

  { .id = "JO30_CAM_OKAYAMA_COAST_CAMERAS", .name = "Okayama Prefecture coastal live cameras (Crisis Management "
      "Division)",
    .name_ja = "岡山沿岸ライブカメラ（危機管理課）",
    .category = "webcam", .portal = "https://www.pref.okayama.jp/page/764167.html",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"coast\",\"port\",\"okayama\",\"prefecture\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.pref.okayama.jp/page/764167.html",
    .href_must = "kikikanri.pref.okayama.jp/screen_",
    .interval = 86400,
    .description = "7 labelled anchors to the prefecture's coastal camera screens on "
      "kikikanri.pref.okayama.jp (日生地区カメラ, 牛窓地区カメラ, 小串地区カメラ ...). "
      "Last-Modified 2026-09-20. Small, but the only Seto Inland Sea "
      "coast camera list on a prefectural host found." },

  { .id = "JO30_CAM_NIIGATA_LIVECAM", .name = "Niigata LIVE Camera — prefecture-wide road camera map",
    .name_ja = "にいがたLIVEカメラ",
    .category = "webcam", .portal = "https://www.live-cam.pref.niigata.jp/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"niigata\",\"prefecture\",\"snow\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.live-cam.pref.niigata.jp/",
    .href_must = "camera/pc/",
    .interval = 3600,
    .timeout_ms = 60000,
    .description = "188 KB map page with 442 distinct camera anchors straight to the "
      "still (camera/pc/NAME.jpg); each anchor is image-only but "
      "carries a title attribute with route and site (一般国道３４５号 寒川 ...), "
      "which the engine uses as the label: run 2026-09-21 emitted 442, "
      "stored 442, titles are the site names (柏崎市西山町坂田, 小阿賀野川 新潟市江南区二本木 "
      "...). Managed by 新潟県土木部 with MLIT and NEXCO cameras mixed in per "
      "the anchor class metadata. Fetched 2026-09-20." },

  { .id = "JO30_CAM_MIE_RIVER_CAMERAS", .name = "MLIT Mie River and National Highway Office — river live camera "
      "list",
    .name_ja = "国土交通省 三重河川国道事務所 — 河川ライブカメラ一覧",
    .category = "webcam", .portal = "https://www.cbr.mlit.go.jp/mie/live/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"mie\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.cbr.mlit.go.jp/mie/live/list_river.php",
    .href_must = "detail_river.php",
    .interval = 3600,
    .description = "103 detail_river.php?cameraId= anchors grouped by river (鈴鹿川, "
      "雲出川, 櫛田川, 宮川 ...), each an image anchor followed inside its li "
      "by the river-km, municipality and site text (鈴鹿川左岸0.2k 四日市市石原町 "
      "鈴鹿川河口部) that the engine takes as the label; run 2026-09-21 "
      "emitted 103, stored 103. Fetched 2026-09-20, 40 KB." },

  { .id = "JO30_CAM_MIE_ROAD_CAMERAS", .name = "MLIT Mie River and National Highway Office — road live camera "
      "list",
    .name_ja = "国土交通省 三重河川国道事務所 — 道路ライブカメラ一覧",
    .category = "webcam", .portal = "https://www.cbr.mlit.go.jp/mie/live/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"mlit\",\"mie\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.cbr.mlit.go.jp/mie/live/list_road.php",
    .href_must = "detail_road.php",
    .interval = 3600,
    .description = "38 detail_road.php?cameraId= anchors in the same li structure as "
      "the river list, site text following each image anchor; run "
      "2026-09-21 emitted 38, stored 38 (34.9kp津市雲出島貫町雲出大橋 ...). "
      "Fetched 2026-09-20, 29 KB." },

  { .id = "JO30_CAM_HOKKAIDO_RIVER_ISHIKARI_UPPER", .name = "Hokkaido Development Bureau river real-time system — Ishikari "
      "River upper",
    .name_ja = "北海道開発局 河川リアルタイム情報システム — 石狩川上流",
    .category = "webcam", .portal = "https://info-dam.hdb.hkd.mlit.go.jp/river/index.htm",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"hokkaido\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://info-dam.hdb.hkd.mlit.go.jp/river/area_01.htm",
    .href_must = "detail/",
    .interval = 3600,
    .description = "Area map with 14 detail/NAME.htm gauge/CCTV anchors, each an "
      "empty anchor followed by a span with the site name inside its "
      "icon div. Fetched 2026-09-20." },

  { .id = "JO30_CAM_HOKKAIDO_RIVER_ISHIKARI_LOWER", .name = "Hokkaido Development Bureau river real-time system — Ishikari "
      "River lower",
    .name_ja = "北海道開発局 河川リアルタイム情報システム — 石狩川下流",
    .category = "webcam", .portal = "https://info-dam.hdb.hkd.mlit.go.jp/river/index.htm",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"hokkaido\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://info-dam.hdb.hkd.mlit.go.jp/river/area_02.htm",
    .href_must = "detail/",
    .interval = 3600,
    .description = "Area map with 50 detail/NAME.htm anchors, the largest of the ten "
      "area pages. Engine run 2026-09-21: emitted 25, stored 25 with "
      "site titles (橋本町, 裏の沢, 多度志, 雨竜橋 ...); the other 25 anchors keep "
      "their name only as data-title on the PARENT div (empty spans "
      "inside the anchor), which the label rule does not read. Fetched "
      "2026-09-20, 42 KB." },

  { .id = "JO30_CAM_HOKKAIDO_RIVER_SHIRIBESHI_TOSHIBETSU", .name = "Hokkaido Development Bureau river real-time system — "
      "Shiribeshi-Toshibetsu River",
    .name_ja = "北海道開発局 河川リアルタイム情報システム — 後志利別川",
    .category = "webcam", .portal = "https://info-dam.hdb.hkd.mlit.go.jp/river/index.htm",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"hokkaido\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://info-dam.hdb.hkd.mlit.go.jp/river/area_03.htm",
    .href_must = "detail/",
    .interval = 3600,
    .description = "Area map with 5 detail/ anchors. Fetched 2026-09-21." },

  { .id = "JO30_CAM_HOKKAIDO_RIVER_MUKAWA_SARU", .name = "Hokkaido Development Bureau river real-time system — Mu River "
      "and Saru River",
    .name_ja = "北海道開発局 河川リアルタイム情報システム — 鵡川・沙流川",
    .category = "webcam", .portal = "https://info-dam.hdb.hkd.mlit.go.jp/river/index.htm",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"hokkaido\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://info-dam.hdb.hkd.mlit.go.jp/river/area_05.htm",
    .href_must = "detail/",
    .interval = 3600,
    .description = "Area map with 5 detail/ anchors. Fetched 2026-09-21." },

  { .id = "JO30_CAM_HOKKAIDO_RIVER_KUSHIRO", .name = "Hokkaido Development Bureau river real-time system — Kushiro "
      "River",
    .name_ja = "北海道開発局 河川リアルタイム情報システム — 釧路川",
    .category = "webcam", .portal = "https://info-dam.hdb.hkd.mlit.go.jp/river/index.htm",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"hokkaido\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://info-dam.hdb.hkd.mlit.go.jp/river/area_06.htm",
    .href_must = "detail/",
    .interval = 3600,
    .description = "Area map with 5 detail/ anchors. Fetched 2026-09-21." },

  { .id = "JO30_CAM_HOKKAIDO_RIVER_TOKACHI", .name = "Hokkaido Development Bureau river real-time system — Tokachi "
      "River",
    .name_ja = "北海道開発局 河川リアルタイム情報システム — 十勝川",
    .category = "webcam", .portal = "https://info-dam.hdb.hkd.mlit.go.jp/river/index.htm",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"hokkaido\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://info-dam.hdb.hkd.mlit.go.jp/river/area_07.htm",
    .href_must = "detail/",
    .interval = 3600,
    .description = "Area map with 17 detail/ anchors. Fetched 2026-09-21." },

  { .id = "JO30_CAM_HOKKAIDO_RIVER_ABASHIRI_TOKORO", .name = "Hokkaido Development Bureau river real-time system — Abashiri, "
      "Tokoro, Yubetsu and Shokotsu Rivers",
    .name_ja = "北海道開発局 河川リアルタイム情報システム — 網走川・常呂川・湧別川・渚滑川",
    .category = "webcam", .portal = "https://info-dam.hdb.hkd.mlit.go.jp/river/index.htm",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"hokkaido\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://info-dam.hdb.hkd.mlit.go.jp/river/area_08.htm",
    .href_must = "detail/",
    .interval = 3600,
    .description = "Area map with 12 detail/ anchors. Fetched 2026-09-21." },

  { .id = "JO30_CAM_HOKKAIDO_RIVER_TESHIO", .name = "Hokkaido Development Bureau river real-time system — Teshio "
      "River",
    .name_ja = "北海道開発局 河川リアルタイム情報システム — 天塩川",
    .category = "webcam", .portal = "https://info-dam.hdb.hkd.mlit.go.jp/river/index.htm",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"hokkaido\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://info-dam.hdb.hkd.mlit.go.jp/river/area_09.htm",
    .href_must = "detail/",
    .interval = 3600,
    .description = "Area map with 12 detail/ anchors. Fetched 2026-09-21." },

  { .id = "JO30_CAM_YODOGAWA_LIVE", .name = "MLIT Yodogawa River Office — live cameras",
    .name_ja = "国土交通省 淀川河川事務所 — ライブカメラ",
    .category = "webcam", .portal = "https://www.kkr.mlit.go.jp/yodogawa/bousai/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"osaka\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.kkr.mlit.go.jp/yodogawa/bousai/live.php",
    .href_must = "live_detail.php",
    .interval = 3600,
    .description = "12 live_detail.php?id=CNNNNN image anchors; stills every 10 "
      "minutes plus a frame-by-frame replay per the page; run "
      "2026-09-21 emitted 12, stored 12 (4.8k地点淀川大橋（左岸）, 26.6k地点枚方大橋 "
      "...). Fetched 2026-09-20, 26 KB." },

  { .id = "JO30_CAM_YAMATO_RIVER_LIVE", .name = "MLIT Yamato River Office — live cameras",
    .name_ja = "国土交通省 大和川河川事務所 — ライブカメラ",
    .category = "webcam", .portal = "https://www.kkr.mlit.go.jp/yamato/bousai/livecamera/index.html",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"nara\",\"osaka\",\"kawabou\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.kkr.mlit.go.jp/yamato/bousai/livecamera/index.html",
    .href_must = "scamId=",
    .interval = 86400,
    .description = "8 numbered map-pin anchors to the Kawabou map with scamId and "
      "centre lat/lon; run 2026-09-21 emitted 8, stored 8, titled "
      "number plus site (4 藤井, 3 道明寺 ...). Last-Modified 2026-03-30." },

  { .id = "JO30_CAM_HIMEJI_KAKOGAWA", .name = "MLIT Himeji River and National Highway Office — Kako River live "
      "cameras",
    .name_ja = "国土交通省 姫路河川国道事務所 — ライブカメラ（加古川）",
    .category = "webcam", .portal = "https://www.kkr.mlit.go.jp/himeji/bousai/livecam/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"hyogo\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.kkr.mlit.go.jp/himeji/bousai/livecam/kakogawa.html",
    .href_must = "kakocam_map/",
    .interval = 3600,
    .description = "7 kakocam_map/NAME.html numbered anchors; run 2026-09-21 emitted "
      "7, stored 7, titled number plus site (1 藍屋（向島）, 2 本町 ...). "
      "Last-Modified 2026-07-21." },

  { .id = "JO30_CAM_HIMEJI_IBOGAWA", .name = "MLIT Himeji River and National Highway Office — Ibo River live "
      "cameras",
    .name_ja = "国土交通省 姫路河川国道事務所 — ライブカメラ（揖保川）",
    .category = "webcam", .portal = "https://www.kkr.mlit.go.jp/himeji/bousai/livecam/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"hyogo\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.kkr.mlit.go.jp/himeji/bousai/livecam/ibo.html",
    .href_must = "cam_map/",
    .interval = 3600,
    .description = "7 ibocam_map/NAME.html numbered anchors. Fetched 2026-09-21." },

  { .id = "JO30_CAM_HIMEJI_R2", .name = "MLIT Himeji River and National Highway Office — Route 2 live "
      "cameras",
    .name_ja = "国土交通省 姫路河川国道事務所 — ライブカメラ（国道2号）",
    .category = "webcam", .portal = "https://www.kkr.mlit.go.jp/himeji/bousai/livecam/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"mlit\",\"hyogo\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.kkr.mlit.go.jp/himeji/bousai/livecam/r2.html",
    .href_must = "cam_map/",
    .interval = 3600,
    .description = "25 r2cam_map anchors along National Route 2; run 2026-09-21 "
      "emitted 25, stored 25 (15 城山東, 6 別所PA（上り）...). Fetched "
      "2026-09-21." },

  { .id = "JO30_CAM_HIMEJI_R29", .name = "MLIT Himeji River and National Highway Office — Route 29 live "
      "cameras",
    .name_ja = "国土交通省 姫路河川国道事務所 — ライブカメラ（国道29号）",
    .category = "webcam", .portal = "https://www.kkr.mlit.go.jp/himeji/bousai/livecam/",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"mlit\",\"hyogo\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.kkr.mlit.go.jp/himeji/bousai/livecam/r29.html",
    .href_must = "cam_map/",
    .interval = 3600,
    .description = "26 cam_map anchors along National Route 29. Fetched 2026-09-21." },

  { .id = "JO30_CAM_SHINANO_LOWER_LIVECAM", .name = "MLIT Shinano River Lower Reaches Office — live cameras",
    .name_ja = "国土交通省 信濃川下流河川事務所 — ライブカメラ",
    .category = "webcam", .portal = "https://www.hrr.mlit.go.jp/shinage/livecam.html",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"river\",\"mlit\",\"niigata\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.hrr.mlit.go.jp/shinage/livecam.html",
    .href_must = "bosai/img/",
    .interval = 3600,
    .description = "8 image anchors straight to stills on "
      "hrr.mlit.go.jp/bosai/img/NNNNNN.jpg; run 2026-09-21 emitted 8, "
      "stored 8 with site titles (保明新田, 荒町, 蒲原大堰下流 ...). Last-Modified "
      "2021-08-03." },

  { .id = "JO30_CAM_KUMAMOTO_ROUTE57_CAMERAS", .name = "MLIT Kumamoto River and National Highway Office — Route 57 live "
      "cameras",
    .name_ja = "国土交通省 熊本河川国道事務所 — 国道57号ライブカメラ",
    .category = "webcam", .portal = "https://www.qsr.mlit.go.jp/kumamoto/bousai/road_live/index.html",
    .record_type = "camera-feed",
    .tags = "\"japan\",\"webcam\",\"camera\",\"road\",\"mlit\",\"kumamoto\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.qsr.mlit.go.jp/kumamoto/bousai/road_live/road_live02.html",
    .href_must = "camImage.php",
    .interval = 3600,
    .description = "12 distinct kmmWeb/camImage.php?no=2_N image anchors along Route "
      "57 (the Route 3 and 208 pages have 4 and 1); engine run "
      "2026-09-21 emitted 12, stored 12, titles from the following cell "
      "text (滝室Ａ, 産山Ｃ, 波野Ｂ, 宇土市長浜 — with a trailing &nbsp; entity). "
      "Last-Modified 2026-09-18." },

  { .id = "JO30_CAM_TOKYO_RITO_PORT_STREAMS", .name = "Tokyo Bureau of Port and Harbor — remote-island port information "
      "platform camera streams",
    .name_ja = "東京都港湾局 離島港湾情報プラットフォーム — カメラ映像",
    .category = "webcam", .portal = "https://open.ritokouwan-infopf.metro.tokyo.lg.jp/",
    .record_type = "camera-stream",
    .tags = "\"japan\",\"webcam\",\"camera\",\"port\",\"tokyo\",\"islands\",\"youtube\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://open.ritokouwan-infopf.metro.tokyo.lg.jp/",
    .href_must = "youtube.com",
    .interval = 86400,
    .description = "11 YouTube playlist anchors, one per Izu/Ogasawara island port "
      "camera set (式根島 ...), 6 with text and 5 image-only; run "
      "2026-09-21 emitted 11, stored 11, all titled by island (式根島, "
      "神津島, 三宅島 ...). Last-Modified 2026-03-16." },
};

HP_REGISTER_TABLE(HP3B30_JPCAM)
