/* collectors/pivot/table/hp3b21_delaw.c -- batch 21: delaw
 *
 * Every row here names a machine-readable endpoint that was proof-of-life
 * verified before it was written: fetched over the wire by
 * collectors/verify_feeds.py, parsed in its declared mode, and confirmed to
 * yield at least one real record. Rows whose endpoint answered but produced
 * an empty result set were rejected rather than shipped -- a source that is
 * structurally guaranteed to emit nothing on every run is the exact failure
 * the no-fabrication rule exists to prevent.
 *
 * The observed shape and record count for each row are recorded in
 * docs/verified-sources-batch21.tsv; the candidates that failed are kept as
 * data in docs/rejected-sources-batch21.tsv rather than silently dropped.
 *
 * Generated by tools/gen_hp_batch.py from
 * docs/candidate-sources-batch21.delaw.txt. Edit the manifest, not this file.
 */
#include "lib/hpengine.h"

static const hp_source HP3B21_DELAW[] = {
  { .id = "DERIB_CASELAW_SEARCH", .name = "Rechtsinformationsportal - federal case law search",
    .name_ja = "ドイツ連邦判例検索",
    .category = "legal", .portal = "https://testphase.rechtsinformationen.bund.de",
    .record_type = "court-decision",
    .tags = "\"germany\",\"court\",\"caselaw\",\"ecli\",\"bmj\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://testphase.rechtsinformationen.bund.de/v1/case-law?searchTerm={q}&size=100",
    .array_path = "member",
    .body_keys = "item.titleLine",
    .date_keys = "item.decisionDate",
    .id_keys = "item.documentNumber",
    .link_keys = "item.@id",
    .link_tmpl = "https://testphase.rechtsinformationen.bund.de{v}",
    .page_param = "pageIndex",
    .page_zero_based = 1,
    .title_keys = "item.headline,item.titleLine,item.documentNumber",
    .description = "Published decisions of the German federal supreme courts "
      "matching a search term - the document number the ECLI the "
      "headline the case file numbers the deciding court and judicial "
      "senate the seat of the court the document type and the decision "
      "date plus direct links to the full text in HTML XML and ZIP. "
      "Each hit also carries the matched passages of the reasoning with "
      "the term marked in place" },

  { .id = "DERIB_LEGISLATION_SEARCH", .name = "Rechtsinformationsportal - federal legislation search",
    .name_ja = "ドイツ連邦法令検索",
    .category = "legal", .portal = "https://testphase.rechtsinformationen.bund.de",
    .record_type = "legislation-record",
    .tags = "\"germany\",\"legislation\",\"eli\",\"bmj\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://testphase.rechtsinformationen.bund.de/v1/legislation?searchTerm={q}&size=100",
    .array_path = "member",
    .date_keys = "item.exampleOfWork.datePublished",
    .id_keys = "item.legislationIdentifier",
    .link_keys = "item.@id",
    .link_tmpl = "https://testphase.rechtsinformationen.bund.de{v}",
    .page_param = "pageIndex",
    .page_zero_based = 1,
    .title_keys = "item.name,item.alternateName,item.abbreviation",
    .description = "German federal statutes and ordinances matching a search term - "
      "the full title the official abbreviation the alternate name the "
      "European Legislation Identifier of both the expression and the "
      "work the gazette issue it was promulgated in the legislation "
      "date and whether the version is still in force. The ELI is the "
      "stable identifier the whole EU legal-data ecosystem joins on" },

  { .id = "DERIB_LEGISLATION_ALL", .name = "Rechtsinformationsportal - federal legislation corpus",
    .name_ja = "ドイツ連邦法令 全件",
    .category = "legal", .portal = "https://testphase.rechtsinformationen.bund.de",
    .record_type = "legislation-record",
    .tags = "\"germany\",\"legislation\",\"eli\",\"bmj\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://testphase.rechtsinformationen.bund.de/v1/legislation?size=100",
    .array_path = "member",
    .date_keys = "item.exampleOfWork.datePublished",
    .id_keys = "item.legislationIdentifier",
    .interval = 604800,
    .link_keys = "item.@id",
    .link_tmpl = "https://testphase.rechtsinformationen.bund.de{v}",
    .page_param = "pageIndex",
    .page_zero_based = 1,
    .title_keys = "item.name,item.alternateName,item.abbreviation",
    .description = "The federal legislation collection walked page by page with "
      "abbreviations ELIs promulgation references and in-force status. "
      "The abbreviation table alone is worth the walk: German legal "
      "text cites almost entirely by abbreviation and resolving StAuskV "
      "or AO to a full title with an ELI is otherwise a manual lookup" },

  { .id = "DERIB_DOCUMENT_SEARCH", .name = "Rechtsinformationsportal - all document types search",
    .name_ja = "ドイツ法情報 横断検索",
    .category = "legal", .portal = "https://testphase.rechtsinformationen.bund.de",
    .record_type = "legal-document",
    .tags = "\"germany\",\"legislation\",\"caselaw\",\"bmj\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://testphase.rechtsinformationen.bund.de/v1/document?searchTerm={q}&size=100&sort=date",
    .array_path = "member",
    .date_keys = "item.decisionDate,item.exampleOfWork.datePublished",
    .id_keys = "item.@id",
    .link_keys = "item.@id",
    .link_tmpl = "https://testphase.rechtsinformationen.bund.de{v}",
    .page_param = "pageIndex",
    .page_zero_based = 1,
    .title_keys = "item.name,item.headline,item.abbreviation,item.documentNumber",
    .description = "The combined index across every document type the portal holds - "
      "legislation and case law in one ranked result set with the "
      "matched passages quoted. A term that appears both in a statute "
      "and in the judgments interpreting it comes back as one answer "
      "here rather than as two searches that have to be reconciled by "
      "hand" },
};

HP_REGISTER_TABLE(HP3B21_DELAW)
