/* collectors/pivot/table/hp3b28_jpgov.c -- batch 28: jpgov
 *
 * Every row here names a machine-readable endpoint that was proof-of-life
 * verified before it was written: fetched over the wire by
 * collectors/verify_feeds.py, parsed in its declared mode, and confirmed to
 * yield at least one real record. Rows whose endpoint answered but produced
 * an empty result set were rejected rather than shipped -- a source that is
 * structurally guaranteed to emit nothing on every run is the exact failure
 * the no-fabrication rule exists to prevent.
 *
 * The observed shape and record count for each row are recorded in
 * docs/verified-sources-batch28.tsv; the candidates that failed are kept as
 * data in docs/rejected-sources-batch28.tsv rather than silently dropped.
 *
 * Generated by tools/gen_hp_batch.py from
 * docs/candidate-sources-batch28.jpgov.txt. Edit the manifest, not this file.
 */
#include "lib/hpengine.h"

static const hp_source HP3B28_JPGOV[] = {
  { .id = "JO28_015_PMDA_DSU_BULLETIN_ARCHIVE", .name = "PMDA Drug Safety Update (DSU) Bulletins",
    .name_ja = "医薬品安全対策情報（DSU）",
    .category = "safety", .portal = "https://www.pmda.go.jp/safety/info-services/drugs/calling-attention/dsu/0001.html",
    .record_type = "safety-bulletin-record",
    .tags = "\"japan\",\"pmda\",\"pharma\",\"safety\",\"bulletin\",\"dsu\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.pmda.go.jp/safety/info-services/drugs/calling-attention/dsu/0001.html",
    .base = "https://www.pmda.go.jp",
    .href_must = "dsu-system.jp/dsu/web/viewer.html?file=",
    .interval = 604800,
    .description = "Chronological archive of PMDA's monthly Drug Safety Update "
      "bulletins, confirmed live through issue No.347 (August 2026), "
      "each entry linking to its PDF via the dsu-system.jp viewer (e.g. "
      "/dsu/347/347.pdf). Each bulletin documents package-insert "
      "revisions and new safety precautions for marketed drugs, letting "
      "an analyst track regulatory-driven label changes over time." },

  { .id = "JO28_016_PMDA_EMERGENCY_SAFETY_COMMUNICATIONS", .name = "PMDA Emergency Safety Communications (Yellow/Blue Letters)",
    .name_ja = "緊急安全性情報・安全性速報（イエローレター・ブルーレター）",
    .category = "safety", .portal = "https://www.pmda.go.jp/safety/info-services/drugs/calling-attention/esc-rsc/0001.html",
    .record_type = "emergency-safety-alert-record",
    .tags = "\"japan\",\"pmda\",\"pharma\",\"safety\",\"recall\",\"emergency\",\"yellowletter\",\"blueletter\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.pmda.go.jp/safety/info-services/drugs/calling-attention/esc-rsc/0001.html",
    .base = "https://www.pmda.go.jp",
    .href_must = "/files/",
    .interval = 86400,
    .description = "Confirmed-live HTML table (1997-present) of Japan's most urgent "
      "drug safety alerts, with real per-entry PDF links under /files/ "
      "(e.g. a 2026-05-21 entry for Kissei Pharmaceutical's Tabneos "
      "Capsule 10mg carrying both a company letter and patient-facing "
      "PDF). Each row names the manufacturer, drug and alert type "
      "(emergency vs. advisory), which is exactly the naming-and-dating "
      "detail an incident analyst needs." },

  { .id = "JO28_022_SOUMU_SETTLEMENT_CARDS_PREFECTURE", .name = "Municipal and Prefectural Settlement Cards",
    .name_ja = "決算カード",
    .category = "government", .portal = "https://www.soumu.go.jp/iken/zaisei/card.html",
    .record_type = "fiscal-settlement-card-record",
    .tags = "\"japan\",\"mic\",\"soumu\",\"municipal\",\"prefecture\",\"fiscal\",\"localfinance\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.soumu.go.jp/iken/zaisei/card.html",
    .base = "https://www.soumu.go.jp",
    .href_must = "/main_content/",
    .interval = 2592000,
    .description = "Confirmed-live page of MIC's per-municipality/prefecture fiscal "
      "\"settlement card\" one-pagers, with roughly 94 direct PDF+Excel "
      "links observed for FY2024 alone (47 prefectures x 2 formats, "
      "e.g. 北海道 to 沖縄県) drawn from the annual Local Finance Status "
      "Survey. Each linked document is a compact one-page fiscal "
      "summary for that jurisdiction, useful for cross-prefecture "
      "financial-health comparison." },

  { .id = "JO28_024_SOUMU_FISCAL_STATUS_MATERIALS_R06", .name = "Local Government Financial Status Material Collection",
    .name_ja = "財政状況資料集",
    .category = "government", .portal = "https://www.soumu.go.jp/iken/zaisei/jyoukyou_shiryou/index.html",
    .record_type = "fiscal-status-material-record",
    .tags = "\"japan\",\"mic\",\"soumu\",\"municipal\",\"prefecture\",\"fiscal\",\"localfinance\",\"fy2024\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.soumu.go.jp/iken/zaisei/jyoukyou_shiryou/r06/index.html",
    .base = "https://www.soumu.go.jp",
    .href_must = "/main_content/",
    .interval = 2592000,
    .description = "Confirmed-live FY2024 (Reiwa 6) edition of MIC's "
      "per-jurisdiction financial status material collection, with 180+ "
      "direct PDF/Excel links observed covering all 47 prefectures plus "
      "Japan's 20 designated cities (two document formats each, e.g. "
      "北海道, 札幌市, 福岡市). The general index page (used as portal) links to "
      "one such year-coded page per fiscal year back to Heisei 22 "
      "(2010), so a full historical corpus would need one row per year; "
      "this row captures the current year only." },

  { .id = "JO28_028_EGOV_DATA_PORTAL_CKAN", .name = "e-Gov Data Portal — CKAN dataset catalog",
    .name_ja = "e-Govデータポータル",
    .category = "government", .portal = "https://data.e-gov.go.jp/",
    .record_type = "dataset-record",
    .tags = "\"japan\",\"opendata\",\"ckan\",\"catalog\",\"egov\",\"digitalagency\"",
    .mode = HP_JSON, .want = HP_ANY, .free_tier = 1,
    .url = "https://data.e-gov.go.jp/data/api/3/action/package_search?rows=100&start=0",
    .array_path = "result.results",
    .body_keys = "notes",
    .date_keys = "metadata_modified,metadata_created",
    .id_keys = "id",
    .interval = 86400,
    .page_param = "start",
    .page_size = 100,
    .page_zero_based = 1,
    .title_keys = "title",
    .description = "The e-Gov open data portal runs on CKAN and exposes its full "
      "package_search API; a live query returned valid JSON reporting "
      "result.count=18141 datasets, each carrying title, name, id "
      "(UUID), publisher/organization, notes, and a resources array of "
      "file distributions. This is the aggregation point for open data "
      "from roughly two dozen national government bodies, so each "
      "record maps to an actual downloadable government dataset rather "
      "than a portal-level summary. Confirmed live and unauthenticated "
      "as of 2026-08-29." },

  { .id = "JO28_034_CAO_SNA_GDP_DATA_FILES", .name = "National Accounts (SNA/GDP Statistics) — data file index",
    .name_ja = "国民経済計算（GDP統計） データファイル一覧",
    .category = "government", .portal = "https://www.esri.cao.go.jp/jp/sna/menu.html",
    .record_type = "statistical-data-file",
    .tags = "\"japan\",\"cao\",\"esri\",\"gdp\",\"nationalaccounts\",\"sna\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.esri.cao.go.jp/jp/sna/menu.html",
    .base = "https://www.esri.cao.go.jp",
    .href_must = "/jp/sna/data/data_list/",
    .interval = 2592000,
    .description = "Cabinet Office ESRI's GDP hub links directly to real per-release "
      "CSV time series (e.g. quarterly real/nominal growth-rate tables) "
      "and XLSX annex tables (national income by factor cost, household "
      "savings rate) under a common /jp/sna/data/data_list/ path, "
      "confirmed via live fetch. Each linked file is one dated "
      "statistical release, so a link-list crawl captures the actual "
      "GDP release history rather than just the current headline "
      "figure." },

  { .id = "JO28_035_CAO_ESRI_CI_DI_INDEX", .name = "Business Conditions Index (CI/DI) — data file index",
    .name_ja = "景気動向指数 データファイル一覧",
    .category = "government", .portal = "https://www.esri.cao.go.jp/jp/stat/di/di.html",
    .record_type = "statistical-data-file",
    .tags = "\"japan\",\"cao\",\"esri\",\"businesscycle\",\"cidi\",\"leadingindicator\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.esri.cao.go.jp/jp/stat/di/di.html",
    .base = "https://www.esri.cao.go.jp",
    .href_must = "/jp/stat/di/",
    .interval = 2592000,
    .description = "Cabinet Office ESRI's leading/coincident/lagging index page "
      "links to real dated XLSX index-series files (e.g. long-term CI "
      "series, individual-series breakdowns) and PDF summary/report "
      "documents hosted in the survey's own /jp/stat/di/ directory, "
      "confirmed via live fetch; no CSV variant is offered, only XLSX "
      "and PDF. Each link is one monthly release, giving a genuine "
      "release-history crawl rather than a single current snapshot." },

  { .id = "JO28_036_CAO_ESRI_MACHINERY_ORDERS", .name = "Machinery Orders Statistics Survey — data file index",
    .name_ja = "機械受注統計調査 データファイル一覧",
    .category = "government", .portal = "https://www.esri.cao.go.jp/jp/stat/juchu/menu_juchu.html",
    .record_type = "statistical-data-file",
    .tags = "\"japan\",\"cao\",\"esri\",\"machineryorders\",\"leadingindicator\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.esri.cao.go.jp/jp/stat/juchu/juchu.html",
    .base = "https://www.cao.go.jp",
    .href_must = "/jp/stat/juchu/",
    .interval = 2592000,
    .description = "The survey's own statistical-tables-list sub-page (the landing "
      "page at menu_juchu.html only links onward to this list) carries "
      "real dated XLSX time-series files — orders by demander type, "
      "machine type, manufacturing/non-manufacturing industry, and "
      "forecast-achievement rate — confirmed via live fetch under a "
      "/jp/stat/juchu/ path on cao.go.jp. This is a closely watched "
      "leading indicator of private capital investment." },

  { .id = "JO28_037_CAO_ESRI_CONSUMER_TREND", .name = "Consumer Trend Survey — data file index",
    .name_ja = "消費動向調査 データファイル一覧",
    .category = "government", .portal = "https://www.esri.cao.go.jp/jp/stat/shouhi/menu_shouhi.html",
    .record_type = "statistical-data-file",
    .tags = "\"japan\",\"cao\",\"esri\",\"consumersentiment\",\"durablegoods\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.esri.cao.go.jp/jp/stat/shouhi/shouhi.html",
    .base = "https://www.esri.cao.go.jp/jp/stat/shouhi/",
    .href_must = ".xls",
    .interval = 2592000,
    .description = "The survey's statistical-tables-list sub-page carries real XLS "
      "files on durable-goods penetration/holdings/replacement, service "
      "expenditure, price outlook, and regional consumer-attitude "
      "index, confirmed via live fetch; the landing page itself only "
      "points onward to this list and to e-Stat. Feeds the monthly "
      "Consumer Attitude Index used as a household-sentiment leading "
      "indicator." },

  { .id = "JO28_038_CAO_ESRI_CORPORATE_BSI", .name = "Corporate Business Conditions Survey (BSI) — data file index",
    .name_ja = "法人企業景気予測調査 データファイル一覧",
    .category = "government", .portal = "https://www.esri.cao.go.jp/jp/stat/hojin/menu_hojin.html",
    .record_type = "statistical-data-file",
    .tags = "\"japan\",\"cao\",\"esri\",\"mof\",\"corporatesentiment\",\"bsi\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.esri.cao.go.jp/jp/stat/hojin/menu_hojin.html",
    .base = "https://www.mof.go.jp",
    .href_must = "/pri/reference/bos/results/",
    .interval = 7776000,
    .description = "This joint Cabinet Office/MOF quarterly survey page links to "
      "real MOF-hosted XLSX time-series files (BSI since FY2004, and a "
      "FY2004-2018 reference series) confirmed via live fetch; the file "
      "set is small (two time-series files plus a publication-schedule "
      "page) but genuine and not otherwise indexed elsewhere in this "
      "batch." },

  { .id = "JO28_039_CAO_ESRI_CORPORATE_BEHAVIOR", .name = "Corporate Behavior Survey — data file index",
    .name_ja = "企業行動に関するアンケート調査 データファイル一覧",
    .category = "government", .portal = "https://www.esri.cao.go.jp/jp/stat/ank/menu_ank.html",
    .record_type = "statistical-data-file",
    .tags = "\"japan\",\"cao\",\"esri\",\"corporatestrategy\",\"survey\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.esri.cao.go.jp/jp/stat/ank/menu_ank.html",
    .base = "https://www.esri.cao.go.jp/jp/stat/ank/",
    .href_must = ".xlsx",
    .interval = 7776000,
    .description = "This annual ESRI survey of listed-company growth/strategy "
      "expectations links to real XLSX files — the FY2025 statistical "
      "dataset (r7ank_data.xlsx) and a multi-year time-series table "
      "(ank_time1.xlsx) — confirmed via live fetch as of the February "
      "2026 release." },

  { .id = "JO28_041_CAO_PROCUREMENT_DISCLOSURE", .name = "Cabinet Office Procurement Contract Disclosure — data file index",
    .name_ja = "内閣府 調達情報（契約状況の公表） データファイル一覧",
    .category = "procurement", .portal = "https://www.cao.go.jp/chotatsu/kohyo/kohyo.html",
    .record_type = "procurement-disclosure-file",
    .tags = "\"japan\",\"cao\",\"procurement\",\"contracts\",\"tekiseika\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.cao.go.jp/chotatsu/kohyo/kohyo.html",
    .base = "https://www.cao.go.jp/chotatsu/kohyo/",
    .href_must = "tekiseika/",
    .interval = 2592000,
    .description = "The Cabinet Office publishes both PDF and real CSV editions of "
      "its competitive-bid (kyoso) and negotiated-contract (zuikei) "
      "disclosures for each fiscal year under a /tekiseika/<N>nendo/ "
      "path, confirmed via live fetch through at least Reiwa 6-8; "
      "monthly updates per the page. A link-list crawl captures the "
      "full multi-year CSV disclosure history." },

  { .id = "JO28_044_BOUSAI_HAKUSHO_ARCHIVE", .name = "Disaster Prevention White Paper Archive",
    .name_ja = "防災白書 アーカイブ",
    .category = "safety", .portal = "https://www.bousai.go.jp/kaigirep/hakusho/index.html",
    .record_type = "white-paper-record",
    .tags = "\"japan\",\"bousai\",\"cao\",\"disasterprevention\",\"whitepaper\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.bousai.go.jp/kaigirep/hakusho/index.html",
    .base = "https://www.bousai.go.jp/kaigirep/hakusho/",
    .href_must = ".pdf",
    .interval = 7776000,
    .description = "Cabinet Office's disaster-prevention white paper archive links "
      "to real per-edition PDF documents and HTML editions spanning "
      "Heisei 13 through Reiwa 8 (2001-2026), confirmed via live fetch; "
      "no CSV/XLS statistical extract is offered separately, only the "
      "PDF/HTML white papers and errata themselves, each carrying the "
      "year's disaster-occurrence and response statistical appendices." },

  { .id = "JO28_048_MONODUKURI_SUBSIDY_AWARD_RESULTS", .name = "Monodukuri Subsidy Award Results — round-by-round file index",
    .name_ja = "ものづくり補助金 採択結果",
    .category = "procurement", .portal = "https://portal.monodukuri-hojo.jp/saitaku.html",
    .record_type = "subsidy-award-record",
    .tags = "\"japan\",\"meti\",\"monodukuri\",\"subsidy\",\"smebusiness\",\"award\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://portal.monodukuri-hojo.jp/saitaku.html",
    .base = "https://portal.monodukuri-hojo.jp",
    .href_must = "/common/bunsho/",
    .interval = 2592000,
    .description = "Japan's flagship manufacturing/SME productivity subsidy "
      "publishes real per-round PDF recipient lists under "
      "/common/bunsho/ippan/<round>/, confirmed via live fetch across "
      "at least 23 rounds from April 2020 through August 2024, naming "
      "awarded companies and project titles; a separate funding-status "
      "table on the same page reports ¥366.2 billion disbursed across "
      "42,783 awards as of 2024-07-08." },

  { .id = "JO28_067_NTA_PUBLIC_AUCTION_PORTAL", .name = "NTA Public Property Auction Portal",
    .name_ja = "国税庁 公売情報",
    .category = "procurement", .portal = "https://www.koubai.nta.go.jp/",
    .record_type = "seized-asset-auction-listing",
    .tags = "\"japan\",\"nta\",\"tax\",\"auction\",\"seized-property\",\"procurement\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.koubai.nta.go.jp/",
    .base = "https://www.koubai.nta.go.jp/",
    .href_must = "hp001_01.php?no=",
    .interval = 86400,
    .description = "National Tax Agency's live internet-auction portal for property "
      "seized from tax delinquents. The homepage itself lists current "
      "inventory with direct per-item links — observed 9 land parcels, "
      "3 buildings, 21 movable-property lots and 28 agricultural-land "
      "lots at time of check — each linking to a detail page carrying "
      "the auction round, lot number and category." },

  { .id = "JO28_070_MAFF_FISHERIES_CENSUS_2023", .name = "Regional Fisheries Census Database — FY2023 Files",
    .name_ja = "地域の漁業を見て・知って・活かすDB（2023年）",
    .category = "government", .portal = "https://www.maff.go.jp/j/tokei/census/fc/database/index.html",
    .record_type = "fisheries-census-file",
    .tags = "\"japan\",\"maff\",\"fisheries\",\"census\",\"municipal\",\"agriculture\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.maff.go.jp/j/tokei/census/fc/database/2023/index.html",
    .base = "https://www.maff.go.jp",
    .href_must = ".xlsx",
    .interval = 2592000,
    .description = "MAFF's 2023 fisheries census file index, one Excel workbook per "
      "prefecture/category pairing — observed real per-prefecture links "
      "such as Hokkaido basic-management-composition data, Nagasaki "
      "individual-operator age/gender breakdowns, and Niigata "
      "fishing-vessel tonnage data. Covers roughly 6,000 fishing "
      "communities nationwide; the parent index also links to "
      "2018/2013/2008 editions not captured by this row." },

  { .id = "JO28_075_MAFF_LIVESTOCK_STATS_RELEASES", .name = "MAFF Livestock Statistics Survey — release file index",
    .name_ja = "畜産統計調査",
    .category = "government", .portal = "https://www.maff.go.jp/j/tokei/kouhyou/tikusan/index.html",
    .record_type = "statistical-release-file",
    .tags = "\"japan\",\"maff\",\"livestock\",\"statistics\",\"agriculture\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.maff.go.jp/j/tokei/kouhyou/tikusan/index.html",
    .base = "https://www.maff.go.jp",
    .href_must = "e-stat.go.jp",
    .interval = 2592000,
    .description = "MAFF's livestock statistics index page links out to "
      "per-fiscal-year e-Stat file listings and direct Excel/PDF "
      "releases, confirmed live via WebFetch — a 762KB first-release "
      "PDF plus e-Stat XLS export links reaching back through fiscal "
      "2003, covering swine, layer-hen, broiler, dairy and beef cattle "
      "population counts. The page itself is a dated index of releases "
      "rather than an embedded dataset, so each record here is a link "
      "to one fiscal year's release page. Valuable for tracking Japan's "
      "livestock sector at prefecture/municipal granularity over two "
      "decades." },

  { .id = "JO28_076_MAFF_DAIRY_STATS_RELEASES", .name = "MAFF Milk and Dairy Products Statistics — release file index",
    .name_ja = "牛乳乳製品統計調査",
    .category = "government", .portal = "https://www.maff.go.jp/j/tokei/kouhyou/gyunyu/index.html",
    .record_type = "statistical-release-file",
    .tags = "\"japan\",\"maff\",\"dairy\",\"milk\",\"statistics\",\"agriculture\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.maff.go.jp/j/tokei/kouhyou/gyunyu/index.html",
    .base = "https://www.maff.go.jp",
    .href_must = "e-stat.go.jp",
    .interval = 2592000,
    .description = "Confirmed live via WebFetch: this MAFF page links to monthly "
      "dairy-production release PDFs plus e-Stat Excel/CSV exports for "
      "the current month and prior fiscal years back through 2002, "
      "covering national milk and dairy-product production and "
      "distribution. Each record is a link to one dated release or its "
      "e-Stat file listing, not an embedded table." },

  { .id = "JO28_077_MAFF_AGRI_FORESTRY_CENSUS_RELEASES", .name = "Agriculture and Forestry Census — release file index",
    .name_ja = "農林業センサス",
    .category = "government", .portal = "https://www.maff.go.jp/j/tokei/census/afc/index.html",
    .record_type = "census-release-file",
    .tags = "\"japan\",\"maff\",\"agriculture\",\"forestry\",\"census\",\"statistics\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.maff.go.jp/j/tokei/census/afc/index.html",
    .base = "https://www.maff.go.jp",
    .href_must = "e-stat.go.jp",
    .interval = 2592000,
    .description = "Confirmed live via WebFetch: the 2025 Census landing page links "
      "to an e-Stat summary-report file listing and a direct Excel "
      "results overview, part of Japan's quinquennial "
      "farm/forestry-household census. The page's GIS and dashboard "
      "tools are separate JS applications not captured here; this row "
      "captures the linked release files themselves." },

  { .id = "JO28_083_JETRO_TRADE_INVESTMENT_STATS", .name = "JETRO Trade and Investment Statistics — data file index",
    .name_ja = "JETRO貿易投資統計",
    .category = "government", .portal = "https://www.jetro.go.jp/en/reports/statistics.html",
    .record_type = "trade-statistics-release",
    .tags = "\"japan\",\"jetro\",\"trade\",\"fdi\",\"statistics\",\"economy\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.jetro.go.jp/en/reports/statistics.html",
    .base = "https://www.jetro.go.jp",
    .href_must = ".xls",
    .interval = 2592000,
    .description = "Confirmed live via WebFetch: the page directly embeds dozens of "
      "downloadable XLSX links — monthly and yearly trade balance data, "
      "inward/outward FDI by country and by industry, and a 1996-2025 "
      "FDI stock series — rather than routing through a search form. "
      "Each record is one dated statistical release file." },

  { .id = "JO28_084_IDE_JETRO_DATA_RESOURCES", .name = "IDE-JETRO Data Resources — dataset file index",
    .name_ja = "アジア経済研究所 統計データ",
    .category = "government", .portal = "https://www.ide.go.jp/Japanese/Data.html",
    .record_type = "research-dataset-file",
    .tags = "\"japan\",\"jetro\",\"ide\",\"asia\",\"trade\",\"gdp\",\"inputoutput\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.ide.go.jp/Japanese/Data.html",
    .base = "https://www.ide.go.jp",
    .href_must = ".xls",
    .interval = 2592000,
    .description = "Confirmed live via WebFetch: the Institute of Developing "
      "Economies' data page mixes narrative links to named datasets "
      "(regional GDP, Asia-Pacific input-output tables, trade indices "
      "for 64 countries) with direct XLS/XLSX downloads such as "
      "Cambodia garment-industry and Philippines disability-data files. "
      "Each record is one linked dataset or research-data file." },

  { .id = "JO28_090_DARTS_PUB_ARCHIVE_INDEX", .name = "DARTS Space Science Data Archive — top-level directory index",
    .name_ja = "宇宙科学データアーカイブ（DARTS）",
    .category = "government", .portal = "https://darts.isas.jaxa.jp/",
    .record_type = "archive-directory-entry",
    .tags = "\"japan\",\"jaxa\",\"isas\",\"space\",\"astronomy\",\"archive\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://data.darts.isas.jaxa.jp/pub/",
    .base = "https://data.darts.isas.jaxa.jp/pub/",
    .href_must = "/",
    .interval = 604800,
    .description = "Confirmed live via WebFetch as a standard Apache mod_autoindex "
      "listing: the top level of JAXA/ISAS's DARTS raw-data archive "
      "enumerates one folder per mission or instrument (Astro_Browse, "
      "HiPS, Solar_Browse, akari, akatsuki, akebono, apollo, app-data, "
      "asca, and more), each itself a further browsable archive tree. "
      "Valuable as a live enumeration of exactly which "
      "satellite/mission datasets JAXA exposes publicly, including "
      "current XRISM data referenced elsewhere on the DARTS portal." },

  { .id = "JO28_095_PPC_QUARTERLY_SUPERVISION_REPORTS", .name = "PPC Quarterly Supervision and Breach-Report Statistics",
    .name_ja = "個人情報保護委員会 監視・監督活動報告",
    .category = "regulator", .portal = "https://www.ppc.go.jp/personalinfo/activity/",
    .record_type = "supervision-quarterly-report",
    .tags = "\"japan\",\"ppc\",\"privacy\",\"dataprotection\",\"databreach\",\"supervision\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.ppc.go.jp/personalinfo/activity/",
    .base = "https://www.ppc.go.jp",
    .href_must = "/files/pdf/",
    .interval = 2592000,
    .description = "Confirmed live via WebFetch: a static list of dated quarterly "
      "PDF reports (e.g. 260610quarter-report_kengenkoushi.pdf covering "
      "FY2025 Q4 supervisory-power exercise, and a matching "
      "roueihoukoku.pdf on mandatory data-breach-notification "
      "processing) reaching back through FY2024. Each record is one "
      "quarter's report on how the PPC exercised its oversight "
      "authority." },

  { .id = "JO28_097_MHLW_FOOD_POISONING_INCIDENT_RELEASES", .name = "Food Poisoning Incident Lists — yearly release file index",
    .name_ja = "食中毒事件一覧",
    .category = "health", .portal = "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/shokuhin/syokuchu/index.html",
    .record_type = "food-poisoning-incident-list-release",
    .tags = "\"japan\",\"mhlw\",\"foodpoisoning\",\"health\",\"outbreak\",\"statistics\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/shokuhin/syokuchu/04.html",
    .base = "https://www.mhlw.go.jp",
    .href_must = ".xlsx",
    .interval = 2592000,
    .description = "Confirmed live via WebFetch: a static list of one XLSX file per "
      "year bundling that year's food-poisoning occurrence status and "
      "case-by-case list (e.g. /content/001681441.xlsx "
      "\"令和7年（2025年）食中毒発生状況\" and /content/001681445.xlsx "
      "\"令和7年（2025年）食中毒発生事例\", back through 2024's "
      "/content/001472343.xlsx). Files are per-year aggregates rather "
      "than per-incident, but are the real statutory MHLW dataset "
      "behind Japan's food-poisoning statistics." },

  { .id = "JO28_104_NDB_OPENDATA_CLAIMS_XLSX", .name = "NDB Open Data (Claims / Health Checkup Database)",
    .name_ja = "NDBオープンデータ",
    .category = "health", .portal = "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000177221.html",
    .record_type = "ndb-open-data-file",
    .tags = "\"japan\",\"mhlw\",\"ndb\",\"health-insurance\",\"claims\",\"healthcheckup\",\"statistics\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000177221.html",
    .base = "https://www.mhlw.go.jp",
    .href_must = "/file/06-Seisakujouhou-12400000-Hokenkyoku/",
    .interval = 7776000,
    .description = "MHLW's NDB (National Database of Health Insurance Claims and "
      "Specific Health Checkups) Open Data page, confirmed via direct "
      "fetch to carry at least 10 real anchor links to distinct .xlsx "
      "aggregate tables under "
      "/file/06-Seisakujouhou-12400000-Hokenkyoku/ — covering "
      "medical-care procedure counts by age/sex, dental procedures, "
      "outpatient/inpatient drug-class dispensing volumes by "
      "prefecture, and BMI/checkup-item distributions by age and "
      "prefecture. Each anchor is one aggregated statistical table, not "
      "a per-patient record, but the directory itself is real and "
      "enumerable, giving OSINT visibility into Japan's national "
      "health-claims patterns by category and geography without needing "
      "e-Stat credentials." },

  { .id = "JO28_105_MHLW_VITAL_STATISTICS_REPORTS", .name = "Vital Statistics Survey",
    .name_ja = "人口動態調査（人口動態統計）",
    .category = "government", .portal = "https://www.mhlw.go.jp/toukei/list/81-1.html",
    .record_type = "vital-statistics-report",
    .tags = "\"japan\",\"mhlw\",\"vital-statistics\",\"demographics\",\"births\",\"deaths\",\"marriages\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.mhlw.go.jp/toukei/list/81-1.html",
    .base = "https://www.mhlw.go.jp",
    .href_must = "/toukei/list/dl/",
    .interval = 2592000,
    .description = "MHLW's Vital Statistics landing page, confirmed via direct fetch "
      "to carry real anchor links under /toukei/list/dl/ to actual "
      "results documents: a provisional-figures overview report for the "
      "current year, a multi-year (2017-2023) historical compilation, "
      "and a methodology Q&A — all real PDFs observed directly, not the "
      "e-Stat search portal it also links to. Small item count (three "
      "observed) but genuine national demographic reporting (births, "
      "deaths, marriages, divorces, stillbirths) rather than a "
      "fabricated shape." },

  { .id = "JO28_124_JTSB_RAILWAY_ACCIDENT_SEARCH", .name = "JTSB Railway Accident Report Search",
    .name_ja = "鉄道事故検索結果",
    .category = "safety", .portal = "https://jtsb.mlit.go.jp/",
    .record_type = "railway-accident-case",
    .tags = "\"japan\",\"jtsb\",\"railway\",\"accident\",\"transportsafety\",\"mlit\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://jtsb.mlit.go.jp/jtsb/railway/rail-toukei.php?init=1",
    .base = "https://jtsb.mlit.go.jp/jtsb/railway/",
    .href_must = "detail2.php",
    .interval = 604800,
    .page_max = 13,
    .page_param = "page",
    .page_start = 1,
    .description = "Server-rendered table of all 383 JTSB railway accident "
      "investigations (derailments, level-crossing collisions, etc), "
      "confirmed via direct fetch showing 383 total results with plain "
      "page-parameter pagination (roughly 13 pages) and no JS "
      "dependency. Each row links to a detail2.php case page naming the "
      "operator and, once published, a report PDF under "
      "/jtsb/railway/rep-acci/." },

  { .id = "JO28_125_JTSB_RAILWAY_INCIDENT_SEARCH", .name = "JTSB Railway Serious Incident Search",
    .name_ja = "鉄道重大インシデント検索結果",
    .category = "safety", .portal = "https://jtsb.mlit.go.jp/",
    .record_type = "railway-serious-incident-case",
    .tags = "\"japan\",\"jtsb\",\"railway\",\"incident\",\"transportsafety\",\"mlit\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://jtsb.mlit.go.jp/jtsb/railway/rail-incident-kensaku-list.php",
    .base = "https://jtsb.mlit.go.jp/jtsb/railway/",
    .href_must = "detail2.php",
    .interval = 604800,
    .page_max = 3,
    .page_param = "page",
    .page_start = 1,
    .description = "Server-rendered list of all 67 JTSB railway serious-incident "
      "cases (vehicle malfunction, runaway, facility damage) distinct "
      "from full accidents, confirmed with detail2.php per-case links "
      "and plain page-parameter pagination (roughly 3 pages), no JS "
      "required." },

  { .id = "JO28_127_MLIT_PORT_STATISTICS_INDEX", .name = "MLIT Port Statistics Portal",
    .name_ja = "港湾統計",
    .category = "government", .portal = "https://www.mlit.go.jp/statistics/",
    .record_type = "port-statistics-document",
    .tags = "\"japan\",\"mlit\",\"port\",\"harbor\",\"cargo\",\"statistics\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.mlit.go.jp/statistics/details/t-other-2_tk_000349.html",
    .base = "https://www.mlit.go.jp",
    .href_must = "/statistics/details/content/",
    .interval = 2592000,
    .description = "Confirmed index page linking to roughly 15 PDF statistical "
      "documents on port cargo handling, container throughput (TEU), "
      "vessel arrivals and world-port rankings, published under "
      "/statistics/details/content/. No CSV or XLS is linked at this "
      "index, only PDF, so each record is a title-plus-PDF-link pointer "
      "rather than a parsed table, but the catalog itself is real and "
      "enumerable." },

  { .id = "JO28_128_MLIT_CONSTRUCTION_ORDERS_MONTHLY", .name = "MLIT Construction Orders Statistics Monthly Report",
    .name_ja = "建設工事受注動態統計調査",
    .category = "government", .portal = "https://www.mlit.go.jp/report/press/",
    .record_type = "construction-orders-statistics-file",
    .tags = "\"japan\",\"mlit\",\"construction\",\"orders\",\"statistics\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.mlit.go.jp/report/press/joho04_hh_001385.html",
    .base = "https://www.mlit.go.jp",
    .href_must = "/report/press/content/",
    .interval = 2592000,
    .description = "Confirmed press-release page for the June 2026 (Reiwa 8) "
      "construction-orders release, linking 8 real XLS data tables "
      "(order-value time series, public and private works by payer, "
      "region and prefecture) plus a PDF summary, all under "
      "/report/press/content/. XLS is binary so it is cataloged as a "
      "link list rather than parsed rows; the page is a single dated "
      "release rather than a rolling index, so this row keeps returning "
      "the same June 2026 file set until MLIT republishes at a new URL." },

  { .id = "JO28_129_MLIT_CONSTRUCTION_STATS_PORTAL", .name = "MLIT Comprehensive Construction Statistics Portal",
    .name_ja = "建設関係統計",
    .category = "government", .portal = "https://www.mlit.go.jp/statistics/",
    .record_type = "survey-index-entry",
    .tags = "\"japan\",\"mlit\",\"construction\",\"statistics\",\"index\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.mlit.go.jp/statistics/details/t-other-2_tk_000344.html",
    .base = "https://www.mlit.go.jp",
    .href_must = "/statistics/details/",
    .interval = 2592000,
    .description = "Confirmed directory page linking to 10 distinct MLIT "
      "construction-economy surveys (investment outlook, progress-rate "
      "survey, cost deflator, materials and labor demand, by-products "
      "survey, etc), each its own further statistics page. Captured "
      "here as the catalog of survey pages itself, since the linked "
      "pages are themselves indices rather than flat data files." },

  { .id = "JO28_130_MOE_AIR_POLLUTION_ANNUAL_REPORTS", .name = "MOE Annual Air Pollution Status Reports",
    .name_ja = "大気汚染状況（年報）",
    .category = "health", .portal = "https://www.env.go.jp/air/osen/",
    .record_type = "air-quality-annual-report",
    .tags = "\"japan\",\"moe\",\"airquality\",\"pollution\",\"no2\",\"pm25\",\"statistics\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.env.go.jp/air/osen/index.html",
    .base = "https://www.env.go.jp",
    .href_must = "/content/",
    .interval = 2592000,
    .description = "Confirmed archive spanning FY1998 through FY2024 (roughly 27 "
      "fiscal years) of Japan's national air-quality compilations "
      "covering NO2, SPM, Ox, SO2, CO and PM2.5, linked as PDF files "
      "under /content/ (for example /content/000406532.pdf for FY2024). "
      "Each record is a year-labelled report pointer; the underlying "
      "tables are PDF, not machine-readable CSV, but the yearly catalog "
      "itself is genuine and complete as observed." },

  { .id = "JO28_131_MOE_WATER_QUALITY_MONITORING", .name = "MOE Public Water Body Water Quality Monitoring Results",
    .name_ja = "公共用水域水質測定結果",
    .category = "health", .portal = "https://www.env.go.jp/water/suiiki/",
    .record_type = "water-quality-annual-report",
    .tags = "\"japan\",\"moe\",\"waterquality\",\"monitoring\",\"statistics\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.env.go.jp/water/suiiki/index.html",
    .base = "https://www.env.go.jp",
    .href_must = "/content/",
    .interval = 2592000,
    .description = "Confirmed archive of annual public-water-body water-quality "
      "monitoring result documents (overview, reference and "
      "attached-table PDFs per fiscal year, with older Heisei-era years "
      "as combined PDFs or HTML archive pages), spanning at least "
      "FY2008 through FY2024 as observed, linked under /content/. Each "
      "record is a year-and-document pointer rather than parsed "
      "measurement rows." },

  { .id = "JO28_134_MOE_PRTR_FACILITY_DATA_ARCHIVE", .name = "PRTR Individual Facility Data Disclosure Archive",
    .name_ja = "PRTR個別事業所データ開示",
    .category = "regulator", .portal = "https://www.env.go.jp/chemi/prtr/kaiji/",
    .record_type = "prtr-annual-dataset-file",
    .tags = "\"japan\",\"moe\",\"prtr\",\"chemical\",\"emissions\",\"facility\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.env.go.jp/chemi/prtr/kaiji/index.html",
    .base = "https://www.env.go.jp",
    .href_must = "PRTRdata.zip",
    .interval = 2592000,
    .description = "Confirmed archive of 24 annual PRTR (Pollutant Release and "
      "Transfer Register) ZIP archives, one per fiscal year from 2001 "
      "through 2024, each containing per-facility chemical release and "
      "transfer text files plus a companion offline search tool. "
      "Cataloged as one record per year's ZIP download link (for "
      "example R06PRTRdata.zip); the ZIP contents are outside this "
      "engine's extraction but the yearly bulk-download catalog is real "
      "and complete as observed." },

  { .id = "JO28_135_MOE_KUROBON_CHEMICALS_SURVEY", .name = "Chemicals in the Environment Survey (Kurobon)",
    .name_ja = "化学物質環境実態調査（黒本調査）",
    .category = "health", .portal = "https://www.env.go.jp/chemi/kurohon/",
    .record_type = "chemical-environment-survey-report",
    .tags = "\"japan\",\"moe\",\"chemicals\",\"environment\",\"kurobon\",\"survey\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.env.go.jp/chemi/kurohon/index.html",
    .base = "https://www.env.go.jp",
    .href_must = "/chemi/kurohon/",
    .interval = 2592000,
    .description = "Confirmed archive of MOE's annual chemical-substance "
      "environmental monitoring survey running since FY1974, comprising "
      "30 Japanese-language and 28 English-language per-year report "
      "pages (58 total), each linked under /chemi/kurohon/. Each record "
      "is a year-and-language report pointer to the full survey "
      "results." },

  { .id = "JO28_136_MOE_CHEMICAL_RISK_ASSESSMENT_REPORTS", .name = "Chemical Substance Environmental Risk Assessment Reports",
    .name_ja = "化学物質の環境リスク評価",
    .category = "health", .portal = "https://www.env.go.jp/chemi/report/",
    .record_type = "chemical-risk-assessment-report",
    .tags = "\"japan\",\"moe\",\"chemicals\",\"riskassessment\",\"dioxin\",\"health\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.env.go.jp/chemi/report/index.html",
    .base = "https://www.env.go.jp",
    .href_must = "/chemi/report/",
    .interval = 2592000,
    .description = "Confirmed index of MOE health and chemical-substance "
      "countermeasure reports spanning the 1990s through recent years, "
      "including environmental risk assessment volumes and dioxin "
      "exposure studies, linked under /chemi/report/. Each record is a "
      "report-title-and-link pointer to the underlying study page or "
      "PDF." },

  { .id = "JO28_140_MOE_SEABIRD_COLONY_DATABASE", .name = "Seabird Colony Database",
    .name_ja = "海鳥コロニーデータベース",
    .category = "government", .portal = "http://www.sizenken.biodic.go.jp/seabirds/",
    .record_type = "seabird-colony-record",
    .tags = "\"japan\",\"moe\",\"seabird\",\"biodiversity\",\"colony\",\"csv\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "http://www.sizenken.biodic.go.jp/seabirds/csv/seabirds_list.csv",
    .date_keys = "年",
    .id_keys = "No",
    .interval = 2592000,
    .title_keys = "種名（和名）,サイト名",
    .description = "Confirmed live UTF-8 CSV export of MOE's national seabird "
      "breeding-colony database, with a verified 20-column header "
      "covering species name, scientific name, "
      "prefecture/region/municipality, site name, coordinates, year, "
      "individual count, nest count, count method, observer, "
      "publication year, citation number, disclosure condition, contact "
      "and notes, covering colonies documented from the 1920s through "
      "recent surveys. A companion bibliography CSV (bunken_list.csv) "
      "exists at the same path but is a separate reference table not "
      "fetched by this row." },

  { .id = "JO28_141_MOE_WATERFOWL_SURVEY_ARCHIVE", .name = "Waterfowl (Geese/Ducks/Swans) Habitat Survey Archive",
    .name_ja = "ガンカモ類生息調査",
    .category = "government", .portal = "https://www.biodic.go.jp/gankamo/",
    .record_type = "waterfowl-survey-data-file",
    .tags = "\"japan\",\"moe\",\"waterfowl\",\"biodiversity\",\"census\",\"avianinfluenza\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.biodic.go.jp/gankamo/gankamo_top.html",
    .base = "https://www.biodic.go.jp/gankamo/",
    .href_must = "gankamo",
    .interval = 2592000,
    .description = "Confirmed archive of Japan's mid-January waterfowl census "
      "running since 1970 (57th round completed 2026), with "
      "per-fiscal-year prefectural-summary and survey-point-level files "
      "linked under /gankamo/data/ (for example r6gankamo.xlsx and "
      "r6gankamo_a.xlsx) in XLSX/XLS format. Cataloged as one record "
      "per year's file link; relevant to avian-influenza risk "
      "surveillance as well as biodiversity monitoring." },

  { .id = "JO28_142_MOE_IMPORTANT_WETLANDS_500", .name = "Japan's Important Wetlands (500 Sites) Regional Index",
    .name_ja = "日本の重要湿地500",
    .category = "government", .portal = "https://www.env.go.jp/nature/important_wetland/",
    .record_type = "wetland-region-index-entry",
    .tags = "\"japan\",\"moe\",\"wetland\",\"conservation\",\"ramsar\"",
    .mode = HP_HTML, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.env.go.jp/nature/important_wetland/",
    .base = "https://www.env.go.jp/nature/important_wetland/",
    .href_must = "wetland/",
    .interval = 2592000,
    .description = "Confirmed curated conservation-planning listing organized into 7 "
      "regional divisions (Hokkaido through Kyushu/Okinawa), each "
      "dividing further into per-wetland detail pages by prefecture. "
      "Cataloged here at the regional-index level (7 real links "
      "observed at this URL) since fetching a single deeper region page "
      "would arbitrarily capture only that one region's sites rather "
      "than the full set." },

  { .id = "JO28_020_SOUMU_TELECOM_CARRIER_COUNT_TIMESERIES", .name = "Telecom Carriers Overview Data",
    .name_ja = "電気通信事業分野データ（事業者の概況）",
    .category = "regulator", .portal = "https://www.soumu.go.jp/johotsusintokei/field/tsuushin04.html",
    .record_type = "carrier-count-time-series-record",
    .tags = "\"japan\",\"mic\",\"soumu\",\"telecom\",\"carrier\",\"statistics\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.soumu.go.jp/johotsusintokei/field/csv/gt010401.csv",
    .charset = "sjis",
    .csv_comment = "@",
    .id_keys = "西暦年,期別",
    .interval = 2592000,
    .title_keys = "西暦年",
    .description = "MIC's telecom-carrier-count time series, confirmed live as a "
      "Shift_JIS CSV with e-Stat-style @Caption/@@Title metadata rows "
      "followed by roughly 210 real yearly/period data rows from 1985 "
      "to the present (columns: year, period, total, registered, "
      "notified, and pre-2004 Type-I/Type-II carrier splits). Documents "
      "the structural 2004 deregulation where Japan's "
      "registration/notification carrier-licensing regime replaced the "
      "old Type-I/Type-II system. A handful of embedded unit/datatype "
      "annotation rows from the e-Stat CSV convention survive the "
      "comment strip and will appear as low-content rows alongside the "
      "real data." },

  { .id = "JO28_032_MYNUMBER_CARD_PENETRATION_CSV", .name = "My Number Card Penetration Dashboard — data table CSV",
    .name_ja = "マイナンバーカード普及状況ダッシュボード データテーブル",
    .category = "government", .portal = "https://www.digital.go.jp/resources/govdashboard/mynumber_card_penetration_usage",
    .record_type = "kpi-metric-record",
    .tags = "\"japan\",\"digitalagency\",\"mynumber\",\"penetration\",\"dashboard\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.digital.go.jp/assets/contents/node/basic_page/field_ref_resources/65ee2cb2-0b1f-46fa-9a40-7eefea58a06b/25399603/20260828_mynumber_card_penetration_usage_table.csv",
    .charset = "sjis",
    .interval = 2592000,
    .description = "The Digital Agency's My Number Card penetration dashboard "
      "publishes its underlying figures as a direct Shift_JIS CSV "
      "download alongside its Power BI visualization, confirmed live as "
      "of the 2026-08-28 refresh — a dated date/metric time series "
      "covering card issuance, health-insurance and driver's-license "
      "linkage, and online-service usage counts (the sibling GBizID "
      "dashboard offers only a zip export and was rejected for that "
      "reason). The filename itself embeds the publish date and is "
      "expected to change with each monthly refresh, so this row's "
      "exact URL may need periodic maintenance; that is stated here "
      "rather than assumed permanent." },
};

HP_REGISTER_TABLE(HP3B28_JPGOV)
