/* collectors/pivot/table/hp3b33_fdsnevent.c -- batch 33: fdsnevent
 *
 * NOT PROOF-OF-LIFE VERIFIED. This is the deliberate exception, and it is
 * stated here rather than in a note someone has to find: the session that
 * authored batch 33 had no outbound HTTPS (the environment's network policy
 * allowed only Anthropic APIs, package registries and GitHub), so NO row in
 * this file was fetched over the wire. There is no docs/verified-sources-batch33.tsv
 * and no rejects file, because nothing was probed to pass or fail.
 *
 * What IS established, and why these rows are candidates rather than guesses:
 *   - every host is proven reachable by a DIFFERENT row already in this tree
 *     that uses the same host and the same API base path;
 *   - the endpoint path, its query parameters, its paging and its response
 *     envelope are fixed by a published specification (the CKAN Action API,
 *     the FDSN web service spec, the Socrata Discovery API) rather than
 *     inferred from a page;
 *   - batch_exclusions.py --bin reports 0 id or endpoint collisions against
 *     the registry's 18,170 sources, and the reachability (rule 3) and
 *     pagination audits are clean.
 *
 * So treat each row as REGISTERED, NOT PROVEN. Rules 4, 4b and 4d — fetching
 * is not emitting, emitting is not storing, answering is not answering the
 * question — are unmeasured here. The first session with egress should run:
 *     python3 tools/audit_registry_emit.py --bin ./bin/japanosint \
 *             --match JO33_ --jobs 6 --timeout 220 --out b33.tsv
 *     python3 tools/probe_hp_batch.py docs/candidate-sources-batch33.*.txt \
 *             --check-filter
 * and retire whatever comes back EMITS_NOTHING, COLLISION or FILTER_IGNORED.
 * Unlike batch 31, the manifests exist, so those tools can be pointed at this
 * batch directly.
 *
 * The engine cannot fabricate: a moved or reshaped endpoint yields an honest
 * empty, never an invented record. An unmeasured row is a coverage gap.
 *
 * Generated by tools/gen_hp_batch.py from
 * docs/candidate-sources-batch33.fdsnevent.txt — scaffolded from it ONCE.
 * This file is the maintained copy from here on: repairs carry the live counts
 * that justify them, which the manifest has nowhere to put. Regenerating over
 * it reverts them, so the generator refuses to without --force. See CLAUDE.md,
 * "Batch tooling".
 */
#include "lib/hpengine.h"

static const hp_source HP3B33_FDSNEVENT[] = {
  { .id = "JO33_FDSNEVT_AUSPASS_EDU_AU", .name = "AusPass, Australian Passive Seismic Server — FDSN event "
      "catalogue",
    .name_ja = "豪州 AusPass 地震カタログ（FDSN）",
    .category = "surveillance", .portal = "https://auspass.edu.au",
    .record_type = "seismic-event",
    .tags = "\"sensor\",\"seismic\",\"hazard\",\"fdsn\",\"event-catalogue\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://auspass.edu.au/fdsnws/event/1/query?format=text&nodata=404&orderby=time&limit=1000",
    .csv_comment = "#",
    .csv_delim = "pipe",
    .csv_no_header = 1,
    .date_keys = "col1",
    .id_keys = "col0",
    .interval = 86400,
    .lat_key = "col2",
    .lon_key = "col3",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 1000,
    .page_start = 1,
    .timeout_ms = 120000,
    .title_keys = "col12,col10",
    .description = "UNPROBED. FDSN event/1: one pipe-delimited row per located event "
      "with event id, origin time, latitude, longitude, depth, the "
      "contributing agency and catalogue, magnitude and magnitude type, "
      "and the region name. Each data centre authoritative for its own "
      "region, so the national catalogues carry events the global feeds "
      "never list. Host and /fdsnws/ base are proven live by an "
      "existing wired row on this host; the path and schema are fixed "
      "by the FDSN specification. Walked by the specification's own "
      "limit/offset, whose offset is 1-based." },

  { .id = "JO33_FDSNEVT_EIDA_BGR_DE", .name = "BGR, German Federal Institute for Geosciences — FDSN event "
      "catalogue",
    .name_ja = "ドイツ連邦地球科学研究所 BGR 地震カタログ（FDSN）",
    .category = "surveillance", .portal = "https://eida.bgr.de",
    .record_type = "seismic-event",
    .tags = "\"sensor\",\"seismic\",\"hazard\",\"fdsn\",\"event-catalogue\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://eida.bgr.de/fdsnws/event/1/query?format=text&nodata=404&orderby=time&limit=1000",
    .csv_comment = "#",
    .csv_delim = "pipe",
    .csv_no_header = 1,
    .date_keys = "col1",
    .id_keys = "col0",
    .interval = 86400,
    .lat_key = "col2",
    .lon_key = "col3",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 1000,
    .page_start = 1,
    .timeout_ms = 120000,
    .title_keys = "col12,col10",
    .description = "UNPROBED. FDSN event/1: one pipe-delimited row per located event "
      "with event id, origin time, latitude, longitude, depth, the "
      "contributing agency and catalogue, magnitude and magnitude type, "
      "and the region name. Each data centre authoritative for its own "
      "region, so the national catalogues carry events the global feeds "
      "never list. Host and /fdsnws/ base are proven live by an "
      "existing wired row on this host; the path and schema are fixed "
      "by the FDSN specification. Walked by the specification's own "
      "limit/offset, whose offset is 1-based." },

  { .id = "JO33_FDSNEVT_EIDA_BGS_AC_UK", .name = "British Geological Survey — FDSN event catalogue",
    .name_ja = "英国地質調査所 BGS 地震カタログ（FDSN）",
    .category = "surveillance", .portal = "https://eida.bgs.ac.uk",
    .record_type = "seismic-event",
    .tags = "\"sensor\",\"seismic\",\"hazard\",\"fdsn\",\"event-catalogue\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://eida.bgs.ac.uk/fdsnws/event/1/query?format=text&nodata=404&orderby=time&limit=1000",
    .csv_comment = "#",
    .csv_delim = "pipe",
    .csv_no_header = 1,
    .date_keys = "col1",
    .id_keys = "col0",
    .interval = 86400,
    .lat_key = "col2",
    .lon_key = "col3",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 1000,
    .page_start = 1,
    .timeout_ms = 120000,
    .title_keys = "col12,col10",
    .description = "UNPROBED. FDSN event/1: one pipe-delimited row per located event "
      "with event id, origin time, latitude, longitude, depth, the "
      "contributing agency and catalogue, magnitude and magnitude type, "
      "and the region name. Each data centre authoritative for its own "
      "region, so the national catalogues carry events the global feeds "
      "never list. Host and /fdsnws/ base are proven live by an "
      "existing wired row on this host; the path and schema are fixed "
      "by the FDSN specification. Walked by the specification's own "
      "limit/offset, whose offset is 1-based." },

  { .id = "JO33_FDSNEVT_EIDA_ETHZ_CH", .name = "Swiss Seismological Service, ETH Zurich — FDSN event catalogue",
    .name_ja = "スイス地震サービス ETHZ 地震カタログ（FDSN）",
    .category = "surveillance", .portal = "https://eida.ethz.ch",
    .record_type = "seismic-event",
    .tags = "\"sensor\",\"seismic\",\"hazard\",\"fdsn\",\"event-catalogue\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://eida.ethz.ch/fdsnws/event/1/query?format=text&nodata=404&orderby=time&limit=1000",
    .csv_comment = "#",
    .csv_delim = "pipe",
    .csv_no_header = 1,
    .date_keys = "col1",
    .id_keys = "col0",
    .interval = 86400,
    .lat_key = "col2",
    .lon_key = "col3",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 1000,
    .page_start = 1,
    .timeout_ms = 120000,
    .title_keys = "col12,col10",
    .description = "UNPROBED. FDSN event/1: one pipe-delimited row per located event "
      "with event id, origin time, latitude, longitude, depth, the "
      "contributing agency and catalogue, magnitude and magnitude type, "
      "and the region name. Each data centre authoritative for its own "
      "region, so the national catalogues carry events the global feeds "
      "never list. Host and /fdsnws/ base are proven live by an "
      "existing wired row on this host; the path and schema are fixed "
      "by the FDSN specification. Walked by the specification's own "
      "limit/offset, whose offset is 1-based." },

  { .id = "JO33_FDSNEVT_EIDA_GEIN_NOA_GR", .name = "National Observatory of Athens — FDSN event catalogue",
    .name_ja = "アテネ国立天文台 地震カタログ（FDSN）",
    .category = "surveillance", .portal = "https://eida.gein.noa.gr",
    .record_type = "seismic-event",
    .tags = "\"sensor\",\"seismic\",\"hazard\",\"fdsn\",\"event-catalogue\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://eida.gein.noa.gr/fdsnws/event/1/query?format=text&nodata=404&orderby=time&limit=1000",
    .csv_comment = "#",
    .csv_delim = "pipe",
    .csv_no_header = 1,
    .date_keys = "col1",
    .id_keys = "col0",
    .interval = 86400,
    .lat_key = "col2",
    .lon_key = "col3",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 1000,
    .page_start = 1,
    .timeout_ms = 120000,
    .title_keys = "col12,col10",
    .description = "UNPROBED. FDSN event/1: one pipe-delimited row per located event "
      "with event id, origin time, latitude, longitude, depth, the "
      "contributing agency and catalogue, magnitude and magnitude type, "
      "and the region name. Each data centre authoritative for its own "
      "region, so the national catalogues carry events the global feeds "
      "never list. Host and /fdsnws/ base are proven live by an "
      "existing wired row on this host; the path and schema are fixed "
      "by the FDSN specification. Walked by the specification's own "
      "limit/offset, whose offset is 1-based." },

  { .id = "JO33_FDSNEVT_EIDA_GEO_UIB_NO", .name = "University of Bergen, Norway — FDSN event catalogue",
    .name_ja = "ノルウェー ベルゲン大学 地震カタログ（FDSN）",
    .category = "surveillance", .portal = "https://eida.geo.uib.no",
    .record_type = "seismic-event",
    .tags = "\"sensor\",\"seismic\",\"hazard\",\"fdsn\",\"event-catalogue\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://eida.geo.uib.no/fdsnws/event/1/query?format=text&nodata=404&orderby=time&limit=1000",
    .csv_comment = "#",
    .csv_delim = "pipe",
    .csv_no_header = 1,
    .date_keys = "col1",
    .id_keys = "col0",
    .interval = 86400,
    .lat_key = "col2",
    .lon_key = "col3",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 1000,
    .page_start = 1,
    .timeout_ms = 120000,
    .title_keys = "col12,col10",
    .description = "UNPROBED. FDSN event/1: one pipe-delimited row per located event "
      "with event id, origin time, latitude, longitude, depth, the "
      "contributing agency and catalogue, magnitude and magnitude type, "
      "and the region name. Each data centre authoritative for its own "
      "region, so the national catalogues carry events the global feeds "
      "never list. Host and /fdsnws/ base are proven live by an "
      "existing wired row on this host; the path and schema are fixed "
      "by the FDSN specification. Walked by the specification's own "
      "limit/offset, whose offset is 1-based." },

  { .id = "JO33_FDSNEVT_EIDA_KOERI_BOUN_EDU_TR", .name = "KOERI, Bogazici University, Turkey — FDSN event catalogue",
    .name_ja = "トルコ KOERI 地震カタログ（FDSN）",
    .category = "surveillance", .portal = "https://eida.koeri.boun.edu.tr",
    .record_type = "seismic-event",
    .tags = "\"sensor\",\"seismic\",\"hazard\",\"fdsn\",\"event-catalogue\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://eida.koeri.boun.edu.tr/fdsnws/event/1/query?format=text&nodata=404&orderby=time&limit=1000",
    .csv_comment = "#",
    .csv_delim = "pipe",
    .csv_no_header = 1,
    .date_keys = "col1",
    .id_keys = "col0",
    .interval = 86400,
    .lat_key = "col2",
    .lon_key = "col3",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 1000,
    .page_start = 1,
    .timeout_ms = 120000,
    .title_keys = "col12,col10",
    .description = "UNPROBED. FDSN event/1: one pipe-delimited row per located event "
      "with event id, origin time, latitude, longitude, depth, the "
      "contributing agency and catalogue, magnitude and magnitude type, "
      "and the region name. Each data centre authoritative for its own "
      "region, so the national catalogues carry events the global feeds "
      "never list. Host and /fdsnws/ base are proven live by an "
      "existing wired row on this host; the path and schema are fixed "
      "by the FDSN specification. Walked by the specification's own "
      "limit/offset, whose offset is 1-based." },

  { .id = "JO33_FDSNEVT_ERDE_GEOPHYSIK_UNI_MUENCHEN_DE", .name = "LMU Munich Geophysics — FDSN event catalogue",
    .name_ja = "ミュンヘン大学 地球物理 地震カタログ（FDSN）",
    .category = "surveillance", .portal = "https://erde.geophysik.uni-muenchen.de",
    .record_type = "seismic-event",
    .tags = "\"sensor\",\"seismic\",\"hazard\",\"fdsn\",\"event-catalogue\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://erde.geophysik.uni-muenchen.de/fdsnws/event/1/query?format=text&nodata=404&orderby=time&limit=1000",
    .csv_comment = "#",
    .csv_delim = "pipe",
    .csv_no_header = 1,
    .date_keys = "col1",
    .id_keys = "col0",
    .interval = 86400,
    .lat_key = "col2",
    .lon_key = "col3",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 1000,
    .page_start = 1,
    .timeout_ms = 120000,
    .title_keys = "col12,col10",
    .description = "UNPROBED. FDSN event/1: one pipe-delimited row per located event "
      "with event id, origin time, latitude, longitude, depth, the "
      "contributing agency and catalogue, magnitude and magnitude type, "
      "and the region name. Each data centre authoritative for its own "
      "region, so the national catalogues carry events the global feeds "
      "never list. Host and /fdsnws/ base are proven live by an "
      "existing wired row on this host; the path and schema are fixed "
      "by the FDSN specification. Walked by the specification's own "
      "limit/offset, whose offset is 1-based." },

  { .id = "JO33_FDSNEVT_SEISDATA_EPOS_FRANCE_FR", .name = "EPOS-France (RESIF) — FDSN event catalogue",
    .name_ja = "EPOS-France (RESIF) 地震カタログ（FDSN）",
    .category = "surveillance", .portal = "https://seisdata.epos-france.fr",
    .record_type = "seismic-event",
    .tags = "\"sensor\",\"seismic\",\"hazard\",\"fdsn\",\"event-catalogue\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://seisdata.epos-france.fr/fdsnws/event/1/query?format=text&nodata=404&orderby=time&limit=1000",
    .csv_comment = "#",
    .csv_delim = "pipe",
    .csv_no_header = 1,
    .date_keys = "col1",
    .id_keys = "col0",
    .interval = 86400,
    .lat_key = "col2",
    .lon_key = "col3",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 1000,
    .page_start = 1,
    .timeout_ms = 120000,
    .title_keys = "col12,col10",
    .description = "UNPROBED. FDSN event/1: one pipe-delimited row per located event "
      "with event id, origin time, latitude, longitude, depth, the "
      "contributing agency and catalogue, magnitude and magnitude type, "
      "and the region name. Each data centre authoritative for its own "
      "region, so the national catalogues carry events the global feeds "
      "never list. Host and /fdsnws/ base are proven live by an "
      "existing wired row on this host; the path and schema are fixed "
      "by the FDSN specification. Walked by the specification's own "
      "limit/offset, whose offset is 1-based." },

  { .id = "JO33_FDSNEVT_SERVICE_IRIS_EDU", .name = "IRIS / EarthScope DMC — FDSN event catalogue",
    .name_ja = "IRIS / EarthScope 地震カタログ（FDSN）",
    .category = "surveillance", .portal = "https://service.iris.edu",
    .record_type = "seismic-event",
    .tags = "\"sensor\",\"seismic\",\"hazard\",\"fdsn\",\"event-catalogue\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://service.iris.edu/fdsnws/event/1/query?format=text&nodata=404&orderby=time&limit=1000",
    .csv_comment = "#",
    .csv_delim = "pipe",
    .csv_no_header = 1,
    .date_keys = "col1",
    .id_keys = "col0",
    .interval = 86400,
    .lat_key = "col2",
    .lon_key = "col3",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 1000,
    .page_start = 1,
    .timeout_ms = 120000,
    .title_keys = "col12,col10",
    .description = "UNPROBED. FDSN event/1: one pipe-delimited row per located event "
      "with event id, origin time, latitude, longitude, depth, the "
      "contributing agency and catalogue, magnitude and magnitude type, "
      "and the region name. Each data centre authoritative for its own "
      "region, so the national catalogues carry events the global feeds "
      "never list. Host and /fdsnws/ base are proven live by an "
      "existing wired row on this host; the path and schema are fixed "
      "by the FDSN specification. Walked by the specification's own "
      "limit/offset, whose offset is 1-based." },

  { .id = "JO33_FDSNEVT_SERVICE_SCEDC_CALTECH_EDU", .name = "SCEDC, Caltech (Southern California) — FDSN event catalogue",
    .name_ja = "南カリフォルニア地震データセンター 地震カタログ（FDSN）",
    .category = "surveillance", .portal = "https://service.scedc.caltech.edu",
    .record_type = "seismic-event",
    .tags = "\"sensor\",\"seismic\",\"hazard\",\"fdsn\",\"event-catalogue\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://service.scedc.caltech.edu/fdsnws/event/1/query?format=text&nodata=404&orderby=time&limit=1000",
    .csv_comment = "#",
    .csv_delim = "pipe",
    .csv_no_header = 1,
    .date_keys = "col1",
    .id_keys = "col0",
    .interval = 86400,
    .lat_key = "col2",
    .lon_key = "col3",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 1000,
    .page_start = 1,
    .timeout_ms = 120000,
    .title_keys = "col12,col10",
    .description = "UNPROBED. FDSN event/1: one pipe-delimited row per located event "
      "with event id, origin time, latitude, longitude, depth, the "
      "contributing agency and catalogue, magnitude and magnitude type, "
      "and the region name. Each data centre authoritative for its own "
      "region, so the national catalogues carry events the global feeds "
      "never list. Host and /fdsnws/ base are proven live by an "
      "existing wired row on this host; the path and schema are fixed "
      "by the FDSN specification. Walked by the specification's own "
      "limit/offset, whose offset is 1-based." },

  { .id = "JO33_FDSNEVT_WS_ICGC_CAT", .name = "ICGC, Catalonia — FDSN event catalogue",
    .name_ja = "カタルーニャ ICGC 地震カタログ（FDSN）",
    .category = "surveillance", .portal = "https://ws.icgc.cat",
    .record_type = "seismic-event",
    .tags = "\"sensor\",\"seismic\",\"hazard\",\"fdsn\",\"event-catalogue\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://ws.icgc.cat/fdsnws/event/1/query?format=text&nodata=404&orderby=time&limit=1000",
    .csv_comment = "#",
    .csv_delim = "pipe",
    .csv_no_header = 1,
    .date_keys = "col1",
    .id_keys = "col0",
    .interval = 86400,
    .lat_key = "col2",
    .lon_key = "col3",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 1000,
    .page_start = 1,
    .timeout_ms = 120000,
    .title_keys = "col12,col10",
    .description = "UNPROBED. FDSN event/1: one pipe-delimited row per located event "
      "with event id, origin time, latitude, longitude, depth, the "
      "contributing agency and catalogue, magnitude and magnitude type, "
      "and the region name. Each data centre authoritative for its own "
      "region, so the national catalogues carry events the global feeds "
      "never list. Host and /fdsnws/ base are proven live by an "
      "existing wired row on this host; the path and schema are fixed "
      "by the FDSN specification. Walked by the specification's own "
      "limit/offset, whose offset is 1-based." },

  { .id = "JO33_FDSNEVT_WWW_ORFEUS_EU_ORG", .name = "ORFEUS, European seismology — FDSN event catalogue",
    .name_ja = "欧州地震学 ORFEUS 地震カタログ（FDSN）",
    .category = "surveillance", .portal = "https://www.orfeus-eu.org",
    .record_type = "seismic-event",
    .tags = "\"sensor\",\"seismic\",\"hazard\",\"fdsn\",\"event-catalogue\"",
    .mode = HP_CSV, .want = HP_ANY, .free_tier = 1,
    .url = "https://www.orfeus-eu.org/fdsnws/event/1/query?format=text&nodata=404&orderby=time&limit=1000",
    .csv_comment = "#",
    .csv_delim = "pipe",
    .csv_no_header = 1,
    .date_keys = "col1",
    .id_keys = "col0",
    .interval = 86400,
    .lat_key = "col2",
    .lon_key = "col3",
    .page_max = 20,
    .page_param = "offset",
    .page_size = 1000,
    .page_start = 1,
    .timeout_ms = 120000,
    .title_keys = "col12,col10",
    .description = "UNPROBED. FDSN event/1: one pipe-delimited row per located event "
      "with event id, origin time, latitude, longitude, depth, the "
      "contributing agency and catalogue, magnitude and magnitude type, "
      "and the region name. Each data centre authoritative for its own "
      "region, so the national catalogues carry events the global feeds "
      "never list. Host and /fdsnws/ base are proven live by an "
      "existing wired row on this host; the path and schema are fixed "
      "by the FDSN specification. Walked by the specification's own "
      "limit/offset, whose offset is 1-based." },
};

HP_REGISTER_TABLE(HP3B33_FDSNEVENT)
