/* UNVERIFIED candidate us_state sources (60), part 1.
 * These endpoints were NOT fetched at generation time — the
 * authoring environment had no outbound egress — so unlike the
 * vsrc_* files there is no recorded 2xx/parse proof behind them.
 * Each one is a documented platform API contract on a real host;
 * see docs/candidate-sources-batch14.tsv for provenance.
 * A dead endpoint here degrades to an explicit fetch error at
 * runtime and never to invented content. Promote to verified with
 * `make verify-candidates` (tools/promote_candidates.py).
 * Generated by collectors/gen_verified_sources.py — regenerate
 * rather than hand-editing. */
#include "_verified_macros.inc"

VJSON(us_arcgishub_addresses, "us-arcgishub-addresses", "ArcGIS Hub — Address Point Layers", "ArcGIS Hub address point レイヤー",
  "us_state", "geospatial",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=address%20point",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"addresses\"]", 86400,
  "Public ArcGIS Hub datasets matching 'address point', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_airports, "us-arcgishub-airports", "ArcGIS Hub — Airport Layers", "ArcGIS Hub airport レイヤー",
  "us_state", "aviation",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=airport",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"airports\"]", 86400,
  "Public ArcGIS Hub datasets matching 'airport', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_bridges, "us-arcgishub-bridges", "ArcGIS Hub — Bridge Layers", "ArcGIS Hub bridge レイヤー",
  "us_state", "infrastructure",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=bridge",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"bridges\"]", 86400,
  "Public ArcGIS Hub datasets matching 'bridge', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_broadband, "us-arcgishub-broadband", "ArcGIS Hub — Broadband Service Layers", "ArcGIS Hub broadband service レイヤー",
  "us_state", "telecom",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=broadband%20service",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"broadband\"]", 86400,
  "Public ArcGIS Hub datasets matching 'broadband service', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_building_footprints, "us-arcgishub-building-footprints", "ArcGIS Hub — Building Footprint Layers", "ArcGIS Hub building footprint レイヤー",
  "us_state", "geospatial",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=building%20footprint",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"building-footprints\"]", 86400,
  "Public ArcGIS Hub datasets matching 'building footprint', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_cell_towers, "us-arcgishub-cell-towers", "ArcGIS Hub — Cell Tower Layers", "ArcGIS Hub cell tower レイヤー",
  "us_state", "telecom",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=cell%20tower",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"cell-towers\"]", 86400,
  "Public ArcGIS Hub datasets matching 'cell tower', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_code_enforcement, "us-arcgishub-code-enforcement", "ArcGIS Hub — Code Enforcement Layers", "ArcGIS Hub code enforcement レイヤー",
  "us_state", "government",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=code%20enforcement",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"code-enforcement\"]", 86400,
  "Public ArcGIS Hub datasets matching 'code enforcement', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_colleges, "us-arcgishub-colleges", "ArcGIS Hub — College Campus Layers", "ArcGIS Hub college campus レイヤー",
  "us_state", "education",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=college%20campus",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"colleges\"]", 86400,
  "Public ArcGIS Hub datasets matching 'college campus', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_crime_incidents, "us-arcgishub-crime-incidents", "ArcGIS Hub — Crime Incident Layers", "ArcGIS Hub crime incident レイヤー",
  "us_state", "crime",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=crime%20incident",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"crime-incidents\"]", 86400,
  "Public ArcGIS Hub datasets matching 'crime incident', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_dams, "us-arcgishub-dams", "ArcGIS Hub — Dam Layers", "ArcGIS Hub dam レイヤー",
  "us_state", "infrastructure",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=dam",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"dams\"]", 86400,
  "Public ArcGIS Hub datasets matching 'dam', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_evacuation_routes, "us-arcgishub-evacuation-routes", "ArcGIS Hub — Evacuation Route Layers", "ArcGIS Hub evacuation route レイヤー",
  "us_state", "disaster",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=evacuation%20route",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"evacuation-routes\"]", 86400,
  "Public ArcGIS Hub datasets matching 'evacuation route', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_fire_stations, "us-arcgishub-fire-stations", "ArcGIS Hub — Fire Station Layers", "ArcGIS Hub fire station レイヤー",
  "us_state", "disaster",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=fire%20station",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"fire-stations\"]", 86400,
  "Public ArcGIS Hub datasets matching 'fire station', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_floodplain, "us-arcgishub-floodplain", "ArcGIS Hub — Floodplain Layers", "ArcGIS Hub floodplain レイヤー",
  "us_state", "disaster",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=floodplain",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"floodplain\"]", 86400,
  "Public ArcGIS Hub datasets matching 'floodplain', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_government_buildings, "us-arcgishub-government-buildings", "ArcGIS Hub — Government Building Layers", "ArcGIS Hub government building レイヤー",
  "us_state", "government",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=government%20building",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"government-buildings\"]", 86400,
  "Public ArcGIS Hub datasets matching 'government building', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_hospitals, "us-arcgishub-hospitals", "ArcGIS Hub — Hospital Layers", "ArcGIS Hub hospital レイヤー",
  "us_state", "health",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=hospital",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"hospitals\"]", 86400,
  "Public ArcGIS Hub datasets matching 'hospital', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_libraries, "us-arcgishub-libraries", "ArcGIS Hub — Library Layers", "ArcGIS Hub library レイヤー",
  "us_state", "government",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=library",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"libraries\"]", 86400,
  "Public ArcGIS Hub datasets matching 'library', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_military, "us-arcgishub-military", "ArcGIS Hub — Military Installation Layers", "ArcGIS Hub military installation レイヤー",
  "us_state", "security",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=military%20installation",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"military\"]", 86400,
  "Public ArcGIS Hub datasets matching 'military installation', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_parcels, "us-arcgishub-parcels", "ArcGIS Hub — Parcel Layers", "ArcGIS Hub parcel レイヤー",
  "us_state", "geospatial",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=parcel",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"parcels\"]", 86400,
  "Public ArcGIS Hub datasets matching 'parcel', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_pipelines, "us-arcgishub-pipelines", "ArcGIS Hub — Pipeline Layers", "ArcGIS Hub pipeline レイヤー",
  "us_state", "infrastructure",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=pipeline",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"pipelines\"]", 86400,
  "Public ArcGIS Hub datasets matching 'pipeline', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_police_stations, "us-arcgishub-police-stations", "ArcGIS Hub — Police Station Layers", "ArcGIS Hub police station レイヤー",
  "us_state", "security",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=police%20station",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"police-stations\"]", 86400,
  "Public ArcGIS Hub datasets matching 'police station', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_ports, "us-arcgishub-ports", "ArcGIS Hub — Port Facility Layers", "ArcGIS Hub port facility レイヤー",
  "us_state", "maritime",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=port%20facility",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"ports\"]", 86400,
  "Public ArcGIS Hub datasets matching 'port facility', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_power_plants, "us-arcgishub-power-plants", "ArcGIS Hub — Power Plant Layers", "ArcGIS Hub power plant レイヤー",
  "us_state", "energy",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=power%20plant",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"power-plants\"]", 86400,
  "Public ArcGIS Hub datasets matching 'power plant', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_railroads, "us-arcgishub-railroads", "ArcGIS Hub — Railroad Layers", "ArcGIS Hub railroad レイヤー",
  "us_state", "transport",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=railroad",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"railroads\"]", 86400,
  "Public ArcGIS Hub datasets matching 'railroad', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_schools, "us-arcgishub-schools", "ArcGIS Hub — School Layers", "ArcGIS Hub school レイヤー",
  "us_state", "education",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=school",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"schools\"]", 86400,
  "Public ArcGIS Hub datasets matching 'school', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_substations, "us-arcgishub-substations", "ArcGIS Hub — Electric Substation Layers", "ArcGIS Hub electric substation レイヤー",
  "us_state", "energy",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=electric%20substation",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"substations\"]", 86400,
  "Public ArcGIS Hub datasets matching 'electric substation', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_surveillance_cameras, "us-arcgishub-surveillance-cameras", "ArcGIS Hub — Surveillance Camera Layers", "ArcGIS Hub surveillance camera レイヤー",
  "us_state", "cameras",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=surveillance%20camera",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"surveillance-cameras\"]", 86400,
  "Public ArcGIS Hub datasets matching 'surveillance camera', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_traffic_cameras, "us-arcgishub-traffic-cameras", "ArcGIS Hub — Traffic Camera Layers", "ArcGIS Hub traffic camera レイヤー",
  "us_state", "cameras",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=traffic%20camera",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"traffic-cameras\"]", 86400,
  "Public ArcGIS Hub datasets matching 'traffic camera', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_traffic_counts, "us-arcgishub-traffic-counts", "ArcGIS Hub — Traffic Count Layers", "ArcGIS Hub traffic count レイヤー",
  "us_state", "transport",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=traffic%20count",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"traffic-counts\"]", 86400,
  "Public ArcGIS Hub datasets matching 'traffic count', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_voting_precincts, "us-arcgishub-voting-precincts", "ArcGIS Hub — Voting Precinct Layers", "ArcGIS Hub voting precinct レイヤー",
  "us_state", "government",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=voting%20precinct",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"voting-precincts\"]", 86400,
  "Public ArcGIS Hub datasets matching 'voting precinct', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_water_treatment, "us-arcgishub-water-treatment", "ArcGIS Hub — Water Treatment Plant Layers", "ArcGIS Hub water treatment plant レイヤー",
  "us_state", "infrastructure",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=water%20treatment%20plant",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"water-treatment\"]", 86400,
  "Public ArcGIS Hub datasets matching 'water treatment plant', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_wildfire_risk, "us-arcgishub-wildfire-risk", "ArcGIS Hub — Wildfire Risk Layers", "ArcGIS Hub wildfire risk レイヤー",
  "us_state", "disaster",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=wildfire%20risk",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"wildfire-risk\"]", 86400,
  "Public ArcGIS Hub datasets matching 'wildfire risk', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_arcgishub_zoning, "us-arcgishub-zoning", "ArcGIS Hub — Zoning Layers", "ArcGIS Hub zoning レイヤー",
  "us_state", "geospatial",
  "https://hub.arcgis.com/api/search/v1/collections/dataset/items?limit=100&q=zoning",
  "features",
  "en", "[\"usa\",\"gis\",\"arcgis\",\"hub\",\"catalog\",\"zoning\"]", 86400,
  "Public ArcGIS Hub datasets matching 'zoning', across US state, county and municipal GIS sites: title, owner organisation, extent, licence and the service URL each layer is served from.");

VJSON(us_socrata_discovery_austin, "us-socrata-discovery-austin", "City of Austin Open Data — Asset Discovery", "オースティン市 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.austintexas.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"austin\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.austintexas.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_baltimore, "us-socrata-discovery-baltimore", "City of Baltimore Open Data — Asset Discovery", "ボルチモア市 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.baltimorecity.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"baltimore\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.baltimorecity.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_boston, "us-socrata-discovery-boston", "City of Boston Open Data — Asset Discovery", "ボストン市 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.boston.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"boston\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.boston.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_bts, "us-socrata-discovery-bts", "US Bureau of Transportation Statistics — Asset Discovery", "米国運輸統計局 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.bts.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"bts\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.bts.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_california, "us-socrata-discovery-california", "State of California Open Data — Asset Discovery", "カリフォルニア州 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.ca.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"california\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.ca.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_cambridge, "us-socrata-discovery-cambridge", "City of Cambridge Open Data — Asset Discovery", "ケンブリッジ市 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.cambridgema.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"cambridge\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.cambridgema.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_cdc, "us-socrata-discovery-cdc", "US CDC Open Data — Asset Discovery", "米国CDC データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.cdc.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"cdc\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.cdc.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_chicago, "us-socrata-discovery-chicago", "City of Chicago Open Data — Asset Discovery", "シカゴ市 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.cityofchicago.org",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"chicago\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.cityofchicago.org, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_chronicdata, "us-socrata-discovery-chronicdata", "US CDC Chronic Disease Data — Asset Discovery", "米国CDC 慢性疾患 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=chronicdata.cdc.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"chronicdata\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on chronicdata.cdc.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_colorado, "us-socrata-discovery-colorado", "State of Colorado Open Data — Asset Discovery", "コロラド州 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.colorado.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"colorado\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.colorado.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_connecticut, "us-socrata-discovery-connecticut", "State of Connecticut Open Data — Asset Discovery", "コネチカット州 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.ct.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"connecticut\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.ct.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_cook, "us-socrata-discovery-cook", "Cook County Open Data — Asset Discovery", "クック郡 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=datacatalog.cookcountyil.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"cook\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on datacatalog.cookcountyil.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_dallas, "us-socrata-discovery-dallas", "City of Dallas Open Data — Asset Discovery", "ダラス市 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=www.dallasopendata.com",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"dallas\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on www.dallasopendata.com, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_delaware, "us-socrata-discovery-delaware", "State of Delaware Open Data — Asset Discovery", "デラウェア州 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.delaware.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"delaware\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.delaware.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_dot, "us-socrata-discovery-dot", "US DOT Open Data — Asset Discovery", "米国運輸省 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.transportation.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"dot\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.transportation.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_energy, "us-socrata-discovery-energy", "US Open Energy Information — Asset Discovery", "米国エネルギー情報 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.openei.org",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"energy\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.openei.org, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_fcc, "us-socrata-discovery-fcc", "US FCC Open Data — Asset Discovery", "米国FCC データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=opendata.fcc.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"fcc\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on opendata.fcc.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_hawaii, "us-socrata-discovery-hawaii", "State of Hawaii Open Data — Asset Discovery", "ハワイ州 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.hawaii.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"hawaii\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.hawaii.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_healthdata, "us-socrata-discovery-healthdata", "US HealthData.gov — Asset Discovery", "米国保健データ データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=healthdata.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"healthdata\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on healthdata.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_hrsa, "us-socrata-discovery-hrsa", "US Health Resources and Services Data — Asset Discovery", "米国HRSA データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.hrsa.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"hrsa\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.hrsa.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_illinois, "us-socrata-discovery-illinois", "State of Illinois Open Data — Asset Discovery", "イリノイ州 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.illinois.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"illinois\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.illinois.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_iowa, "us-socrata-discovery-iowa", "State of Iowa Open Data — Asset Discovery", "アイオワ州 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.iowa.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"iowa\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.iowa.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_kansascity, "us-socrata-discovery-kansascity", "Kansas City Open Data — Asset Discovery", "カンザスシティ データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.kcmo.org",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"kansascity\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.kcmo.org, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_kingcounty, "us-socrata-discovery-kingcounty", "King County Open Data — Asset Discovery", "キング郡 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.kingcounty.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"kingcounty\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.kingcounty.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_losangeles, "us-socrata-discovery-losangeles", "City of Los Angeles Open Data — Asset Discovery", "ロサンゼルス市 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.lacity.org",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"losangeles\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.lacity.org, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_louisville, "us-socrata-discovery-louisville", "Louisville Metro Open Data — Asset Discovery", "ルイビル市 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.louisvilleky.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"louisville\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.louisvilleky.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_maryland, "us-socrata-discovery-maryland", "State of Maryland Open Data — Asset Discovery", "メリーランド州 データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=opendata.maryland.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"maryland\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on opendata.maryland.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");

VJSON(us_socrata_discovery_medicare, "us-socrata-discovery-medicare", "US Centers for Medicare and Medicaid Data — Asset Discovery", "米国CMS データ資産一覧",
  "us_state", "registry",
  "https://api.us.socrata.com/api/catalog/v1?limit=100&domains=data.cms.gov",
  "results",
  "en", "[\"usa\",\"opendata\",\"socrata\",\"discovery\",\"medicare\"]", 86400,
  "Every dataset, chart, map, filtered view and file published on data.cms.gov, via the Socrata federated discovery API: identifier, owner, category, column schema and update time.");
