/* UNVERIFIED candidate jp_prefectural sources (60), part 2.
 * These endpoints were NOT fetched at generation time — the
 * authoring environment had no outbound egress — so unlike the
 * vsrc_* files there is no recorded 2xx/parse proof behind them.
 * Each one is a documented platform API contract on a real host;
 * see docs/candidate-sources-batch14.tsv for provenance.
 * A dead endpoint here degrades to an explicit fetch error at
 * runtime and never to invented content. Promote to verified with
 * `make verify-candidates` (tools/promote_candidates.py).
 * Generated by collectors/gen_verified_sources.py — regenerate
 * rather than hand-editing. */
#include "_verified_macros.inc"

VJSON(jp_ckan_geospatial_q_hoikuen, "jp-ckan-geospatial-q-hoikuen", "G-Spatial Information Center (Japan) — Childcare Facilities Datasets", "G空間情報センター 保育園データセット",
  "jp_prefectural", "education",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=保育園",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"hoikuen\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '保育園' (childcare facilities), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_iryou, "jp-ckan-geospatial-q-iryou", "G-Spatial Information Center (Japan) — Healthcare Datasets", "G空間情報センター 医療データセット",
  "jp_prefectural", "health",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=医療",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"iryou\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '医療' (healthcare), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_jinko, "jp-ckan-geospatial-q-jinko", "G-Spatial Information Center (Japan) — Population Datasets", "G空間情報センター 人口データセット",
  "jp_prefectural", "statistics",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=人口",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"jinko\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '人口' (population), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_jishin, "jp-ckan-geospatial-q-jishin", "G-Spatial Information Center (Japan) — Earthquakes Datasets", "G空間情報センター 地震データセット",
  "jp_prefectural", "disaster",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=地震",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"jishin\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '地震' (earthquakes), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_joho, "jp-ckan-geospatial-q-joho", "G-Spatial Information Center (Japan) — Information Systems Datasets", "G空間情報センター 情報システムデータセット",
  "jp_prefectural", "technology",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=情報システム",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"joho\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '情報システム' (information systems), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_kankou, "jp-ckan-geospatial-q-kankou", "G-Spatial Information Center (Japan) — Tourism Datasets", "G空間情報センター 観光データセット",
  "jp_prefectural", "tourism",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=観光",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"kankou\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '観光' (tourism), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_kankyou, "jp-ckan-geospatial-q-kankyou", "G-Spatial Information Center (Japan) — Environment Datasets", "G空間情報センター 環境データセット",
  "jp_prefectural", "environment",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=環境",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"kankyou\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '環境' (environment), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_kasen, "jp-ckan-geospatial-q-kasen", "G-Spatial Information Center (Japan) — Rivers And Flood Control Datasets", "G空間情報センター 河川データセット",
  "jp_prefectural", "disaster",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=河川",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"kasen\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '河川' (rivers and flood control), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_keisatsu, "jp-ckan-geospatial-q-keisatsu", "G-Spatial Information Center (Japan) — Policing Datasets", "G空間情報センター 警察データセット",
  "jp_prefectural", "security",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=警察",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"keisatsu\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '警察' (policing), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_kigyou, "jp-ckan-geospatial-q-kigyou", "G-Spatial Information Center (Japan) — Enterprises Datasets", "G空間情報センター 企業データセット",
  "jp_prefectural", "corporate",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=企業",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"kigyou\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '企業' (enterprises), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_kion, "jp-ckan-geospatial-q-kion", "G-Spatial Information Center (Japan) — Temperature Datasets", "G空間情報センター 気温データセット",
  "jp_prefectural", "weather",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=気温",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"kion\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '気温' (temperature), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_koujou, "jp-ckan-geospatial-q-koujou", "G-Spatial Information Center (Japan) — Factories Datasets", "G空間情報センター 工場データセット",
  "jp_prefectural", "industry",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=工場",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"koujou\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '工場' (factories), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_koutsuu, "jp-ckan-geospatial-q-koutsuu", "G-Spatial Information Center (Japan) — Transport Datasets", "G空間情報センター 交通データセット",
  "jp_prefectural", "transport",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=交通",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"koutsuu\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '交通' (transport), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_kouwan, "jp-ckan-geospatial-q-kouwan", "G-Spatial Information Center (Japan) — Ports Datasets", "G空間情報センター 港湾データセット",
  "jp_prefectural", "maritime",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=港湾",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"kouwan\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '港湾' (ports), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_kouzui, "jp-ckan-geospatial-q-kouzui", "G-Spatial Information Center (Japan) — Flooding Datasets", "G空間情報センター 洪水データセット",
  "jp_prefectural", "disaster",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=洪水",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"kouzui\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '洪水' (flooding), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_kuukou, "jp-ckan-geospatial-q-kuukou", "G-Spatial Information Center (Japan) — Airports Datasets", "G空間情報センター 空港データセット",
  "jp_prefectural", "aviation",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=空港",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"kuukou\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '空港' (airports), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_kyouiku, "jp-ckan-geospatial-q-kyouiku", "G-Spatial Information Center (Japan) — Education Datasets", "G空間情報センター 教育データセット",
  "jp_prefectural", "education",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=教育",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"kyouiku\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '教育' (education), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_nyuusatsu, "jp-ckan-geospatial-q-nyuusatsu", "G-Spatial Information Center (Japan) — Procurement And Tenders Datasets", "G空間情報センター 入札データセット",
  "jp_prefectural", "procurement",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=入札",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"nyuusatsu\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '入札' (procurement and tenders), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_sangyou, "jp-ckan-geospatial-q-sangyou", "G-Spatial Information Center (Japan) — Industry Datasets", "G空間情報センター 産業データセット",
  "jp_prefectural", "industry",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=産業",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"sangyou\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '産業' (industry), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_shisetsu, "jp-ckan-geospatial-q-shisetsu", "G-Spatial Information Center (Japan) — Public Facilities Datasets", "G空間情報センター 施設データセット",
  "jp_prefectural", "infrastructure",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=施設",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"shisetsu\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '施設' (public facilities), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_shoubou, "jp-ckan-geospatial-q-shoubou", "G-Spatial Information Center (Japan) — Fire And Rescue Datasets", "G空間情報センター 消防データセット",
  "jp_prefectural", "disaster",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=消防",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"shoubou\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '消防' (fire and rescue), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_suidou, "jp-ckan-geospatial-q-suidou", "G-Spatial Information Center (Japan) — Water Supply Datasets", "G空間情報センター 水道データセット",
  "jp_prefectural", "infrastructure",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=水道",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"suidou\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '水道' (water supply), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_tetsudou, "jp-ckan-geospatial-q-tetsudou", "G-Spatial Information Center (Japan) — Railways Datasets", "G空間情報センター 鉄道データセット",
  "jp_prefectural", "transport",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=鉄道",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"tetsudou\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '鉄道' (railways), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_toukei, "jp-ckan-geospatial-q-toukei", "G-Spatial Information Center (Japan) — Statistics Datasets", "G空間情報センター 統計データセット",
  "jp_prefectural", "statistics",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=統計",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"toukei\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '統計' (statistics), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_tsunami, "jp-ckan-geospatial-q-tsunami", "G-Spatial Information Center (Japan) — Tsunami Datasets", "G空間情報センター 津波データセット",
  "jp_prefectural", "disaster",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=津波",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"tsunami\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '津波' (tsunami), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_tsuushin, "jp-ckan-geospatial-q-tsuushin", "G-Spatial Information Center (Japan) — Telecommunications Datasets", "G空間情報センター 通信データセット",
  "jp_prefectural", "telecom",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=通信",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"tsuushin\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '通信' (telecommunications), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_q_zaisei, "jp-ckan-geospatial-q-zaisei", "G-Spatial Information Center (Japan) — Public Finance Datasets", "G空間情報センター 財政データセット",
  "jp_prefectural", "economy",
  "https://www.geospatial.jp/ckan/api/3/action/package_search?rows=100&q=財政",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"zaisei\",\"geospatial\"]", 86400,
  "Every dataset in G-Spatial Information Center (Japan) matching '財政' (public finance), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_geospatial_recent_changes, "jp-ckan-geospatial-recent-changes", "G-Spatial Information Center (Japan) — Recent Dataset Activity", "G空間情報センター 最近の更新",
  "jp_prefectural", "opendata",
  "https://www.geospatial.jp/ckan/api/3/action/recently_changed_packages_activity_list?limit=100",
  "result",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"registry\",\"geospatial\"]", 86400,
  "The most recent create/update activity across the whole catalogue — a change feed for the portal. Source: G-Spatial Information Center (Japan).");

VJSON(jp_ckan_geospatial_tag_list, "jp-ckan-geospatial-tag-list", "G-Spatial Information Center (Japan) — Tag Vocabulary", "G空間情報センター タグ語彙",
  "jp_prefectural", "opendata",
  "https://www.geospatial.jp/ckan/api/3/action/tag_list?all_fields=false",
  "result",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"registry\",\"geospatial\"]", 86400,
  "The portal's full free-tag vocabulary — a cheap map of what the publisher covers. Source: G-Spatial Information Center (Japan).");

VJSON(jp_ckan_tokyo_group_list, "jp-ckan-tokyo-group-list", "Tokyo Metropolitan Government Open Data — Group Registry", "東京都オープンデータカタログ グループ一覧",
  "jp_prefectural", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/group_list?all_fields=true",
  "result",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"registry\",\"tokyo\"]", 86400,
  "Every thematic group defined in the portal, with dataset counts. Source: Tokyo Metropolitan Government Open Data.");

VJSON(jp_ckan_tokyo_license_list, "jp-ckan-tokyo-license-list", "Tokyo Metropolitan Government Open Data — Licence Registry", "東京都オープンデータカタログ ライセンス一覧",
  "jp_prefectural", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/license_list",
  "result",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"registry\",\"tokyo\"]", 86400,
  "Licences in use across the portal's datasets. Source: Tokyo Metropolitan Government Open Data.");

VJSON(jp_ckan_tokyo_organization_list, "jp-ckan-tokyo-organization-list", "Tokyo Metropolitan Government Open Data — Publisher Registry", "東京都オープンデータカタログ 提供組織一覧",
  "jp_prefectural", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/organization_list?all_fields=true&limit=1000",
  "result",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"registry\",\"tokyo\"]", 86400,
  "Every publishing organisation in the portal with title, description and dataset count. Source: Tokyo Metropolitan Government Open Data.");

VJSON(jp_ckan_tokyo_q_anzen, "jp-ckan-tokyo-q-anzen", "Tokyo Metropolitan Government Open Data — Public Safety Datasets", "東京都オープンデータカタログ 安全データセット",
  "jp_prefectural", "security",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=安全",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"anzen\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '安全' (public safety), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_basu, "jp-ckan-tokyo-q-basu", "Tokyo Metropolitan Government Open Data — Bus Services Datasets", "東京都オープンデータカタログ バスデータセット",
  "jp_prefectural", "transport",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=バス",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"basu\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching 'バス' (bus services), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_bousai, "jp-ckan-tokyo-q-bousai", "Tokyo Metropolitan Government Open Data — Disaster Preparedness Datasets", "東京都オープンデータカタログ 防災データセット",
  "jp_prefectural", "disaster",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=防災",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"bousai\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '防災' (disaster preparedness), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_byouin, "jp-ckan-tokyo-q-byouin", "Tokyo Metropolitan Government Open Data — Hospitals Datasets", "東京都オープンデータカタログ 病院データセット",
  "jp_prefectural", "health",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=病院",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"byouin\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '病院' (hospitals), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_chiiki, "jp-ckan-tokyo-q-chiiki", "Tokyo Metropolitan Government Open Data — Regional Planning Datasets", "東京都オープンデータカタログ 地域データセット",
  "jp_prefectural", "government",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=地域",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"chiiki\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '地域' (regional planning), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_chuusha, "jp-ckan-tokyo-q-chuusha", "Tokyo Metropolitan Government Open Data — Parking Datasets", "東京都オープンデータカタログ 駐車場データセット",
  "jp_prefectural", "transport",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=駐車場",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"chuusha\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '駐車場' (parking), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_dejitaru, "jp-ckan-tokyo-q-dejitaru", "Tokyo Metropolitan Government Open Data — Digital Government Datasets", "東京都オープンデータカタログ デジタルデータセット",
  "jp_prefectural", "technology",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=デジタル",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"dejitaru\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching 'デジタル' (digital government), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_denryoku, "jp-ckan-tokyo-q-denryoku", "Tokyo Metropolitan Government Open Data — Electricity Datasets", "東京都オープンデータカタログ 電力データセット",
  "jp_prefectural", "energy",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=電力",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"denryoku\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '電力' (electricity), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_doro, "jp-ckan-tokyo-q-doro", "Tokyo Metropolitan Government Open Data — Roads Datasets", "東京都オープンデータカタログ 道路データセット",
  "jp_prefectural", "infrastructure",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=道路",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"doro\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '道路' (roads), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_dosha, "jp-ckan-tokyo-q-dosha", "Tokyo Metropolitan Government Open Data — Landslide Hazard Datasets", "東京都オープンデータカタログ 土砂災害データセット",
  "jp_prefectural", "disaster",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=土砂災害",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"dosha\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '土砂災害' (landslide hazard), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_gakkou, "jp-ckan-tokyo-q-gakkou", "Tokyo Metropolitan Government Open Data — Schools Datasets", "東京都オープンデータカタログ 学校データセット",
  "jp_prefectural", "education",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=学校",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"gakkou\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '学校' (schools), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_gomi, "jp-ckan-tokyo-q-gomi", "Tokyo Metropolitan Government Open Data — Waste Collection Datasets", "東京都オープンデータカタログ ごみデータセット",
  "jp_prefectural", "environment",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=ごみ",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"gomi\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching 'ごみ' (waste collection), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_hinanjo, "jp-ckan-tokyo-q-hinanjo", "Tokyo Metropolitan Government Open Data — Evacuation Shelters Datasets", "東京都オープンデータカタログ 避難所データセット",
  "jp_prefectural", "disaster",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=避難所",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"hinanjo\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '避難所' (evacuation shelters), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_hoikuen, "jp-ckan-tokyo-q-hoikuen", "Tokyo Metropolitan Government Open Data — Childcare Facilities Datasets", "東京都オープンデータカタログ 保育園データセット",
  "jp_prefectural", "education",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=保育園",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"hoikuen\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '保育園' (childcare facilities), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_iryou, "jp-ckan-tokyo-q-iryou", "Tokyo Metropolitan Government Open Data — Healthcare Datasets", "東京都オープンデータカタログ 医療データセット",
  "jp_prefectural", "health",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=医療",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"iryou\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '医療' (healthcare), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_jinko, "jp-ckan-tokyo-q-jinko", "Tokyo Metropolitan Government Open Data — Population Datasets", "東京都オープンデータカタログ 人口データセット",
  "jp_prefectural", "statistics",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=人口",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"jinko\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '人口' (population), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_jishin, "jp-ckan-tokyo-q-jishin", "Tokyo Metropolitan Government Open Data — Earthquakes Datasets", "東京都オープンデータカタログ 地震データセット",
  "jp_prefectural", "disaster",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=地震",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"jishin\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '地震' (earthquakes), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_joho, "jp-ckan-tokyo-q-joho", "Tokyo Metropolitan Government Open Data — Information Systems Datasets", "東京都オープンデータカタログ 情報システムデータセット",
  "jp_prefectural", "technology",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=情報システム",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"joho\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '情報システム' (information systems), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_kankou, "jp-ckan-tokyo-q-kankou", "Tokyo Metropolitan Government Open Data — Tourism Datasets", "東京都オープンデータカタログ 観光データセット",
  "jp_prefectural", "tourism",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=観光",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"kankou\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '観光' (tourism), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_kankyou, "jp-ckan-tokyo-q-kankyou", "Tokyo Metropolitan Government Open Data — Environment Datasets", "東京都オープンデータカタログ 環境データセット",
  "jp_prefectural", "environment",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=環境",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"kankyou\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '環境' (environment), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_kasen, "jp-ckan-tokyo-q-kasen", "Tokyo Metropolitan Government Open Data — Rivers And Flood Control Datasets", "東京都オープンデータカタログ 河川データセット",
  "jp_prefectural", "disaster",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=河川",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"kasen\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '河川' (rivers and flood control), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_keisatsu, "jp-ckan-tokyo-q-keisatsu", "Tokyo Metropolitan Government Open Data — Policing Datasets", "東京都オープンデータカタログ 警察データセット",
  "jp_prefectural", "security",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=警察",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"keisatsu\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '警察' (policing), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_kigyou, "jp-ckan-tokyo-q-kigyou", "Tokyo Metropolitan Government Open Data — Enterprises Datasets", "東京都オープンデータカタログ 企業データセット",
  "jp_prefectural", "corporate",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=企業",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"kigyou\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '企業' (enterprises), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_kion, "jp-ckan-tokyo-q-kion", "Tokyo Metropolitan Government Open Data — Temperature Datasets", "東京都オープンデータカタログ 気温データセット",
  "jp_prefectural", "weather",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=気温",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"kion\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '気温' (temperature), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_koujou, "jp-ckan-tokyo-q-koujou", "Tokyo Metropolitan Government Open Data — Factories Datasets", "東京都オープンデータカタログ 工場データセット",
  "jp_prefectural", "industry",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=工場",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"koujou\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '工場' (factories), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_koutsuu, "jp-ckan-tokyo-q-koutsuu", "Tokyo Metropolitan Government Open Data — Transport Datasets", "東京都オープンデータカタログ 交通データセット",
  "jp_prefectural", "transport",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=交通",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"koutsuu\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '交通' (transport), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_kouwan, "jp-ckan-tokyo-q-kouwan", "Tokyo Metropolitan Government Open Data — Ports Datasets", "東京都オープンデータカタログ 港湾データセット",
  "jp_prefectural", "maritime",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=港湾",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"kouwan\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '港湾' (ports), with publisher, licence, resources and update time as held in the catalogue.");

VJSON(jp_ckan_tokyo_q_kouzui, "jp-ckan-tokyo-q-kouzui", "Tokyo Metropolitan Government Open Data — Flooding Datasets", "東京都オープンデータカタログ 洪水データセット",
  "jp_prefectural", "disaster",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?rows=100&q=洪水",
  "result.results",
  "ja", "[\"japan\",\"opendata\",\"ckan\",\"kouzui\",\"tokyo\"]", 86400,
  "Every dataset in Tokyo Metropolitan Government Open Data matching '洪水' (flooding), with publisher, licence, resources and update time as held in the catalogue.");
