/* Verified-live government sources (60), part 4.
 * Every endpoint in this file returned 2xx and parsed to at
 * least one record at generation time; see
 * docs/verified-sources-manifest.tsv for the recorded proof.
 * Generated by collectors/gen_verified_sources.py — regenerate
 * rather than hand-editing. */
#include "_verified_macros.inc"

VJSON(jpx_tokyo_cat_t131105, "jpx-tokyo-cat-t131105", "Tokyo Open Data Catalog — 目黒区", "東京都オープンデータカタログサイト 目黒区",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t131105&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 186 datasets published by 目黒区.");

VJSON(jpx_tokyo_cat_t131113, "jpx-tokyo-cat-t131113", "Tokyo Open Data Catalog — 大田区", "東京都オープンデータカタログサイト 大田区",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t131113&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 278 datasets published by 大田区.");

VJSON(jpx_tokyo_cat_t131148, "jpx-tokyo-cat-t131148", "Tokyo Open Data Catalog — 中野区", "東京都オープンデータカタログサイト 中野区",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t131148&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 167 datasets published by 中野区.");

VJSON(jpx_tokyo_cat_t131156, "jpx-tokyo-cat-t131156", "Tokyo Open Data Catalog — 杉並区", "東京都オープンデータカタログサイト 杉並区",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t131156&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 103 datasets published by 杉並区.");

VJSON(jpx_tokyo_cat_t131199, "jpx-tokyo-cat-t131199", "Tokyo Open Data Catalog — 板橋区", "東京都オープンデータカタログサイト 板橋区",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t131199&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 211 datasets published by 板橋区.");

VJSON(jpx_tokyo_cat_t131202, "jpx-tokyo-cat-t131202", "Tokyo Open Data Catalog — 練馬区", "東京都オープンデータカタログサイト 練馬区",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t131202&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 79 datasets published by 練馬区.");

VJSON(jpx_tokyo_cat_t131237, "jpx-tokyo-cat-t131237", "Tokyo Open Data Catalog — 江戸川区", "東京都オープンデータカタログサイト 江戸川区",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t131237&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 266 datasets published by 江戸川区.");

VJSON(jpx_tokyo_cat_t132012, "jpx-tokyo-cat-t132012", "Tokyo Open Data Catalog — 八王子市", "東京都オープンデータカタログサイト 八王子市",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t132012&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 78 datasets published by 八王子市.");

VJSON(jpx_tokyo_cat_t132021, "jpx-tokyo-cat-t132021", "Tokyo Open Data Catalog — 立川市", "東京都オープンデータカタログサイト 立川市",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t132021&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 35 datasets published by 立川市.");

VJSON(jpx_tokyo_cat_t132055, "jpx-tokyo-cat-t132055", "Tokyo Open Data Catalog — 青梅市", "東京都オープンデータカタログサイト 青梅市",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t132055&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 51 datasets published by 青梅市.");

VJSON(jpx_tokyo_cat_t132080, "jpx-tokyo-cat-t132080", "Tokyo Open Data Catalog — 調布市", "東京都オープンデータカタログサイト 調布市",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t132080&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 1487 datasets published by 調布市.");

VJSON(jpx_tokyo_cat_t132098, "jpx-tokyo-cat-t132098", "Tokyo Open Data Catalog — 町田市", "東京都オープンデータカタログサイト 町田市",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t132098&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 127 datasets published by 町田市.");

VJSON(jpx_tokyo_cat_t132101, "jpx-tokyo-cat-t132101", "Tokyo Open Data Catalog — 小金井市", "東京都オープンデータカタログサイト 小金井市",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t132101&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 50 datasets published by 小金井市.");

VJSON(jpx_tokyo_cat_t132136, "jpx-tokyo-cat-t132136", "Tokyo Open Data Catalog — 東村山市", "東京都オープンデータカタログサイト 東村山市",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t132136&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 45 datasets published by 東村山市.");

VJSON(jpx_tokyo_cat_t132195, "jpx-tokyo-cat-t132195", "Tokyo Open Data Catalog — 狛江市", "東京都オープンデータカタログサイト 狛江市",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t132195&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 399 datasets published by 狛江市.");

VJSON(jpx_tokyo_cat_t132217, "jpx-tokyo-cat-t132217", "Tokyo Open Data Catalog — 清瀬市", "東京都オープンデータカタログサイト 清瀬市",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t132217&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 64 datasets published by 清瀬市.");

VJSON(jpx_tokyo_cat_t132241, "jpx-tokyo-cat-t132241", "Tokyo Open Data Catalog — 多摩市", "東京都オープンデータカタログサイト 多摩市",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t132241&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 61 datasets published by 多摩市.");

VJSON(jpx_tokyo_cat_t132292, "jpx-tokyo-cat-t132292", "Tokyo Open Data Catalog — 西東京市", "東京都オープンデータカタログサイト 西東京市",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t132292&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 37 datasets published by 西東京市.");

VJSON(jpx_tokyo_cat_t313360, "jpx-tokyo-cat-t313360", "Tokyo Open Data Catalog — 東京都生活文化スポーツ局", "東京都オープンデータカタログサイト 東京都生活文化スポーツ局",
  "government", "opendata",
  "https://catalog.data.metro.tokyo.lg.jp/api/3/action/package_search?fq=organization:t313360&rows=100",
  "result.results",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"catalog\"]", 86400,
  "CKAN catalogue slice listing the 46 datasets published by 東京都生活文化スポーツ局.");

VCSV(jpx_tokyo_t000006_toilet, "jpx-tokyo-t000006-toilet", "東京都生活文化局 — public toilets", "東京都生活文化局 都立文化施設におけるエレベーター・多目的トイレのバリアフリー情報",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/seikatubunka/cultural-facilities-barrier-free-elv.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public toilets published by 東京都生活文化局 with per-record coordinates.");

VCSV(jpx_tokyo_t000029_shisetsu, "jpx-tokyo-t000029-shisetsu", "東京都デジタルサービス局 — public facilities", "東京都デジタルサービス局 公共施設一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/suisyoudataset/130001_public_facility.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public facilities published by 東京都デジタルサービス局 with per-record coordinates.");

VCSV(jpx_tokyo_t131016_chusha, "jpx-tokyo-t131016-chusha", "千代田区 — car parks", "千代田区 公営駐車場一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/chiyoda/131016_25car_park.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of car parks published by 千代田区 with per-record coordinates.");

VCSV(jpx_tokyo_t131016_shisetsu, "jpx-tokyo-t131016-shisetsu", "千代田区 — public facilities", "千代田区 公共施設一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/chiyoda/131016_01public_facility.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public facilities published by 千代田区 with per-record coordinates.");

VCSV(jpx_tokyo_t131016_toilet, "jpx-tokyo-t131016-toilet", "千代田区 — public toilets", "千代田区 公衆トイレ一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/chiyoda/131016_13public_toilet.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public toilets published by 千代田区 with per-record coordinates.");

VCSV(jpx_tokyo_t131075_shisetsu, "jpx-tokyo-t131075-shisetsu", "墨田区 — public facilities", "墨田区 公共施設一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/sumida/131075_public_facility.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public facilities published by 墨田区 with per-record coordinates.");

VCSV(jpx_tokyo_t131075_toilet, "jpx-tokyo-t131075-toilet", "墨田区 — public toilets", "墨田区 公衆トイレ一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/sumida/131075_public_toilet.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public toilets published by 墨田区 with per-record coordinates.");

VCSV(jpx_tokyo_t131083_toilet, "jpx-tokyo-t131083-toilet", "江東区 — public toilets", "江東区 公衆トイレ一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/koto/131083_013_public_toilet.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public toilets published by 江東区 with per-record coordinates.");

VCSV(jpx_tokyo_t131091_kosodate, "jpx-tokyo-t131091-kosodate", "品川区 — childcare facilities", "品川区 子育てネウボラ相談実施児童センター一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/shinagawa/kosodateneubora.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of childcare facilities published by 品川区 with per-record coordinates.");

VCSV(jpx_tokyo_t131113_chusha, "jpx-tokyo-t131113-chusha", "大田区 — car parks", "大田区 区営自転車駐車場一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/ootaku/131113_hokanjo-o.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of car parks published by 大田区 with per-record coordinates.");

VCSV(jpx_tokyo_t131156_chusha, "jpx-tokyo-t131156-chusha", "杉並区 — car parks", "杉並区 公営駐車場一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/suginami/131156_car_park.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of car parks published by 杉並区 with per-record coordinates.");

VCSV(jpx_tokyo_t131164_shisetsu, "jpx-tokyo-t131164-shisetsu", "豊島区 — public facilities", "豊島区 公共施設一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/toyoshima/R4_public_facility.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public facilities published by 豊島区 with per-record coordinates.");

VCSV(jpx_tokyo_t131164_toilet, "jpx-tokyo-t131164-toilet", "豊島区 — public toilets", "豊島区 公衆トイレ一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/toyoshima/R4_public_toilet.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public toilets published by 豊島区 with per-record coordinates.");

VCSV(jpx_tokyo_t131199_shisetsu, "jpx-tokyo-t131199-shisetsu", "板橋区 — public facilities", "板橋区 公共施設一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/itabashi/131199_public_facility.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public facilities published by 板橋区 with per-record coordinates.");

VCSV(jpx_tokyo_t131199_toilet, "jpx-tokyo-t131199-toilet", "板橋区 — public toilets", "板橋区 公衆トイレ一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/itabashi/131199_public_toilet.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public toilets published by 板橋区 with per-record coordinates.");

VCSV(jpx_tokyo_t131229_chusha, "jpx-tokyo-t131229-chusha", "葛飾区 — car parks", "葛飾区 公営駐車場一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/katsushika/ods25/131229_car_park.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of car parks published by 葛飾区 with per-record coordinates.");

VCSV(jpx_tokyo_t131229_shisetsu, "jpx-tokyo-t131229-shisetsu", "葛飾区 — public facilities", "葛飾区 公共施設一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/katsushika/131229_public_facility.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public facilities published by 葛飾区 with per-record coordinates.");

VCSV(jpx_tokyo_t131229_toilet, "jpx-tokyo-t131229-toilet", "葛飾区 — public toilets", "葛飾区 公衆トイレ一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/katsushika/131229_public_toilet.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public toilets published by 葛飾区 with per-record coordinates.");

VCSV(jpx_tokyo_t131237_chusha, "jpx-tokyo-t131237-chusha", "江戸川区 — car parks", "江戸川区 公営駐車場一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/edogawa/131237_car_park.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of car parks published by 江戸川区 with per-record coordinates.");

VCSV(jpx_tokyo_t131237_toilet, "jpx-tokyo-t131237-toilet", "江戸川区 — public toilets", "江戸川区 公衆トイレ一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/edogawa/131237_public_toilet.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public toilets published by 江戸川区 with per-record coordinates.");

VCSV(jpx_tokyo_t132039_shisetsu, "jpx-tokyo-t132039-shisetsu", "武蔵野市 — public facilities", "武蔵野市 公共施設一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/musashino/132039_public_facility.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public facilities published by 武蔵野市 with per-record coordinates.");

VCSV(jpx_tokyo_t132039_toilet, "jpx-tokyo-t132039-toilet", "武蔵野市 — public toilets", "武蔵野市 公衆トイレ一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/musashino/132039_public_toilet.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public toilets published by 武蔵野市 with per-record coordinates.");

VCSV(jpx_tokyo_t132080_kosodate, "jpx-tokyo-t132080-kosodate", "調布市 — childcare facilities", "調布市 保育所一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/chofu/132080_chofushi_nurseryschool.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of childcare facilities published by 調布市 with per-record coordinates.");

VCSV(jpx_tokyo_t132101_chusha, "jpx-tokyo-t132101-chusha", "小金井市 — car parks", "小金井市 公営駐車場一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/koganei/25_carparking.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of car parks published by 小金井市 with per-record coordinates.");

VCSV(jpx_tokyo_t132101_shisetsu, "jpx-tokyo-t132101-shisetsu", "小金井市 — public facilities", "小金井市 公共施設一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/koganei/01_koukyoushisetsu.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public facilities published by 小金井市 with per-record coordinates.");

VCSV(jpx_tokyo_t132110_shisetsu, "jpx-tokyo-t132110-shisetsu", "小平市 — public facilities", "小平市 公共施設一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/kodaira/132110_public_facility.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public facilities published by 小平市 with per-record coordinates.");

VCSV(jpx_tokyo_t132110_toilet, "jpx-tokyo-t132110-toilet", "小平市 — public toilets", "小平市 公衆トイレ一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/kodaira/132110_public_toilet.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public toilets published by 小平市 with per-record coordinates.");

VCSV(jpx_tokyo_t132136_shisetsu, "jpx-tokyo-t132136-shisetsu", "東村山市 — public facilities", "東村山市 東村山市公共施設一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/higashimurayama/20240619_public_facility.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public facilities published by 東村山市 with per-record coordinates.");

VCSV(jpx_tokyo_t132144_kosodate, "jpx-tokyo-t132144-kosodate", "国分寺市 — childcare facilities", "国分寺市 保育所一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/kokubunji/132144_kokubunjishi_nurseryschool.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of childcare facilities published by 国分寺市 with per-record coordinates.");

VCSV(jpx_tokyo_t132144_shisetsu, "jpx-tokyo-t132144-shisetsu", "国分寺市 — public facilities", "国分寺市 公共施設一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/kokubunji/132144_public_facility.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public facilities published by 国分寺市 with per-record coordinates.");

VCSV(jpx_tokyo_t132144_toilet, "jpx-tokyo-t132144-toilet", "国分寺市 — public toilets", "国分寺市 公衆トイレ一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/kokubunji/132144_public_toilet.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public toilets published by 国分寺市 with per-record coordinates.");

VCSV(jpx_tokyo_t132152_shisetsu, "jpx-tokyo-t132152-shisetsu", "国立市 — public facilities", "国立市 公共施設一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/kunitachi/132152_public_facility.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public facilities published by 国立市 with per-record coordinates.");

VCSV(jpx_tokyo_t132152_toilet, "jpx-tokyo-t132152-toilet", "国立市 — public toilets", "国立市 公衆トイレ一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/kunitachi/132152_public_toilet.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public toilets published by 国立市 with per-record coordinates.");

VCSV(jpx_tokyo_t132195_chusha, "jpx-tokyo-t132195-chusha", "狛江市 — car parks", "狛江市 公営駐車場一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/komae/132195_car_park.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of car parks published by 狛江市 with per-record coordinates.");

VCSV(jpx_tokyo_t132195_shisetsu, "jpx-tokyo-t132195-shisetsu", "狛江市 — public facilities", "狛江市 公共施設一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.jp/suisyoudataset/132195_public_facility.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public facilities published by 狛江市 with per-record coordinates.");

VCSV(jpx_tokyo_t132195_toilet, "jpx-tokyo-t132195-toilet", "狛江市 — public toilets", "狛江市 公衆トイレ一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/komae/132195_public_toilet.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public toilets published by 狛江市 with per-record coordinates.");

VCSV(jpx_tokyo_t132209_kosodate, "jpx-tokyo-t132209-kosodate", "東大和市 — childcare facilities", "東大和市 子育て施設一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/suisyoudataset/132209_preschool.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of childcare facilities published by 東大和市 with per-record coordinates.");

VCSV(jpx_tokyo_t132209_shisetsu, "jpx-tokyo-t132209-shisetsu", "東大和市 — public facilities", "東大和市 公共施設一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/higashiyamato/ods/132209_public_facility.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public facilities published by 東大和市 with per-record coordinates.");

VCSV(jpx_tokyo_t132209_toilet, "jpx-tokyo-t132209-toilet", "東大和市 — public toilets", "東大和市 公衆トイレ一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/higashiyamato/ods/132209_public_toilet.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public toilets published by 東大和市 with per-record coordinates.");

VCSV(jpx_tokyo_t132225_shisetsu, "jpx-tokyo-t132225-shisetsu", "東久留米市 — public facilities", "東久留米市 公共施設一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/higashikurume/132225_public_facility.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public facilities published by 東久留米市 with per-record coordinates.");

VCSV(jpx_tokyo_t132225_toilet, "jpx-tokyo-t132225-toilet", "東久留米市 — public toilets", "東久留米市 公衆トイレ一覧",
  "government", "local-gov",
  "https://www.opendata.metro.tokyo.lg.jp/higashikurume/132225_public_toilet.csv",
  "ja", "[\"japan\",\"tokyo\",\"opendata\",\"geodata\",\"local-gov\"]", 86400,
  "Point layer of public toilets published by 東久留米市 with per-record coordinates.");
