/* Verified-live aviation sources (31), part 2.
 * Every endpoint in this file returned 2xx and parsed to at
 * least one record at generation time; see
 * docs/verified-sources-manifest.tsv for the recorded proof.
 * Generated by collectors/gen_verified_sources.py — regenerate
 * rather than hand-editing. */
#include "_verified_macros.inc"

VGEO(sec_faa_stadium_tfr, "sec-faa-stadium-tfr", "FAA Stadium Flight Restrictions", "FAA スタジアム飛行制限",
  "aviation", "airspace",
  "https://services6.arcgis.com/ssFJjBXIUyZDrSYZ/arcgis/rest/services/Stadiums/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson&resultRecordCount=500",
  "en", "[\"tfr\",\"stadium\",\"restriction\"]", 86400,
  "FAA NASR aeronautical data published as ArcGIS features: FAA Stadium Flight Restrictions. Real published US aeronautical geometry, refreshed on the 28-day AIRAC cycle.");

VGEO(sec_faa_sua, "sec-faa-sua", "FAA Special Use Airspace", "FAA 特別用途空域",
  "aviation", "defence",
  "https://services6.arcgis.com/ssFJjBXIUyZDrSYZ/arcgis/rest/services/Special_Use_Airspace/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson&resultRecordCount=200",
  "en", "[\"sua\",\"restricted\",\"warning-area\",\"military\"]", 86400,
  "FAA NASR aeronautical data published as ArcGIS features: FAA Special Use Airspace. Real published US aeronautical geometry, refreshed on the 28-day AIRAC cycle.");

VGEO(sec_faa_taxiway, "sec-faa-taxiway", "FAA Taxiways", "FAA 誘導路",
  "aviation", "airspace",
  "https://services6.arcgis.com/ssFJjBXIUyZDrSYZ/arcgis/rest/services/AM_Taxiway/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson&resultRecordCount=200",
  "en", "[\"airport\",\"taxiway\",\"mapping\"]", 86400,
  "FAA NASR aeronautical data published as ArcGIS features: FAA Taxiways. Real published US aeronautical geometry, refreshed on the 28-day AIRAC cycle.");

VGEO(sec_faa_uas_facility_map, "sec-faa-uas-facility-map", "FAA UAS Facility Maps (LAANC ceilings)", "FAA 無人機施設マップ（LAANC上限高度）",
  "aviation", "airspace",
  "https://services6.arcgis.com/ssFJjBXIUyZDrSYZ/arcgis/rest/services/FAA_UAS_FacilityMap_Data/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson&resultRecordCount=500",
  "en", "[\"uas\",\"drone\",\"laanc\",\"ceiling\"]", 86400,
  "FAA NASR aeronautical data published as ArcGIS features: FAA UAS Facility Maps (LAANC ceilings). Real published US aeronautical geometry, refreshed on the 28-day AIRAC cycle.");

VGEO(sec_faa_us_airport, "sec-faa-us-airport", "FAA US Airports", "FAA 米国空港",
  "aviation", "airspace",
  "https://services6.arcgis.com/ssFJjBXIUyZDrSYZ/arcgis/rest/services/US_Airport/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson&resultRecordCount=500",
  "en", "[\"airport\",\"nasr\"]", 86400,
  "FAA NASR aeronautical data published as ArcGIS features: FAA US Airports. Real published US aeronautical geometry, refreshed on the 28-day AIRAC cycle.");

VGEO(sec_faa_wind_indicator, "sec-faa-wind-indicator", "FAA Wind Indicators", "FAA 風向指示器",
  "aviation", "airspace",
  "https://services6.arcgis.com/ssFJjBXIUyZDrSYZ/arcgis/rest/services/AM_Wind_Indicator/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson&resultRecordCount=500",
  "en", "[\"airport\",\"windsock\"]", 86400,
  "FAA NASR aeronautical data published as ArcGIS features: FAA Wind Indicators. Real published US aeronautical geometry, refreshed on the 28-day AIRAC cycle.");

VJSON(sec_fedreg_faa, "sec-fedreg-faa", "Federal Register — FAA", "官報 — 米連邦航空局",
  "aviation", "aviation-safety",
  "https://www.federalregister.gov/api/v1/documents.json?conditions%5Bagencies%5D%5B%5D=federal-aviation-administration&per_page=100&order=newest&fields%5B%5D=title&fields%5B%5D=html_url&fields%5B%5D=publication_date&fields%5B%5D=abstract&fields%5B%5D=document_number&fields%5B%5D=type",
  "results",
  "en", "[\"faa\",\"airworthiness\",\"ad\",\"regulation\",\"federal-register\",\"usa\"]", 3600,
  "US Federal Register rulemakings, notices and proposed rules issued by FAA; the authoritative first-publication channel for US regulatory action.");

VJSON(sec_fedreg_ntsb, "sec-fedreg-ntsb", "Federal Register — NTSB", "官報 — 米国家運輸安全委員会",
  "aviation", "aviation-safety",
  "https://www.federalregister.gov/api/v1/documents.json?conditions%5Bagencies%5D%5B%5D=national-transportation-safety-board&per_page=100&order=newest&fields%5B%5D=title&fields%5B%5D=html_url&fields%5B%5D=publication_date&fields%5B%5D=abstract&fields%5B%5D=document_number&fields%5B%5D=type",
  "results",
  "en", "[\"ntsb\",\"accident\",\"investigation\",\"federal-register\",\"usa\"]", 3600,
  "US Federal Register rulemakings, notices and proposed rules issued by NTSB; the authoritative first-publication channel for US regulatory action.");

VJSON(sec_fedreg_tsa, "sec-fedreg-tsa", "Federal Register — TSA", "官報 — 米運輸保安庁",
  "aviation", "aviation-safety",
  "https://www.federalregister.gov/api/v1/documents.json?conditions%5Bagencies%5D%5B%5D=transportation-security-administration&per_page=100&order=newest&fields%5B%5D=title&fields%5B%5D=html_url&fields%5B%5D=publication_date&fields%5B%5D=abstract&fields%5B%5D=document_number&fields%5B%5D=type",
  "results",
  "en", "[\"tsa\",\"aviation-security\",\"federal-register\",\"usa\"]", 3600,
  "US Federal Register rulemakings, notices and proposed rules issued by TSA; the authoritative first-publication channel for US regulatory action.");

VRSS(sec_flightglobal, "sec-flightglobal", "FlightGlobal", "FlightGlobal",
  "aviation", "aviation-safety",
  "https://www.flightglobal.com/rss",
  "en", "[\"aviation\",\"airline\",\"industry\"]", 3600,
  "Commercial and military aviation industry reporting.");

VRSS(sec_flightsafety_aerosafety, "sec-flightsafety-aerosafety", "Flight Safety Foundation", "飛行安全財団",
  "aviation", "aviation-safety",
  "https://flightsafety.org/feed/",
  "en", "[\"flight-safety\",\"aerosafety\",\"foundation\"]", 3600,
  "Flight Safety Foundation analysis, AeroSafety World articles and safety-initiative updates.");

VRSS(sec_govuk_aaib_reports, "sec-govuk-aaib-reports", "UK AAIB Air Accident Reports", "英国航空事故調査支部 事故報告書",
  "aviation", "aviation-safety",
  "https://www.gov.uk/aaib-reports.atom",
  "en", "[\"aaib\",\"accident\",\"investigation\",\"uk\"]", 86400,
  "Formal air accident and serious incident investigation reports published by the UK Air Accidents Investigation Branch.");

VRSS(sec_govuk_caa, "sec-govuk-caa", "UK Civil Aviation Authority", "英国民間航空局",
  "aviation", "aviation-safety",
  "https://www.gov.uk/government/organisations/civil-aviation-authority.atom",
  "en", "[\"caa\",\"regulation\",\"uk\"]", 3600,
  "Official UK government publications and news from the UK Civil Aviation Authority, as the department's own Atom feed.");

VRSS(sec_govuk_ukspace, "sec-govuk-ukspace", "UK Space Agency", "英国宇宙庁",
  "aviation", "space",
  "https://www.gov.uk/government/organisations/uk-space-agency.atom",
  "en", "[\"space\",\"uk\",\"launch\"]", 86400,
  "Official UK government publications and news from the UK Space Agency, as the department's own Atom feed.");

VRSS(sec_jaxa_press, "sec-jaxa-press", "JAXA Press Releases (English)", "JAXA プレスリリース（英語）",
  "aviation", "space",
  "https://global.jaxa.jp/rss/press.rdf",
  "en", "[\"jaxa\",\"japan\",\"space\"]", 86400,
  "Official JAXA press releases in English, covering launches, satellites and ISS operations.");

VRSS(sec_nasa_blogs_artemis, "sec-nasa-blogs-artemis", "NASA Artemis Programme Blog", "NASA アルテミス計画ブログ",
  "aviation", "space",
  "https://blogs.nasa.gov/artemis/feed/",
  "en", "[\"nasa\",\"artemis\",\"moon\"]", 86400,
  "Operational updates from the NASA Artemis lunar programme, often ahead of formal releases.");

VRSS(sec_nasa_news, "sec-nasa-news", "NASA News Releases", "NASA ニュースリリース",
  "aviation", "space",
  "https://www.nasa.gov/news-release/feed/",
  "en", "[\"nasa\",\"space\",\"usa\"]", 86400,
  "Official NASA news releases across human spaceflight, science and aeronautics.");

VGEO(sec_ntad_airport_parcels, "sec-ntad-airport-parcels", "NTAD Primary Airport Parcels", "NTAD 主要空港敷地",
  "aviation", "airspace",
  "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Hazard_Exposure_Primary_Airport_Parcels/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson&resultRecordCount=300",
  "en", "[\"airport\",\"parcel\",\"footprint\",\"usa\"]", 604800,
  "US DOT National Transportation Atlas layer (NTAD Primary Airport Parcels) with authoritative published geometry; useful as a persistent infrastructure base layer.");

VGEO(sec_ntad_aviation_facilities, "sec-ntad-aviation-facilities", "NTAD Aviation Facilities", "NTAD 航空施設",
  "aviation", "airspace",
  "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Aviation_Facilities/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson&resultRecordCount=500",
  "en", "[\"airport\",\"heliport\",\"ntad\",\"usa\"]", 604800,
  "US DOT National Transportation Atlas layer (NTAD Aviation Facilities) with authoritative published geometry; useful as a persistent infrastructure base layer.");

VGEO(sec_ntad_intermodal_air_truck, "sec-ntad-intermodal-air-truck", "NTAD Air-to-Truck Freight Facilities", "NTAD 航空・トラック貨物施設",
  "aviation", "shipping",
  "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Intermodal_Freight_Facilities_Air_to_Truck/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson&resultRecordCount=500",
  "en", "[\"intermodal\",\"air-cargo\",\"freight\",\"usa\"]", 604800,
  "US DOT National Transportation Atlas layer (NTAD Air-to-Truck Freight Facilities) with authoritative published geometry; useful as a persistent infrastructure base layer.");

VGEO(sec_ntad_spaceports, "sec-ntad-spaceports", "NTAD Spaceports", "NTAD 宇宙港",
  "aviation", "space",
  "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Spaceports/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson&resultRecordCount=500",
  "en", "[\"spaceport\",\"launch-site\",\"ntad\",\"usa\"]", 604800,
  "US DOT National Transportation Atlas layer (NTAD Spaceports) with authoritative published geometry; useful as a persistent infrastructure base layer.");

VRSS(sec_otkes_decisions, "sec-otkes-decisions", "OTKES Finland — Investigation Decisions", "フィンランドOTKES 調査決定",
  "aviation", "aviation-safety",
  "https://www.turvallisuustutkinta.fi/feed/rss-feed?post_type=tutkintapaatos",
  "fi", "[\"otkes\",\"finland\",\"decision\"]", 86400,
  "Finnish Safety Investigation Authority investigation decisions across aviation, marine and rail.");

VRSS(sec_otkes_investigations, "sec-otkes-investigations", "OTKES Finland — Open Investigations", "フィンランドOTKES 進行中の調査",
  "aviation", "aviation-safety",
  "https://www.turvallisuustutkinta.fi/feed/rss-feed?post_type=tutkinta",
  "fi", "[\"otkes\",\"finland\",\"investigation\"]", 86400,
  "Investigations currently open at the Finnish Safety Investigation Authority.");

VRSS(sec_otkes_news, "sec-otkes-news", "OTKES Finland — News", "フィンランドOTKES ニュース",
  "aviation", "aviation-safety",
  "https://www.turvallisuustutkinta.fi/feed/rss-feed?post_type=ajankohtaiset",
  "fi", "[\"otkes\",\"finland\",\"news\"]", 86400,
  "News and initial notifications from the Finnish Safety Investigation Authority.");

VRSS(sec_otkes_recommendations, "sec-otkes-recommendations", "OTKES Finland — Safety Recommendations", "フィンランドOTKES 安全勧告",
  "aviation", "aviation-safety",
  "https://www.turvallisuustutkinta.fi/feed/rss-feed?post_type=turvallisuussuositus",
  "fi", "[\"otkes\",\"finland\",\"recommendation\"]", 86400,
  "Safety recommendations issued by the Finnish Safety Investigation Authority.");

VRSS(sec_simpleflying, "sec-simpleflying", "Simple Flying", "Simple Flying",
  "aviation", "aviation-safety",
  "https://simpleflying.com/feed/",
  "en", "[\"aviation\",\"airline\",\"fleet\"]", 3600,
  "Airline fleet, route and operational reporting.");

VRSS(sec_skybrary, "sec-skybrary", "SKYbrary Aviation Safety", "SKYbrary 航空安全",
  "aviation", "aviation-safety",
  "https://skybrary.aero/rss.xml",
  "en", "[\"aviation-safety\",\"skybrary\",\"eurocontrol\"]", 3600,
  "EUROCONTROL-backed aviation safety knowledge base updates, including accident and incident case studies.");

VJSON(sec_spacedevs_launch_previous, "sec-spacedevs-launch-previous", "Launch Library — Recent Launches", "ローンチライブラリ — 直近の打上げ",
  "aviation", "space",
  "https://ll.thespacedevs.com/2.2.0/launch/previous/?limit=50",
  "results",
  "en", "[\"launch\",\"space\",\"orbital\",\"thespacedevs\"]", 21600,
  "Recently conducted orbital launches with outcome, vehicle and pad coordinates — ground truth against which launch notices are checked; the anonymous API tier is rate limited.");

VJSON(sec_spacedevs_launch_upcoming, "sec-spacedevs-launch-upcoming", "Launch Library — Upcoming Orbital Launches", "ローンチライブラリ — 今後の軌道打上げ",
  "aviation", "space",
  "https://ll.thespacedevs.com/2.2.0/launch/upcoming/?limit=50",
  "results",
  "en", "[\"launch\",\"space\",\"orbital\",\"thespacedevs\"]", 21600,
  "Every scheduled orbital launch worldwide with window, vehicle, payload and launch-pad coordinates; the anonymous API tier is rate limited, so poll no faster than the stated interval.");

VRSS(sec_spaceflightnow, "sec-spaceflightnow", "Spaceflight Now", "Spaceflight Now",
  "aviation", "space",
  "https://spaceflightnow.com/feed/",
  "en", "[\"space\",\"launch\",\"schedule\"]", 3600,
  "Launch schedule and mission coverage.");

VRSS(sec_spaceforce_news, "sec-spaceforce-news", "US Space Force News", "米宇宙軍 ニュース",
  "aviation", "space",
  "https://www.spaceforce.mil/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=1060&max=20",
  "en", "[\"space-force\",\"usa\",\"military\",\"space\"]", 3600,
  "Official US Space Force news covering space domain awareness and launch support.");
