/* Verified-live maritime sources (42), part 1.
 * Every endpoint in this file returned 2xx and parsed to at
 * least one record at generation time; see
 * docs/verified-sources-manifest.tsv for the recorded proof.
 * Generated by collectors/gen_verified_sources.py — regenerate
 * rather than hand-editing. */
#include "_verified_macros.inc"

VRSS(sec_amti_csis, "sec-amti-csis", "CSIS Asia Maritime Transparency Initiative", "CSIS アジア海洋透明性イニシアティブ",
  "maritime", "conflict",
  "https://amti.csis.org/feed/",
  "en", "[\"south-china-sea\",\"maritime\",\"china\",\"amti\"]", 86400,
  "Imagery-based reporting on South China Sea features, militarisation and maritime law-enforcement activity.");

VJSON(sec_cablemap_cable_index, "sec-cablemap-cable-index", "Submarine Cable Map — Cable Index", "海底ケーブルマップ — ケーブル一覧",
  "maritime", "shipping",
  "https://www.submarinecablemap.com/api/v3/cable/all.json",
  "",
  "en", "[\"cable\",\"subsea\",\"telecom\",\"index\"]", 604800,
  "Metadata index of submarine cables (name, ready-for-service year, owners, landing points) without geometry.");

VRSS(sec_canada_coastguard, "sec-canada-coastguard", "Canadian Coast Guard News", "カナダ沿岸警備隊 ニュース",
  "maritime", "navwarning",
  "https://api.io.canada.ca/io-server/gc/news/en/v2?dept=canadiancoastguard&sort=publishedDate&orderBy=desc&pick=50&format=atom&atomtitle=Canada",
  "en", "[\"canada\",\"coastguard\",\"sar\"]", 3600,
  "News releases from the Canadian Coast Guard, including SAR and icebreaking operations.");

VRSS(sec_dryad_global, "sec-dryad-global", "Dryad Global Channel 16", "Dryad Global Channel 16（海上保安）",
  "maritime", "piracy",
  "https://channel16.dryadglobal.com/rss.xml",
  "en", "[\"piracy\",\"maritime-security\",\"risk\"]", 3600,
  "Commercial maritime-security reporting on piracy, armed robbery, drone and missile attacks on shipping.");

VJSON(sec_fedreg_engineers_corps, "sec-fedreg-engineers-corps", "Federal Register — US Army Corps of Engineers", "官報 — 米陸軍工兵隊",
  "maritime", "shipping",
  "https://www.federalregister.gov/api/v1/documents.json?conditions%5Bagencies%5D%5B%5D=engineers-corps&per_page=100&order=newest",
  "results",
  "en", "[\"usace\",\"navigation\",\"waterway\",\"federal-register\",\"usa\"]", 3600,
  "US Federal Register rulemakings, notices and proposed rules issued by US Army Corps of Engineers; the authoritative first-publication channel for US regulatory action.");

VJSON(sec_fedreg_marad, "sec-fedreg-marad", "Federal Register — Maritime Administration", "官報 — 米海事局",
  "maritime", "shipping",
  "https://www.federalregister.gov/api/v1/documents.json?conditions%5Bagencies%5D%5B%5D=maritime-administration&per_page=100&order=newest&fields%5B%5D=title&fields%5B%5D=html_url&fields%5B%5D=publication_date&fields%5B%5D=abstract&fields%5B%5D=document_number&fields%5B%5D=type",
  "results",
  "en", "[\"marad\",\"shipping\",\"jones-act\",\"federal-register\",\"usa\"]", 3600,
  "US Federal Register rulemakings, notices and proposed rules issued by Maritime Administration; the authoritative first-publication channel for US regulatory action.");

VJSON(sec_fedreg_uscg, "sec-fedreg-uscg", "Federal Register — US Coast Guard", "官報 — 米沿岸警備隊",
  "maritime", "navwarning",
  "https://www.federalregister.gov/api/v1/documents.json?conditions%5Bagencies%5D%5B%5D=coast-guard&per_page=100&order=newest&fields%5B%5D=title&fields%5B%5D=html_url&fields%5B%5D=publication_date&fields%5B%5D=abstract&fields%5B%5D=document_number&fields%5B%5D=type",
  "results",
  "en", "[\"uscg\",\"safety-zone\",\"security-zone\",\"federal-register\",\"usa\"]", 3600,
  "US Federal Register rulemakings, notices and proposed rules issued by US Coast Guard; the authoritative first-publication channel for US regulatory action.");

VRSS(sec_govuk_maib_reports, "sec-govuk-maib-reports", "UK MAIB Marine Accident Reports", "英国海難調査支部 事故報告書",
  "maritime", "aviation-safety",
  "https://www.gov.uk/maib-reports.atom",
  "en", "[\"maib\",\"marine-casualty\",\"investigation\",\"uk\"]", 86400,
  "Marine casualty investigation reports published by the UK Marine Accident Investigation Branch.");

VRSS(sec_govuk_mca, "sec-govuk-mca", "UK Maritime and Coastguard Agency", "英国海事沿岸警備庁",
  "maritime", "navwarning",
  "https://www.gov.uk/government/organisations/maritime-and-coastguard-agency.atom",
  "en", "[\"mca\",\"coastguard\",\"uk\"]", 3600,
  "Official UK government publications and news from the Maritime and Coastguard Agency, as the department's own Atom feed.");

VRSS(sec_govuk_submarine_delivery, "sec-govuk-submarine-delivery", "UK Submarine Delivery Agency", "英国潜水艦調達庁",
  "maritime", "defence",
  "https://www.gov.uk/government/organisations/submarine-delivery-agency.atom",
  "en", "[\"submarine\",\"procurement\",\"uk\"]", 86400,
  "Official UK government publications and news from the Submarine Delivery Agency, as the department's own Atom feed.");

VRSS(sec_govuk_ukho, "sec-govuk-ukho", "UK Hydrographic Office", "英国水路部",
  "maritime", "navwarning",
  "https://www.gov.uk/government/organisations/uk-hydrographic-office.atom",
  "en", "[\"ukho\",\"admiralty\",\"chart\",\"uk\"]", 86400,
  "Official UK government publications and news from the UK Hydrographic Office, as the department's own Atom feed.");

VRSS(sec_navaltoday, "sec-navaltoday", "Naval Today", "Naval Today",
  "maritime", "defence",
  "https://www.navaltoday.com/feed/",
  "en", "[\"navy\",\"naval\",\"shipbuilding\"]", 3600,
  "Daily naval industry and operations reporting.");

VRSS(sec_navy_news, "sec-navy-news", "US Navy News", "米海軍 ニュース",
  "maritime", "defence",
  "https://www.navy.mil/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=1067&max=20",
  "en", "[\"navy\",\"usa\",\"military\",\"fleet\"]", 3600,
  "Official US Navy news feed, including deployments and fleet movements.");

VJSON(sec_nga_dgps, "sec-nga-dgps", "NGA Differential GPS Stations (Pub 112 series)", "NGA ディファレンシャルGPS局",
  "maritime", "navwarning",
  "https://msi.nga.mil/api/publications/ngalol/dgpsstations?output=json&includeRemovals=false",
  "ngalol",
  "en", "[\"dgps\",\"radionavigation\",\"pub112\",\"nga\"]", 604800,
  "Worldwide differential GPS station list with real per-station positions published in degrees/minutes/seconds.");

VJSON(sec_nga_dnc, "sec-nga-dnc", "NGA Digital Nautical Chart Catalogue", "NGA デジタル航海用海図カタログ",
  "maritime", "navwarning",
  "https://msi.nga.mil/api/publications/products/dnc?output=json",
  "prodcat",
  "en", "[\"dnc\",\"chart\",\"catalogue\",\"nga\"]", 604800,
  "Catalogue of NGA Digital Nautical Chart libraries and their currency.");

VJSON(sec_nga_modu_areas, "sec-nga-modu-areas", "NGA Mobile Offshore Drilling Unit Areas", "NGA 移動式海洋掘削装置区域",
  "maritime", "shipping",
  "https://msi.nga.mil/api/publications/modu/areas?output=json",
  "subregions",
  "en", "[\"modu\",\"offshore\",\"drilling\",\"nga\"]", 604800,
  "Index of the sea areas used by NGA to report mobile offshore drilling unit positions.");

VJSON(sec_nga_navwarn_current, "sec-nga-navwarn-current", "NGA Current Broadcast Navigational Warnings", "NGA 現行航行警報",
  "maritime", "navwarning",
  "https://msi.nga.mil/api/publications/broadcast-warn/current-warnings?output=json",
  "",
  "en", "[\"navwarn\",\"navarea\",\"hydropac\",\"hydrolant\",\"nga\"]", 3600,
  "The in-force NAVAREA/HYDROLANT/HYDROPAC broadcast warning texts issued by NGA; positions are embedded in the warning text, not as structured geometry.");

VJSON(sec_nga_navwarn_subregions, "sec-nga-navwarn-subregions", "NGA Navigational Warning Subregions", "NGA 航行警報サブリージョン",
  "maritime", "navwarning",
  "https://msi.nga.mil/api/publications/broadcast-warn/subregions?output=json",
  "",
  "en", "[\"navwarn\",\"subregion\",\"index\",\"nga\"]", 604800,
  "Index of NGA broadcast-warning subregions used to scope NAVAREA warning queries.");

VJSON(sec_nga_nganos, "sec-nga-nganos", "NGA Nautical and Aeronautical Product Catalogue", "NGA 海図・航空図製品カタログ",
  "maritime", "navwarning",
  "https://msi.nga.mil/api/publications/products/nganos?output=json",
  "prodcat",
  "en", "[\"chart\",\"catalogue\",\"product\",\"nga\"]", 604800,
  "Full NGA nautical/aeronautical standard product catalogue with edition and currency data.");

VJSON(sec_nga_ntm_graphics, "sec-nga-ntm-graphics", "NGA Notice to Mariners Graphics Index", "NGA 水路通報図版索引",
  "maritime", "navwarning",
  "https://msi.nga.mil/api/publications/ntm/ntm-graphics?output=json",
  "ntmgraphics",
  "en", "[\"ntm\",\"chartlet\",\"graphic\",\"nga\"]", 86400,
  "Index of chartlets and graphics issued with NGA Notices to Mariners, keyed by chart and notice number.");

VJSON(sec_nga_ntm_navpub_corr, "sec-nga-ntm-navpub-corr", "NGA Notice to Mariners Publication Corrections", "NGA 水路書誌訂正",
  "maritime", "navwarning",
  "https://msi.nga.mil/api/publications/ntm/ntm-nav-pub-corr?output=json",
  "navpubcorr",
  "en", "[\"ntm\",\"publication\",\"correction\",\"nga\"]", 86400,
  "Corrections to NGA navigational publications issued through the weekly Notice to Mariners.");

VJSON(sec_nga_radiobeacons, "sec-nga-radiobeacons", "NGA Radiobeacons (Pub 110-117)", "NGA 無線標識局",
  "maritime", "navwarning",
  "https://msi.nga.mil/api/publications/ngalol/radiobeacons?output=json&includeRemovals=false",
  "ngalol",
  "en", "[\"radiobeacon\",\"radionavigation\",\"aton\",\"nga\"]", 604800,
  "Worldwide marine and aeromarine radiobeacon list with real per-station positions published in degrees/minutes/seconds.");

VJSON(sec_nga_radionav_warn, "sec-nga-radionav-warn", "NGA Radio Navigational Warning Stations", "NGA 無線航行警報放送局",
  "maritime", "navwarning",
  "https://msi.nga.mil/api/publications/radio-navaids/warn?output=json",
  "radio-navaids",
  "en", "[\"radio\",\"navwarn\",\"broadcast\",\"nga\"]", 604800,
  "Stations that broadcast radio navigational warnings, with frequencies, times and the sea areas they serve.");

VJSON(sec_nga_tod, "sec-nga-tod", "NGA Tactical Oceanographic Data Catalogue", "NGA 戦術海洋データカタログ",
  "maritime", "navwarning",
  "https://msi.nga.mil/api/publications/products/tod?output=json",
  "prodcat",
  "en", "[\"tod\",\"oceanographic\",\"catalogue\",\"nga\"]", 604800,
  "Catalogue of NGA tactical oceanographic data products and their coverage levels.");

VGEO(sec_noaa_enc_coverage, "sec-noaa-enc-coverage", "NOAA ENC Coverage Cells", "NOAA ENCカバレッジセル",
  "maritime", "navwarning",
  "https://gis.charttools.noaa.gov/arcgis/rest/services/encdirect/enc_coverage/MapServer/0/query?where=1%3D1&outFields=*&resultRecordCount=300&geometryPrecision=5&outSR=4326&f=geojson",
  "en", "[\"enc\",\"chart\",\"coverage\"]", 604800,
  "Coverage footprints of NOAA electronic navigational chart cells; real cell polygons useful for chart-availability questions.");

VGEO(sec_noaa_maritime_limits, "sec-noaa-maritime-limits", "NOAA US Maritime Limits and Boundaries", "NOAA 米国海洋限界・境界",
  "maritime", "navwarning",
  "https://gis.charttools.noaa.gov/arcgis/rest/services/MaritimeBoundaries/US_Maritime_Limits_Boundaries/MapServer/0/query?where=1%3D1&outFields=*&resultRecordCount=200&geometryPrecision=5&outSR=4326&f=geojson",
  "en", "[\"maritime-boundary\",\"eez\",\"territorial-sea\"]", 604800,
  "Official US territorial sea, contiguous zone and EEZ limit lines as published by NOAA; coarse-but-real zone geometry, not point events.");

VGEO(sec_noaa_nav_managers, "sec-noaa-nav-managers", "NOAA Navigation Manager Areas", "NOAA 航行管理官担当区域",
  "maritime", "navwarning",
  "https://gis.charttools.noaa.gov/arcgis/rest/services/Navigation_Services/NOAA_Navigation_Managers/MapServer/0/query?where=1%3D1&outFields=*&resultRecordCount=100&geometryPrecision=5&outSR=4326&f=geojson",
  "en", "[\"noaa\",\"navigation\",\"contact\"]", 604800,
  "NOAA regional navigation manager points of contact with their real published office locations.");

VGEO(sec_noaa_ntm_aoi, "sec-noaa-ntm-aoi", "NOAA Notice to Mariners Chart Update Areas", "NOAA 水路通報 海図更新区域",
  "maritime", "navwarning",
  "https://gis.charttools.noaa.gov/arcgis/rest/services/MarineChart_Services/NNU_AOI_PRODUCTION/FeatureServer/0/query?where=1%3D1&outFields=*&resultRecordCount=500&geometryPrecision=5&outSR=4326&f=geojson",
  "en", "[\"ntm\",\"chart\",\"update\",\"noaa\"]", 86400,
  "Areas of NOAA electronic navigational charts changed by recent Notices to Mariners, with real chart-update geometry.");

VGEO(sec_noaa_ntm_beta_crit, "sec-noaa-ntm-beta-crit", "NOAA Critical Chart Corrections", "NOAA 重要海図訂正",
  "maritime", "navwarning",
  "https://gis.charttools.noaa.gov/arcgis/rest/services/MarineChart_Services/beta_notice_to_mariner_critical_updates/FeatureServer/0/query?where=1%3D1&outFields=*&resultRecordCount=500&geometryPrecision=5&outSR=4326&f=geojson",
  "en", "[\"ntm\",\"critical\",\"correction\",\"aton\"]", 86400,
  "Critical Notice to Mariners corrections (aids to navigation added, moved or removed) as points with real published latitude/longitude.");

VGEO(sec_ntad_ferry_routes, "sec-ntad-ferry-routes", "NTAD Ferry Routes", "NTAD フェリー航路",
  "maritime", "shipping",
  "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Ferry_Routes/FeatureServer/0/query?where=1%3D1&outFields=OBJECTID&resultRecordCount=100&geometryPrecision=5&outSR=4326&f=geojson",
  "en", "[\"ferry\",\"route\",\"ntad\",\"usa\"]", 604800,
  "US DOT National Transportation Atlas layer (NTAD Ferry Routes) with authoritative published geometry; useful as a persistent infrastructure base layer.");

VGEO(sec_ntad_ferry_terminals, "sec-ntad-ferry-terminals", "NTAD Ferry Terminals", "NTAD フェリーターミナル",
  "maritime", "shipping",
  "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Ferry_Terminals/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson&resultRecordCount=500",
  "en", "[\"ferry\",\"terminal\",\"ntad\",\"usa\"]", 604800,
  "US DOT National Transportation Atlas layer (NTAD Ferry Terminals) with authoritative published geometry; useful as a persistent infrastructure base layer.");

VGEO(sec_ntad_intermodal_liquid_bulk, "sec-ntad-intermodal-liquid-bulk", "NTAD Liquid Bulk Terminals", "NTAD 液体バルクターミナル",
  "maritime", "shipping",
  "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Intermodal_Freight_Facilities_Liquid_Bulk/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson&resultRecordCount=500",
  "en", "[\"intermodal\",\"liquid-bulk\",\"terminal\",\"usa\"]", 604800,
  "US DOT National Transportation Atlas layer (NTAD Liquid Bulk Terminals) with authoritative published geometry; useful as a persistent infrastructure base layer.");

VGEO(sec_ntad_intermodal_pipeline_terminals, "sec-ntad-intermodal-pipeline-terminals", "NTAD Pipeline Terminals", "NTAD パイプラインターミナル",
  "maritime", "shipping",
  "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Intermodal_Freight_Facilities_Pipeline_Terminals/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson&resultRecordCount=500",
  "en", "[\"intermodal\",\"pipeline\",\"terminal\",\"usa\"]", 604800,
  "US DOT National Transportation Atlas layer (NTAD Pipeline Terminals) with authoritative published geometry; useful as a persistent infrastructure base layer.");

VGEO(sec_ntad_intermodal_roro, "sec-ntad-intermodal-roro", "NTAD Ro-Ro Terminals", "NTAD ローロー船ターミナル",
  "maritime", "shipping",
  "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Intermodal_Freight_Facilities_Marine_Roll_on_Roll_off/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson&resultRecordCount=500",
  "en", "[\"intermodal\",\"roro\",\"terminal\",\"usa\"]", 604800,
  "US DOT National Transportation Atlas layer (NTAD Ro-Ro Terminals) with authoritative published geometry; useful as a persistent infrastructure base layer.");

VGEO(sec_ntad_marad_gateways, "sec-ntad-marad-gateways", "NTAD MARAD Gateway Offices", "NTAD MARADゲートウェイ事務所",
  "maritime", "shipping",
  "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_DOT_MARAD_Gateway_Offices/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson&resultRecordCount=500",
  "en", "[\"marad\",\"gateway\",\"ntad\",\"usa\"]", 604800,
  "US DOT National Transportation Atlas layer (NTAD MARAD Gateway Offices) with authoritative published geometry; useful as a persistent infrastructure base layer.");

VGEO(sec_ntad_marine_highways, "sec-ntad-marine-highways", "NTAD Marine Highways", "NTAD 海上ハイウェイ",
  "maritime", "shipping",
  "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Marine_Highways/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson&resultRecordCount=300",
  "en", "[\"marine-highway\",\"corridor\",\"ntad\",\"usa\"]", 604800,
  "US DOT National Transportation Atlas layer (NTAD Marine Highways) with authoritative published geometry; useful as a persistent infrastructure base layer.");

VGEO(sec_ntad_principal_ports, "sec-ntad-principal-ports", "NTAD Principal Ports", "NTAD 主要港湾",
  "maritime", "shipping",
  "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Hazard_Exposure_Principal_Ports/FeatureServer/0/query?where=1%3D1&outFields=OBJECTID&resultRecordCount=100&geometryPrecision=5&outSR=4326&f=geojson",
  "en", "[\"port\",\"ntad\",\"usa\"]", 604800,
  "US DOT National Transportation Atlas layer (NTAD Principal Ports) with authoritative published geometry; useful as a persistent infrastructure base layer.");

VGEO(sec_ntad_strategic_seaports, "sec-ntad-strategic-seaports", "NTAD Commercial Strategic Seaports", "NTAD 戦略商業港湾",
  "maritime", "shipping",
  "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Commercial_Strategic_Seaports/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson&resultRecordCount=500",
  "en", "[\"port\",\"strategic\",\"seaport\",\"ntad\",\"usa\"]", 604800,
  "US DOT National Transportation Atlas layer (NTAD Commercial Strategic Seaports) with authoritative published geometry; useful as a persistent infrastructure base layer.");

VRSS(sec_offshore_energy, "sec-offshore-energy", "Offshore Energy", "Offshore Energy（海洋エネルギー）",
  "maritime", "shipping",
  "https://www.offshore-energy.biz/feed/",
  "en", "[\"offshore\",\"energy\",\"subsea\"]", 3600,
  "Offshore energy, subsea infrastructure and vessel activity reporting.");

VRSS(sec_parismou_news, "sec-parismou-news", "Paris MoU Port State Control News", "パリMOU ポートステートコントロール ニュース",
  "maritime", "shipping",
  "https://www.parismou.org/rss.xml",
  "en", "[\"port-state-control\",\"detention\",\"paris-mou\"]", 86400,
  "Paris Memorandum of Understanding announcements on port state control regimes, banned ships and detention performance.");

VRSS(sec_seatrade_maritime, "sec-seatrade-maritime", "Seatrade Maritime News", "Seatrade Maritime News",
  "maritime", "shipping",
  "https://www.seatrade-maritime.com/rss.xml",
  "en", "[\"shipping\",\"ports\",\"maritime\"]", 3600,
  "Shipping and port sector news.");

VRSS(sec_usni_news, "sec-usni-news", "USNI News", "USNI ニュース（米海軍協会）",
  "maritime", "defence",
  "https://news.usni.org/feed",
  "en", "[\"navy\",\"fleet-tracker\",\"usni\"]", 3600,
  "US Naval Institute News, including the weekly fleet and Marine tracker of where major US warships are deployed.");
