/* Verified-live health sources (60), part 1.
 * Every endpoint in this file returned 2xx and parsed to at
 * least one record at generation time; see
 * docs/verified-sources-manifest.tsv for the recorded proof.
 * Generated by collectors/gen_verified_sources.py — regenerate
 * rather than hand-editing. */
#include "_verified_macros.inc"

VJSON(sci_biorxiv_covid19, "sci-biorxiv-covid19", "bioRxiv/medRxiv COVID-19 collection", "bioRxiv/medRxiv 新型コロナ関連コレクション",
  "health", "preprint",
  "https://connect.biorxiv.org/relate/collection_json.php?grp=181",
  "rels",
  "en", "[\"preprint\",\"covid19\",\"outbreak\"]", 7200,
  "Curated COVID-19 preprint stream across bioRxiv and medRxiv.");

VRSS(sci_cdc_mmwr, "sci-cdc-mmwr", "CDC Morbidity and Mortality Weekly Report", "CDC 疾病・死亡週報（MMWR）",
  "health", "clinical",
  "https://tools.cdc.gov/api/v2/resources/media/132036.rss",
  "en", "[\"cdc\",\"mmwr\",\"epidemiology\"]", 21600,
  "MMWR articles — the US reference channel for outbreak and surveillance findings.");

VJSON(sci_clinvar_recent, "sci-clinvar-recent", "ClinVar recent variant submissions", "ClinVar 最新バリアント登録",
  "health", "genomics",
  "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=clinvar&retmode=json&retmax=100&term=all%5Bfilter%5D&sort=most+recent",
  "esearchresult.idlist",
  "en", "[\"clinvar\",\"variant\",\"ncbi\"]", 21600,
  "Newly submitted clinical variant interpretations.");

VJSON(sci_crossref_clinical_trial_linked, "sci-crossref-clinical-trial-linked", "Crossref clinical-trial-linked papers", "Crossref 臨床試験番号付き論文",
  "health", "clinical",
  "https://api.crossref.org/works?filter=has-clinical-trial-number:true&sort=created&order=desc&rows=100",
  "message.items",
  "en", "[\"clinical-trial\",\"crossref\"]", 21600,
  "Papers that declare a clinical trial registration number — links literature to registries.");

VJSON(sci_ctgov_antibiotic, "sci-ctgov-antibiotic", "ClinicalTrials.gov — antibiotic", "臨床試験登録（ClinicalTrials.gov）— 抗菌薬",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&query.term=antibiotic&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"antibiotic\"]", 21600,
  "ClinicalTrials.gov registry slice: antibiotic.");

VJSON(sci_ctgov_cell_therapy, "sci-ctgov-cell-therapy", "ClinicalTrials.gov — cell therapy", "臨床試験登録（ClinicalTrials.gov）— 細胞治療",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&query.term=cell%20therapy&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"cell-therapy\"]", 21600,
  "ClinicalTrials.gov registry slice: cell therapy.");

VJSON(sci_ctgov_china, "sci-ctgov-china", "ClinicalTrials.gov — china", "臨床試験登録（ClinicalTrials.gov）— 中国",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&query.locn=China&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"china\"]", 21600,
  "ClinicalTrials.gov registry slice: china.");

VJSON(sci_ctgov_crispr, "sci-ctgov-crispr", "ClinicalTrials.gov — crispr", "臨床試験登録（ClinicalTrials.gov）— CRISPR",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&query.term=CRISPR&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"crispr\"]", 21600,
  "ClinicalTrials.gov registry slice: crispr.");

VJSON(sci_ctgov_eu, "sci-ctgov-eu", "ClinicalTrials.gov — eu", "臨床試験登録（ClinicalTrials.gov）— ドイツ",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&query.locn=Germany&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"eu\"]", 21600,
  "ClinicalTrials.gov registry slice: eu.");

VJSON(sci_ctgov_gene_therapy, "sci-ctgov-gene-therapy", "ClinicalTrials.gov — gene therapy", "臨床試験登録（ClinicalTrials.gov）— 遺伝子治療",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&query.term=gene%20therapy&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"gene-therapy\"]", 21600,
  "ClinicalTrials.gov registry slice: gene therapy.");

VJSON(sci_ctgov_india, "sci-ctgov-india", "ClinicalTrials.gov — india", "臨床試験登録（ClinicalTrials.gov）— インド",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&query.locn=India&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"india\"]", 21600,
  "ClinicalTrials.gov registry slice: india.");

VJSON(sci_ctgov_industry_sponsored, "sci-ctgov-industry-sponsored", "ClinicalTrials.gov — industry sponsored", "臨床試験登録（ClinicalTrials.gov）— 企業治験",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&filter.advanced=AREA%5BLeadSponsorClass%5DINDUSTRY&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"industry-sponsored\"]", 21600,
  "ClinicalTrials.gov registry slice: industry sponsored.");

VJSON(sci_ctgov_infectious_disease, "sci-ctgov-infectious-disease", "ClinicalTrials.gov — infectious disease", "臨床試験登録（ClinicalTrials.gov）— 感染症",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&query.cond=infectious%20disease&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"infectious-disease\"]", 21600,
  "ClinicalTrials.gov registry slice: infectious disease.");

VJSON(sci_ctgov_japan, "sci-ctgov-japan", "ClinicalTrials.gov — japan", "臨床試験登録（ClinicalTrials.gov）— 日本",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&query.locn=Japan&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"japan\"]", 21600,
  "ClinicalTrials.gov registry slice: japan.");

VJSON(sci_ctgov_korea, "sci-ctgov-korea", "ClinicalTrials.gov — korea", "臨床試験登録（ClinicalTrials.gov）— 韓国",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&query.locn=Korea&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"korea\"]", 21600,
  "ClinicalTrials.gov registry slice: korea.");

VJSON(sci_ctgov_latest, "sci-ctgov-latest", "ClinicalTrials.gov — latest", "臨床試験登録（ClinicalTrials.gov）— 最新更新",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"latest\"]", 21600,
  "ClinicalTrials.gov registry slice: latest.");

VJSON(sci_ctgov_mrna, "sci-ctgov-mrna", "ClinicalTrials.gov — mrna", "臨床試験登録（ClinicalTrials.gov）— mRNA",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&query.term=mRNA&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"mrna\"]", 21600,
  "ClinicalTrials.gov registry slice: mrna.");

VJSON(sci_ctgov_newly_posted, "sci-ctgov-newly-posted", "ClinicalTrials.gov — newly posted", "臨床試験登録（ClinicalTrials.gov）— 新規登録",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&sort=StudyFirstPostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"newly-posted\"]", 21600,
  "ClinicalTrials.gov registry slice: newly posted.");

VJSON(sci_ctgov_oncology, "sci-ctgov-oncology", "ClinicalTrials.gov — oncology", "臨床試験登録（ClinicalTrials.gov）— がん",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&query.cond=cancer&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"oncology\"]", 21600,
  "ClinicalTrials.gov registry slice: oncology.");

VJSON(sci_ctgov_phase1, "sci-ctgov-phase1", "ClinicalTrials.gov — phase1", "臨床試験登録（ClinicalTrials.gov）— 第I相",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&query.term=AREA%5BPhase%5DPHASE1&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"phase1\"]", 21600,
  "ClinicalTrials.gov registry slice: phase1.");

VJSON(sci_ctgov_phase3, "sci-ctgov-phase3", "ClinicalTrials.gov — phase3", "臨床試験登録（ClinicalTrials.gov）— 第III相",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&query.term=AREA%5BPhase%5DPHASE3&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"phase3\"]", 21600,
  "ClinicalTrials.gov registry slice: phase3.");

VJSON(sci_ctgov_rare_disease, "sci-ctgov-rare-disease", "ClinicalTrials.gov — rare disease", "臨床試験登録（ClinicalTrials.gov）— 希少疾患",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&query.cond=rare%20disease&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"rare-disease\"]", 21600,
  "ClinicalTrials.gov registry slice: rare disease.");

VJSON(sci_ctgov_recruiting, "sci-ctgov-recruiting", "ClinicalTrials.gov — recruiting", "臨床試験登録（ClinicalTrials.gov）— 被験者募集中",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&filter.overallStatus=RECRUITING&sort=StudyFirstPostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"recruiting\"]", 21600,
  "ClinicalTrials.gov registry slice: recruiting.");

VJSON(sci_ctgov_russia, "sci-ctgov-russia", "ClinicalTrials.gov — russia", "臨床試験登録（ClinicalTrials.gov）— ロシア",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=50&query.locn=Russian%20Federation&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"russia\"]", 21600,
  "ClinicalTrials.gov registry slice: russia.");

VJSON(sci_ctgov_stats_field_values, "sci-ctgov-stats-field-values", "ClinicalTrials.gov field value statistics", "ClinicalTrials.gov フィールド値統計",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/stats/field/values",
  "",
  "en", "[\"clinicaltrials\",\"statistics\"]", 86400,
  "Value distributions per registry field, useful for detecting registry-wide shifts.");

VJSON(sci_ctgov_stats_size, "sci-ctgov-stats-size", "ClinicalTrials.gov study size statistics", "ClinicalTrials.gov 研究規模統計",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/stats/size",
  "ranges",
  "en", "[\"clinicaltrials\",\"statistics\"]", 86400,
  "Distribution statistics over the registry's study records.");

VJSON(sci_ctgov_suspended, "sci-ctgov-suspended", "ClinicalTrials.gov — suspended", "臨床試験登録（ClinicalTrials.gov）— 一時停止",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&filter.overallStatus=SUSPENDED&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"suspended\"]", 7200,
  "Trials suspended — early warning of safety holds and programme failures.");

VJSON(sci_ctgov_terminated, "sci-ctgov-terminated", "ClinicalTrials.gov — terminated", "臨床試験登録（ClinicalTrials.gov）— 中止",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&filter.overallStatus=TERMINATED&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"terminated\"]", 7200,
  "Trials terminated — early warning of safety holds and programme failures.");

VJSON(sci_ctgov_vaccines, "sci-ctgov-vaccines", "ClinicalTrials.gov — vaccines", "臨床試験登録（ClinicalTrials.gov）— ワクチン",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&query.cond=vaccine&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"vaccines\"]", 21600,
  "ClinicalTrials.gov registry slice: vaccines.");

VJSON(sci_ctgov_withdrawn, "sci-ctgov-withdrawn", "ClinicalTrials.gov — withdrawn", "臨床試験登録（ClinicalTrials.gov）— 取下げ",
  "health", "clinical",
  "https://clinicaltrials.gov/api/v2/studies?pageSize=100&filter.overallStatus=WITHDRAWN&sort=LastUpdatePostDate:desc",
  "studies",
  "en", "[\"clinicaltrials\",\"registry\",\"withdrawn\"]", 7200,
  "Trials withdrawn — early warning of safety holds and programme failures.");

VJSON(sci_doaj_articles_virology, "sci-doaj-articles-virology", "DOAJ virology articles", "DOAJ ウイルス学論文",
  "health", "literature",
  "https://doaj.org/api/search/articles/virology?pageSize=100",
  "results",
  "en", "[\"doaj\",\"virology\",\"open-access\"]", 21600,
  "Open-access virology literature.");

VRSS(sci_ecdc_threat_reports, "sci-ecdc-threat-reports", "ECDC communicable disease threat reports", "ECDC 感染症脅威報告",
  "health", "clinical",
  "https://www.ecdc.europa.eu/en/taxonomy/term/1808/feed",
  "en", "[\"ecdc\",\"outbreak\",\"europe\"]", 21600,
  "ECDC weekly communicable disease threat assessments for Europe.");

VJSON(sci_europepmc_antimicrobial_resistance, "sci-europepmc-antimicrobial-resistance", "Europe PMC — antimicrobial resistance", "Europe PMC — 薬剤耐性",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=%22antimicrobial%20resistance%22&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"antimicrobial-resistance\"]", 7200,
  "Europe PMC search stream for antimicrobial resistance, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_avian_influenza, "sci-europepmc-avian-influenza", "Europe PMC — avian influenza", "Europe PMC — 鳥インフルエンザ",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=%22avian%20influenza%22&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"avian-influenza\"]", 7200,
  "Europe PMC search stream for avian influenza, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_biosafety, "sci-europepmc-biosafety", "Europe PMC — biosafety", "Europe PMC — バイオセーフティ",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=biosafety&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"biosafety\"]", 7200,
  "Europe PMC search stream for biosafety, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_crispr, "sci-europepmc-crispr", "Europe PMC — crispr", "Europe PMC — ゲノム編集（CRISPR）",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=CRISPR&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"crispr\"]", 7200,
  "Europe PMC search stream for crispr, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_dengue, "sci-europepmc-dengue", "Europe PMC — dengue", "Europe PMC — デング熱",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=dengue&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"dengue\"]", 7200,
  "Europe PMC search stream for dengue, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_dual_use_research, "sci-europepmc-dual-use-research", "Europe PMC — dual use research", "Europe PMC — デュアルユース研究",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=%22dual%20use%20research%22&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"dual-use-research\"]", 7200,
  "Europe PMC search stream for dual use research, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_ebola, "sci-europepmc-ebola", "Europe PMC — ebola", "Europe PMC — エボラ",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=ebola&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"ebola\"]", 7200,
  "Europe PMC search stream for ebola, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_gain_of_function, "sci-europepmc-gain-of-function", "Europe PMC — gain of function", "Europe PMC — 機能獲得研究",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=%22gain%20of%20function%22&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"gain-of-function\"]", 7200,
  "Europe PMC search stream for gain of function, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_gene_drive, "sci-europepmc-gene-drive", "Europe PMC — gene drive", "Europe PMC — 遺伝子ドライブ",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=%22gene%20drive%22&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"gene-drive\"]", 7200,
  "Europe PMC search stream for gene drive, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_guidelines, "sci-europepmc-guidelines", "Europe PMC — guidelines", "Europe PMC — 診療ガイドライン",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=PUB_TYPE%3A%22Guideline%22&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"guidelines\"]", 7200,
  "Europe PMC search stream for guidelines, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_japan_affiliation, "sci-europepmc-japan-affiliation", "Europe PMC — japan affiliation", "Europe PMC — 日本所属機関",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=AFF%3A%22Japan%22&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"japan-affiliation\"]", 7200,
  "Europe PMC search stream for japan affiliation, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_latest, "sci-europepmc-latest", "Europe PMC — latest", "Europe PMC — 最新論文",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=SRC%3AMED&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"latest\"]", 7200,
  "Europe PMC search stream for latest, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_malaria, "sci-europepmc-malaria", "Europe PMC — malaria", "Europe PMC — マラリア",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=malaria&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"malaria\"]", 7200,
  "Europe PMC search stream for malaria, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_mpox, "sci-europepmc-mpox", "Europe PMC — mpox", "Europe PMC — エムポックス（サル痘）",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=mpox&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"mpox\"]", 7200,
  "Europe PMC search stream for mpox, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_nipah, "sci-europepmc-nipah", "Europe PMC — nipah", "Europe PMC — ニパウイルス",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=nipah&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"nipah\"]", 7200,
  "Europe PMC search stream for nipah, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_open_access, "sci-europepmc-open-access", "Europe PMC — open access", "Europe PMC — オープンアクセス",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=OPEN_ACCESS%3AY&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"open-access\"]", 7200,
  "Europe PMC search stream for open access, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_preprints, "sci-europepmc-preprints", "Europe PMC — preprints", "Europe PMC — プレプリント",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=SRC%3APPR&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"preprints\"]", 7200,
  "Europe PMC search stream for preprints, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_prion, "sci-europepmc-prion", "Europe PMC — prion", "Europe PMC — プリオン",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=prion&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"prion\"]", 7200,
  "Europe PMC search stream for prion, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_retracted, "sci-europepmc-retracted", "Europe PMC — retracted", "Europe PMC — 撤回論文",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=PUB_TYPE%3A%22Retracted%20Publication%22&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"retracted\"]", 7200,
  "Europe PMC search stream for retracted, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_sars_cov_2_variant, "sci-europepmc-sars-cov-2-variant", "Europe PMC — sars cov 2 variant", "Europe PMC — SARS-CoV-2 変異株",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=%22SARS-CoV-2%20variant%22&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"sars-cov-2-variant\"]", 7200,
  "Europe PMC search stream for sars cov 2 variant, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_tuberculosis, "sci-europepmc-tuberculosis", "Europe PMC — tuberculosis", "Europe PMC — 結核",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=tuberculosis&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"tuberculosis\"]", 7200,
  "Europe PMC search stream for tuberculosis, covering PubMed, PMC, preprints and patents.");

VJSON(sci_europepmc_vaccine_safety, "sci-europepmc-vaccine-safety", "Europe PMC — vaccine safety", "Europe PMC — ワクチン安全性",
  "health", "literature",
  "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=%22vaccine%20safety%22&format=json&pageSize=100&sort=P_PDATE_D%20desc",
  "resultlist.result",
  "en", "[\"europepmc\",\"literature\",\"vaccine-safety\"]", 7200,
  "Europe PMC search stream for vaccine safety, covering PubMed, PMC, preprints and patents.");

VJSON(sci_medrxiv_recent, "sci-medrxiv-recent", "medRxiv new preprints", "medRxiv 新着プレプリント",
  "health", "preprint",
  "https://api.medrxiv.org/details/medrxiv/2026-01-01/2030-01-01/0/json",
  "collection",
  "en", "[\"preprint\",\"medicine\",\"medrxiv\"]", 3600,
  "Newly posted medRxiv clinical and public-health preprints before peer review.");

VJSON(sci_ncbi_books, "sci-ncbi-books", "NCBI Bookshelf", "NCBI ブックシェルフ",
  "health", "literature",
  "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=books&retmode=json&retmax=100&term=all%5Bfilter%5D",
  "esearchresult.idlist",
  "en", "[\"bookshelf\",\"ncbi\",\"reference\"]", 86400,
  "Biomedical books and reference works hosted at NCBI.");

VJSON(sci_ncbi_dbvar, "sci-ncbi-dbvar", "NCBI dbVar structural variants", "NCBI dbVar 構造多型",
  "health", "genomics",
  "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=dbvar&retmode=json&retmax=100&term=all%5Bfilter%5D",
  "esearchresult.idlist",
  "en", "[\"dbvar\",\"structural-variant\",\"ncbi\"]", 86400,
  "Human genomic structural variation records.");

VJSON(sci_ncbi_medgen, "sci-ncbi-medgen", "NCBI MedGen conditions", "NCBI MedGen 疾患情報",
  "health", "genomics",
  "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=medgen&retmode=json&retmax=100&term=all%5Bfilter%5D",
  "esearchresult.idlist",
  "en", "[\"medgen\",\"ncbi\",\"genetics\"]", 86400,
  "Medical genetics conditions with linked genes and variants.");

VRSS(sci_nextstrain_blog, "sci-nextstrain-blog", "Nextstrain situation reports", "Nextstrain 状況報告ブログ",
  "health", "genomics",
  "https://nextstrain.org/blog/atom.xml",
  "en", "[\"genomics\",\"outbreak\",\"nextstrain\"]", 21600,
  "Nextstrain narrative situation reports on circulating pathogen lineages.");

VJSON(sci_nextstrain_datasets, "sci-nextstrain-datasets", "Nextstrain pathogen builds", "Nextstrain 病原体系統樹データセット",
  "health", "genomics",
  "https://nextstrain.org/charon/getAvailable?prefix=/",
  "datasets",
  "en", "[\"genomics\",\"pathogen\",\"phylogenetics\"]", 21600,
  "Catalogue of live Nextstrain phylogenetic builds for influenza, SARS-CoV-2, mpox and more.");
