/* Verified-live europe_data sources (60), part 1.
 * Every endpoint in this file returned 2xx and parsed to at
 * least one record at generation time; see
 * docs/verified-sources-manifest.tsv for the recorded proof.
 * Generated by collectors/gen_verified_sources.py — regenerate
 * rather than hand-editing. */
#include "_verified_macros.inc"

VJSON(eur_api_dane_pl, "eur-api-dane-pl", "dane.gov.pl — dataset index", "dane.gov.pl — dataset index",
  "europe_data", "opendata",
  "https://api.dane.gov.pl/1.4/datasets?page=1&per_page=100",
  "data",
  "pl", "[\"pol\",\"opendata\"]", 86400,
  "Poland's national open-data catalogue: dataset records with organisation and licence.");

VJSON(eur_api_dane_pl_inst, "eur-api-dane-pl-inst", "dane.gov.pl — publishing institutions", "dane.gov.pl — publishing institutions",
  "europe_data", "opendata",
  "https://api.dane.gov.pl/1.4/institutions?page=1&per_page=100",
  "data",
  "pl", "[\"pol\",\"opendata\"]", 86400,
  "Polish public institutions that publish on the national open-data portal.");

VJSON(eur_api_dane_pl_res, "eur-api-dane-pl-res", "dane.gov.pl — distributed resources", "dane.gov.pl — distributed resources",
  "europe_data", "opendata",
  "https://api.dane.gov.pl/1.4/resources?page=1&per_page=100",
  "data",
  "pl", "[\"pol\",\"opendata\"]", 86400,
  "Individual file/API resources attached to Polish national open-data datasets.");

VJSON(eur_api_datagovlt, "eur-api-datagovlt", "data.gov.lt — dataset index", "data.gov.lt — dataset index",
  "europe_data", "opendata",
  "https://get.data.gov.lt/datasets/gov/?format(json)",
  "_data",
  "lt", "[\"ltu\",\"opendata\"]", 86400,
  "Lithuanian national open-data catalogue dataset list.");

VJSON(eur_ckan_andal_recent, "eur-ckan-andal-recent", "Junta de Andalucia open data — most recently updated datasets", "Junta de Andalucia open data — most recently updated datasets",
  "europe_data", "opendata",
  "https://www.juntadeandalucia.es/datosabiertos/portal/api/3/action/package_search?rows=100&sort=metadata_modified+desc",
  "result.results",
  "es", "[\"esp\",\"opendata\"]", 86400,
  "Most recently updated datasets from the Junta de Andalucia open data open-data catalogue.");

VJSON(eur_ckan_andal_trans, "eur-ckan-andal-trans", "Junta de Andalucia open data — transport datasets", "Junta de Andalucia open data — transport datasets",
  "europe_data", "opendata",
  "https://www.juntadeandalucia.es/datosabiertos/portal/api/3/action/package_search?q=transport&rows=100",
  "result.results",
  "es", "[\"esp\",\"opendata\"]", 86400,
  "Transport datasets from the Junta de Andalucia open data open-data catalogue.");

VJSON(eur_ckan_andalucia, "eur-ckan-andalucia", "Junta de Andalucia — open data catalogue", "Junta de Andalucia — open data catalogue",
  "europe_data", "opendata",
  "https://www.juntadeandalucia.es/datosabiertos/portal/api/3/action/package_search?rows=100",
  "result.results",
  "es", "[\"esp\",\"opendata\"]", 86400,
  "Andalusian regional government dataset catalogue.");

VJSON(eur_ckan_bcn, "eur-ckan-bcn", "Barcelona City Council — open data catalogue", "Barcelona City Council — open data catalogue",
  "europe_data", "opendata",
  "https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_search?rows=100",
  "result.results",
  "ca", "[\"esp\",\"opendata\"]", 86400,
  "Barcelona municipal dataset catalogue with resource URLs.");

VJSON(eur_ckan_berlin, "eur-ckan-berlin", "Berlin Datenregister — open data catalogue", "Berlin Datenregister — open data catalogue",
  "europe_data", "opendata",
  "https://datenregister.berlin.de/api/3/action/package_search?rows=100",
  "result.results",
  "de", "[\"deu\",\"opendata\"]", 86400,
  "Berlin state open-data register dataset listing.");

VJSON(eur_ckan_berlin_budget, "eur-ckan-berlin-budget", "Berlin Datenregister — budget and spending datasets", "Berlin Datenregister — budget and spending datasets",
  "europe_data", "opendata",
  "https://datenregister.berlin.de/api/3/action/package_search?q=budget&rows=100",
  "result.results",
  "de", "[\"deu\",\"opendata\"]", 86400,
  "Budget and spending datasets from the Berlin Datenregister open-data catalogue.");

VJSON(eur_ckan_berlin_health, "eur-ckan-berlin-health", "Berlin Datenregister — health datasets", "Berlin Datenregister — health datasets",
  "europe_data", "opendata",
  "https://datenregister.berlin.de/api/3/action/package_search?q=health&rows=100",
  "result.results",
  "de", "[\"deu\",\"opendata\"]", 86400,
  "Health datasets from the Berlin Datenregister open-data catalogue.");

VJSON(eur_ckan_berlin_recent, "eur-ckan-berlin-recent", "Berlin Datenregister — most recently updated datasets", "Berlin Datenregister — most recently updated datasets",
  "europe_data", "opendata",
  "https://datenregister.berlin.de/api/3/action/package_search?rows=100&sort=metadata_modified+desc",
  "result.results",
  "de", "[\"deu\",\"opendata\"]", 86400,
  "Most recently updated datasets from the Berlin Datenregister open-data catalogue.");

VJSON(eur_ckan_berlin_trans, "eur-ckan-berlin-trans", "Berlin Datenregister — transport datasets", "Berlin Datenregister — transport datasets",
  "europe_data", "opendata",
  "https://datenregister.berlin.de/api/3/action/package_search?q=transport&rows=100",
  "result.results",
  "de", "[\"deu\",\"opendata\"]", 86400,
  "Transport datasets from the Berlin Datenregister open-data catalogue.");

VJSON(eur_ckan_datagovhr2, "eur-ckan-datagovhr2", "data.gov.hr — open data catalogue", "data.gov.hr — open data catalogue",
  "europe_data", "opendata",
  "https://data.gov.hr/ckan/api/3/action/package_search?rows=100",
  "result.results",
  "hr", "[\"hrv\",\"opendata\"]", 86400,
  "Croatian national open-data catalogue dataset listing.");

VJSON(eur_ckan_datagovie, "eur-ckan-datagovie", "data.gov.ie — open data catalogue", "data.gov.ie — open data catalogue",
  "europe_data", "opendata",
  "https://data.gov.ie/api/3/action/package_search?rows=100",
  "result.results",
  "en", "[\"irl\",\"opendata\"]", 86400,
  "Irish national open-data catalogue dataset listing.");

VJSON(eur_ckan_datagovie_budget, "eur-ckan-datagovie-budget", "Ireland open data portal — budget and spending datasets", "Ireland open data portal — budget and spending datasets",
  "europe_data", "opendata",
  "https://data.gov.ie/api/3/action/package_search?q=budget&rows=100",
  "result.results",
  "en", "[\"irl\",\"opendata\"]", 86400,
  "Budget and spending datasets from the Ireland open data portal open-data catalogue.");

VJSON(eur_ckan_datagovie_env, "eur-ckan-datagovie-env", "Ireland open data portal — environment datasets", "Ireland open data portal — environment datasets",
  "europe_data", "opendata",
  "https://data.gov.ie/api/3/action/package_search?q=environment&rows=100",
  "result.results",
  "en", "[\"irl\",\"opendata\"]", 86400,
  "Environment datasets from the Ireland open data portal open-data catalogue.");

VJSON(eur_ckan_datagovie_health, "eur-ckan-datagovie-health", "Ireland open data portal — health datasets", "Ireland open data portal — health datasets",
  "europe_data", "opendata",
  "https://data.gov.ie/api/3/action/package_search?q=health&rows=100",
  "result.results",
  "en", "[\"irl\",\"opendata\"]", 86400,
  "Health datasets from the Ireland open data portal open-data catalogue.");

VJSON(eur_ckan_datagovie_recent, "eur-ckan-datagovie-recent", "Ireland open data portal — most recently updated datasets", "Ireland open data portal — most recently updated datasets",
  "europe_data", "opendata",
  "https://data.gov.ie/api/3/action/package_search?rows=100&sort=metadata_modified+desc",
  "result.results",
  "en", "[\"irl\",\"opendata\"]", 86400,
  "Most recently updated datasets from the Ireland open data portal open-data catalogue.");

VJSON(eur_ckan_datagovie_trans, "eur-ckan-datagovie-trans", "Ireland open data portal — transport datasets", "Ireland open data portal — transport datasets",
  "europe_data", "opendata",
  "https://data.gov.ie/api/3/action/package_search?q=transport&rows=100",
  "result.results",
  "en", "[\"irl\",\"opendata\"]", 86400,
  "Transport datasets from the Ireland open data portal open-data catalogue.");

VJSON(eur_ckan_datagovlv, "eur-ckan-datagovlv", "data.gov.lv — open data catalogue", "data.gov.lv — open data catalogue",
  "europe_data", "opendata",
  "https://data.gov.lv/api/3/action/package_search?rows=100",
  "result.results",
  "lv", "[\"lva\",\"opendata\"]", 86400,
  "Latvian national open-data catalogue dataset listing.");

VJSON(eur_ckan_datagovlv_env, "eur-ckan-datagovlv-env", "Latvia open data portal — environment datasets", "Latvia open data portal — environment datasets",
  "europe_data", "opendata",
  "https://data.gov.lv/api/3/action/package_search?q=environment&rows=100",
  "result.results",
  "lv", "[\"lva\",\"opendata\"]", 86400,
  "Environment datasets from the Latvia open data portal open-data catalogue.");

VJSON(eur_ckan_datagovlv_health, "eur-ckan-datagovlv-health", "Latvia open data portal — health datasets", "Latvia open data portal — health datasets",
  "europe_data", "opendata",
  "https://data.gov.lv/api/3/action/package_search?q=health&rows=100",
  "result.results",
  "lv", "[\"lva\",\"opendata\"]", 86400,
  "Health datasets from the Latvia open data portal open-data catalogue.");

VJSON(eur_ckan_datagovlv_trans, "eur-ckan-datagovlv-trans", "Latvia open data portal — transport datasets", "Latvia open data portal — transport datasets",
  "europe_data", "opendata",
  "https://data.gov.lv/api/3/action/package_search?q=transport&rows=100",
  "result.results",
  "lv", "[\"lva\",\"opendata\"]", 86400,
  "Transport datasets from the Latvia open data portal open-data catalogue.");

VJSON(eur_ckan_datagovro, "eur-ckan-datagovro", "data.gov.ro — open data catalogue", "data.gov.ro — open data catalogue",
  "europe_data", "opendata",
  "https://data.gov.ro/api/3/action/package_search?rows=100",
  "result.results",
  "ro", "[\"rou\",\"opendata\"]", 86400,
  "Romanian national open-data catalogue dataset listing.");

VJSON(eur_ckan_datagovro_trans, "eur-ckan-datagovro-trans", "Romania open data portal — transport datasets", "Romania open data portal — transport datasets",
  "europe_data", "opendata",
  "https://data.gov.ro/api/3/action/package_search?q=transport&rows=100",
  "result.results",
  "ro", "[\"rou\",\"opendata\"]", 86400,
  "Transport datasets from the Romania open data portal open-data catalogue.");

VJSON(eur_ckan_datagovua, "eur-ckan-datagovua", "data.gov.ua — open data catalogue", "data.gov.ua — open data catalogue",
  "europe_data", "opendata",
  "https://data.gov.ua/api/3/action/package_search?rows=100",
  "result.results",
  "uk", "[\"ukr\",\"opendata\"]", 86400,
  "Ukrainian national open-data catalogue dataset listing.");

VJSON(eur_ckan_datagovua_budget, "eur-ckan-datagovua-budget", "Ukraine open data portal — budget and spending datasets", "Ukraine open data portal — budget and spending datasets",
  "europe_data", "opendata",
  "https://data.gov.ua/api/3/action/package_search?q=budget&rows=100",
  "result.results",
  "uk", "[\"ukr\",\"opendata\"]", 86400,
  "Budget and spending datasets from the Ukraine open data portal open-data catalogue.");

VJSON(eur_ckan_datagovua_health, "eur-ckan-datagovua-health", "Ukraine open data portal — health datasets", "Ukraine open data portal — health datasets",
  "europe_data", "opendata",
  "https://data.gov.ua/api/3/action/package_search?q=health&rows=100",
  "result.results",
  "uk", "[\"ukr\",\"opendata\"]", 86400,
  "Health datasets from the Ukraine open data portal open-data catalogue.");

VJSON(eur_ckan_datagovua_trans, "eur-ckan-datagovua-trans", "Ukraine open data portal — transport datasets", "Ukraine open data portal — transport datasets",
  "europe_data", "opendata",
  "https://data.gov.ua/api/3/action/package_search?q=transport&rows=100",
  "result.results",
  "uk", "[\"ukr\",\"opendata\"]", 86400,
  "Transport datasets from the Ukraine open data portal open-data catalogue.");

VJSON(eur_ckan_datigovit, "eur-ckan-datigovit", "dati.gov.it — national open data catalogue", "dati.gov.it — national open data catalogue",
  "europe_data", "opendata",
  "https://www.dati.gov.it/opendata/api/3/action/package_search?rows=100",
  "result.results",
  "it", "[\"ita\",\"opendata\"]", 86400,
  "Italian national open-data catalogue dataset listing.");

VJSON(eur_ckan_datigovit_budget, "eur-ckan-datigovit-budget", "dati.gov.it national catalogue — budget and spending datasets", "dati.gov.it national catalogue — budget and spending datasets",
  "europe_data", "opendata",
  "https://www.dati.gov.it/opendata/api/3/action/package_search?q=budget&rows=100",
  "result.results",
  "it", "[\"ita\",\"opendata\"]", 86400,
  "Budget and spending datasets from the dati.gov.it national catalogue open-data catalogue.");

VJSON(eur_ckan_datigovit_env, "eur-ckan-datigovit-env", "dati.gov.it national catalogue — environment datasets", "dati.gov.it national catalogue — environment datasets",
  "europe_data", "opendata",
  "https://www.dati.gov.it/opendata/api/3/action/package_search?q=environment&rows=100",
  "result.results",
  "it", "[\"ita\",\"opendata\"]", 86400,
  "Environment datasets from the dati.gov.it national catalogue open-data catalogue.");

VJSON(eur_ckan_datigovit_health, "eur-ckan-datigovit-health", "dati.gov.it national catalogue — health datasets", "dati.gov.it national catalogue — health datasets",
  "europe_data", "opendata",
  "https://www.dati.gov.it/opendata/api/3/action/package_search?q=health&rows=100",
  "result.results",
  "it", "[\"ita\",\"opendata\"]", 86400,
  "Health datasets from the dati.gov.it national catalogue open-data catalogue.");

VJSON(eur_ckan_datigovit_trans, "eur-ckan-datigovit-trans", "dati.gov.it national catalogue — transport datasets", "dati.gov.it national catalogue — transport datasets",
  "europe_data", "opendata",
  "https://www.dati.gov.it/opendata/api/3/action/package_search?q=transport&rows=100",
  "result.results",
  "it", "[\"ita\",\"opendata\"]", 86400,
  "Transport datasets from the dati.gov.it national catalogue open-data catalogue.");

VJSON(eur_ckan_govdata_budget, "eur-ckan-govdata-budget", "GovData Germany — budget and spending datasets", "GovData Germany — budget and spending datasets",
  "europe_data", "opendata",
  "https://ckan.govdata.de/api/3/action/package_search?q=budget&rows=100",
  "result.results",
  "de", "[\"deu\",\"opendata\"]", 86400,
  "Budget and spending datasets from the GovData Germany open-data catalogue.");

VJSON(eur_ckan_govdata_de, "eur-ckan-govdata-de", "GovData Germany — open data catalogue", "GovData Germany — open data catalogue",
  "europe_data", "opendata",
  "https://ckan.govdata.de/api/3/action/package_search?rows=100",
  "result.results",
  "de", "[\"deu\",\"opendata\"]", 86400,
  "German federal open-data catalogue dataset listing across all Laender.");

VJSON(eur_ckan_govdata_env, "eur-ckan-govdata-env", "GovData Germany — environment datasets", "GovData Germany — environment datasets",
  "europe_data", "opendata",
  "https://ckan.govdata.de/api/3/action/package_search?q=environment&rows=100",
  "result.results",
  "de", "[\"deu\",\"opendata\"]", 86400,
  "Environment datasets from the GovData Germany open-data catalogue.");

VJSON(eur_ckan_govdata_health, "eur-ckan-govdata-health", "GovData Germany — health datasets", "GovData Germany — health datasets",
  "europe_data", "opendata",
  "https://ckan.govdata.de/api/3/action/package_search?q=health&rows=100",
  "result.results",
  "de", "[\"deu\",\"opendata\"]", 86400,
  "Health datasets from the GovData Germany open-data catalogue.");

VJSON(eur_ckan_govdata_recent, "eur-ckan-govdata-recent", "GovData Germany — most recently updated datasets", "GovData Germany — most recently updated datasets",
  "europe_data", "opendata",
  "https://ckan.govdata.de/api/3/action/package_search?rows=100&sort=metadata_modified+desc",
  "result.results",
  "de", "[\"deu\",\"opendata\"]", 86400,
  "Most recently updated datasets from the GovData Germany open-data catalogue.");

VJSON(eur_ckan_govdata_trans, "eur-ckan-govdata-trans", "GovData Germany — transport datasets", "GovData Germany — transport datasets",
  "europe_data", "opendata",
  "https://ckan.govdata.de/api/3/action/package_search?q=transport&rows=100",
  "result.results",
  "de", "[\"deu\",\"opendata\"]", 86400,
  "Transport datasets from the GovData Germany open-data catalogue.");

VJSON(eur_ckan_hamburg, "eur-ckan-hamburg", "Hamburg Transparency Portal — dataset search", "Hamburg Transparency Portal — dataset search",
  "europe_data", "opendata",
  "https://suche.transparenz.hamburg.de/api/3/action/package_search?rows=100",
  "result.results",
  "de", "[\"deu\",\"opendata\"]", 86400,
  "Hamburg transparency portal datasets, including contracts and permits.");

VJSON(eur_ckan_hr_env, "eur-ckan-hr-env", "data.gov.hr — environment datasets", "data.gov.hr — environment datasets",
  "europe_data", "opendata",
  "https://data.gov.hr/ckan/api/3/action/package_search?q=okolis&rows=100",
  "result.results",
  "hr", "[\"hrv\",\"opendata\"]", 86400,
  "Croatian national open datasets matching the environment topic.");

VJSON(eur_ckan_hr_recent, "eur-ckan-hr-recent", "data.gov.hr — recently updated datasets", "data.gov.hr — recently updated datasets",
  "europe_data", "opendata",
  "https://data.gov.hr/ckan/api/3/action/package_search?rows=100&sort=metadata_modified+desc",
  "result.results",
  "hr", "[\"hrv\",\"opendata\"]", 21600,
  "Most recently updated Croatian national open datasets.");

VJSON(eur_ckan_hr_trans, "eur-ckan-hr-trans", "data.gov.hr — transport datasets", "data.gov.hr — transport datasets",
  "europe_data", "opendata",
  "https://data.gov.hr/ckan/api/3/action/package_search?q=promet&rows=100",
  "result.results",
  "hr", "[\"hrv\",\"opendata\"]", 86400,
  "Croatian national open datasets matching the transport topic.");

VJSON(eur_ckan_it_recent, "eur-ckan-it-recent", "dati.gov.it — recently updated datasets", "dati.gov.it — recently updated datasets",
  "europe_data", "opendata",
  "https://www.dati.gov.it/opendata/api/3/action/package_search?rows=100&sort=metadata_modified+desc",
  "result.results",
  "it", "[\"ita\",\"opendata\"]", 21600,
  "Most recently updated datasets in the Italian national catalogue.");

VJSON(eur_ckan_lv_recent, "eur-ckan-lv-recent", "data.gov.lv — recently updated datasets", "data.gov.lv — recently updated datasets",
  "europe_data", "opendata",
  "https://data.gov.lv/api/3/action/package_search?rows=100&sort=metadata_modified+desc",
  "result.results",
  "lv", "[\"lva\",\"opendata\"]", 21600,
  "Most recently updated Latvian national open datasets.");

VJSON(eur_ckan_malaga, "eur-ckan-malaga", "Malaga City Council — open data catalogue", "Malaga City Council — open data catalogue",
  "europe_data", "opendata",
  "https://datosabiertos.malaga.eu/api/3/action/package_search?rows=100",
  "result.results",
  "es", "[\"esp\",\"opendata\"]", 86400,
  "Malaga municipal open-data catalogue dataset listing.");

VJSON(eur_ckan_malaga_recent, "eur-ckan-malaga-recent", "Malaga City Council open data — most recently updated datasets", "Malaga City Council open data — most recently updated datasets",
  "europe_data", "opendata",
  "https://datosabiertos.malaga.eu/api/3/action/package_search?rows=100&sort=metadata_modified+desc",
  "result.results",
  "es", "[\"esp\",\"opendata\"]", 86400,
  "Most recently updated datasets from the Malaga City Council open data open-data catalogue.");

VJSON(eur_ckan_malaga_trans, "eur-ckan-malaga-trans", "Malaga City Council open data — transport datasets", "Malaga City Council open data — transport datasets",
  "europe_data", "opendata",
  "https://datosabiertos.malaga.eu/api/3/action/package_search?q=transport&rows=100",
  "result.results",
  "es", "[\"esp\",\"opendata\"]", 86400,
  "Transport datasets from the Malaga City Council open data open-data catalogue.");

VJSON(eur_ckan_muenchen, "eur-ckan-muenchen", "City of Munich — open data catalogue", "City of Munich — open data catalogue",
  "europe_data", "opendata",
  "https://opendata.muenchen.de/api/3/action/package_search?rows=100",
  "result.results",
  "de", "[\"deu\",\"opendata\"]", 86400,
  "Munich municipal open-data catalogue dataset listing.");

VJSON(eur_ckan_muenchen_recent, "eur-ckan-muenchen-recent", "City of Munich open data — most recently updated datasets", "City of Munich open data — most recently updated datasets",
  "europe_data", "opendata",
  "https://opendata.muenchen.de/api/3/action/package_search?rows=100&sort=metadata_modified+desc",
  "result.results",
  "de", "[\"deu\",\"opendata\"]", 86400,
  "Most recently updated datasets from the City of Munich open data open-data catalogue.");

VJSON(eur_ckan_odp_de, "eur-ckan-odp-de", "Offenes Datenportal — German municipal open data", "Offenes Datenportal — German municipal open data",
  "europe_data", "opendata",
  "https://www.offenesdatenportal.de/api/3/action/package_search?rows=100",
  "result.results",
  "de", "[\"deu\",\"opendata\"]", 86400,
  "Shared open-data portal for several hundred German municipalities.");

VJSON(eur_ckan_odpde_budget, "eur-ckan-odpde-budget", "Offenes Datenportal Germany — budget and spending datasets", "Offenes Datenportal Germany — budget and spending datasets",
  "europe_data", "opendata",
  "https://www.offenesdatenportal.de/api/3/action/package_search?q=budget&rows=100",
  "result.results",
  "de", "[\"deu\",\"opendata\"]", 86400,
  "Budget and spending datasets from the Offenes Datenportal Germany open-data catalogue.");

VJSON(eur_ckan_odpde_recent, "eur-ckan-odpde-recent", "Offenes Datenportal Germany — most recently updated datasets", "Offenes Datenportal Germany — most recently updated datasets",
  "europe_data", "opendata",
  "https://www.offenesdatenportal.de/api/3/action/package_search?rows=100&sort=metadata_modified+desc",
  "result.results",
  "de", "[\"deu\",\"opendata\"]", 86400,
  "Most recently updated datasets from the Offenes Datenportal Germany open-data catalogue.");

VJSON(eur_ckan_odpde_trans, "eur-ckan-odpde-trans", "Offenes Datenportal Germany — transport datasets", "Offenes Datenportal Germany — transport datasets",
  "europe_data", "opendata",
  "https://www.offenesdatenportal.de/api/3/action/package_search?q=transport&rows=100",
  "result.results",
  "de", "[\"deu\",\"opendata\"]", 86400,
  "Transport datasets from the Offenes Datenportal Germany open-data catalogue.");

VJSON(eur_ckan_overheid_budget, "eur-ckan-overheid-budget", "Data.overheid.nl — budget and spending datasets", "Data.overheid.nl — budget and spending datasets",
  "europe_data", "opendata",
  "https://data.overheid.nl/data/api/3/action/package_search?q=budget&rows=100",
  "result.results",
  "nl", "[\"nld\",\"opendata\"]", 86400,
  "Budget and spending datasets from the Data.overheid.nl open-data catalogue.");

VJSON(eur_ckan_overheid_env, "eur-ckan-overheid-env", "Data.overheid.nl — environment datasets", "Data.overheid.nl — environment datasets",
  "europe_data", "opendata",
  "https://data.overheid.nl/data/api/3/action/package_search?q=environment&rows=100",
  "result.results",
  "nl", "[\"nld\",\"opendata\"]", 86400,
  "Environment datasets from the Data.overheid.nl open-data catalogue.");

VJSON(eur_ckan_overheid_health, "eur-ckan-overheid-health", "Data.overheid.nl — health datasets", "Data.overheid.nl — health datasets",
  "europe_data", "opendata",
  "https://data.overheid.nl/data/api/3/action/package_search?q=health&rows=100",
  "result.results",
  "nl", "[\"nld\",\"opendata\"]", 86400,
  "Health datasets from the Data.overheid.nl open-data catalogue.");

VJSON(eur_ckan_overheid_nl, "eur-ckan-overheid-nl", "data.overheid.nl — open data catalogue", "data.overheid.nl — open data catalogue",
  "europe_data", "opendata",
  "https://data.overheid.nl/data/api/3/action/package_search?rows=100",
  "result.results",
  "nl", "[\"nld\",\"opendata\"]", 86400,
  "Dutch national open-data catalogue dataset listing.");
