/* Verified-live africa_gov sources (60), part 1.
 * Every endpoint in this file returned 2xx and parsed to at
 * least one record at generation time; see
 * docs/verified-sources-manifest.tsv for the recorded proof.
 * Generated by collectors/gen_verified_sources.py — regenerate
 * rather than hand-editing. */
#include "_verified_macros.inc"

VRSS(afr_comesa_news, "afr-comesa-news", "COMESA — Common Market for Eastern and Southern Africa news", "COMESA — Common Market for Eastern and Southern Africa news",
  "africa_gov", "economy",
  "https://www.comesa.int/feed/",
  "en", "[\"africa\",\"comesa\"]", 7200,
  "Trade-bloc announcements covering tariffs, summits and member-state economic policy.");

VGEO(afr_cpt_background_maps_base_data_terrain_ext_dams_1, "afr-cpt-background-maps-base-data-terrain-ext-dams-1", "City of Cape Town — dams", "City of Cape Town — dams",
  "africa_gov", "environment",
  "https://citymaps.capetown.gov.za/agsext/rest/services/Background_Maps/Base_Data_Terrain_Ext/MapServer/1/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"capetown\",\"geospatial\",\"municipal\"]", 43200,
  "Dam polygons in the City of Cape Town area, relevant to water-supply monitoring.");

VGEO(afr_cpt_background_maps_base_data_terrain_ext_wetlan_0, "afr-cpt-background-maps-base-data-terrain-ext-wetlan-0", "City of Cape Town — wetlands", "City of Cape Town — wetlands",
  "africa_gov", "environment",
  "https://citymaps.capetown.gov.za/agsext/rest/services/Background_Maps/Base_Data_Terrain_Ext/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"capetown\",\"geospatial\",\"municipal\"]", 86400,
  "Wetland polygons within the City of Cape Town municipal area.");

VGEO(afr_cpt_hosted_odp_split_1_electricity_public_lighti_1, "afr-cpt-hosted-odp-split-1-electricity-public-lighti-1", "City of Cape Town — public lighting network", "City of Cape Town — public lighting network",
  "africa_gov", "energy",
  "https://citymaps.capetown.gov.za/agsext/rest/services/Hosted/ODP_SPLIT_1/FeatureServer/1/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"capetown\",\"geospatial\",\"municipal\"]", 43200,
  "Public street-lighting assets in the City of Cape Town electricity network.");

VGEO(afr_cpt_layers_sl_film_srvc_area_film_service_areas_0, "afr-cpt-layers-sl-film-srvc-area-film-service-areas-0", "City of Cape Town — film service areas", "City of Cape Town — film service areas",
  "africa_gov", "gov",
  "https://citymaps.capetown.gov.za/agsext/rest/services/Layers/SL_FILM_SRVC_AREA/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"capetown\",\"geospatial\",\"municipal\"]", 86400,
  "Film permit service areas across the City of Cape Town.");

VGEO(afr_cpt_search_layers_esmsfeatureupdate_lines_events_0, "afr-cpt-search-layers-esmsfeatureupdate-lines-events-0", "City of Cape Town — event support line features", "City of Cape Town — event support line features",
  "africa_gov", "gov",
  "https://citymaps.capetown.gov.za/agsext/rest/services/Search_Layers/ESMSFeatureUpdate_Lines/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"capetown\",\"geospatial\",\"municipal\"]", 43200,
  "Event support and management line features maintained by Cape Town's events unit.");

VGEO(afr_cpt_search_layers_gen_property_info_servitude_3, "afr-cpt-search-layers-gen-property-info-servitude-3", "City of Cape Town — property servitudes", "City of Cape Town — property servitudes",
  "africa_gov", "gov",
  "https://citymaps.capetown.gov.za/agsext/rest/services/Search_Layers/Gen_Property_Info/MapServer/3/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"capetown\",\"geospatial\",\"municipal\"]", 86400,
  "Registered servitudes over Cape Town properties.");

VGEO(afr_cpt_search_layers_sl_cgis_sub_cncl_sub_council_0, "afr-cpt-search-layers-sl-cgis-sub-cncl-sub-council-0", "City of Cape Town — sub-council boundaries", "City of Cape Town — sub-council boundaries",
  "africa_gov", "gov",
  "https://citymaps.capetown.gov.za/agsext/rest/services/Search_Layers/SL_CGIS_SUB_CNCL/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"capetown\",\"geospatial\",\"municipal\"]", 43200,
  "City of Cape Town sub-council boundary polygons.");

VGEO(afr_cpt_search_layers_sl_evnt_prmt_line_events_permi_0, "afr-cpt-search-layers-sl-evnt-prmt-line-events-permi-0", "City of Cape Town — permitted event routes", "City of Cape Town — permitted event routes",
  "africa_gov", "gov",
  "https://citymaps.capetown.gov.za/agsext/rest/services/Search_Layers/SL_EVNT_PRMT_LINE/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"capetown\",\"geospatial\",\"municipal\"]", 86400,
  "Routes for events permitted by the City of Cape Town, with permit metadata.");

VGEO(afr_cpt_search_layers_sl_fclt_bkng_community_centres_0, "afr-cpt-search-layers-sl-fclt-bkng-community-centres-0", "City of Cape Town — community centres", "City of Cape Town — community centres",
  "africa_gov", "gov",
  "https://citymaps.capetown.gov.za/agsext/rest/services/Search_Layers/SL_FCLT_BKNG/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"capetown\",\"geospatial\",\"municipal\"]", 43200,
  "Bookable community centres operated by the City of Cape Town with location and facility detail.");

VGEO(afr_cpt_search_layers_sl_fclt_bkng_resorts_1, "afr-cpt-search-layers-sl-fclt-bkng-resorts-1", "City of Cape Town — municipal resorts", "City of Cape Town — municipal resorts",
  "africa_gov", "gov",
  "https://citymaps.capetown.gov.za/agsext/rest/services/Search_Layers/SL_FCLT_BKNG/MapServer/1/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"capetown\",\"geospatial\",\"municipal\"]", 86400,
  "City of Cape Town municipal resorts and camping facilities.");

VGEO(afr_cpt_search_layers_sl_hrtg_inv_un_heritage_invent_0, "afr-cpt-search-layers-sl-hrtg-inv-un-heritage-invent-0", "City of Cape Town — heritage inventory", "City of Cape Town — heritage inventory",
  "africa_gov", "gov",
  "https://citymaps.capetown.gov.za/agsext/rest/services/Search_Layers/SL_HRTG_INV_UN/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"capetown\",\"geospatial\",\"municipal\"]", 43200,
  "Cape Town heritage inventory sites with grading and protection status.");

VGEO(afr_cpt_search_layers_sl_hrtg_prsd_area_proposed_her_0, "afr-cpt-search-layers-sl-hrtg-prsd-area-proposed-her-0", "City of Cape Town — proposed heritage areas", "City of Cape Town — proposed heritage areas",
  "africa_gov", "gov",
  "https://citymaps.capetown.gov.za/agsext/rest/services/Search_Layers/SL_HRTG_PRSD_AREA/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"capetown\",\"geospatial\",\"municipal\"]", 86400,
  "Proposed heritage protection overlay areas in Cape Town.");

VGEO(afr_cpt_search_layers_sl_mjr_sbrb_major_suburbs_0, "afr-cpt-search-layers-sl-mjr-sbrb-major-suburbs-0", "City of Cape Town — major suburbs", "City of Cape Town — major suburbs",
  "africa_gov", "gov",
  "https://citymaps.capetown.gov.za/agsext/rest/services/Search_Layers/SL_MJR_SBRB/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"capetown\",\"geospatial\",\"municipal\"]", 43200,
  "Major suburb polygons for the City of Cape Town.");

VGEO(afr_cpt_search_layers_sl_pbdm_rgn_planning_and_build_0, "afr-cpt-search-layers-sl-pbdm-rgn-planning-and-build-0", "City of Cape Town — planning and building districts", "City of Cape Town — planning and building districts",
  "africa_gov", "gov",
  "https://citymaps.capetown.gov.za/agsext/rest/services/Search_Layers/SL_PBDM_RGN/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"capetown\",\"geospatial\",\"municipal\"]", 86400,
  "Planning and building management district boundaries for Cape Town.");

VGEO(afr_cpt_search_layers_sl_rgdb_ward_tm_wards_0, "afr-cpt-search-layers-sl-rgdb-ward-tm-wards-0", "City of Cape Town — ward boundaries", "City of Cape Town — ward boundaries",
  "africa_gov", "gov",
  "https://citymaps.capetown.gov.za/agsext/rest/services/Search_Layers/SL_RGDB_WARD_TM/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"capetown\",\"geospatial\",\"municipal\"]", 43200,
  "City of Cape Town municipal ward boundaries used for election and service-delivery analysis.");

VGEO(afr_cpt_search_layers_sl_wgdb_ofc_sbrb_official_subu_0, "afr-cpt-search-layers-sl-wgdb-ofc-sbrb-official-subu-0", "City of Cape Town — official suburbs", "City of Cape Town — official suburbs",
  "africa_gov", "gov",
  "https://citymaps.capetown.gov.za/agsext/rest/services/Search_Layers/SL_WGDB_OFC_SBRB/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"capetown\",\"geospatial\",\"municipal\"]", 86400,
  "Official suburb boundary polygons maintained by the City of Cape Town.");

VRSS(afr_ecowas_news, "afr-ecowas-news", "ECOWAS — Commission news", "ECOWAS — Commission news",
  "africa_gov", "gov",
  "https://ecowas.int/feed/",
  "en", "[\"africa\",\"ecowas\"]", 7200,
  "Official communiques and summit decisions from the Economic Community of West African States.");

VGEO(afr_ekur_cif_procap_procapman_masterlist_0, "afr-ekur-cif-procap-procapman-masterlist-0", "City of Ekurhuleni — capital project masterlist", "City of Ekurhuleni — capital project masterlist",
  "africa_gov", "gov",
  "https://gis.ekurhuleni.gov.za/arcgis/rest/services/CIF/ProCAP/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"ekurhuleni\",\"geospatial\",\"municipal\"]", 43200,
  "Ekurhuleni capital investment framework project locations and status.");

VGEO(afr_ekur_covid19_coe_covid_data_cases_per_suburb_0, "afr-ekur-covid19-coe-covid-data-cases-per-suburb-0", "City of Ekurhuleni — COVID-19 cases per suburb", "City of Ekurhuleni — COVID-19 cases per suburb",
  "africa_gov", "health",
  "https://gis.ekurhuleni.gov.za/arcgis/rest/services/Covid19/CoE_Covid_data/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"ekurhuleni\",\"geospatial\",\"municipal\"]", 86400,
  "Suburb-level COVID-19 case counts recorded by the City of Ekurhuleni.");

VGEO(afr_ekur_covid19_coe_covid_data_cases_per_ward_1, "afr-ekur-covid19-coe-covid-data-cases-per-ward-1", "City of Ekurhuleni — COVID-19 cases per ward", "City of Ekurhuleni — COVID-19 cases per ward",
  "africa_gov", "health",
  "https://gis.ekurhuleni.gov.za/arcgis/rest/services/Covid19/CoE_Covid_data/MapServer/1/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"ekurhuleni\",\"geospatial\",\"municipal\"]", 43200,
  "Ward-level COVID-19 case counts recorded by the City of Ekurhuleni.");

VGEO(afr_ekur_ekurhuleni_ekurhuleni_poi_map_nature_1, "afr-ekur-ekurhuleni-ekurhuleni-poi-map-nature-1", "City of Ekurhuleni — nature points of interest", "City of Ekurhuleni — nature points of interest",
  "africa_gov", "environment",
  "https://gis.ekurhuleni.gov.za/arcgis/rest/services/Ekurhuleni/Ekurhuleni_POI_Map/MapServer/1/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"ekurhuleni\",\"geospatial\",\"municipal\"]", 43200,
  "Nature reserves and environmental points of interest in Ekurhuleni.");

VGEO(afr_ekur_ekurhuleni_ekurhuleni_propety_data_map_stand_1, "afr-ekur-ekurhuleni-ekurhuleni-propety-data-map-stand-1", "City of Ekurhuleni — cadastral stands", "City of Ekurhuleni — cadastral stands",
  "africa_gov", "gov",
  "https://gis.ekurhuleni.gov.za/arcgis/rest/services/Ekurhuleni/Ekurhuleni_Propety_Data_Map/MapServer/1/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"ekurhuleni\",\"geospatial\",\"municipal\"]", 86400,
  "Cadastral stand (erf) polygons for the City of Ekurhuleni with property identifiers.");

VGEO(afr_ekur_ekurhuleni_ekurhuleni_transportation_map_v1_0, "afr-ekur-ekurhuleni-ekurhuleni-transportation-map-v1--0", "City of Ekurhuleni — transportation network", "City of Ekurhuleni — transportation network",
  "africa_gov", "transport",
  "https://gis.ekurhuleni.gov.za/arcgis/rest/services/Ekurhuleni/Ekurhuleni_Transportation_Map_v1/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"ekurhuleni\",\"geospatial\",\"municipal\"]", 43200,
  "Ekurhuleni transportation network features including roads and transit infrastructure.");

VGEO(afr_ekur_ekurhuleni_gridlayout_current_tile_layout_0, "afr-ekur-ekurhuleni-gridlayout-current-tile-layout-0", "City of Ekurhuleni — map tile grid layout", "City of Ekurhuleni — map tile grid layout",
  "africa_gov", "gov",
  "https://gis.ekurhuleni.gov.za/arcgis/rest/services/Ekurhuleni/GRIDLayout/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"ekurhuleni\",\"geospatial\",\"municipal\"]", 86400,
  "Current map-sheet tile grid used by the City of Ekurhuleni GIS for cadastral sheet referencing.");

VGEO(afr_ekur_ekurhuleni_servitudes_servitude_area_1, "afr-ekur-ekurhuleni-servitudes-servitude-area-1", "City of Ekurhuleni — servitude areas", "City of Ekurhuleni — servitude areas",
  "africa_gov", "gov",
  "https://gis.ekurhuleni.gov.za/arcgis/rest/services/Ekurhuleni/Servitudes/MapServer/1/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"ekurhuleni\",\"geospatial\",\"municipal\"]", 43200,
  "Registered servitude areas across the City of Ekurhuleni.");

VGEO(afr_ekur_engineering_services_stormwater_network_stor_0, "afr-ekur-engineering-services-stormwater-network-stor-0", "City of Ekurhuleni — stormwater network", "City of Ekurhuleni — stormwater network",
  "africa_gov", "environment",
  "https://gis.ekurhuleni.gov.za/arcgis/rest/services/Engineering_Services/Stormwater_Network/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"ekurhuleni\",\"geospatial\",\"municipal\"]", 86400,
  "Stormwater drainage network assets for the City of Ekurhuleni.");

VGEO(afr_ekur_enviromental_final_cba_draft3_gauteng_reserv_0, "afr-ekur-enviromental-final-cba-draft3-gauteng-reserv-0", "City of Ekurhuleni — Gauteng reserves and critical biodiversity areas", "City of Ekurhuleni — Gauteng reserves and critical biodiversity areas",
  "africa_gov", "environment",
  "https://gis.ekurhuleni.gov.za/arcgis/rest/services/Enviromental/FINAL_CBA_DRAFT3/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"ekurhuleni\",\"geospatial\",\"municipal\"]", 43200,
  "Protected reserves and critical biodiversity areas mapped across Gauteng.");

VGEO(afr_ekur_mdb_map_mil1_wards_2021_0, "afr-ekur-mdb-map-mil1-wards-2021-0", "City of Ekurhuleni — ward boundaries (2021)", "City of Ekurhuleni — ward boundaries (2021)",
  "africa_gov", "gov",
  "https://gis.ekurhuleni.gov.za/arcgis/rest/services/MDB_Map_MIL1/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"zaf\",\"ekurhuleni\",\"geospatial\",\"municipal\"]", 86400,
  "Ekurhuleni municipal ward boundaries as demarcated for the 2021 local elections.");

VRSS(afr_eskom_news, "afr-eskom-news", "Eskom — Media statements", "Eskom — Media statements",
  "africa_gov", "energy",
  "https://www.eskom.co.za/feed/",
  "en", "[\"zaf\",\"energy\"]", 3600,
  "South African grid operator statements including load-shedding stage changes and plant outages.");

VGEO(afr_grid3_accessibility_profile_by_lga_health_faciliti_0, "afr-grid3-accessibility-profile-by-lga-health-faciliti-0", "GRID3 — Nigeria health-facility accessibility by LGA", "GRID3 — Nigeria health-facility accessibility by LGA",
  "africa_gov", "health",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/Accessibility_Profile_by_LGA/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"nga\",\"cod\",\"geospatial\",\"grid3\"]", 43200,
  "Travel-time accessibility to health facilities aggregated to Nigerian local government areas.");

VGEO(afr_grid3_africa_country_boundary_africa_country_bound_35, "afr-grid3-africa-country-boundary-africa-country-bound-35", "GRID3 — Africa country boundaries", "GRID3 — Africa country boundaries",
  "africa_gov", "opendata",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/Africa_Country_Boundary/FeatureServer/35/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"nga\",\"cod\",\"geospatial\",\"grid3\"]", 86400,
  "Continental Africa country boundary polygons for base mapping.");

VGEO(afr_grid3_churches_in_nigeria_fc_poi_church_0, "afr-grid3-churches-in-nigeria-fc-poi-church-0", "GRID3 — Nigeria places of worship (churches)", "GRID3 — Nigeria places of worship (churches)",
  "africa_gov", "gov",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/Churches_in_Nigeria/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"nga\",\"cod\",\"geospatial\",\"grid3\"]", 43200,
  "Geolocated churches in Nigeria, used for settlement and population-distribution work.");

VGEO(afr_grid3_cod_grid3_health_facilities_v8_0_cod_grid3_h_0, "afr-grid3-cod-grid3-health-facilities-v8-0-cod-grid3-h-0", "GRID3 — DR Congo health facilities", "GRID3 — DR Congo health facilities",
  "africa_gov", "health",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/COD_GRID3_health_facilities_v8_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"nga\",\"cod\",\"geospatial\",\"grid3\"]", 86400,
  "Geolocated health facilities across the Democratic Republic of the Congo.");

VGEO(afr_grid3_communications_lga_communications_access_ris_0, "afr-grid3-communications-lga-communications-access-ris-0", "GRID3 — Nigeria communications access risk by LGA", "GRID3 — Nigeria communications access risk by LGA",
  "africa_gov", "gov",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/communications_LGA/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"nga\",\"cod\",\"geospatial\",\"grid3\"]", 43200,
  "LGA-level mobile and communications access risk indicators for Nigeria.");

VGEO(afr_grid3_comorbidities_risk_profile_profile_by_lga_co_0, "afr-grid3-comorbidities-risk-profile-profile-by-lga-co-0", "GRID3 — Nigeria comorbidity risk profile by LGA", "GRID3 — Nigeria comorbidity risk profile by LGA",
  "africa_gov", "health",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/Comorbidities_Risk_Profile_Profile_by_LGA/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"nga\",\"cod\",\"geospatial\",\"grid3\"]", 86400,
  "LGA-level comorbidity risk indicators for Nigerian health planning.");

VGEO(afr_grid3_energy_and_electricity_substations_in_nigeri_0, "afr-grid3-energy-and-electricity-substations-in-nigeri-0", "GRID3 — Nigeria electricity substations", "GRID3 — Nigeria electricity substations",
  "africa_gov", "energy",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/Energy_and_electricity_substations_in_Nigeria/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"nga\",\"cod\",\"geospatial\",\"grid3\"]", 43200,
  "Locations of Nigerian electricity substations for grid and outage analysis.");

VGEO(afr_grid3_factories_and_industrial_sites_in_nigeria_gr_0, "afr-grid3-factories-and-industrial-sites-in-nigeria-gr-0", "GRID3 — Nigeria factories and industrial sites", "GRID3 — Nigeria factories and industrial sites",
  "africa_gov", "economy",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/Factories_and_industrial_sites_in_Nigeria/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"nga\",\"cod\",\"geospatial\",\"grid3\"]", 43200,
  "Geolocated Nigerian factories and industrial sites.");

VGEO(afr_grid3_farms_in_nigeria_grid3_nga_poi_farm_0, "afr-grid3-farms-in-nigeria-grid3-nga-poi-farm-0", "GRID3 — Nigeria farm points", "GRID3 — Nigeria farm points",
  "africa_gov", "environment",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/Farms_in_Nigeria/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"nga\",\"cod\",\"geospatial\",\"grid3\"]", 86400,
  "Geolocated farm sites across Nigeria from the GRID3 points-of-interest database.");

VGEO(afr_grid3_grid3_admin_0_global_admin_0_0, "afr-grid3-grid3-admin-0-global-admin-0-0", "GRID3 — GRID3 admin level 0 boundaries", "GRID3 — GRID3 admin level 0 boundaries",
  "africa_gov", "opendata",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_Admin_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"nga\",\"cod\",\"geospatial\",\"grid3\"]", 43200,
  "National boundary polygons used as the reference admin-0 layer across GRID3 African datasets.");

VGEO(afr_grid3_grid3_ago_settlement_extents_v3_0_grid3_ago_0, "afr-grid3-grid3-ago-settlement-extents-v3-0-grid3-ago--0", "GRID3 — Angola settlement extents", "GRID3 — Angola settlement extents",
  "africa_gov", "opendata",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_AGO_Settlement_Extents_v3_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"ago\",\"settlements\",\"geospatial\",\"grid3\"]", 64800,
  "Polygon settlement extents for Angola (built-up areas classified as urban, small settlement or hamlet) with real geometry for map layers.");

VGEO(afr_grid3_grid3_bdi_settlement_extents_v3_0_grid3_bdi_0, "afr-grid3-grid3-bdi-settlement-extents-v3-0-grid3-bdi--0", "GRID3 — Burundi settlement extents", "GRID3 — Burundi settlement extents",
  "africa_gov", "opendata",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_BDI_Settlement_Extents_v3_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"bdi\",\"settlements\",\"geospatial\",\"grid3\"]", 86400,
  "Polygon settlement extents for Burundi (built-up areas classified as urban, small settlement or hamlet) with real geometry for map layers.");

VGEO(afr_grid3_grid3_ben_settlement_extents_v3_0_grid3_ben_0, "afr-grid3-grid3-ben-settlement-extents-v3-0-grid3-ben--0", "GRID3 — Benin settlement extents", "GRID3 — Benin settlement extents",
  "africa_gov", "opendata",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_BEN_Settlement_Extents_v3_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"ben\",\"settlements\",\"geospatial\",\"grid3\"]", 64800,
  "Polygon settlement extents for Benin (built-up areas classified as urban, small settlement or hamlet) with real geometry for map layers.");

VGEO(afr_grid3_grid3_bfa_preeas_v1_grid3_bfa_preeas_v1_0, "afr-grid3-grid3-bfa-preeas-v1-grid3-bfa-preeas-v1-0", "GRID3 — Burkina Faso pre-census enumeration areas", "GRID3 — Burkina Faso pre-census enumeration areas",
  "africa_gov", "gov",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_BFA_preEAs_v1/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"nga\",\"cod\",\"geospatial\",\"grid3\"]", 86400,
  "Pre-census enumeration-area polygons for Burkina Faso.");

VGEO(afr_grid3_grid3_bfa_settlement_extents_v3_0_grid3_bfa_0, "afr-grid3-grid3-bfa-settlement-extents-v3-0-grid3-bfa--0", "GRID3 — Burkina Faso settlement extents", "GRID3 — Burkina Faso settlement extents",
  "africa_gov", "opendata",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_BFA_Settlement_Extents_v3_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"bfa\",\"settlements\",\"geospatial\",\"grid3\"]", 86400,
  "Polygon settlement extents for Burkina Faso (built-up areas classified as urban, small settlement or hamlet) with real geometry for map layers.");

VGEO(afr_grid3_grid3_bwa_settlement_extents_v3_0_grid3_bwa_0, "afr-grid3-grid3-bwa-settlement-extents-v3-0-grid3-bwa--0", "GRID3 — Botswana settlement extents", "GRID3 — Botswana settlement extents",
  "africa_gov", "opendata",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_BWA_Settlement_Extents_v3_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"bwa\",\"settlements\",\"geospatial\",\"grid3\"]", 64800,
  "Polygon settlement extents for Botswana (built-up areas classified as urban, small settlement or hamlet) with real geometry for map layers.");

VGEO(afr_grid3_grid3_caf_settlement_extents_v3_0_grid3_caf_0, "afr-grid3-grid3-caf-settlement-extents-v3-0-grid3-caf--0", "GRID3 — Central African Republic settlement extents", "GRID3 — Central African Republic settlement extents",
  "africa_gov", "opendata",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_CAF_Settlement_Extents_v3_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"caf\",\"settlements\",\"geospatial\",\"grid3\"]", 86400,
  "Polygon settlement extents for Central African Republic (built-up areas classified as urban, small settlement or hamlet) with real geometry for map layers.");

VGEO(afr_grid3_grid3_civ_settlement_extents_v3_0_grid3_civ_0, "afr-grid3-grid3-civ-settlement-extents-v3-0-grid3-civ--0", "GRID3 — Cote d'Ivoire settlement extents", "GRID3 — Cote d'Ivoire settlement extents",
  "africa_gov", "opendata",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_CIV_Settlement_Extents_v3_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"civ\",\"settlements\",\"geospatial\",\"grid3\"]", 64800,
  "Polygon settlement extents for Cote d'Ivoire (built-up areas classified as urban, small settlement or hamlet) with real geometry for map layers.");

VGEO(afr_grid3_grid3_cmr_settlement_extents_v3_0_grid3_cmr_0, "afr-grid3-grid3-cmr-settlement-extents-v3-0-grid3-cmr--0", "GRID3 — Cameroon settlement extents", "GRID3 — Cameroon settlement extents",
  "africa_gov", "opendata",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_CMR_Settlement_Extents_v3_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"cmr\",\"settlements\",\"geospatial\",\"grid3\"]", 86400,
  "Polygon settlement extents for Cameroon (built-up areas classified as urban, small settlement or hamlet) with real geometry for map layers.");

VGEO(afr_grid3_grid3_cod_religious_centers_v1_0_grid3_cod_r_0, "afr-grid3-grid3-cod-religious-centers-v1-0-grid3-cod-r-0", "GRID3 — DR Congo religious centres", "GRID3 — DR Congo religious centres",
  "africa_gov", "gov",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_COD_religious_centers_v1_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"nga\",\"cod\",\"geospatial\",\"grid3\"]", 43200,
  "Geolocated churches and religious centres in the Democratic Republic of the Congo.");

VGEO(afr_grid3_grid3_cod_roads_v1_0_main_grid3_cod_roads_v1_0, "afr-grid3-grid3-cod-roads-v1-0-main-grid3-cod-roads-v1-0", "GRID3 — DR Congo road network", "GRID3 — DR Congo road network",
  "africa_gov", "transport",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_COD_roads_v1_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"nga\",\"cod\",\"geospatial\",\"grid3\"]", 86400,
  "Road centrelines for the Democratic Republic of the Congo with surface and class attributes.");

VGEO(afr_grid3_grid3_cod_schools_v1_0_grid3_cod_schools_v1_0, "afr-grid3-grid3-cod-schools-v1-0-grid3-cod-schools-v1--0", "GRID3 — DR Congo schools", "GRID3 — DR Congo schools",
  "africa_gov", "gov",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_COD_schools_v1_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"nga\",\"cod\",\"geospatial\",\"grid3\"]", 43200,
  "Geolocated schools across the Democratic Republic of the Congo.");

VGEO(afr_grid3_grid3_cod_settlement_extents_v4_main_grid3_c_0, "afr-grid3-grid3-cod-settlement-extents-v4-main-grid3-c-0", "GRID3 — DR Congo settlement extents", "GRID3 — DR Congo settlement extents",
  "africa_gov", "opendata",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/grid3_cod_settlement_extents_v4/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"nga\",\"cod\",\"geospatial\",\"grid3\"]", 86400,
  "Settlement extent polygons for the Democratic Republic of the Congo.");

VGEO(afr_grid3_grid3_cog_settlement_extents_v3_0_grid3_cog_0, "afr-grid3-grid3-cog-settlement-extents-v3-0-grid3-cog--0", "GRID3 — Republic of the Congo settlement extents", "GRID3 — Republic of the Congo settlement extents",
  "africa_gov", "opendata",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_COG_Settlement_Extents_v3_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"cog\",\"settlements\",\"geospatial\",\"grid3\"]", 64800,
  "Polygon settlement extents for Republic of the Congo (built-up areas classified as urban, small settlement or hamlet) with real geometry for map layers.");

VGEO(afr_grid3_grid3_com_settlement_extents_v3_0_grid3_com_0, "afr-grid3-grid3-com-settlement-extents-v3-0-grid3-com--0", "GRID3 — Comoros settlement extents", "GRID3 — Comoros settlement extents",
  "africa_gov", "opendata",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_COM_Settlement_Extents_v3_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"com\",\"settlements\",\"geospatial\",\"grid3\"]", 86400,
  "Polygon settlement extents for Comoros (built-up areas classified as urban, small settlement or hamlet) with real geometry for map layers.");

VGEO(afr_grid3_grid3_cpv_settlement_extents_v3_0_grid3_cpv_0, "afr-grid3-grid3-cpv-settlement-extents-v3-0-grid3-cpv--0", "GRID3 — Cabo Verde settlement extents", "GRID3 — Cabo Verde settlement extents",
  "africa_gov", "opendata",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_CPV_Settlement_Extents_v3_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"cpv\",\"settlements\",\"geospatial\",\"grid3\"]", 64800,
  "Polygon settlement extents for Cabo Verde (built-up areas classified as urban, small settlement or hamlet) with real geometry for map layers.");

VGEO(afr_grid3_grid3_dji_settlement_extents_v3_0_grid3_dji_0, "afr-grid3-grid3-dji-settlement-extents-v3-0-grid3-dji--0", "GRID3 — Djibouti settlement extents", "GRID3 — Djibouti settlement extents",
  "africa_gov", "opendata",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_DJI_Settlement_Extents_v3_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"dji\",\"settlements\",\"geospatial\",\"grid3\"]", 86400,
  "Polygon settlement extents for Djibouti (built-up areas classified as urban, small settlement or hamlet) with real geometry for map layers.");

VGEO(afr_grid3_grid3_eri_settlement_extents_v3_0_grid3_eri_0, "afr-grid3-grid3-eri-settlement-extents-v3-0-grid3-eri--0", "GRID3 — Eritrea settlement extents", "GRID3 — Eritrea settlement extents",
  "africa_gov", "opendata",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_ERI_Settlement_Extents_v3_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"eri\",\"settlements\",\"geospatial\",\"grid3\"]", 64800,
  "Polygon settlement extents for Eritrea (built-up areas classified as urban, small settlement or hamlet) with real geometry for map layers.");

VGEO(afr_grid3_grid3_eth_settlement_extents_v3_0_grid3_eth_0, "afr-grid3-grid3-eth-settlement-extents-v3-0-grid3-eth--0", "GRID3 — Ethiopia settlement extents", "GRID3 — Ethiopia settlement extents",
  "africa_gov", "opendata",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_ETH_Settlement_Extents_v3_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"eth\",\"settlements\",\"geospatial\",\"grid3\"]", 86400,
  "Polygon settlement extents for Ethiopia (built-up areas classified as urban, small settlement or hamlet) with real geometry for map layers.");

VGEO(afr_grid3_grid3_gab_settlement_extents_v3_0_grid3_gab_0, "afr-grid3-grid3-gab-settlement-extents-v3-0-grid3-gab--0", "GRID3 — Gabon settlement extents", "GRID3 — Gabon settlement extents",
  "africa_gov", "opendata",
  "https://services3.arcgis.com/BU6Aadhn6tbBEdyk/arcgis/rest/services/GRID3_GAB_Settlement_Extents_v3_0/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultRecordCount=500&f=geojson",
  "en", "[\"gab\",\"settlements\",\"geospatial\",\"grid3\"]", 64800,
  "Polygon settlement extents for Gabon (built-up areas classified as urban, small settlement or hamlet) with real geometry for map layers.");
