/* Verified-live academic sources (11), part 7.
 * Every endpoint in this file returned 2xx and parsed to at
 * least one record at generation time; see
 * docs/verified-sources-manifest.tsv for the recorded proof.
 * Generated by collectors/gen_verified_sources.py — regenerate
 * rather than hand-editing. */
#include "_verified_macros.inc"

VRSS(sci_springer_j_translational_medicine, "sci-springer-j-translational-medicine", "Latest Results", "シュプリンガー：j translational medicine",
  "academic", "clinical",
  "https://link.springer.com/search.rss?facet-journal-id=12967",
  "en", "[\"springer\",\"journal\",\"j-translational-medicine\"]", 21600,
  "New articles matching j translational medicine from Springer.");

VRSS(sci_springer_pandemic_preparedness, "sci-springer-pandemic-preparedness", "Latest Results", "シュプリンガー：pandemic preparedness",
  "academic", "literature",
  "https://link.springer.com/search.rss?query=pandemic+preparedness&sortOrder=newestFirst",
  "en", "[\"springer\",\"journal\",\"pandemic-preparedness\"]", 21600,
  "New articles matching pandemic preparedness from Springer.");

VRSS(sci_springer_parasites_and_vectors, "sci-springer-parasites-and-vectors", "Latest Results", "シュプリンガー：parasites and vectors",
  "academic", "genomics",
  "https://link.springer.com/search.rss?facet-journal-id=13071",
  "en", "[\"springer\",\"journal\",\"parasites-and-vectors\"]", 21600,
  "New articles matching parasites and vectors from Springer.");

VRSS(sci_springer_perovskite, "sci-springer-perovskite", "Latest Results", "シュプリンガー：perovskite",
  "academic", "literature",
  "https://link.springer.com/search.rss?query=perovskite&sortOrder=newestFirst",
  "en", "[\"springer\",\"journal\",\"perovskite\"]", 21600,
  "New articles matching perovskite from Springer.");

VRSS(sci_springer_quantum_computing, "sci-springer-quantum-computing", "Latest Results", "シュプリンガー：quantum computing",
  "academic", "literature",
  "https://link.springer.com/search.rss?query=quantum+computing&sortOrder=newestFirst",
  "en", "[\"springer\",\"journal\",\"quantum-computing\"]", 21600,
  "New articles matching quantum computing from Springer.");

VRSS(sci_springer_semiconductor_lithography, "sci-springer-semiconductor-lithography", "Latest Results", "シュプリンガー：semiconductor lithography",
  "academic", "literature",
  "https://link.springer.com/search.rss?query=semiconductor+lithography&sortOrder=newestFirst",
  "en", "[\"springer\",\"journal\",\"semiconductor-lithography\"]", 21600,
  "New articles matching semiconductor lithography from Springer.");

VRSS(sci_springer_solid_state_battery, "sci-springer-solid-state-battery", "Latest Results", "シュプリンガー：solid state battery",
  "academic", "literature",
  "https://link.springer.com/search.rss?query=solid+state+battery&sortOrder=newestFirst",
  "en", "[\"springer\",\"journal\",\"solid-state-battery\"]", 21600,
  "New articles matching solid state battery from Springer.");

VRSS(sci_springer_synthetic_biology, "sci-springer-synthetic-biology", "Latest Results", "シュプリンガー：synthetic biology",
  "academic", "genomics",
  "https://link.springer.com/search.rss?query=synthetic+biology&sortOrder=newestFirst",
  "en", "[\"springer\",\"journal\",\"synthetic-biology\"]", 21600,
  "New articles matching synthetic biology from Springer.");

VRSS(sci_titech_events, "sci-titech-events", "Institute of Science Tokyo events", "東京科学大学 イベント",
  "academic", "policy",
  "https://www.titech.ac.jp/event/rss.xml",
  "ja", "[\"japan\",\"university\",\"events\"]", 86400,
  "Institute of Science Tokyo seminar and symposium listings.");

VRSS(sci_titech_news, "sci-titech-news", "Institute of Science Tokyo news", "東京科学大学（旧東工大）ニュース",
  "academic", "policy",
  "https://www.titech.ac.jp/news/rss.xml",
  "ja", "[\"japan\",\"university\",\"research\"]", 21600,
  "Institute of Science Tokyo research announcements.");

VRSS(sci_u_tokyo_press, "sci-u-tokyo-press", "University of Tokyo press releases", "東京大学 プレスリリース",
  "academic", "policy",
  "https://www.u-tokyo.ac.jp/focus/ja/press/feed.rdf",
  "ja", "[\"japan\",\"university\",\"research\"]", 21600,
  "University of Tokyo research press releases.");
