/* Verified-live security sources (10), part 3.
 * Every endpoint in this file returned 2xx and parsed to at
 * least one record at generation time; see
 * docs/verified-sources-manifest.tsv for the recorded proof.
 * Generated by collectors/gen_verified_sources.py — regenerate
 * rather than hand-editing. */
#include "_verified_macros.inc"

VRSS(cyb_tenable_cves, "cyb-tenable-cves", "Tenable CVE Feed", "Tenable CVE フィード",
  "security", "vulnerability",
  "https://www.tenable.com/cve/feeds?sort=newest",
  "en", "[\"tenable\",\"cve\",\"scanner\"]", 3600,
  "Newest CVEs as tracked and scored by Tenable research.");

VRSS(cyb_twcert_news, "cyb-twcert-news", "TWCERT/CC Security News", "台湾 TWCERT/CC 資安ニュース",
  "security", "advisory",
  "https://www.twcert.org.tw/tw/rss-104-1.xml",
  "zh", "[\"twcert\",\"taiwan\",\"news\"]", 7200,
  "TWCERT/CC security news and campaign warnings for Taiwan.");

VRSS(cyb_twcert_tvn, "cyb-twcert-tvn", "TWCERT/CC Taiwan Vulnerability Notes", "台湾 TWCERT/CC 脆弱性公告",
  "security", "vulnerability",
  "https://www.twcert.org.tw/tw/rss-132-1.xml",
  "zh", "[\"twcert\",\"taiwan\",\"tvn\",\"advisory\"]", 3600,
  "Taiwan Vulnerability Note advisories coordinated by TWCERT/CC.");

VRSS(cyb_twcert_tvn_en, "cyb-twcert-tvn-en", "TWCERT/CC Vulnerability Notes (English)", "台湾 TWCERT/CC 脆弱性公告（英語）",
  "security", "vulnerability",
  "https://www.twcert.org.tw/en/rss-128-2.xml",
  "en", "[\"twcert\",\"taiwan\",\"tvn\",\"advisory\"]", 3600,
  "English edition of Taiwan Vulnerability Note advisories.");

VJSON(cyb_ubuntu_cves_json, "cyb-ubuntu-cves-json", "Ubuntu Security CVE API", "Ubuntu セキュリティ CVE API",
  "security", "vulnerability",
  "https://ubuntu.com/security/cves.json",
  "cves",
  "en", "[\"ubuntu\",\"canonical\",\"cve\"]", 3600,
  "Canonical's structured CVE tracker with per-release fix status.");

VJSON(cyb_ubuntu_notices_json, "cyb-ubuntu-notices-json", "Ubuntu Security Notices API", "Ubuntu セキュリティ通知 API",
  "security", "advisory",
  "https://ubuntu.com/security/notices.json",
  "notices",
  "en", "[\"ubuntu\",\"usn\",\"canonical\"]", 3600,
  "Ubuntu Security Notices in JSON with affected packages and releases.");

VRSS(cyb_vulners_rss, "cyb-vulners-rss", "Vulners Aggregated Feed", "Vulners 統合フィード",
  "security", "vulnerability",
  "https://vulners.com/rss.xml",
  "en", "[\"vulners\",\"cve\",\"exploit\",\"aggregator\"]", 3600,
  "Vulners aggregation of vendor bulletins, CVEs and exploit references.");

VJSON(cyb_vulnrichment, "cyb-vulnrichment", "CISA Vulnrichment Commits", "CISA Vulnrichment コミット",
  "security", "vulnerability",
  "https://api.github.com/repos/cisagov/vulnrichment/commits?per_page=50",
  "",
  "en", "[\"cisa\",\"ssvc\",\"cvss\",\"enrichment\"]", 21600,
  "CISA enrichment of CVE records with SSVC decision points and CVSS.");

VJSON(cyb_wolfi_secdb, "cyb-wolfi-secdb", "Wolfi OS Security Database", "Wolfi OS セキュリティDB",
  "security", "vulnerability",
  "https://packages.wolfi.dev/os/security.json",
  "packages",
  "en", "[\"wolfi\",\"container\",\"secdb\",\"supplychain\"]", 21600,
  "Wolfi distroless OS security database of fixed vulnerabilities.");

VRSS(cyb_wordpress_news, "cyb-wordpress-news", "WordPress News and Releases", "WordPress ニュース・リリース",
  "security", "advisory",
  "https://wordpress.org/news/feed/",
  "en", "[\"wordpress\",\"cms\",\"release\"]", 21600,
  "WordPress core release announcements including security releases.");
