/* Verified-live seasia_gov sources (4), part 2.
 * Every endpoint in this file returned 2xx and parsed to at
 * least one record at generation time; see
 * docs/verified-sources-manifest.tsv for the recorded proof.
 * Generated by collectors/gen_verified_sources.py — regenerate
 * rather than hand-editing. */
#include "_verified_macros.inc"

VRSS(sas_th_matichon, "sas-th-matichon", "Matichon — Thailand news", "Matichon — Thailand news",
  "seasia_gov", "news",
  "https://www.matichon.co.th/feed",
  "th", "[\"tha\",\"news\"]", 3600,
  "Publisher-own news feed; headline, link and timestamp for each item.");

VRSS(sas_th_thairath, "sas-th-thairath", "Thairath — Thailand news", "Thairath — Thailand news",
  "seasia_gov", "news",
  "https://www.thairath.co.th/rss/news",
  "th", "[\"tha\",\"news\"]", 3600,
  "Publisher-own news feed; headline, link and timestamp for each item.");

VRSS(sas_vn_rfa, "sas-vn-rfa", "RFA Vietnamese — Vietnam coverage", "RFA Vietnamese — Vietnam coverage",
  "seasia_gov", "news",
  "https://www.rfa.org/vietnamese/rss2.xml",
  "vi", "[\"vnm\",\"news\",\"rights\"]", 3600,
  "Publisher-own news feed; headline, link and timestamp for each item.");

VJSON(sas_wp_tatoli, "sas-wp-tatoli", "Tatoli — Timor-Leste state news agency", "Tatoli — Timor-Leste state news agency",
  "seasia_gov", "news",
  "https://tatoli.tl/wp-json/wp/v2/posts?per_page=50",
  "",
  "en", "[\"tls\",\"news\",\"wire\"]", 3600,
  "Publisher-own news feed; headline, link and timestamp for each item.");
