#!/usr/bin/env python3
"""tests/unit/fixtures/gen_xlsx_fixture.py — build the workbook test_xlsx.c
reads, and emit it as a C byte array.

The workbook is written by hand (zipfile + literal XML), not by openpyxl, so
the test controls EXACTLY which OOXML shapes are present: a rich-text shared
string with a phonetic <rPh> run, an inline string, a boolean, an error cell,
a formula-string cell, a row with only column C, a row number the sheet
skips, a value holding a comma and quotes, and a second sheet. Each of those
is one line of the CSV the test asserts on.

    python3 gen_xlsx_fixture.py xlsx_fixture.h

The header is checked in so `make unit` needs neither Python nor a fixture
file on disk; re-run this only when the fixture changes."""
import io
import sys
import zipfile

WORKBOOK = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
 xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
<sheets>
<sheet name="登録一覧" sheetId="1" r:id="rId1"/>
<sheet name="Memo" sheetId="2" r:id="rId2"/>
</sheets>
</workbook>"""

RELS = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/>
<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/>
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
</Relationships>"""

SHARED = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="5" uniqueCount="5">
<si><t>商号</t></si>
<si><t>登録番号</t></si>
<si><r><t>株式会社</t></r><r><rPr><b/></rPr><t>テスト</t></r><rPh sb="0" eb="4"><t>カブシキガイシャ</t></rPh><phoneticPr fontId="1"/></si>
<si><t>a, &quot;b&quot; &amp; c</t></si>
<si><t xml:space="preserve">Memo header</t></si>
</sst>"""

# Row 4 is absent on purpose; row 3 holds only C3; row 5 is the widest.
SHEET1 = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<dimension ref="A1:D5"/>
<sheetData>
<row r="1"><c r="A1" t="s"><v>0</v></c><c r="B1" t="s"><v>1</v></c><c r="C1" t="inlineStr"><is><t>備考</t></is></c></row>
<row r="2"><c r="A2" t="s"><v>2</v></c><c r="B2"><v>20240401</v></c><c r="C2" t="b"><v>1</v></c></row>
<row r="3"><c r="C3" t="s"><v>3</v></c></row>
<row r="5"><c r="A5" t="str"><f>CONCATENATE("x","y")</f><v>xy</v></c><c r="B5" t="e"><v>#N/A</v></c><c r="C5"/><c r="D5"><v>1.5E-3</v></c></row>
</sheetData>
<mergeCells count="1"><mergeCell ref="A3:B3"/></mergeCells>
</worksheet>"""

SHEET2 = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<sheetData>
<row r="1"><c r="A1" t="s"><v>4</v></c></row>
</sheetData>
</worksheet>"""


def workbook():
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml", "<Types/>")
        z.writestr("xl/workbook.xml", WORKBOOK)
        z.writestr("xl/_rels/workbook.xml.rels", RELS)
        z.writestr("xl/sharedStrings.xml", SHARED)
        z.writestr("xl/worksheets/sheet1.xml", SHEET1)
        z.writestr("xl/worksheets/sheet2.xml", SHEET2)
    return buf.getvalue()


def plain_zip():
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("hello.txt", "not a workbook\n")
    return buf.getvalue()


def c_array(name, data):
    lines = ["static const unsigned char %s[] = {" % name]
    for i in range(0, len(data), 16):
        lines.append("  " + ", ".join("0x%02x" % b for b in data[i:i + 16]) + ",")
    lines.append("};")
    lines.append("static const size_t %s_len = %d;" % (name, len(data)))
    return "\n".join(lines)


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "xlsx_fixture.h"
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* GENERATED by gen_xlsx_fixture.py — do not edit. */\n")
        f.write("#include <stddef.h>\n")
        f.write(c_array("FIXTURE_XLSX", workbook()) + "\n")
        f.write(c_array("FIXTURE_PLAIN_ZIP", plain_zip()) + "\n")


if __name__ == "__main__":
    main()
