/**
 * Central registry of all Japan OSINT data sources.
 * Each entry describes a source, its type, category, update cadence, and the
 * map layer it feeds.
 */

const sources = [
  // ── Weather / Seismic ────────────────────────────────────────────────
  {
    id: 'jma-earthquake',
    name: 'JMA Earthquake API',
    nameJa: '気象庁 地震情報',
    type: 'api',
    category: 'environment',
    url: 'https://www.jma.go.jp/bosai/quake/data/list.json',
    description: 'Real-time earthquake data from the Japan Meteorological Agency',
    updateInterval: 60,
    layer: 'earthquake',
    free: true,
    status: 'offline',
  },
  {
    id: 'jma-weather',
    name: 'JMA Weather Forecast',
    nameJa: '気象庁 天気予報',
    type: 'api',
    category: 'environment',
    url: 'https://www.jma.go.jp/bosai/forecast/',
    description: 'Weather forecast data for all prefectures',
    updateInterval: 3600,
    layer: 'weather',
    free: true,
    status: 'offline',
  },
  {
    id: 'jma-tsunami',
    name: 'JMA Tsunami Warnings',
    nameJa: '気象庁 津波情報',
    type: 'api',
    category: 'environment',
    url: 'https://www.jma.go.jp/bosai/tsunami/',
    description: 'Tsunami warning and advisory data',
    updateInterval: 60,
    layer: 'tsunami',
    free: true,
    status: 'offline',
  },
  {
    id: 'jma-volcano',
    name: 'JMA Volcanic Alerts',
    nameJa: '気象庁 火山情報',
    type: 'api',
    category: 'environment',
    url: 'https://www.jma.go.jp/bosai/volcano/',
    description: 'Volcanic activity alerts and warnings',
    updateInterval: 3600,
    layer: 'volcano',
    free: true,
    status: 'offline',
  },

  // ── Air / Radiation ──────────────────────────────────────────────────
  {
    id: 'soramame',
    name: 'SORAMAME Air Quality',
    nameJa: 'そらまめ君 大気汚染情報',
    type: 'api',
    category: 'environment',
    url: 'http://soramame.env.go.jp/',
    description: 'Hourly air quality monitoring station data (PM2.5, Ox, SO2, etc.)',
    updateInterval: 3600,
    layer: 'air-quality',
    free: true,
    status: 'offline',
  },
  {
    id: 'nra-radiation',
    name: 'NRA Radiation Monitoring',
    nameJa: '原子力規制委員会 放射線モニタリング',
    type: 'api',
    category: 'environment',
    url: 'https://radioactivity.nra.go.jp/',
    description: 'Real-time radiation dose monitoring across Japan (10-min intervals)',
    updateInterval: 600,
    layer: 'radiation',
    free: true,
    status: 'offline',
  },

  // ── Transport ────────────────────────────────────────────────────────
  {
    id: 'odpt-train',
    name: 'ODPT Train Real-time',
    nameJa: 'ODPT 鉄道リアルタイム',
    type: 'api',
    category: 'transport',
    url: 'https://api.odpt.org/api/v4/',
    description: 'Real-time train location and delay data in Tokyo metro area',
    updateInterval: 30,
    layer: 'transport',
    free: true,
    status: 'offline',
  },
  {
    id: 'odpt-bus',
    name: 'ODPT Bus Real-time',
    nameJa: 'ODPT バスリアルタイム',
    type: 'api',
    category: 'transport',
    url: 'https://api.odpt.org/api/v4/',
    description: 'Real-time bus location data',
    updateInterval: 30,
    layer: 'transport',
    free: true,
    status: 'offline',
  },
  {
    id: 'odpt-station',
    name: 'ODPT Station Data',
    nameJa: 'ODPT 駅データ',
    type: 'api',
    category: 'transport',
    url: 'https://api.odpt.org/api/v4/',
    description: 'Static station location and metadata',
    updateInterval: 86400,
    layer: 'transport',
    free: true,
    status: 'offline',
  },
  {
    id: 'navitime',
    name: 'Navitime Transit',
    nameJa: 'ナビタイム 交通情報',
    type: 'web_request',
    category: 'transport',
    url: 'https://www.navitime.co.jp/',
    description: 'Transit and route information (placeholder)',
    updateInterval: 300,
    layer: 'transport',
    free: false,
    status: 'offline',
  },

  // ── Geospatial ───────────────────────────────────────────────────────
  {
    id: 'plateau-buildings',
    name: 'PLATEAU 3D Buildings',
    nameJa: 'PLATEAU 3D都市モデル',
    type: 'dataset',
    category: 'geospatial',
    url: 'https://www.geospatial.jp/ckan/dataset/plateau',
    description: 'MLIT PLATEAU 3D city model building data',
    updateInterval: 604800,
    layer: 'buildings',
    free: true,
    status: 'offline',
  },
  {
    id: 'gsi-tiles',
    name: 'GSI Map Tiles',
    nameJa: '国土地理院 地図タイル',
    type: 'api',
    category: 'geospatial',
    url: 'https://cyberjapandata.gsi.go.jp/',
    description: 'Geospatial Information Authority base map tiles',
    updateInterval: 86400,
    layer: 'basemap',
    free: true,
    status: 'offline',
  },
  {
    id: 'gsi-elevation',
    name: 'GSI Elevation',
    nameJa: '国土地理院 標高データ',
    type: 'api',
    category: 'geospatial',
    url: 'https://cyberjapandata.gsi.go.jp/',
    description: 'Digital elevation model tiles',
    updateInterval: 86400,
    layer: 'elevation',
    free: true,
    status: 'offline',
  },
  {
    id: 'nlni-landuse',
    name: 'National Land Numerical Info',
    nameJa: '国土数値情報 土地利用',
    type: 'dataset',
    category: 'geospatial',
    url: 'https://nlftp.mlit.go.jp/ksj/',
    description: 'Land use mesh data from MLIT',
    updateInterval: 604800,
    layer: 'landuse',
    free: true,
    status: 'offline',
  },

  // ── Population / Statistics ──────────────────────────────────────────
  {
    id: 'estat-population',
    name: 'e-Stat Population Mesh',
    nameJa: 'e-Stat 人口メッシュ',
    type: 'api',
    category: 'statistics',
    url: 'https://api.e-stat.go.jp/',
    description: 'Grid-square population statistics',
    updateInterval: 86400,
    layer: 'population',
    free: true,
    status: 'offline',
  },

  // ── Real Estate / Prices ─────────────────────────────────────────────
  {
    id: 'mlit-landprice',
    name: 'MLIT Land Price Survey',
    nameJa: '国交省 地価公示',
    type: 'api',
    category: 'economy',
    url: 'https://www.land.mlit.go.jp/webland/api/',
    description: 'Official land price survey data',
    updateInterval: 86400,
    layer: 'landprice',
    free: true,
    status: 'offline',
  },
  {
    id: 'reinfolib',
    name: 'Real Estate Transaction Prices',
    nameJa: '不動産取引価格情報',
    type: 'api',
    category: 'economy',
    url: 'https://www.reinfolib.mlit.go.jp/',
    description: 'Actual real estate transaction price data',
    updateInterval: 86400,
    layer: 'landprice',
    free: true,
    status: 'offline',
  },
  {
    id: 'suumo',
    name: 'Suumo Rental Prices',
    nameJa: 'SUUMO 賃料情報',
    type: 'scraped',
    category: 'economy',
    url: 'https://suumo.jp/',
    description: 'Scraped rental price listings',
    updateInterval: 86400,
    layer: 'landprice',
    free: true,
    status: 'offline',
  },

  // ── Safety / Emergency ───────────────────────────────────────────────
  {
    id: 'police-incidents',
    name: 'Prefectural Police Crime Maps',
    nameJa: '都道府県警 犯罪発生マップ',
    type: 'scraped',
    category: 'safety',
    url: 'https://www.keishicho.metro.tokyo.lg.jp/jiken_jiko/hassei/index.html',
    description: 'Crime incident reports from prefectural police',
    updateInterval: 86400,
    layer: 'crime',
    free: true,
    status: 'offline',
  },
  {
    id: 'fire-department',
    name: 'Fire Department Dispatches',
    nameJa: '消防庁 出動情報',
    type: 'web_request',
    category: 'safety',
    url: 'https://www.fdma.go.jp/',
    description: 'Fire department emergency dispatch data',
    updateInterval: 300,
    layer: 'emergency',
    free: true,
    status: 'offline',
  },
  {
    id: 'jma-warnings',
    name: 'JMA Weather Warnings',
    nameJa: '気象庁 気象警報',
    type: 'api',
    category: 'safety',
    url: 'https://www.jma.go.jp/bosai/warning/',
    description: 'Weather warnings and advisories by region',
    updateInterval: 300,
    layer: 'warnings',
    free: true,
    status: 'offline',
  },

  // ── Infrastructure / IoT ─────────────────────────────────────────────
  {
    id: 'mlit-river',
    name: 'MLIT River Water Levels',
    nameJa: '国交省 河川水位情報',
    type: 'api',
    category: 'infrastructure',
    url: 'https://www.river.go.jp/',
    description: 'Real-time river water level monitoring (10-min)',
    updateInterval: 600,
    layer: 'river',
    free: true,
    status: 'offline',
  },
  {
    id: 'xrain-radar',
    name: 'XRAIN Rain Radar',
    nameJa: 'XRAIN 高解像度降雨レーダー',
    type: 'api',
    category: 'infrastructure',
    url: 'https://www.river.go.jp/x/',
    description: 'High-resolution rain radar imagery (1-min)',
    updateInterval: 60,
    layer: 'radar',
    free: true,
    status: 'offline',
  },
  {
    id: 'traffic-cameras',
    name: 'Road Traffic Cameras (JARTIC)',
    nameJa: 'JARTIC 道路交通カメラ',
    type: 'web_request',
    category: 'infrastructure',
    url: 'https://www.jartic.or.jp/',
    description: 'Live road traffic camera feeds',
    updateInterval: 300,
    layer: 'cameras',
    free: true,
    status: 'offline',
  },
  {
    id: 'public-webcams',
    name: 'Public Webcams / Livecams',
    nameJa: '公開ウェブカメラ',
    type: 'scraped',
    category: 'infrastructure',
    url: 'https://livecam.asia/',
    description: 'Aggregated public webcam and livecam feeds across Japan',
    updateInterval: 3600,
    layer: 'cameras',
    free: true,
    status: 'offline',
  },

  // ── Communications / Cyber ───────────────────────────────────────────
  {
    id: 'shodan-japan',
    name: 'Shodan Japan IoT Devices',
    nameJa: 'Shodan 日本IoTデバイス',
    type: 'api',
    category: 'cyber',
    url: 'https://api.shodan.io/',
    description: 'Internet-connected devices in Japan via Shodan',
    updateInterval: 86400,
    layer: 'cyber',
    free: false,
    status: 'offline',
  },
  {
    id: 'censys-japan',
    name: 'Censys Japan Scan Data',
    nameJa: 'Censys 日本スキャンデータ',
    type: 'api',
    category: 'cyber',
    url: 'https://search.censys.io/api/',
    description: 'Host and certificate scan data for Japanese IP ranges',
    updateInterval: 86400,
    layer: 'cyber',
    free: false,
    status: 'offline',
  },
  {
    id: 'insecam-japan',
    name: 'Insecam Public Cameras',
    nameJa: 'Insecam 公開カメラ',
    type: 'scraped',
    category: 'cyber',
    url: 'http://www.insecam.org/en/bycountry/JP/',
    description: 'Publicly accessible IP cameras in Japan',
    updateInterval: 86400,
    layer: 'cameras',
    free: true,
    status: 'offline',
  },

  // ── Social / Media ───────────────────────────────────────────────────
  {
    id: 'twitter-geo',
    name: 'Twitter/X Geotagged Posts',
    nameJa: 'Twitter/X ジオタグ投稿',
    type: 'api',
    category: 'social',
    url: 'https://api.twitter.com/2/',
    description: 'Geotagged tweets from Japan',
    updateInterval: 300,
    layer: 'social',
    free: false,
    status: 'offline',
  },
  {
    id: 'flickr-geo',
    name: 'Flickr Geotagged Photos',
    nameJa: 'Flickr ジオタグ写真',
    type: 'api',
    category: 'social',
    url: 'https://api.flickr.com/services/rest/',
    description: 'Geotagged photos from Flickr in Japan',
    updateInterval: 3600,
    layer: 'social',
    free: true,
    status: 'offline',
  },
  {
    id: 'youtube-live',
    name: 'YouTube Live Streams Japan',
    nameJa: 'YouTube ライブ配信 日本',
    type: 'api',
    category: 'social',
    url: 'https://www.googleapis.com/youtube/v3/',
    description: 'Live streaming videos geolocated in Japan',
    updateInterval: 600,
    layer: 'social',
    free: false,
    status: 'offline',
  },

  // ── Satellite ────────────────────────────────────────────────────────
  {
    id: 'tellus-satellite',
    name: 'Tellus Satellite Imagery',
    nameJa: 'Tellus 衛星画像',
    type: 'api',
    category: 'satellite',
    url: 'https://www.tellusxdp.com/',
    description: 'Japanese satellite imagery platform',
    updateInterval: 86400,
    layer: 'satellite',
    free: true,
    status: 'offline',
  },
  {
    id: 'sentinel-japan',
    name: 'Sentinel Hub Japan',
    nameJa: 'Sentinel Hub 日本',
    type: 'api',
    category: 'satellite',
    url: 'https://services.sentinel-hub.com/',
    description: 'Copernicus Sentinel satellite imagery over Japan',
    updateInterval: 86400,
    layer: 'satellite',
    free: true,
    status: 'offline',
  },

  // ── Commercial ──────────────────────────────────────────────────────
  {
    id: 'docomo-population',
    name: 'NTT Docomo Population Stats',
    nameJa: 'NTTドコモ モバイル空間統計',
    type: 'api',
    category: 'commercial',
    url: 'https://mobaku.jp/',
    description: 'Mobile spatial statistics from NTT Docomo (paid)',
    updateInterval: 3600,
    layer: 'population',
    free: false,
    status: 'offline',
  },
  {
    id: 'agoop-flow',
    name: 'Agoop People Flow',
    nameJa: 'Agoop 人流データ',
    type: 'api',
    category: 'commercial',
    url: 'https://www.agoop.co.jp/',
    description: 'People flow analytics data (paid)',
    updateInterval: 3600,
    layer: 'population',
    free: false,
    status: 'offline',
  },

  // ── Environment Extended ────────────────────────────────────────────
  { id: 'jma-amedas', name: 'JMA AMeDAS', nameJa: 'アメダス', type: 'api', category: 'environment', url: 'https://www.jma.go.jp/bosai/amedas/', description: 'Automated Meteorological Data Acquisition System stations', updateInterval: 600, layer: 'weather', free: true, status: 'offline' },
  { id: 'jma-himawari', name: 'JMA Himawari Satellite', nameJa: 'ひまわり衛星', type: 'api', category: 'environment', url: 'https://www.jma.go.jp/bosai/map.html', description: 'Himawari-9 geostationary satellite imagery', updateInterval: 600, layer: 'satellite', free: true, status: 'offline' },
  { id: 'jma-typhoon', name: 'JMA Typhoon Track', nameJa: '気象庁 台風情報', type: 'api', category: 'environment', url: 'https://www.jma.go.jp/bosai/map.html#contents=typhoon', description: 'Typhoon tracking and forecast paths', updateInterval: 3600, layer: 'weather', free: true, status: 'offline' },
  { id: 'jma-uv', name: 'JMA UV Index', nameJa: '気象庁 紫外線情報', type: 'api', category: 'environment', url: 'https://www.jma.go.jp/bosai/uv/', description: 'UV index forecast data', updateInterval: 3600, layer: 'weather', free: true, status: 'offline' },
  { id: 'jma-pollen', name: 'Pollen Forecast', nameJa: '環境省花粉情報', type: 'api', category: 'environment', url: 'https://kafun.env.go.jp/', description: 'Cedar and cypress pollen distribution forecast', updateInterval: 3600, layer: 'air-quality', free: true, status: 'offline' },
  { id: 'pm25-japan', name: 'PM2.5 Distribution', nameJa: 'PM2.5分布予測', type: 'api', category: 'environment', url: 'https://pm25.jp/', description: 'PM2.5 real-time distribution map', updateInterval: 3600, layer: 'air-quality', free: true, status: 'offline' },
  { id: 'windy-japan', name: 'Windy Japan', nameJa: 'Windy 日本', type: 'web_request', category: 'environment', url: 'https://www.windy.com/', description: 'Wind and weather visualization overlay', updateInterval: 1800, layer: 'weather', free: true, status: 'offline' },
  { id: 'tenki-jp', name: 'tenki.jp Weather', nameJa: 'tenki.jp 天気', type: 'scraped', category: 'environment', url: 'https://tenki.jp/', description: 'Detailed Japanese weather forecasts', updateInterval: 1800, layer: 'weather', free: true, status: 'offline' },

  // ── Seismic / Volcanic ──────────────────────────────────────────────
  { id: 'vnet', name: 'V-net Volcano Observation', nameJa: 'V-net 火山観測網', type: 'api', category: 'seismic', url: 'https://www.vnet.bosai.go.jp/', description: 'Fundamental Volcano Observation Network', updateInterval: 600, layer: 'volcano', free: true, status: 'offline' },
  { id: 'bosai-volcano-cam', name: 'NIED Volcano Cameras', nameJa: '防災科研 火山カメラ', type: 'web_request', category: 'seismic', url: 'https://www.vnet.bosai.go.jp/', description: 'Live volcano monitoring cameras', updateInterval: 300, layer: 'cameras', free: true, status: 'offline' },

  // ── Ocean / Marine ──────────────────────────────────────────────────
  { id: 'jamstec-argo', name: 'JAMSTEC Argo Floats', nameJa: 'JAMSTEC アルゴフロート', type: 'api', category: 'ocean', url: 'https://www.jamstec.go.jp/', description: 'Deep ocean profiling float data', updateInterval: 86400, layer: 'ocean', free: true, status: 'offline' },
  { id: 'jma-ice', name: 'JMA Sea Ice Okhotsk', nameJa: '気象庁 オホーツク海氷', type: 'api', category: 'ocean', url: 'https://www.jma.go.jp/bosai/ice/', description: 'Sea ice extent in Sea of Okhotsk', updateInterval: 86400, layer: 'ocean', free: true, status: 'offline' },

  // ── Transport Extended ──────────────────────────────────────────────
  { id: 'odpt-flight', name: 'ODPT Flight Data', nameJa: 'ODPT 航空データ', type: 'api', category: 'transport', url: 'https://api.odpt.org/api/v4/', description: 'Flight arrival/departure data', updateInterval: 300, layer: 'aviation', free: true, status: 'offline' },
  { id: 'flightradar-jp', name: 'FlightRadar24 Japan', nameJa: 'FlightRadar24 日本', type: 'scraped', category: 'transport', url: 'https://www.flightradar24.com/', description: 'Live aircraft positions over Japan', updateInterval: 60, layer: 'aviation', free: true, status: 'offline' },
  { id: 'marinetraffic-jp', name: 'MarineTraffic Japan', nameJa: 'MarineTraffic 日本', type: 'scraped', category: 'transport', url: 'https://www.marinetraffic.com/', description: 'Live vessel positions around Japan', updateInterval: 300, layer: 'maritime', free: true, status: 'offline' },
  { id: 'jr-east-delay', name: 'JR East Delay Info', nameJa: 'JR東日本 運行情報', type: 'web_request', category: 'transport', url: 'https://traininfo.jreast.co.jp/', description: 'JR East train delay and disruption info', updateInterval: 60, layer: 'transport', free: true, status: 'offline' },
  { id: 'jr-west-delay', name: 'JR West Delay Info', nameJa: 'JR西日本 運行情報', type: 'web_request', category: 'transport', url: 'https://trafficinfo.westjr.co.jp/', description: 'JR West train service status', updateInterval: 60, layer: 'transport', free: true, status: 'offline' },
  { id: 'jr-central-delay', name: 'JR Central Delay Info', nameJa: 'JR東海 運行情報', type: 'web_request', category: 'transport', url: 'https://traininfo.jr-central.co.jp/', description: 'JR Central / Shinkansen status', updateInterval: 60, layer: 'transport', free: true, status: 'offline' },
  { id: 'shinkansen-status', name: 'Shinkansen Line Status', nameJa: '新幹線 運行状況', type: 'web_request', category: 'transport', url: 'https://www.jreast.co.jp/shinkansen/', description: 'All Shinkansen lines operational status', updateInterval: 60, layer: 'transport', free: true, status: 'offline' },
  { id: 'cycling-ports', name: 'Bike Share Ports', nameJa: 'シェアサイクル ポート', type: 'api', category: 'transport', url: 'https://docomo-cycle.jp/', description: 'Docomo bike sharing port locations and availability', updateInterval: 3600, layer: 'transport', free: true, status: 'offline' },
  { id: 'mlit-road-traffic', name: 'MLIT Road Traffic Census', nameJa: '国交省 道路交通センサス', type: 'dataset', category: 'transport', url: 'https://www.mlit.go.jp/road/', description: 'Road traffic volume census data', updateInterval: 604800, layer: 'transport', free: true, status: 'offline' },

  // ── Geospatial Extended ─────────────────────────────────────────────
  { id: 'plateau-tokyo23', name: 'PLATEAU Tokyo 23 Wards', nameJa: 'PLATEAU 東京23区', type: 'dataset', category: 'geospatial', url: 'https://www.geospatial.jp/ckan/dataset/plateau-tokyo23ku', description: 'PLATEAU 3D model for all 23 Tokyo wards', updateInterval: 604800, layer: 'buildings', free: true, status: 'offline' },
  { id: 'plateau-osaka', name: 'PLATEAU Osaka', nameJa: 'PLATEAU 大阪市', type: 'dataset', category: 'geospatial', url: 'https://www.geospatial.jp/ckan/dataset/plateau-osaka', description: 'PLATEAU 3D city model for Osaka', updateInterval: 604800, layer: 'buildings', free: true, status: 'offline' },
  { id: 'gsi-photo', name: 'GSI Aerial Photography', nameJa: '国土地理院 空中写真', type: 'api', category: 'geospatial', url: 'https://cyberjapandata.gsi.go.jp/', description: 'Aerial photography tiles from GSI', updateInterval: 86400, layer: 'basemap', free: true, status: 'offline' },
  { id: 'gsi-hazard', name: 'GSI Hazard Maps', nameJa: '国土地理院 ハザードマップ', type: 'api', category: 'geospatial', url: 'https://disaportal.gsi.go.jp/', description: 'Flood/landslide/tsunami hazard map overlays', updateInterval: 86400, layer: 'hazard', free: true, status: 'offline' },
  { id: 'gsi-active-fault', name: 'GSI Active Fault Map', nameJa: '国土地理院 活断層図', type: 'dataset', category: 'geospatial', url: 'https://www.gsi.go.jp/bousaichiri/active_fault.html', description: 'Active fault line locations', updateInterval: 604800, layer: 'hazard', free: true, status: 'offline' },
  { id: 'openstreetmap-jp', name: 'OpenStreetMap Japan', nameJa: 'OpenStreetMap 日本', type: 'dataset', category: 'geospatial', url: 'https://download.geofabrik.de/asia/japan.html', description: 'OpenStreetMap Japan data extract', updateInterval: 604800, layer: 'basemap', free: true, status: 'online' },
  { id: 'parking-facilities', name: 'OSM Parking Facilities', nameJa: 'OSM 駐車場', type: 'api', category: 'geospatial', url: 'https://overpass-api.de/', description: 'amenity=parking / parking_entrance via Overpass', updateInterval: 86400, layer: 'poi', free: true, status: 'online' },
  { id: 'water-towers', name: 'OSM Water Towers', nameJa: 'OSM 給水塔', type: 'api', category: 'infrastructure', url: 'https://overpass-api.de/', description: 'man_made=water_tower / water_works via Overpass', updateInterval: 604800, layer: 'infrastructure', free: true, status: 'online' },
  { id: 'transmission-towers', name: 'OSM Transmission Towers', nameJa: 'OSM 送電鉄塔', type: 'api', category: 'infrastructure', url: 'https://overpass-api.de/', description: 'power=tower / tower:type=transmission via Overpass', updateInterval: 604800, layer: 'energy', free: true, status: 'online' },
  { id: 'utility-poles', name: 'OSM Utility Poles', nameJa: 'OSM 電柱', type: 'api', category: 'infrastructure', url: 'https://overpass-api.de/', description: 'man_made=utility_pole via Overpass', updateInterval: 604800, layer: 'telecom', free: true, status: 'online' },
  { id: 'admin-boundaries', name: 'OSM Administrative Boundaries', nameJa: 'OSM 行政境界', type: 'api', category: 'geospatial', url: 'https://overpass-api.de/', description: 'boundary=administrative (prefecture/municipality) via Overpass', updateInterval: 604800, layer: 'basemap', free: true, status: 'online' },
  { id: 'zenrin-map', name: 'Zenrin Detailed Maps', nameJa: 'ゼンリン 住宅地図', type: 'api', category: 'geospatial', url: 'https://www.zenrin.co.jp/', description: 'High-detail Zenrin building-level maps', updateInterval: 86400, layer: 'basemap', free: false, status: 'offline' },

  // ── Statistics Extended ─────────────────────────────────────────────
  { id: 'estat-household', name: 'e-Stat Household Data', nameJa: 'e-Stat 世帯データ', type: 'api', category: 'statistics', url: 'https://api.e-stat.go.jp/', description: 'Household composition statistics', updateInterval: 86400, layer: 'population', free: true, status: 'offline' },
  { id: 'estat-employment', name: 'e-Stat Employment', nameJa: 'e-Stat 雇用統計', type: 'api', category: 'statistics', url: 'https://api.e-stat.go.jp/', description: 'Employment and labor statistics', updateInterval: 86400, layer: 'economy', free: true, status: 'offline' },
  { id: 'estat-industry', name: 'e-Stat Industry Data', nameJa: 'e-Stat 産業統計', type: 'api', category: 'statistics', url: 'https://api.e-stat.go.jp/', description: 'Industrial production statistics by region', updateInterval: 86400, layer: 'economy', free: true, status: 'offline' },
  { id: 'jstat-map', name: 'jSTAT MAP Grid Stats', nameJa: 'jSTAT MAP 統計地図', type: 'api', category: 'statistics', url: 'https://jstatmap.e-stat.go.jp/', description: 'Grid-square based statistical mapping', updateInterval: 86400, layer: 'population', free: true, status: 'offline' },
  { id: 'mhlw-health', name: 'MHLW Health Statistics', nameJa: '厚労省 保健統計', type: 'dataset', category: 'statistics', url: 'https://www.mhlw.go.jp/toukei/', description: 'Ministry of Health health statistics', updateInterval: 604800, layer: 'health', free: true, status: 'offline' },
  { id: 'mhlw-covid', name: 'MHLW COVID-19 Data', nameJa: '厚労省 COVID-19データ', type: 'api', category: 'statistics', url: 'https://www.mhlw.go.jp/stf/covid-19/', description: 'COVID-19 case and vaccination data', updateInterval: 3600, layer: 'health', free: true, status: 'offline' },

  // ── Economy Extended ────────────────────────────────────────────────
  { id: 'homes-co', name: 'Homes.co.jp Rentals', nameJa: 'HOME\'S 賃貸情報', type: 'scraped', category: 'economy', url: 'https://www.homes.co.jp/', description: 'Rental property listings and prices', updateInterval: 86400, layer: 'landprice', free: true, status: 'offline' },
  { id: 'athome-price', name: 'At Home Real Estate', nameJa: 'アットホーム 不動産', type: 'scraped', category: 'economy', url: 'https://www.athome.co.jp/', description: 'Real estate listing prices', updateInterval: 86400, layer: 'landprice', free: true, status: 'offline' },

  // ── Safety / Disaster Extended ──────────────────────────────────────
  { id: 'saigai-info', name: 'Cabinet Office Disaster', nameJa: '内閣府 災害情報', type: 'api', category: 'safety', url: 'https://www.bousai.go.jp/', description: 'Cabinet Office disaster information system', updateInterval: 300, layer: 'emergency', free: true, status: 'offline' },

  // ── Infrastructure Extended ─────────────────────────────────────────
  { id: 'mlit-dam', name: 'MLIT Dam Data', nameJa: '国交省 ダム情報', type: 'api', category: 'infrastructure', url: 'https://www.river.go.jp/', description: 'Dam operational data and water storage', updateInterval: 600, layer: 'river', free: true, status: 'offline' },
  { id: 'tepco-power', name: 'TEPCO Power Usage', nameJa: '東京電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.tepco.co.jp/', description: 'Tokyo Electric Power usage and capacity', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'kepco-power', name: 'KEPCO Power Usage', nameJa: '関西電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.kepco.co.jp/', description: 'Kansai Electric Power usage data', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'chubu-power', name: 'Chubu Electric Power', nameJa: '中部電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.chuden.co.jp/', description: 'Chubu Electric Power usage', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'tohoku-power', name: 'Tohoku Electric Power', nameJa: '東北電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.tohoku-epco.co.jp/', description: 'Tohoku Electric Power usage', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'cell-tower-jp', name: 'Cell Tower Locations', nameJa: '携帯基地局', type: 'dataset', category: 'infrastructure', url: 'https://www.tele.soumu.go.jp/', description: 'Cell tower and base station locations', updateInterval: 604800, layer: 'telecom', free: true, status: 'offline' },
  { id: 'ev-charging', name: 'EV Charging Stations', nameJa: 'EV充電スタンド', type: 'api', category: 'infrastructure', url: 'https://ev.gogo.gs/', description: 'Electric vehicle charging station map', updateInterval: 86400, layer: 'poi', free: true, status: 'offline' },
  { id: 'wifi-hotspot', name: 'Free WiFi Hotspots', nameJa: 'フリーWiFiスポット', type: 'dataset', category: 'infrastructure', url: 'https://flets.com/freewifi/', description: 'Free WiFi hotspot locations across Japan', updateInterval: 604800, layer: 'telecom', free: true, status: 'offline' },

  // ── Cyber / IoT Extended ────────────────────────────────────────────
  { id: 'nicter-darknet', name: 'NICTER Darknet Monitor', nameJa: 'NICTER ダークネット観測', type: 'web_request', category: 'cyber', url: 'https://www.nicter.jp/', description: 'NICT darknet traffic monitoring', updateInterval: 3600, layer: 'cyber', free: true, status: 'offline' },
  { id: 'jpcert-alerts', name: 'JPCERT/CC Alerts', nameJa: 'JPCERT/CC 注意喚起', type: 'api', category: 'cyber', url: 'https://www.jpcert.or.jp/', description: 'JPCERT Coordination Center security alerts', updateInterval: 3600, layer: 'cyber', free: true, status: 'offline' },
  { id: 'ipa-vuln', name: 'IPA Vulnerability DB', nameJa: 'IPA 脆弱性対策情報', type: 'api', category: 'cyber', url: 'https://jvndb.jvn.jp/', description: 'IPA/JVN vulnerability database', updateInterval: 86400, layer: 'cyber', free: true, status: 'offline' },
  { id: 'atlas-jp', name: 'RIPE Atlas Japan Probes', nameJa: 'RIPE Atlas 日本プローブ', type: 'api', category: 'cyber', url: 'https://atlas.ripe.net/', description: 'RIPE Atlas internet measurement probes in Japan', updateInterval: 3600, layer: 'cyber', free: true, status: 'offline' },

  // ── Social / Culture Extended ───────────────────────────────────────
  { id: 'instagram-geo', name: 'Instagram Geotagged', nameJa: 'Instagram ジオタグ', type: 'scraped', category: 'social', url: 'https://www.instagram.com/', description: 'Geotagged Instagram posts from Japan', updateInterval: 600, layer: 'social', free: false, status: 'offline' },
  { id: 'tiktok-geo', name: 'TikTok Geotagged', nameJa: 'TikTok ジオタグ', type: 'scraped', category: 'social', url: 'https://www.tiktok.com/', description: 'Geotagged TikTok content from Japan', updateInterval: 600, layer: 'social', free: false, status: 'offline' },
  { id: 'google-trends-jp', name: 'Google Trends Japan', nameJa: 'Googleトレンド 日本', type: 'web_request', category: 'social', url: 'https://trends.google.co.jp/', description: 'Trending search topics by region in Japan', updateInterval: 3600, layer: 'social', free: true, status: 'offline' },
  { id: 'yahoo-realtime', name: 'Yahoo! Japan Realtime', nameJa: 'Yahoo!リアルタイム検索', type: 'scraped', category: 'social', url: 'https://search.yahoo.co.jp/realtime', description: 'Yahoo! Japan real-time trending topics', updateInterval: 300, layer: 'social', free: true, status: 'offline' },
  { id: '5ch-activity', name: '5ch Board Activity', nameJa: '5ちゃんねる 掲示板', type: 'scraped', category: 'social', url: 'https://5ch.net/', description: '5ch/2ch anonymous board activity metrics', updateInterval: 600, layer: 'social', free: true, status: 'offline' },
  { id: 'matsuri-events', name: 'Festival Calendar', nameJa: '祭り・イベント情報', type: 'scraped', category: 'social', url: 'https://www.walkerplus.com/festival/', description: 'Japanese festival and event calendar with locations', updateInterval: 86400, layer: 'events', free: true, status: 'offline' },
  { id: 'shrine-temple', name: 'Shrine & Temple Map', nameJa: '神社仏閣マップ', type: 'dataset', category: 'social', url: 'https://www.jinja.or.jp/', description: 'Shinto shrine and Buddhist temple locations', updateInterval: 604800, layer: 'poi', free: true, status: 'offline' },
  { id: 'onsen-map', name: 'Hot Spring Map', nameJa: '温泉マップ', type: 'dataset', category: 'social', url: 'https://www.onsen-r.co.jp/', description: 'Onsen (hot spring) locations across Japan', updateInterval: 604800, layer: 'poi', free: true, status: 'offline' },

  // ── Satellite Extended ──────────────────────────────────────────────
  { id: 'alos-palsar', name: 'ALOS/PALSAR SAR', nameJa: 'ALOS/PALSAR 合成開口レーダー', type: 'api', category: 'satellite', url: 'https://www.eorc.jaxa.jp/ALOS/', description: 'JAXA ALOS synthetic aperture radar data', updateInterval: 604800, layer: 'satellite', free: true, status: 'offline' },
  { id: 'himawari-realtime', name: 'Himawari-9 Realtime', nameJa: 'ひまわり9号 リアルタイム', type: 'api', category: 'satellite', url: 'https://www.data.jma.go.jp/mscweb/data/himawari/', description: 'Himawari-9 real-time satellite imagery', updateInterval: 600, layer: 'satellite', free: true, status: 'offline' },
  { id: 'jaxa-earth', name: 'JAXA Earth Observation', nameJa: 'JAXA 地球観測', type: 'api', category: 'satellite', url: 'https://earth.jaxa.jp/', description: 'JAXA Earth observation satellite data portal', updateInterval: 86400, layer: 'satellite', free: true, status: 'offline' },
  { id: 'landsat-jp', name: 'Landsat Japan Coverage', nameJa: 'Landsat 日本域', type: 'api', category: 'satellite', url: 'https://earthexplorer.usgs.gov/', description: 'Landsat satellite imagery covering Japan', updateInterval: 604800, layer: 'satellite', free: true, status: 'offline' },

  // ── Commercial Extended ─────────────────────────────────────────────
  { id: 'docomo-insight', name: 'Docomo Insight', nameJa: 'ドコモ・インサイト', type: 'api', category: 'commercial', url: 'https://mobaku.jp/', description: 'NTT Docomo population flow insights', updateInterval: 3600, layer: 'population', free: false, status: 'offline' },
  { id: 'softbank-crowd', name: 'SoftBank Crowd Analytics', nameJa: 'ソフトバンク 混雑統計', type: 'api', category: 'commercial', url: 'https://www.softbank.jp/', description: 'SoftBank crowd density analytics', updateInterval: 3600, layer: 'population', free: false, status: 'offline' },
  { id: 'zenrin-address', name: 'Zenrin Address Data', nameJa: 'ゼンリン 住所データ', type: 'api', category: 'commercial', url: 'https://www.zenrin.co.jp/', description: 'Zenrin address-level geocoding data', updateInterval: 86400, layer: 'basemap', free: false, status: 'offline' },
  { id: 'navitime-api', name: 'Navitime API', nameJa: 'ナビタイム API', type: 'api', category: 'commercial', url: 'https://api-sdk.navitime.co.jp/', description: 'Navitime routing and transit API', updateInterval: 300, layer: 'transport', free: false, status: 'offline' },
  { id: 'here-japan', name: 'HERE Maps Japan', nameJa: 'HERE Maps 日本', type: 'api', category: 'commercial', url: 'https://developer.here.com/', description: 'HERE location platform Japan', updateInterval: 86400, layer: 'basemap', free: false, status: 'offline' },
  { id: 'yahoo-map-api', name: 'Yahoo! Japan Map API', nameJa: 'Yahoo!地図 API', type: 'api', category: 'commercial', url: 'https://map.yahoo.co.jp/', description: 'Yahoo! Japan Map and geocoding API', updateInterval: 86400, layer: 'basemap', free: true, status: 'offline' },

  // ── Health / Medical ────────────────────────────────────────────────
  { id: 'ndb-open', name: 'NDB Open Data', nameJa: 'NDB オープンデータ', type: 'dataset', category: 'health', url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000177182.html', description: 'National Database of health insurance claims open data', updateInterval: 604800, layer: 'health', free: true, status: 'offline' },
  { id: 'influenza-surveillance', name: 'NIID Influenza Watch', nameJa: '国立感染研 インフルエンザ', type: 'api', category: 'health', url: 'https://www.niid.go.jp/niid/ja/flu-map.html', description: 'NIID influenza surveillance by prefecture', updateInterval: 604800, layer: 'health', free: true, status: 'offline' },
  { id: 'food-poisoning', name: 'Food Poisoning Reports', nameJa: '食中毒情報', type: 'api', category: 'health', url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/', description: 'MHLW food poisoning incident reports', updateInterval: 604800, layer: 'health', free: true, status: 'offline' },
  { id: 'cancer-registry', name: 'Cancer Registry Stats', nameJa: 'がん登録統計', type: 'dataset', category: 'health', url: 'https://ganjoho.jp/', description: 'National cancer registry incidence data', updateInterval: 604800, layer: 'health', free: true, status: 'offline' },

  // ── Additional Infrastructure / Energy ──────────────────────────────
  { id: 'kyushu-power', name: 'Kyushu Electric Power', nameJa: '九州電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.kyuden.co.jp/', description: 'Kyushu Electric Power usage', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'hokkaido-power', name: 'Hokkaido Electric Power', nameJa: '北海道電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.hepco.co.jp/', description: 'Hokkaido Electric Power grid usage', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'shikoku-power', name: 'Shikoku Electric Power', nameJa: '四国電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.yonden.co.jp/', description: 'Shikoku Electric Power usage', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'hokuriku-power', name: 'Hokuriku Electric Power', nameJa: '北陸電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.rikuden.co.jp/', description: 'Hokuriku Electric Power usage', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'chugoku-power', name: 'Chugoku Electric Power', nameJa: '中国電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.energia.co.jp/', description: 'Chugoku Electric Power usage', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'okinawa-power', name: 'Okinawa Electric Power', nameJa: '沖縄電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.okiden.co.jp/', description: 'Okinawa Electric Power usage', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'ntt-fiber', name: 'NTT Fiber Coverage', nameJa: 'NTT光回線 エリア', type: 'web_request', category: 'infrastructure', url: 'https://flets.com/', description: 'NTT fiber optic coverage map', updateInterval: 604800, layer: 'telecom', free: true, status: 'offline' },
  { id: 'mlit-bridge', name: 'MLIT Bridge Inspection', nameJa: '国交省 橋梁点検', type: 'dataset', category: 'infrastructure', url: 'https://road-structures-map.mlit.go.jp/', description: 'Bridge condition inspection data', updateInterval: 604800, layer: 'infrastructure', free: true, status: 'offline' },

  // ── Additional Transport ────────────────────────────────────────────
  { id: 'vics-traffic', name: 'VICS Traffic Info', nameJa: 'VICS 道路交通情報', type: 'web_request', category: 'transport', url: 'https://www.vics.or.jp/', description: 'Vehicle Information Communication System traffic data', updateInterval: 300, layer: 'transport', free: true, status: 'offline' },
  { id: 'kansai-flights', name: 'Kansai Airport Flights', nameJa: '関西空港 フライト情報', type: 'web_request', category: 'transport', url: 'https://www.kansai-airport.or.jp/', description: 'Kansai International Airport flights', updateInterval: 300, layer: 'aviation', free: true, status: 'offline' },
  { id: 'ekitan-transfer', name: 'Ekitan Transfer Info', nameJa: '駅探 乗換情報', type: 'scraped', category: 'transport', url: 'https://ekitan.com/', description: 'Station transfer and route information', updateInterval: 3600, layer: 'transport', free: true, status: 'offline' },

  // ── Additional Statistics ───────────────────────────────────────────
  { id: 'estat-education', name: 'e-Stat Education Stats', nameJa: 'e-Stat 教育統計', type: 'api', category: 'statistics', url: 'https://api.e-stat.go.jp/', description: 'School enrollment and education data by region', updateInterval: 86400, layer: 'population', free: true, status: 'offline' },
  { id: 'resas-municipality', name: 'RESAS Municipal Comparison', nameJa: 'RESAS 自治体比較', type: 'api', category: 'statistics', url: 'https://opendata.resas-portal.go.jp/', description: 'Municipal-level economic/demographic comparison', updateInterval: 86400, layer: 'population', free: true, status: 'offline' },
  { id: 'covid19-japan', name: 'COVID-19 Japan Dashboard', nameJa: 'COVID-19 ダッシュボード', type: 'api', category: 'statistics', url: 'https://covid19.mhlw.go.jp/', description: 'COVID-19 Japan open data dashboard', updateInterval: 3600, layer: 'health', free: true, status: 'offline' },

  // ── Additional Economy ──────────────────────────────────────────────
  { id: 'lifull-homes', name: 'LIFULL HOME\'S', nameJa: 'LIFULL HOME\'S 物件', type: 'scraped', category: 'economy', url: 'https://www.homes.co.jp/', description: 'Real estate listings and price analysis', updateInterval: 86400, layer: 'landprice', free: true, status: 'offline' },
  { id: 'japan-reit', name: 'J-REIT Properties', nameJa: 'J-REIT 不動産', type: 'scraped', category: 'economy', url: 'https://www.japan-reit.com/', description: 'J-REIT investment property portfolio data', updateInterval: 86400, layer: 'landprice', free: true, status: 'offline' },
  { id: 'tochi-info', name: 'Tochi.info Land Use', nameJa: '土地情報 土地利用', type: 'api', category: 'economy', url: 'https://tochi.mlit.go.jp/', description: 'Land use and zoning information', updateInterval: 86400, layer: 'landprice', free: true, status: 'offline' },

  // ── Additional Social ───────────────────────────────────────────────
  { id: 'hatena-bookmark', name: 'Hatena Bookmark', nameJa: 'はてなブックマーク', type: 'scraped', category: 'social', url: 'https://b.hatena.ne.jp/', description: 'Hatena Bookmark trending topics', updateInterval: 3600, layer: 'social', free: true, status: 'offline' },

  // ── Additional Geospatial ───────────────────────────────────────────
  { id: 'chiriin-place', name: 'GSI Place Names', nameJa: '地理院 地名情報', type: 'api', category: 'geospatial', url: 'https://www.gsi.go.jp/', description: 'Official geographic place name database', updateInterval: 86400, layer: 'basemap', free: true, status: 'offline' },
  { id: 'gcom-w', name: 'GCOM-W Water Cycle', nameJa: 'GCOM-W 水循環', type: 'api', category: 'satellite', url: 'https://suzaku.eorc.jaxa.jp/GCOM_W/', description: 'GCOM-W satellite water cycle observation', updateInterval: 86400, layer: 'satellite', free: true, status: 'offline' },
  { id: 'bgp-japan', name: 'BGP Routing Japan', nameJa: 'BGPルーティング 日本', type: 'api', category: 'cyber', url: 'https://stat.ripe.net/', description: 'BGP routing data for Japanese ASNs', updateInterval: 86400, layer: 'cyber', free: true, status: 'offline' },
  { id: 'mapfan-api', name: 'MapFan API', nameJa: 'MapFan API', type: 'api', category: 'commercial', url: 'https://mapfan.com/', description: 'MapFan mapping and POI data', updateInterval: 86400, layer: 'basemap', free: false, status: 'offline' },

  // ── New: Social Media Geo (twitter/facebook/snapchat enhanced) ──────
  { id: 'twitter-geo', name: 'Twitter/X Geo Posts', nameJa: 'Twitter/X ジオ投稿', type: 'api', category: 'social', url: 'https://api.twitter.com/2/tweets/search/recent', description: 'Geocoded Twitter/X posts across Japan with engagement metrics', updateInterval: 600, layer: 'twitter-geo', free: false, status: 'online' },
  { id: 'facebook-geo', name: 'Facebook Check-ins', nameJa: 'Facebook チェックイン', type: 'api', category: 'social', url: 'https://graph.facebook.com/', description: 'Facebook check-ins and geotagged posts at landmarks across Japan', updateInterval: 1800, layer: 'facebook-geo', free: false, status: 'online' },
  { id: 'snapchat-heatmap', name: 'Snapchat Snap Map', nameJa: 'Snapchat スナップマップ', type: 'scraped', category: 'social', url: 'https://map.snapchat.com/', description: 'Snapchat Snap Map activity heatmap (youth activity zones)', updateInterval: 600, layer: 'snapchat-heatmap', free: false, status: 'online' },

  // ── New: Marketplace / Classifieds ──────────────────────────────────
  { id: 'classifieds', name: 'Jmty / Mercari / Yahoo Auctions', nameJa: 'ジモティー・メルカリ・ヤフオク', type: 'scraped', category: 'marketplace', url: 'https://jmty.jp/', description: 'Classifieds listings (free items, barter, jobs, trades) across Japan', updateInterval: 1800, layer: 'classifieds', free: true, status: 'online' },
  { id: 'real-estate', name: 'Suumo / Homes / AtHome', nameJa: 'スーモ・ホームズ・アットホーム', type: 'scraped', category: 'marketplace', url: 'https://suumo.jp/', description: 'Real estate listings (rent / sale) across Japan', updateInterval: 3600, layer: 'real-estate', free: true, status: 'online' },
  { id: 'job-boards', name: 'TownWork / Baitoru / Indeed', nameJa: 'タウンワーク・バイトル・Indeed', type: 'scraped', category: 'marketplace', url: 'https://townwork.net/', description: 'Job listings (part-time / full-time) across Japan', updateInterval: 3600, layer: 'job-boards', free: true, status: 'online' },

  // ── New: Cyber OSINT ────────────────────────────────────────────────
  { id: 'google-dorking', name: 'Google Dorking Results', nameJa: 'Google Dork 結果', type: 'web_request', category: 'cyber', url: 'https://www.google.com/search', description: 'Geo-coded Google dorking results (exposed admin panels, files, cameras, IoT)', updateInterval: 7200, layer: 'google-dorking', free: true, status: 'online' },
  { id: 'shodan-iot', name: 'Shodan IoT Devices', nameJa: 'Shodan IoT デバイス', type: 'api', category: 'cyber', url: 'https://api.shodan.io/', description: 'Internet-exposed IoT devices in Japan (cameras, routers, NAS, SCADA, PLCs)', updateInterval: 3600, layer: 'shodan-iot', free: false, status: 'online' },
  { id: 'insecam-webcams', name: 'Open Webcams', nameJa: '公開ウェブカメラ', type: 'web_request', category: 'cyber', url: 'http://www.insecam.org/en/bycountry/JP/', description: 'Open public webcams (insecam, municipal cams, ski/beach/port/volcano monitors)', updateInterval: 3600, layer: 'insecam-webcams', free: true, status: 'online' },
  { id: 'wifi-networks', name: 'WiGLE WiFi Networks', nameJa: 'WiGLE WiFi ネットワーク', type: 'api', category: 'cyber', url: 'https://api.wigle.net/', description: 'WiFi network database across Japan (SSID/BSSID/security)', updateInterval: 86400, layer: 'wifi-networks', free: false, status: 'online' },

  // ── New: Transport (nationwide expansion) ───────────────────────────
  { id: 'maritime-ais', name: 'AIS Ship Tracking', nameJa: 'AIS 船舶追跡', type: 'api', category: 'transport', url: 'https://www.marinetraffic.com/', description: 'AIS vessel positions around Japan ports and shipping lanes', updateInterval: 300, layer: 'maritime-ais', free: false, status: 'online' },
  { id: 'flight-adsb', name: 'ADS-B Flight Tracking', nameJa: 'ADS-B フライト追跡', type: 'api', category: 'transport', url: 'https://opensky-network.org/api/', description: 'ADS-B aircraft positions over Japan (airliners, GA, military)', updateInterval: 60, layer: 'flight-adsb', free: true, status: 'online' },
  { id: 'full-transport', name: 'Japan Rail Network', nameJa: '日本鉄道網', type: 'dataset', category: 'transport', url: 'https://www.jreast.co.jp/', description: 'Nationwide rail network: Shinkansen, JR lines, private railways, subways, monorails, trams', updateInterval: 86400, layer: 'full-transport', free: true, status: 'online' },
  { id: 'mlit-n02-stations', name: 'MLIT N02 Rail Stations', nameJa: '国土数値情報 鉄道駅 N02', type: 'dataset', category: 'transport', url: 'https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-N02-v3_0.html', description: 'MLIT KSJ N02 authoritative nationwide rail station dataset (~10,000 stations, yearly updates) — set MLIT_N02_GEOJSON_URL to enable', updateInterval: 2592000, layer: 'mlit-n02-stations', free: true, status: 'online' },
  { id: 'bus-routes', name: 'Bus Terminals', nameJa: 'バスターミナル', type: 'dataset', category: 'transport', url: 'https://www.bus.or.jp/', description: 'Highway bus terminals and city bus depots across Japan', updateInterval: 86400, layer: 'bus-routes', free: true, status: 'online' },
  { id: 'ferry-routes', name: 'Ferry Terminals', nameJa: 'フェリーターミナル', type: 'dataset', category: 'transport', url: 'https://www.jsanet.or.jp/', description: 'Ferry terminals (inter-island, Seto Inland, Okinawa, international)', updateInterval: 86400, layer: 'ferry-routes', free: true, status: 'online' },
  { id: 'highway-traffic', name: 'Expressway IC/JCT/SA/PA', nameJa: '高速道路 IC/JCT/SA/PA', type: 'web_request', category: 'transport', url: 'https://www.driveplaza.com/', description: 'NEXCO expressway interchanges, junctions, service areas, parking areas, congestion', updateInterval: 600, layer: 'highway-traffic', free: true, status: 'online' },

  // ── New: Infrastructure Networks ────────────────────────────────────
  { id: 'electrical-grid', name: 'Electrical Grid', nameJa: '電力網', type: 'dataset', category: 'infrastructure', url: 'https://www.fepc.or.jp/', description: 'Power plants (thermal/hydro/wind/solar/geothermal), substations, frequency converters', updateInterval: 86400, layer: 'electrical-grid', free: true, status: 'online' },
  { id: 'gas-network', name: 'Gas Network', nameJa: 'ガス網', type: 'dataset', category: 'infrastructure', url: 'https://www.gas.or.jp/', description: 'LNG terminals, distribution stations across Tokyo/Osaka/Toho/Saibu/Hokkaido Gas + JERA', updateInterval: 86400, layer: 'gas-network', free: true, status: 'online' },
  { id: 'water-infra', name: 'Water Infrastructure', nameJa: '水道インフラ', type: 'dataset', category: 'infrastructure', url: 'https://www.mlit.go.jp/river/', description: 'Major dams, water treatment plants, sewage treatment plants', updateInterval: 86400, layer: 'water-infra', free: true, status: 'online' },
  { id: 'cell-towers', name: 'Cell Towers', nameJa: '携帯基地局', type: 'api', category: 'infrastructure', url: 'https://opencellid.org/', description: 'Mobile network base stations (Docomo, au, SoftBank, Rakuten Mobile) - 4G/5G', updateInterval: 86400, layer: 'cell-towers', free: false, status: 'online' },
  { id: 'nuclear-facilities', name: 'Nuclear Facilities', nameJa: '原子力施設', type: 'dataset', category: 'infrastructure', url: 'https://www.nra.go.jp/', description: 'Nuclear power plants, fuel cycle facilities, research reactors, waste storage sites', updateInterval: 86400, layer: 'nuclear-facilities', free: true, status: 'online' },

  // ── Wave 1: Public Safety + Disaster ────────────────────────────────
  { id: 'hospital-map', name: 'Hospital Map', nameJa: '病院マップ', type: 'api', category: 'health', url: 'https://overpass-api.de/api/interpreter', description: 'Hospitals across Japan via OSM Overpass + MHLW open data (university, general, specialized)', updateInterval: 86400, layer: 'hospital-map', free: true, status: 'online' },
  { id: 'aed-map', name: 'AED Map', nameJa: 'AEDマップ', type: 'api', category: 'health', url: 'https://overpass-api.de/api/interpreter', description: 'AED (defibrillator) locations at stations, airports, public facilities', updateInterval: 86400, layer: 'aed-map', free: true, status: 'online' },
  { id: 'koban-map', name: 'Koban / Police Boxes', nameJa: '交番マップ', type: 'api', category: 'safety', url: 'https://overpass-api.de/api/interpreter', description: 'Japanese police boxes (koban), stations, prefectural HQs via OSM Overpass', updateInterval: 86400, layer: 'koban-map', free: true, status: 'online' },
  { id: 'fire-station-map', name: 'Fire Stations', nameJa: '消防署マップ', type: 'api', category: 'safety', url: 'https://overpass-api.de/api/interpreter', description: 'Fire stations and fire department HQs across Japan via OSM Overpass', updateInterval: 86400, layer: 'fire-station-map', free: true, status: 'online' },
  { id: 'bosai-shelter', name: 'Disaster Shelters', nameJa: '防災避難所', type: 'api', category: 'safety', url: 'https://overpass-api.de/api/interpreter', description: 'Designated emergency shelters, evacuation areas, tsunami towers across Japan', updateInterval: 86400, layer: 'bosai-shelter', free: true, status: 'online' },
  { id: 'hazard-map-portal', name: 'MLIT Hazard Map Portal', nameJa: '国土交通省 ハザードマップポータル', type: 'dataset', category: 'safety', url: 'https://disaportal.gsi.go.jp/', description: 'Hazard zones - tsunami inundation, volcanic eruption, landslide, flood, liquefaction', updateInterval: 86400, layer: 'hazard-map-portal', free: true, status: 'online' },
  { id: 'jshis-seismic', name: 'NIED J-SHIS Seismic Hazard', nameJa: 'NIED J-SHIS 地震ハザード', type: 'api', category: 'safety', url: 'https://www.j-shis.bosai.go.jp/', description: 'Probability of seismic intensity 6-lower or higher within 30 years (mesh)', updateInterval: 86400, layer: 'jshis-seismic', free: true, status: 'online' },
  { id: 'hi-net', name: 'NIED Hi-net Stations', nameJa: 'NIED Hi-net 観測点', type: 'dataset', category: 'environment', url: 'https://www.hinet.bosai.go.jp/', description: 'NIED Hi-net high-sensitivity seismograph stations across Japan', updateInterval: 86400, layer: 'hi-net', free: true, status: 'online' },
  { id: 'k-net', name: 'NIED K-NET Stations', nameJa: 'NIED K-NET 観測点', type: 'dataset', category: 'environment', url: 'https://www.kyoshin.bosai.go.jp/', description: 'NIED K-NET strong motion seismograph stations across Japan', updateInterval: 86400, layer: 'k-net', free: true, status: 'online' },
  { id: 'jma-intensity', name: 'JMA Seismic Intensity', nameJa: '気象庁 震度情報', type: 'api', category: 'environment', url: 'https://www.jma.go.jp/bosai/quake/', description: 'JMA seismic intensity reports for recent significant earthquakes', updateInterval: 60, layer: 'jma-intensity', free: true, status: 'online' },

  // ── Wave 2: Health + Statistics + Commerce ──────────────────────────
  { id: 'pharmacy-map', name: 'Pharmacy Map', nameJa: '薬局マップ', type: 'api', category: 'health', url: 'https://overpass-api.de/api/interpreter', description: 'Pharmacies across Japan (Matsumoto Kiyoshi, Welcia, Tsuruha, Sundrug, Sugi) via OSM Overpass', updateInterval: 604800, layer: 'pharmacy-map', free: true, status: 'online' },
  { id: 'convenience-stores', name: 'Convenience Stores', nameJa: 'コンビニ店舗', type: 'api', category: 'marketplace', url: 'https://overpass-api.de/api/interpreter', description: 'Convenience stores (7-Eleven, FamilyMart, Lawson, MiniStop, NewDays) via OSM Overpass', updateInterval: 604800, layer: 'convenience-stores', free: true, status: 'online' },
  { id: 'gas-stations', name: 'Gas Stations', nameJa: 'ガソリンスタンド', type: 'api', category: 'infrastructure', url: 'https://overpass-api.de/api/interpreter', description: 'Gas stations (ENEOS, Idemitsu, Cosmo, Shell, JA-SS) via OSM Overpass', updateInterval: 86400, layer: 'gas-stations', free: true, status: 'online' },
  { id: 'tabelog-restaurants', name: 'Tabelog / HotPepper Restaurants', nameJa: '食べログ・ホットペッパー グルメ', type: 'api', category: 'marketplace', url: 'https://webservice.recruit.co.jp/hotpepper/gourmet/v1/', description: 'Famous Japanese restaurants + HotPepper Gourmet API listings', updateInterval: 86400, layer: 'tabelog-restaurants', free: false, status: 'online' },
  { id: 'estat-census', name: 'e-Stat Census', nameJa: 'e-Stat 国勢調査', type: 'api', category: 'statistics', url: 'https://api.e-stat.go.jp/rest/3.0/app/json/getStatsData', description: 'Prefecture-level census demographics from e-Stat (population, households, age structure)', updateInterval: 86400, layer: 'estat-census', free: true, status: 'online' },
  { id: 'resas-population', name: 'RESAS Population by City', nameJa: 'RESAS 市町村別人口', type: 'api', category: 'statistics', url: 'https://opendata.resas-portal.go.jp/api/v1/', description: 'RESAS population by city with age composition (0-14, 15-64, 65+)', updateInterval: 86400, layer: 'resas-population', free: true, status: 'online' },
  { id: 'resas-tourism', name: 'RESAS Tourism', nameJa: 'RESAS 観光統計', type: 'api', category: 'statistics', url: 'https://opendata.resas-portal.go.jp/api/v1/', description: 'RESAS tourism + major tourist sites with annual visitor counts and foreign visitor share', updateInterval: 86400, layer: 'resas-tourism', free: true, status: 'online' },
  { id: 'resas-industry', name: 'RESAS Industry', nameJa: 'RESAS 産業構造', type: 'api', category: 'statistics', url: 'https://opendata.resas-portal.go.jp/api/v1/', description: 'RESAS industry composition by city - manufacturing, services, agriculture, fishery', updateInterval: 86400, layer: 'resas-industry', free: true, status: 'online' },
  { id: 'mlit-transaction', name: 'MLIT Land Transactions', nameJa: '国交省 不動産取引価格', type: 'api', category: 'economy', url: 'https://www.land.mlit.go.jp/webland/api/TradeListSearch', description: 'MLIT real estate transaction prices by district (free public API)', updateInterval: 86400, layer: 'mlit-transaction', free: true, status: 'online' },
  { id: 'dam-water-level', name: 'Dam Water Levels', nameJa: 'ダム貯水位', type: 'api', category: 'infrastructure', url: 'https://www1.river.go.jp/', description: 'Major Japanese dams - storage capacity and current reservoir levels (Tokuyama, Kurobe, Sameura, etc.)', updateInterval: 600, layer: 'dam-water-level', free: true, status: 'online' },

  // ── Wave 3: Maritime + Ocean + Aviation ─────────────────────────────
  { id: 'jma-ocean-wave', name: 'JMA Ocean Wave', nameJa: '気象庁 波浪観測', type: 'api', category: 'environment', url: 'https://www.data.jma.go.jp/gmd/kaiyou/data/db/wave/', description: 'Significant wave heights from JMA coastal observation network', updateInterval: 3600, layer: 'jma-ocean-wave', free: true, status: 'online' },
  { id: 'jma-ocean-temp', name: 'JMA Sea Surface Temp', nameJa: '気象庁 海面水温', type: 'api', category: 'environment', url: 'https://www.data.jma.go.jp/gmd/kaiyou/data/db/kaikyo/', description: 'Sea surface temperature with anomaly grid - Pacific, Japan Sea, East China Sea', updateInterval: 86400, layer: 'jma-ocean-temp', free: true, status: 'online' },
  { id: 'jma-tide', name: 'JMA Tide Levels', nameJa: '気象庁 潮位情報', type: 'api', category: 'environment', url: 'https://www.data.jma.go.jp/kaiyou/data/db/tide/', description: 'JMA tide gauge observations across Japan with anomaly from astronomic tide', updateInterval: 600, layer: 'jma-tide', free: true, status: 'online' },
  { id: 'nowphas-wave', name: 'NOWPHAS Wave Network', nameJa: 'NOWPHAS 波浪観測網', type: 'api', category: 'environment', url: 'https://nowphas.mlit.go.jp/', description: 'PARI NOWPHAS GPS-buoys + ultrasonic wave gauges around Japan', updateInterval: 1800, layer: 'nowphas-wave', free: true, status: 'online' },
  { id: 'lighthouse-map', name: 'Lighthouses', nameJa: '灯台マップ', type: 'api', category: 'transport', url: 'https://overpass-api.de/api/interpreter', description: 'JCG lighthouses across Japan via OSM Overpass + historic Meiji-era register', updateInterval: 604800, layer: 'lighthouse-map', free: true, status: 'online' },
  { id: 'jartic-traffic', name: 'JARTIC Traffic', nameJa: 'JARTIC 道路交通情報', type: 'api', category: 'transport', url: 'https://www.jartic.or.jp/', description: 'JARTIC traffic congestion - urban expressways and national highway hotspots', updateInterval: 300, layer: 'jartic-traffic', free: true, status: 'online' },
  { id: 'narita-flights', name: 'Narita Airport Flights', nameJa: '成田空港 発着便', type: 'api', category: 'transport', url: 'https://aerodatabox.p.rapidapi.com/', description: 'Narita International Airport (RJAA/NRT) arrivals + departures via AeroDataBox', updateInterval: 300, layer: 'narita-flights', free: false, status: 'online' },
  { id: 'haneda-flights', name: 'Haneda Airport Flights', nameJa: '羽田空港 発着便', type: 'api', category: 'transport', url: 'https://aerodatabox.p.rapidapi.com/', description: 'Tokyo Haneda Airport (RJTT/HND) arrivals + departures via AeroDataBox', updateInterval: 300, layer: 'haneda-flights', free: false, status: 'online' },
  { id: 'drone-nofly', name: 'Drone No-Fly Zones', nameJa: 'ドローン飛行禁止区域', type: 'dataset', category: 'safety', url: 'https://www.mlit.go.jp/koku/', description: 'MLIT/JCAB drone no-fly zones - airports, DID, nuclear, military, imperial', updateInterval: 86400, layer: 'drone-nofly', free: true, status: 'online' },
  { id: 'jcg-patrol', name: 'JCG Patrol Bases', nameJa: '海上保安庁 巡視船基地', type: 'dataset', category: 'safety', url: 'https://www.kaiho.mlit.go.jp/', description: 'Japan Coast Guard - 11 regional headquarters and patrol vessel bases', updateInterval: 604800, layer: 'jcg-patrol', free: true, status: 'online' },

  // Wave 4: Government + Defense
  { id: 'government-buildings', name: 'Government Buildings', nameJa: '官公庁', type: 'api', category: 'government', url: 'https://overpass-api.de/api/interpreter', description: 'Cabinet, Diet, ministries, agencies and prefectural HQ via OSM Overpass', updateInterval: 604800, layer: 'government-buildings', free: true, status: 'online' },
  { id: 'city-halls', name: 'City Halls', nameJa: '市区町村役場', type: 'api', category: 'government', url: 'https://overpass-api.de/api/interpreter', description: 'Tokyo wards, designated cities, core cities and prefectural capital halls', updateInterval: 604800, layer: 'city-halls', free: true, status: 'online' },
  { id: 'courts-prisons', name: 'Courts & Prisons', nameJa: '裁判所・刑務所', type: 'api', category: 'government', url: 'https://overpass-api.de/api/interpreter', description: 'High/district courts and major correctional facilities (MOJ)', updateInterval: 604800, layer: 'courts-prisons', free: true, status: 'online' },
  { id: 'embassies', name: 'Embassies', nameJa: '大使館', type: 'api', category: 'government', url: 'https://overpass-api.de/api/interpreter', description: 'Foreign embassies in Japan via OSM Overpass diplomatic=embassy', updateInterval: 604800, layer: 'embassies', free: true, status: 'online' },
  { id: 'jsdf-bases', name: 'JSDF Bases', nameJa: '自衛隊基地', type: 'dataset', category: 'defense', url: 'https://www.mod.go.jp/', description: 'GSDF, MSDF, ASDF installations across Japan', updateInterval: 604800, layer: 'jsdf-bases', free: true, status: 'online' },
  { id: 'usfj-bases', name: 'USFJ Bases', nameJa: '在日米軍基地', type: 'dataset', category: 'defense', url: 'https://www.usfj.mil/', description: 'United States Forces Japan installations: USAF, USN, USMC, USA', updateInterval: 604800, layer: 'usfj-bases', free: true, status: 'online' },
  { id: 'radar-sites', name: 'Radar Sites', nameJa: 'レーダーサイト', type: 'dataset', category: 'defense', url: 'https://www.mod.go.jp/asdf/', description: 'JADGE air-defense radar (FPS-3/FPS-7), BMD X-band (AN/TPY-2), JMA weather radar', updateInterval: 604800, layer: 'radar-sites', free: true, status: 'online' },
  { id: 'coast-guard-stations', name: 'Coast Guard Stations', nameJa: '海上保安部・署', type: 'dataset', category: 'defense', url: 'https://www.kaiho.mlit.go.jp/', description: 'JCG offices and signal stations across 11 regional headquarters', updateInterval: 604800, layer: 'coast-guard-stations', free: true, status: 'online' },

  // Wave 5: Industry + Energy Deep
  { id: 'auto-plants', name: 'Automotive Plants', nameJa: '自動車工場', type: 'api', category: 'industry', url: 'https://overpass-api.de/api/interpreter', description: 'Toyota, Nissan, Honda, Mazda, Subaru, Mitsubishi, Suzuki, Daihatsu, Isuzu, Hino assembly + engine plants', updateInterval: 604800, layer: 'auto-plants', free: true, status: 'online' },
  { id: 'steel-mills', name: 'Steel Mills', nameJa: '製鉄所', type: 'api', category: 'industry', url: 'https://overpass-api.de/api/interpreter', description: 'Nippon Steel, JFE, Kobelco, Daido, Tokyo Steel: integrated mills + EAF', updateInterval: 604800, layer: 'steel-mills', free: true, status: 'online' },
  { id: 'petrochemical', name: 'Petrochemical', nameJa: '石油化学コンビナート', type: 'api', category: 'industry', url: 'https://overpass-api.de/api/interpreter', description: 'Major Japanese petrochemical complexes (Keiyou, Kashima, Yokkaichi, Mizushima, Tokuyama, Oita)', updateInterval: 604800, layer: 'petrochemical', free: true, status: 'online' },
  { id: 'refineries', name: 'Oil Refineries', nameJa: '製油所', type: 'api', category: 'industry', url: 'https://overpass-api.de/api/interpreter', description: 'METI registered active oil refineries: ENEOS, Idemitsu, Cosmo, Fuji, Taiyo, Kashima Oil', updateInterval: 604800, layer: 'refineries', free: true, status: 'online' },
  { id: 'semiconductor-fabs', name: 'Semiconductor Fabs', nameJa: '半導体工場', type: 'dataset', category: 'industry', url: 'https://www.meti.go.jp/', description: 'Kioxia, Sony, Renesas, Rohm, Mitsubishi, Fuji, TSMC JASM, Rapidus, Micron Japan', updateInterval: 604800, layer: 'semiconductor-fabs', free: true, status: 'online' },
  { id: 'shipyards', name: 'Shipyards', nameJa: '造船所', type: 'api', category: 'industry', url: 'https://overpass-api.de/api/interpreter', description: 'Imabari, JMU, MHI, KHI, Mitsui ES, Tsuneishi, Onomichi, Hakodate Dock', updateInterval: 604800, layer: 'shipyards', free: true, status: 'online' },
  { id: 'petroleum-stockpile', name: 'Petroleum Stockpile', nameJa: '国家石油備蓄基地', type: 'dataset', category: 'industry', url: 'https://www.jogmec.go.jp/', description: 'JOGMEC strategic petroleum reserves (10 oil + 5 LPG) and commercial depots', updateInterval: 2592000, layer: 'petroleum-stockpile', free: true, status: 'online' },
  { id: 'wind-turbines', name: 'Wind Turbines', nameJa: '風力発電所', type: 'api', category: 'industry', url: 'https://overpass-api.de/api/interpreter', description: 'Onshore + offshore wind farms across Japan including Goto floating array', updateInterval: 604800, layer: 'wind-turbines', free: true, status: 'online' },

  // Wave 6: Telecom + Internet Infrastructure
  { id: 'data-centers', name: 'Data Centers', nameJa: 'データセンター', type: 'api', category: 'telecom', url: 'https://overpass-api.de/api/interpreter', description: 'Equinix, NTT, KDDI/Telehouse, IDC Frontier, IIJ, SAKURA, AWS, Azure, Google, Colt, MC Digital Realty', updateInterval: 604800, layer: 'data-centers', free: true, status: 'online' },
  { id: 'internet-exchanges', name: 'Internet Exchanges', nameJa: 'インターネットエクスチェンジ', type: 'api', category: 'telecom', url: 'https://www.peeringdb.com/api/ix?country=JP', description: 'JPNAP, JPIX, BBIX, Equinix IX, DIX-IE and regional IXPs (PeeringDB API)', updateInterval: 86400, layer: 'internet-exchanges', free: true, status: 'online' },
  { id: 'submarine-cables', name: 'Submarine Cable Landings', nameJa: '海底ケーブル陸揚局', type: 'dataset', category: 'telecom', url: 'https://www.telegeography.com/', description: 'Major Pacific (Chiba), Asia (Aichi), Russia (Niigata), Korea (Saga), Okinawa cable landing stations', updateInterval: 2592000, layer: 'submarine-cables', free: true, status: 'online' },
  { id: 'tor-exit-nodes', name: 'Tor Exit Nodes', nameJa: 'Tor 出口ノード', type: 'api', category: 'telecom', url: 'https://onionoo.torproject.org/details?country=jp&flag=Exit', description: 'Live Tor exit relays in Japan via Tor Project onionoo API', updateInterval: 3600, layer: 'tor-exit-nodes', free: true, status: 'online' },
  { id: '5g-coverage', name: '5G Coverage', nameJa: '5G カバレッジ', type: 'dataset', category: 'telecom', url: 'https://www.soumu.go.jp/', description: 'Docomo, KDDI au, SoftBank, Rakuten Mobile 5G NSA/SA - n77/n78 sub-6 + n257 mmWave hotspots', updateInterval: 86400, layer: '5g-coverage', free: true, status: 'online' },
  { id: 'satellite-ground-stations', name: 'Satellite Ground Stations', nameJa: '衛星地上局', type: 'dataset', category: 'telecom', url: 'https://global.jaxa.jp/', description: 'JAXA, NICT, KDDI, SKY Perfect JSAT, NAOJ ground stations and tracking facilities', updateInterval: 2592000, layer: 'satellite-ground-stations', free: true, status: 'online' },
  { id: 'amateur-radio-repeaters', name: 'Amateur Radio Repeaters', nameJa: 'アマチュア無線レピータ', type: 'dataset', category: 'telecom', url: 'https://www.jarl.org/', description: 'JARL VHF/UHF FM, D-STAR, C4FM digital, HF beacons across Japan', updateInterval: 2592000, layer: 'amateur-radio-repeaters', free: true, status: 'online' },

  // ── Wave 7: Tourism + Culture ───────────────────────────────────────
  { id: 'national-parks', name: 'National Parks', nameJa: '国立公園', type: 'api', category: 'tourism', url: 'https://overpass-api.de/api/interpreter', description: '34 national parks + 56 quasi-national parks under Ministry of Environment via OSM', updateInterval: 2592000, layer: 'national-parks', free: true, status: 'online' },
  { id: 'unesco-heritage', name: 'UNESCO World Heritage', nameJa: 'ユネスコ世界遺産', type: 'dataset', category: 'tourism', url: 'https://whc.unesco.org/', description: 'UNESCO World Heritage Sites in Japan (25 cultural + natural sites as of 2024)', updateInterval: 2592000, layer: 'unesco-heritage', free: true, status: 'online' },
  { id: 'castles', name: 'Japanese Castles', nameJa: '日本の城', type: 'api', category: 'tourism', url: 'https://overpass-api.de/api/interpreter', description: '100 Famous Castles + 100 Continued Famous Castles across Japan via OSM historic=castle', updateInterval: 2592000, layer: 'castles', free: true, status: 'online' },
  { id: 'museums', name: 'Museums', nameJa: '博物館・美術館', type: 'api', category: 'tourism', url: 'https://overpass-api.de/api/interpreter', description: 'National and major museums across Japan (art, history, science, natural history)', updateInterval: 604800, layer: 'museums', free: true, status: 'online' },
  { id: 'stadiums', name: 'Stadiums', nameJa: 'スタジアム', type: 'api', category: 'tourism', url: 'https://overpass-api.de/api/interpreter', description: 'NPB baseball, J-League football, sumo, rugby and multipurpose stadiums', updateInterval: 604800, layer: 'stadiums', free: true, status: 'online' },
  { id: 'racetracks', name: 'Racetracks', nameJa: '競馬・競輪・競艇・オート場', type: 'api', category: 'tourism', url: 'https://overpass-api.de/api/interpreter', description: 'JRA + NAR horse racing, keirin velodromes, kyotei boat race, auto race venues', updateInterval: 604800, layer: 'racetracks', free: true, status: 'online' },
  { id: 'shrine-temple', name: 'Shrines & Temples', nameJa: '神社・寺院', type: 'api', category: 'culture', url: 'https://overpass-api.de/api/interpreter', description: 'Shinto shrines and Buddhist temples - major historic sites via OSM Overpass', updateInterval: 2592000, layer: 'shrine-temple', free: true, status: 'online' },
  { id: 'onsen-map', name: 'Onsen (Hot Springs)', nameJa: '温泉', type: 'api', category: 'culture', url: 'https://overpass-api.de/api/interpreter', description: 'Japanese hot spring towns and public bath houses - 三名泉, 三古泉 and 100名湯', updateInterval: 604800, layer: 'onsen-map', free: true, status: 'online' },
  { id: 'ski-resorts', name: 'Ski Resorts', nameJa: 'スキー場', type: 'api', category: 'tourism', url: 'https://overpass-api.de/api/interpreter', description: 'Ski and snowboard resorts across Hokkaido, Tohoku, Niigata, Nagano, Gifu', updateInterval: 2592000, layer: 'ski-resorts', free: true, status: 'online' },
  { id: 'anime-pilgrimage', name: 'Anime Pilgrimage Sites', nameJa: 'アニメ聖地巡礼', type: 'dataset', category: 'culture', url: 'https://animetourism88.com/', description: 'Real-world locations featured in anime/manga - seichi junrei sites from Your Name, K-On!, Lucky Star, Love Live and more', updateInterval: 2592000, layer: 'anime-pilgrimage', free: true, status: 'online' },

  // ── Wave 8: Crime + Vice + Wildlife ─────────────────────────────────
  { id: 'yakuza-hq', name: 'Yakuza Headquarters', nameJa: '指定暴力団 総本部', type: 'dataset', category: 'crime', url: 'https://www.npa.go.jp/bureau/sosikihanzai/bouryokudan/', description: 'NPA designated bouryokudan HQs (六代目山口組、住吉会、稲川会、工藤會 etc.) with membership estimates', updateInterval: 2592000, layer: 'yakuza-hq', free: true, status: 'online' },
  { id: 'red-light-zones', name: 'Red Light Districts', nameJa: '風俗営業地区', type: 'api', category: 'crime', url: 'https://overpass-api.de/api/interpreter', description: 'Tolerated entertainment districts - Kabukicho, Tobita Shinchi, Susukino, Nakasu, Gion, etc.', updateInterval: 2592000, layer: 'red-light-zones', free: true, status: 'online' },
  { id: 'pachinko-density', name: 'Pachinko Parlor Density', nameJa: 'パチンコ店密度', type: 'api', category: 'crime', url: 'https://overpass-api.de/api/interpreter', description: 'Pachinko parlor density by city (NPA 遊技場営業許可) - adult gaming centers via OSM', updateInterval: 604800, layer: 'pachinko-density', free: true, status: 'online' },
  { id: 'bear-encounters', name: 'Bear Encounters', nameJa: 'クマ出没情報', type: 'api', category: 'wildlife', url: 'https://www.pref.hokkaido.lg.jp/', description: 'Asiatic black bear and Hokkaido brown bear encounter hotspots - prefectural wildlife data', updateInterval: 86400, layer: 'bear-encounters', free: true, status: 'online' },
  { id: 'bird-flu-outbreaks', name: 'Bird Flu Outbreaks', nameJa: '高病原性鳥インフルエンザ', type: 'api', category: 'wildlife', url: 'https://www.maff.go.jp/j/syouan/douei/tori/', description: 'MAFF HPAI (H5N1) confirmed farm outbreaks across Japan with culled bird counts by prefecture', updateInterval: 86400, layer: 'bird-flu-outbreaks', free: true, status: 'online' },
  { id: 'sakura-front', name: 'Sakura Front', nameJa: '桜前線', type: 'api', category: 'wildlife', url: 'https://weathernews.jp/s/topics/sakura/', description: 'Cherry blossom progression front - JMA 標本木 observation network + hanami hotspots', updateInterval: 3600, layer: 'sakura-front', free: true, status: 'online' },
  { id: 'wanted-persons', name: 'NPA Wanted Persons', nameJa: '警察庁 指名手配', type: 'dataset', category: 'crime', url: 'https://www.npa.go.jp/sousa/shimeitehai/', description: 'NPA designated wanted persons (指名手配) by issuing prefectural police HQ', updateInterval: 86400, layer: 'wanted-persons', free: true, status: 'online' },
  { id: 'phone-scam-hotspots', name: 'Phone Scam Hotspots', nameJa: '特殊詐欺発生地点', type: 'dataset', category: 'crime', url: 'https://www.npa.go.jp/bureau/criminal/souni/tokushusagi/', description: 'NPA 特殊詐欺 (oreore-sagi / refund fraud) ward-level incident counts and damage totals', updateInterval: 86400, layer: 'phone-scam-hotspots', free: true, status: 'online' },

  // ── Wave 9: Food + Agriculture ──────────────────────────────────────
  { id: 'sake-breweries', name: 'Sake Breweries', nameJa: '日本酒蔵元', type: 'api', category: 'food', url: 'https://overpass-api.de/api/interpreter', description: 'Japan Sake Brewers Association registered breweries (~1,200 nationwide) - Hakutsuru, Dassai, Kubota, Juyondai', updateInterval: 2592000, layer: 'sake-breweries', free: true, status: 'online' },
  { id: 'wineries-craftbeer', name: 'Wineries & Craft Beer', nameJa: 'ワイナリー・地ビール・蒸溜所', type: 'api', category: 'food', url: 'https://overpass-api.de/api/interpreter', description: 'NTA license registry - Katsunuma wineries, craft beer breweries, whisky distilleries (Yamazaki, Hakushu, Yoichi)', updateInterval: 2592000, layer: 'wineries-craftbeer', free: true, status: 'online' },
  { id: 'fish-markets', name: 'Fish Markets', nameJa: '魚市場・水産卸売', type: 'api', category: 'food', url: 'https://overpass-api.de/api/interpreter', description: 'MAFF wholesale fish markets (Toyosu, Osaka, Fukuoka) + regional port markets and morning markets', updateInterval: 604800, layer: 'fish-markets', free: true, status: 'online' },
  { id: 'wagyu-ranches', name: 'Wagyu Ranches', nameJa: '和牛産地', type: 'dataset', category: 'food', url: 'https://www.jlec.net/', description: 'Certified wagyu brand production regions - Matsusaka, Kobe, Omi, Hida, Yonezawa, Miyazaki, Kagoshima', updateInterval: 2592000, layer: 'wagyu-ranches', free: true, status: 'online' },
  { id: 'tea-zones', name: 'Tea Zones', nameJa: '茶産地', type: 'api', category: 'agriculture', url: 'https://overpass-api.de/api/interpreter', description: 'MAFF tea-growing regions - Shizuoka, Kagoshima, Uji, Yame, Sayama, Ise with cultivar and production volume', updateInterval: 2592000, layer: 'tea-zones', free: true, status: 'online' },
  { id: 'rice-paddies', name: 'Rice Paddies', nameJa: '稲作産地', type: 'api', category: 'agriculture', url: 'https://overpass-api.de/api/interpreter', description: 'MAFF premium rice-producing regions - Uonuma Koshihikari, Yumepirika, Akitakomachi and heritage tanada', updateInterval: 2592000, layer: 'rice-paddies', free: true, status: 'online' },

  // ── Wave 10: Niche + Pop Culture ────────────────────────────────────
  { id: 'vending-machines', name: 'Vending Machines', nameJa: '自動販売機', type: 'api', category: 'culture', url: 'https://overpass-api.de/api/interpreter', description: 'Japanese vending machine density - ~2.3M units nationwide, world record per-capita (drinks, hot/cold, novelty)', updateInterval: 2592000, layer: 'vending-machines', free: true, status: 'online' },
  { id: 'karaoke-chains', name: 'Karaoke Chains', nameJa: 'カラオケチェーン', type: 'api', category: 'culture', url: 'https://overpass-api.de/api/interpreter', description: 'Japanese karaoke box chains - Big Echo, Karaoke-kan, JOYSOUND, Manekineko, Jankara, Cote d\'Azur', updateInterval: 2592000, layer: 'karaoke-chains', free: true, status: 'online' },
  { id: 'manga-net-cafes', name: 'Manga / Net Cafes', nameJa: '漫画喫茶・ネットカフェ', type: 'api', category: 'culture', url: 'https://overpass-api.de/api/interpreter', description: '24-hour manga/internet cafes - Jiyu-kukan, Media Cafe Popeye, Gran Cyber Cafe Bagus, DiCE, Manboo!', updateInterval: 2592000, layer: 'manga-net-cafes', free: true, status: 'online' },
  { id: 'sento-public-baths', name: 'Sento Public Baths', nameJa: '銭湯', type: 'api', category: 'culture', url: 'https://www.1010.or.jp/', description: 'Traditional Japanese sento public bathhouses (~3,000 nationwide) - Tokyo Sento Association registered + OSM', updateInterval: 604800, layer: 'sento-public-baths', free: true, status: 'online' },
  { id: 'manhole-covers', name: 'Manhole Cards', nameJa: 'マンホールカード', type: 'dataset', category: 'culture', url: 'https://www.gk-p.jp/activity/mhcard/', description: 'GKP Manhole Card (マンホールカード) issuance sites - decorative civic manhole cover designs by municipality', updateInterval: 2592000, layer: 'manhole-covers', free: true, status: 'online' },
  { id: 'themed-cafes', name: 'Themed Cafes', nameJa: 'コンセプトカフェ', type: 'dataset', category: 'culture', url: 'https://animetourism88.com/', description: 'Japanese themed cafes - maid (Maidreamin, @home), cat/owl/hedgehog, character (Pokemon, Kirby), robot, butler', updateInterval: 2592000, layer: 'themed-cafes', free: true, status: 'online' },

  // ── Wave 11: External Mapping Platforms ─────────────────────────────
  { id: 'marine-traffic', name: 'MarineTraffic AIS', nameJa: 'マリントラフィック AIS', type: 'api', category: 'transport', url: 'https://services.marinetraffic.com/api/exportvessels/v:8/', description: 'MarineTraffic Exportvessels REST API - live AIS positions in Japan bbox (needs MARINETRAFFIC_API_KEY, freemium)', updateInterval: 300, layer: 'marine-traffic', free: false, status: 'online' },
  { id: 'vessel-finder', name: 'VesselFinder AIS', nameJa: 'ベッセルファインダー AIS', type: 'api', category: 'transport', url: 'https://api.vesselfinder.com/vesselslist', description: 'VesselFinder Master REST API - live AIS positions in Japan bbox (needs VESSELFINDER_API_KEY, freemium)', updateInterval: 300, layer: 'vessel-finder', free: false, status: 'online' },
  { id: 'sentinel-hub', name: 'Sentinel-2 L2A Scenes', nameJa: 'センチネル2 L2A シーン', type: 'api', category: 'environment', url: 'https://earth-search.aws.element84.com/v1/search', description: 'Copernicus Sentinel-2 L2A scene footprints over Japan - last 10 days <40% cloud. Free-first fallback chain: Sentinel Hub (if creds) → Element84 Earth Search (AWS Open Data, no auth) → Microsoft Planetary Computer (no auth) → Copernicus Data Space OData (no auth) → seed tiles', updateInterval: 86400, layer: 'sentinel-hub', free: true, status: 'online' },
  { id: 'google-earth', name: 'Google Earth Layers', nameJa: 'グーグルアース レイヤー', type: 'api', category: 'tourism', url: 'https://volcano.si.edu/ReportKMLs/Holocene.kml', description: 'Public KML/GeoRSS layers visible in Google Earth - Smithsonian GVP volcanoes + Wikipedia GeoSearch populated places, Japan bbox filtered', updateInterval: 604800, layer: 'google-earth', free: true, status: 'online' },
  { id: 'google-my-maps', name: 'Google My Maps', nameJa: 'グーグル マイマップ', type: 'api', category: 'tourism', url: 'https://www.google.com/maps/d/kml', description: 'Google My Maps public KML exports parsed to points (configure GOOGLE_MYMAPS_IDS env var with comma-separated mids)', updateInterval: 3600, layer: 'google-my-maps', free: true, status: 'online' },

  // ── Wave 12: Unified Camera Discovery ───────────────────────────────
  { id: 'camera-discovery', name: 'Unified Camera Discovery', nameJa: '統合カメラディスカバリー', type: 'api', category: 'cyber', url: 'https://overpass-api.de/api/interpreter', description: 'Fused public-camera discovery across every channel: OSM surveillance, JMA volcano cams, MLIT river cams, Shutoko/Hanshin/NEXCO expressway CCTV, NHK/YouTube/municipal livecams, ski/beach/port webcams, Insecam, Windy/SkylineWebcams/EarthCam aggregators, DuckDuckGo camera dorks, and Shodan camera queries', updateInterval: 3600, layer: 'camera-discovery', free: true, status: 'online' },
];

export default sources;
