/**
 * Central registry of all Japan OSINT data sources.
 * Each entry describes a source, its type, category, update cadence, and the
 * map layer it feeds.
 */

const sources = [
  // ── Weather / Seismic ────────────────────────────────────────────────
  {
    id: 'jma-earthquake',
    name: 'JMA Earthquake API',
    nameJa: '気象庁 地震情報',
    type: 'api',
    category: 'environment',
    url: 'https://www.jma.go.jp/bosai/quake/data/list.json',
    description: 'Real-time earthquake data from the Japan Meteorological Agency',
    updateInterval: 60,
    layer: 'earthquake',
    free: true,
    status: 'offline',
  },
  {
    id: 'jma-weather',
    name: 'JMA Weather Forecast',
    nameJa: '気象庁 天気予報',
    type: 'api',
    category: 'environment',
    url: 'https://www.jma.go.jp/bosai/forecast/',
    description: 'Weather forecast data for all prefectures',
    updateInterval: 3600,
    layer: 'weather',
    free: true,
    status: 'offline',
  },
  {
    id: 'jma-tsunami',
    name: 'JMA Tsunami Warnings',
    nameJa: '気象庁 津波情報',
    type: 'api',
    category: 'environment',
    url: 'https://www.jma.go.jp/bosai/tsunami/',
    description: 'Tsunami warning and advisory data',
    updateInterval: 60,
    layer: 'tsunami',
    free: true,
    status: 'offline',
  },
  {
    id: 'jma-volcano',
    name: 'JMA Volcanic Alerts',
    nameJa: '気象庁 火山情報',
    type: 'api',
    category: 'environment',
    url: 'https://www.jma.go.jp/bosai/volcano/',
    description: 'Volcanic activity alerts and warnings',
    updateInterval: 3600,
    layer: 'volcano',
    free: true,
    status: 'offline',
  },

  // ── Air / Radiation ──────────────────────────────────────────────────
  {
    id: 'soramame',
    name: 'SORAMAME Air Quality',
    nameJa: 'そらまめ君 大気汚染情報',
    type: 'api',
    category: 'environment',
    url: 'http://soramame.env.go.jp/',
    description: 'Hourly air quality monitoring station data (PM2.5, Ox, SO2, etc.)',
    updateInterval: 3600,
    layer: 'air-quality',
    free: true,
    status: 'offline',
  },
  {
    id: 'nra-radiation',
    name: 'NRA Radiation Monitoring',
    nameJa: '原子力規制委員会 放射線モニタリング',
    type: 'api',
    category: 'environment',
    url: 'https://radioactivity.nra.go.jp/',
    description: 'Real-time radiation dose monitoring across Japan (10-min intervals)',
    updateInterval: 600,
    layer: 'radiation',
    free: true,
    status: 'offline',
  },

  // ── Transport ────────────────────────────────────────────────────────
  {
    id: 'odpt-train',
    name: 'ODPT Train Real-time',
    nameJa: 'ODPT 鉄道リアルタイム',
    type: 'api',
    category: 'transport',
    url: 'https://api.odpt.org/api/v4/',
    description: 'Real-time train location and delay data in Tokyo metro area',
    updateInterval: 30,
    layer: 'transport',
    free: true,
    status: 'offline',
  },
  {
    id: 'odpt-bus',
    name: 'ODPT Bus Real-time',
    nameJa: 'ODPT バスリアルタイム',
    type: 'api',
    category: 'transport',
    url: 'https://api.odpt.org/api/v4/',
    description: 'Real-time bus location data',
    updateInterval: 30,
    layer: 'transport',
    free: true,
    status: 'offline',
  },
  {
    id: 'odpt-station',
    name: 'ODPT Station Data',
    nameJa: 'ODPT 駅データ',
    type: 'api',
    category: 'transport',
    url: 'https://api.odpt.org/api/v4/',
    description: 'Static station location and metadata',
    updateInterval: 86400,
    layer: 'transport',
    free: true,
    status: 'offline',
  },
  {
    id: 'navitime',
    name: 'Navitime Transit',
    nameJa: 'ナビタイム 交通情報',
    type: 'web_request',
    category: 'transport',
    url: 'https://www.navitime.co.jp/',
    description: 'Transit and route information (placeholder)',
    updateInterval: 300,
    layer: 'transport',
    free: false,
    status: 'offline',
  },

  // ── Geospatial ───────────────────────────────────────────────────────
  {
    id: 'plateau-buildings',
    name: 'PLATEAU 3D Buildings',
    nameJa: 'PLATEAU 3D都市モデル',
    type: 'dataset',
    category: 'geospatial',
    url: 'https://www.geospatial.jp/ckan/dataset/plateau',
    description: 'MLIT PLATEAU 3D city model building data',
    updateInterval: 604800,
    layer: 'buildings',
    free: true,
    status: 'offline',
  },
  {
    id: 'gsi-tiles',
    name: 'GSI Map Tiles',
    nameJa: '国土地理院 地図タイル',
    type: 'api',
    category: 'geospatial',
    url: 'https://cyberjapandata.gsi.go.jp/',
    description: 'Geospatial Information Authority base map tiles',
    updateInterval: 86400,
    layer: 'basemap',
    free: true,
    status: 'offline',
  },
  {
    id: 'gsi-elevation',
    name: 'GSI Elevation',
    nameJa: '国土地理院 標高データ',
    type: 'api',
    category: 'geospatial',
    url: 'https://cyberjapandata.gsi.go.jp/',
    description: 'Digital elevation model tiles',
    updateInterval: 86400,
    layer: 'elevation',
    free: true,
    status: 'offline',
  },
  {
    id: 'nlni-landuse',
    name: 'National Land Numerical Info',
    nameJa: '国土数値情報 土地利用',
    type: 'dataset',
    category: 'geospatial',
    url: 'https://nlftp.mlit.go.jp/ksj/',
    description: 'Land use mesh data from MLIT',
    updateInterval: 604800,
    layer: 'landuse',
    free: true,
    status: 'offline',
  },

  // ── Population / Statistics ──────────────────────────────────────────
  {
    id: 'estat-population',
    name: 'e-Stat Population Mesh',
    nameJa: 'e-Stat 人口メッシュ',
    type: 'api',
    category: 'statistics',
    url: 'https://api.e-stat.go.jp/',
    description: 'Grid-square population statistics',
    updateInterval: 86400,
    layer: 'population',
    free: true,
    status: 'offline',
  },
  {
    id: 'estat-census',
    name: 'e-Stat Census Data',
    nameJa: 'e-Stat 国勢調査',
    type: 'api',
    category: 'statistics',
    url: 'https://api.e-stat.go.jp/',
    description: 'National census demographic data',
    updateInterval: 86400,
    layer: 'population',
    free: true,
    status: 'offline',
  },
  {
    id: 'resas-population',
    name: 'RESAS Population Flow',
    nameJa: 'RESAS 人口流動',
    type: 'api',
    category: 'statistics',
    url: 'https://opendata.resas-portal.go.jp/',
    description: 'Regional Economy and Society Analyzing System population flow',
    updateInterval: 86400,
    layer: 'population',
    free: true,
    status: 'offline',
  },

  // ── Real Estate / Prices ─────────────────────────────────────────────
  {
    id: 'mlit-landprice',
    name: 'MLIT Land Price Survey',
    nameJa: '国交省 地価公示',
    type: 'api',
    category: 'economy',
    url: 'https://www.land.mlit.go.jp/webland/api/',
    description: 'Official land price survey data',
    updateInterval: 86400,
    layer: 'landprice',
    free: true,
    status: 'offline',
  },
  {
    id: 'reinfolib',
    name: 'Real Estate Transaction Prices',
    nameJa: '不動産取引価格情報',
    type: 'api',
    category: 'economy',
    url: 'https://www.reinfolib.mlit.go.jp/',
    description: 'Actual real estate transaction price data',
    updateInterval: 86400,
    layer: 'landprice',
    free: true,
    status: 'offline',
  },
  {
    id: 'suumo',
    name: 'Suumo Rental Prices',
    nameJa: 'SUUMO 賃料情報',
    type: 'scraped',
    category: 'economy',
    url: 'https://suumo.jp/',
    description: 'Scraped rental price listings',
    updateInterval: 86400,
    layer: 'landprice',
    free: true,
    status: 'offline',
  },

  // ── Safety / Emergency ───────────────────────────────────────────────
  {
    id: 'police-incidents',
    name: 'Prefectural Police Crime Maps',
    nameJa: '都道府県警 犯罪発生マップ',
    type: 'scraped',
    category: 'safety',
    url: 'https://www.keishicho.metro.tokyo.lg.jp/jiken_jiko/hassei/index.html',
    description: 'Crime incident reports from prefectural police',
    updateInterval: 86400,
    layer: 'crime',
    free: true,
    status: 'offline',
  },
  {
    id: 'fire-department',
    name: 'Fire Department Dispatches',
    nameJa: '消防庁 出動情報',
    type: 'web_request',
    category: 'safety',
    url: 'https://www.fdma.go.jp/',
    description: 'Fire department emergency dispatch data',
    updateInterval: 300,
    layer: 'emergency',
    free: true,
    status: 'offline',
  },
  {
    id: 'jma-warnings',
    name: 'JMA Weather Warnings',
    nameJa: '気象庁 気象警報',
    type: 'api',
    category: 'safety',
    url: 'https://www.jma.go.jp/bosai/warning/',
    description: 'Weather warnings and advisories by region',
    updateInterval: 300,
    layer: 'warnings',
    free: true,
    status: 'offline',
  },

  // ── Infrastructure / IoT ─────────────────────────────────────────────
  {
    id: 'mlit-river',
    name: 'MLIT River Water Levels',
    nameJa: '国交省 河川水位情報',
    type: 'api',
    category: 'infrastructure',
    url: 'https://www.river.go.jp/',
    description: 'Real-time river water level monitoring (10-min)',
    updateInterval: 600,
    layer: 'river',
    free: true,
    status: 'offline',
  },
  {
    id: 'xrain-radar',
    name: 'XRAIN Rain Radar',
    nameJa: 'XRAIN 高解像度降雨レーダー',
    type: 'api',
    category: 'infrastructure',
    url: 'https://www.river.go.jp/x/',
    description: 'High-resolution rain radar imagery (1-min)',
    updateInterval: 60,
    layer: 'radar',
    free: true,
    status: 'offline',
  },
  {
    id: 'traffic-cameras',
    name: 'Road Traffic Cameras (JARTIC)',
    nameJa: 'JARTIC 道路交通カメラ',
    type: 'web_request',
    category: 'infrastructure',
    url: 'https://www.jartic.or.jp/',
    description: 'Live road traffic camera feeds',
    updateInterval: 300,
    layer: 'cameras',
    free: true,
    status: 'offline',
  },
  {
    id: 'public-webcams',
    name: 'Public Webcams / Livecams',
    nameJa: '公開ウェブカメラ',
    type: 'scraped',
    category: 'infrastructure',
    url: 'https://livecam.asia/',
    description: 'Aggregated public webcam and livecam feeds across Japan',
    updateInterval: 3600,
    layer: 'cameras',
    free: true,
    status: 'offline',
  },

  // ── Communications / Cyber ───────────────────────────────────────────
  {
    id: 'shodan-japan',
    name: 'Shodan Japan IoT Devices',
    nameJa: 'Shodan 日本IoTデバイス',
    type: 'api',
    category: 'cyber',
    url: 'https://api.shodan.io/',
    description: 'Internet-connected devices in Japan via Shodan',
    updateInterval: 86400,
    layer: 'cyber',
    free: false,
    status: 'offline',
  },
  {
    id: 'censys-japan',
    name: 'Censys Japan Scan Data',
    nameJa: 'Censys 日本スキャンデータ',
    type: 'api',
    category: 'cyber',
    url: 'https://search.censys.io/api/',
    description: 'Host and certificate scan data for Japanese IP ranges',
    updateInterval: 86400,
    layer: 'cyber',
    free: false,
    status: 'offline',
  },
  {
    id: 'insecam-japan',
    name: 'Insecam Public Cameras',
    nameJa: 'Insecam 公開カメラ',
    type: 'scraped',
    category: 'cyber',
    url: 'http://www.insecam.org/en/bycountry/JP/',
    description: 'Publicly accessible IP cameras in Japan',
    updateInterval: 86400,
    layer: 'cameras',
    free: true,
    status: 'offline',
  },

  // ── Social / Media ───────────────────────────────────────────────────
  {
    id: 'twitter-geo',
    name: 'Twitter/X Geotagged Posts',
    nameJa: 'Twitter/X ジオタグ投稿',
    type: 'api',
    category: 'social',
    url: 'https://api.twitter.com/2/',
    description: 'Geotagged tweets from Japan',
    updateInterval: 300,
    layer: 'social',
    free: false,
    status: 'offline',
  },
  {
    id: 'flickr-geo',
    name: 'Flickr Geotagged Photos',
    nameJa: 'Flickr ジオタグ写真',
    type: 'api',
    category: 'social',
    url: 'https://api.flickr.com/services/rest/',
    description: 'Geotagged photos from Flickr in Japan',
    updateInterval: 3600,
    layer: 'social',
    free: true,
    status: 'offline',
  },
  {
    id: 'youtube-live',
    name: 'YouTube Live Streams Japan',
    nameJa: 'YouTube ライブ配信 日本',
    type: 'api',
    category: 'social',
    url: 'https://www.googleapis.com/youtube/v3/',
    description: 'Live streaming videos geolocated in Japan',
    updateInterval: 600,
    layer: 'social',
    free: false,
    status: 'offline',
  },

  // ── Satellite ────────────────────────────────────────────────────────
  {
    id: 'tellus-satellite',
    name: 'Tellus Satellite Imagery',
    nameJa: 'Tellus 衛星画像',
    type: 'api',
    category: 'satellite',
    url: 'https://www.tellusxdp.com/',
    description: 'Japanese satellite imagery platform',
    updateInterval: 86400,
    layer: 'satellite',
    free: true,
    status: 'offline',
  },
  {
    id: 'sentinel-japan',
    name: 'Sentinel Hub Japan',
    nameJa: 'Sentinel Hub 日本',
    type: 'api',
    category: 'satellite',
    url: 'https://services.sentinel-hub.com/',
    description: 'Copernicus Sentinel satellite imagery over Japan',
    updateInterval: 86400,
    layer: 'satellite',
    free: true,
    status: 'offline',
  },

  // ── Commercial ──────────────────────────────────────────────────────
  {
    id: 'docomo-population',
    name: 'NTT Docomo Population Stats',
    nameJa: 'NTTドコモ モバイル空間統計',
    type: 'api',
    category: 'commercial',
    url: 'https://mobaku.jp/',
    description: 'Mobile spatial statistics from NTT Docomo (paid)',
    updateInterval: 3600,
    layer: 'population',
    free: false,
    status: 'offline',
  },
  {
    id: 'agoop-flow',
    name: 'Agoop People Flow',
    nameJa: 'Agoop 人流データ',
    type: 'api',
    category: 'commercial',
    url: 'https://www.agoop.co.jp/',
    description: 'People flow analytics data (paid)',
    updateInterval: 3600,
    layer: 'population',
    free: false,
    status: 'offline',
  },

  // ── Environment Extended ────────────────────────────────────────────
  { id: 'jma-amedas', name: 'JMA AMeDAS', nameJa: 'アメダス', type: 'api', category: 'environment', url: 'https://www.jma.go.jp/bosai/amedas/', description: 'Automated Meteorological Data Acquisition System stations', updateInterval: 600, layer: 'weather', free: true, status: 'offline' },
  { id: 'jma-himawari', name: 'JMA Himawari Satellite', nameJa: 'ひまわり衛星', type: 'api', category: 'environment', url: 'https://www.jma.go.jp/bosai/map.html', description: 'Himawari-9 geostationary satellite imagery', updateInterval: 600, layer: 'satellite', free: true, status: 'offline' },
  { id: 'jma-typhoon', name: 'JMA Typhoon Track', nameJa: '気象庁 台風情報', type: 'api', category: 'environment', url: 'https://www.jma.go.jp/bosai/map.html#contents=typhoon', description: 'Typhoon tracking and forecast paths', updateInterval: 3600, layer: 'weather', free: true, status: 'offline' },
  { id: 'jma-uv', name: 'JMA UV Index', nameJa: '気象庁 紫外線情報', type: 'api', category: 'environment', url: 'https://www.jma.go.jp/bosai/uv/', description: 'UV index forecast data', updateInterval: 3600, layer: 'weather', free: true, status: 'offline' },
  { id: 'jma-pollen', name: 'Pollen Forecast', nameJa: '環境省花粉情報', type: 'api', category: 'environment', url: 'https://kafun.env.go.jp/', description: 'Cedar and cypress pollen distribution forecast', updateInterval: 3600, layer: 'air-quality', free: true, status: 'offline' },
  { id: 'pm25-japan', name: 'PM2.5 Distribution', nameJa: 'PM2.5分布予測', type: 'api', category: 'environment', url: 'https://pm25.jp/', description: 'PM2.5 real-time distribution map', updateInterval: 3600, layer: 'air-quality', free: true, status: 'offline' },
  { id: 'windy-japan', name: 'Windy Japan', nameJa: 'Windy 日本', type: 'web_request', category: 'environment', url: 'https://www.windy.com/', description: 'Wind and weather visualization overlay', updateInterval: 1800, layer: 'weather', free: true, status: 'offline' },
  { id: 'tenki-jp', name: 'tenki.jp Weather', nameJa: 'tenki.jp 天気', type: 'scraped', category: 'environment', url: 'https://tenki.jp/', description: 'Detailed Japanese weather forecasts', updateInterval: 1800, layer: 'weather', free: true, status: 'offline' },

  // ── Seismic / Volcanic ──────────────────────────────────────────────
  { id: 'hi-net', name: 'NIED Hi-net Seismograph', nameJa: 'Hi-net 高感度地震観測網', type: 'api', category: 'seismic', url: 'https://www.hinet.bosai.go.jp/', description: 'High-sensitivity seismograph network', updateInterval: 60, layer: 'earthquake', free: true, status: 'offline' },
  { id: 'k-net', name: 'NIED K-NET Strong Motion', nameJa: 'K-NET 強震観測網', type: 'api', category: 'seismic', url: 'https://www.kyoshin.bosai.go.jp/', description: 'Strong-motion seismograph network', updateInterval: 60, layer: 'earthquake', free: true, status: 'offline' },
  { id: 'jma-intensity', name: 'JMA Seismic Intensity', nameJa: '気象庁 震度情報', type: 'api', category: 'seismic', url: 'https://www.jma.go.jp/bosai/map.html#contents=intensity', description: 'Real-time seismic intensity map', updateInterval: 30, layer: 'earthquake', free: true, status: 'offline' },
  { id: 'vnet', name: 'V-net Volcano Observation', nameJa: 'V-net 火山観測網', type: 'api', category: 'seismic', url: 'https://www.vnet.bosai.go.jp/', description: 'Fundamental Volcano Observation Network', updateInterval: 600, layer: 'volcano', free: true, status: 'offline' },
  { id: 'bosai-volcano-cam', name: 'NIED Volcano Cameras', nameJa: '防災科研 火山カメラ', type: 'web_request', category: 'seismic', url: 'https://www.vnet.bosai.go.jp/', description: 'Live volcano monitoring cameras', updateInterval: 300, layer: 'cameras', free: true, status: 'offline' },

  // ── Ocean / Marine ──────────────────────────────────────────────────
  { id: 'jma-ocean-wave', name: 'JMA Ocean Wave', nameJa: '気象庁 波浪予報', type: 'api', category: 'ocean', url: 'https://www.jma.go.jp/bosai/wave/', description: 'Ocean wave height forecast', updateInterval: 3600, layer: 'ocean', free: true, status: 'offline' },
  { id: 'jma-ocean-temp', name: 'JMA Sea Surface Temp', nameJa: '気象庁 海面水温', type: 'api', category: 'ocean', url: 'https://www.jma.go.jp/bosai/ocean/', description: 'Sea surface temperature data', updateInterval: 86400, layer: 'ocean', free: true, status: 'offline' },
  { id: 'jma-tide', name: 'JMA Tide Level', nameJa: '気象庁 潮位情報', type: 'api', category: 'ocean', url: 'https://www.jma.go.jp/bosai/tide/', description: 'Tidal observation data', updateInterval: 3600, layer: 'ocean', free: true, status: 'offline' },
  { id: 'jcg-ais', name: 'JCG AIS Vessel Tracking', nameJa: '海上保安庁 AIS船舶追跡', type: 'api', category: 'ocean', url: 'https://www.kaiho.mlit.go.jp/', description: 'Japan Coast Guard AIS vessel positions', updateInterval: 60, layer: 'maritime', free: true, status: 'offline' },
  { id: 'nowphas-wave', name: 'NOWPHAS Wave Observation', nameJa: 'NOWPHAS 波浪観測', type: 'api', category: 'ocean', url: 'https://www.mlit.go.jp/kowan/nowphas/', description: 'Nationwide Ocean Wave information network', updateInterval: 600, layer: 'ocean', free: true, status: 'offline' },
  { id: 'jamstec-argo', name: 'JAMSTEC Argo Floats', nameJa: 'JAMSTEC アルゴフロート', type: 'api', category: 'ocean', url: 'https://www.jamstec.go.jp/', description: 'Deep ocean profiling float data', updateInterval: 86400, layer: 'ocean', free: true, status: 'offline' },
  { id: 'jma-ice', name: 'JMA Sea Ice Okhotsk', nameJa: '気象庁 オホーツク海氷', type: 'api', category: 'ocean', url: 'https://www.jma.go.jp/bosai/ice/', description: 'Sea ice extent in Sea of Okhotsk', updateInterval: 86400, layer: 'ocean', free: true, status: 'offline' },

  // ── Transport Extended ──────────────────────────────────────────────
  { id: 'odpt-flight', name: 'ODPT Flight Data', nameJa: 'ODPT 航空データ', type: 'api', category: 'transport', url: 'https://api.odpt.org/api/v4/', description: 'Flight arrival/departure data', updateInterval: 300, layer: 'aviation', free: true, status: 'offline' },
  { id: 'jartic-traffic', name: 'JARTIC Road Traffic', nameJa: 'JARTIC 道路交通情報', type: 'web_request', category: 'transport', url: 'https://www.jartic.or.jp/', description: 'Road congestion and incident data', updateInterval: 300, layer: 'transport', free: true, status: 'offline' },
  { id: 'flightradar-jp', name: 'FlightRadar24 Japan', nameJa: 'FlightRadar24 日本', type: 'scraped', category: 'transport', url: 'https://www.flightradar24.com/', description: 'Live aircraft positions over Japan', updateInterval: 60, layer: 'aviation', free: true, status: 'offline' },
  { id: 'marinetraffic-jp', name: 'MarineTraffic Japan', nameJa: 'MarineTraffic 日本', type: 'scraped', category: 'transport', url: 'https://www.marinetraffic.com/', description: 'Live vessel positions around Japan', updateInterval: 300, layer: 'maritime', free: true, status: 'offline' },
  { id: 'jr-east-delay', name: 'JR East Delay Info', nameJa: 'JR東日本 運行情報', type: 'web_request', category: 'transport', url: 'https://traininfo.jreast.co.jp/', description: 'JR East train delay and disruption info', updateInterval: 60, layer: 'transport', free: true, status: 'offline' },
  { id: 'jr-west-delay', name: 'JR West Delay Info', nameJa: 'JR西日本 運行情報', type: 'web_request', category: 'transport', url: 'https://trafficinfo.westjr.co.jp/', description: 'JR West train service status', updateInterval: 60, layer: 'transport', free: true, status: 'offline' },
  { id: 'jr-central-delay', name: 'JR Central Delay Info', nameJa: 'JR東海 運行情報', type: 'web_request', category: 'transport', url: 'https://traininfo.jr-central.co.jp/', description: 'JR Central / Shinkansen status', updateInterval: 60, layer: 'transport', free: true, status: 'offline' },
  { id: 'shinkansen-status', name: 'Shinkansen Line Status', nameJa: '新幹線 運行状況', type: 'web_request', category: 'transport', url: 'https://www.jreast.co.jp/shinkansen/', description: 'All Shinkansen lines operational status', updateInterval: 60, layer: 'transport', free: true, status: 'offline' },
  { id: 'narita-flights', name: 'Narita Airport Flights', nameJa: '成田空港 フライト情報', type: 'web_request', category: 'transport', url: 'https://www.narita-airport.jp/', description: 'Narita Airport live arrivals/departures', updateInterval: 300, layer: 'aviation', free: true, status: 'offline' },
  { id: 'haneda-flights', name: 'Haneda Airport Flights', nameJa: '羽田空港 フライト情報', type: 'web_request', category: 'transport', url: 'https://tokyo-haneda.com/', description: 'Haneda Airport live flight data', updateInterval: 300, layer: 'aviation', free: true, status: 'offline' },
  { id: 'cycling-ports', name: 'Bike Share Ports', nameJa: 'シェアサイクル ポート', type: 'api', category: 'transport', url: 'https://docomo-cycle.jp/', description: 'Docomo bike sharing port locations and availability', updateInterval: 3600, layer: 'transport', free: true, status: 'offline' },
  { id: 'mlit-road-traffic', name: 'MLIT Road Traffic Census', nameJa: '国交省 道路交通センサス', type: 'dataset', category: 'transport', url: 'https://www.mlit.go.jp/road/', description: 'Road traffic volume census data', updateInterval: 604800, layer: 'transport', free: true, status: 'offline' },

  // ── Geospatial Extended ─────────────────────────────────────────────
  { id: 'plateau-tokyo23', name: 'PLATEAU Tokyo 23 Wards', nameJa: 'PLATEAU 東京23区', type: 'dataset', category: 'geospatial', url: 'https://www.geospatial.jp/ckan/dataset/plateau-tokyo23ku', description: 'PLATEAU 3D model for all 23 Tokyo wards', updateInterval: 604800, layer: 'buildings', free: true, status: 'offline' },
  { id: 'plateau-osaka', name: 'PLATEAU Osaka', nameJa: 'PLATEAU 大阪市', type: 'dataset', category: 'geospatial', url: 'https://www.geospatial.jp/ckan/dataset/plateau-osaka', description: 'PLATEAU 3D city model for Osaka', updateInterval: 604800, layer: 'buildings', free: true, status: 'offline' },
  { id: 'gsi-photo', name: 'GSI Aerial Photography', nameJa: '国土地理院 空中写真', type: 'api', category: 'geospatial', url: 'https://cyberjapandata.gsi.go.jp/', description: 'Aerial photography tiles from GSI', updateInterval: 86400, layer: 'basemap', free: true, status: 'offline' },
  { id: 'gsi-hazard', name: 'GSI Hazard Maps', nameJa: '国土地理院 ハザードマップ', type: 'api', category: 'geospatial', url: 'https://disaportal.gsi.go.jp/', description: 'Flood/landslide/tsunami hazard map overlays', updateInterval: 86400, layer: 'hazard', free: true, status: 'offline' },
  { id: 'gsi-active-fault', name: 'GSI Active Fault Map', nameJa: '国土地理院 活断層図', type: 'dataset', category: 'geospatial', url: 'https://www.gsi.go.jp/bousaichiri/active_fault.html', description: 'Active fault line locations', updateInterval: 604800, layer: 'hazard', free: true, status: 'offline' },
  { id: 'openstreetmap-jp', name: 'OpenStreetMap Japan', nameJa: 'OpenStreetMap 日本', type: 'dataset', category: 'geospatial', url: 'https://download.geofabrik.de/asia/japan.html', description: 'OpenStreetMap Japan data extract', updateInterval: 604800, layer: 'basemap', free: true, status: 'offline' },
  { id: 'zenrin-map', name: 'Zenrin Detailed Maps', nameJa: 'ゼンリン 住宅地図', type: 'api', category: 'geospatial', url: 'https://www.zenrin.co.jp/', description: 'High-detail Zenrin building-level maps', updateInterval: 86400, layer: 'basemap', free: false, status: 'offline' },

  // ── Statistics Extended ─────────────────────────────────────────────
  { id: 'estat-household', name: 'e-Stat Household Data', nameJa: 'e-Stat 世帯データ', type: 'api', category: 'statistics', url: 'https://api.e-stat.go.jp/', description: 'Household composition statistics', updateInterval: 86400, layer: 'population', free: true, status: 'offline' },
  { id: 'estat-employment', name: 'e-Stat Employment', nameJa: 'e-Stat 雇用統計', type: 'api', category: 'statistics', url: 'https://api.e-stat.go.jp/', description: 'Employment and labor statistics', updateInterval: 86400, layer: 'economy', free: true, status: 'offline' },
  { id: 'estat-industry', name: 'e-Stat Industry Data', nameJa: 'e-Stat 産業統計', type: 'api', category: 'statistics', url: 'https://api.e-stat.go.jp/', description: 'Industrial production statistics by region', updateInterval: 86400, layer: 'economy', free: true, status: 'offline' },
  { id: 'resas-industry', name: 'RESAS Industry Analysis', nameJa: 'RESAS 産業分析', type: 'api', category: 'statistics', url: 'https://opendata.resas-portal.go.jp/', description: 'Regional industry structure analysis', updateInterval: 86400, layer: 'economy', free: true, status: 'offline' },
  { id: 'resas-tourism', name: 'RESAS Tourism Stats', nameJa: 'RESAS 観光統計', type: 'api', category: 'statistics', url: 'https://opendata.resas-portal.go.jp/', description: 'Tourism flow and visitor statistics', updateInterval: 86400, layer: 'population', free: true, status: 'offline' },
  { id: 'jstat-map', name: 'jSTAT MAP Grid Stats', nameJa: 'jSTAT MAP 統計地図', type: 'api', category: 'statistics', url: 'https://jstatmap.e-stat.go.jp/', description: 'Grid-square based statistical mapping', updateInterval: 86400, layer: 'population', free: true, status: 'offline' },
  { id: 'mhlw-health', name: 'MHLW Health Statistics', nameJa: '厚労省 保健統計', type: 'dataset', category: 'statistics', url: 'https://www.mhlw.go.jp/toukei/', description: 'Ministry of Health health statistics', updateInterval: 604800, layer: 'health', free: true, status: 'offline' },
  { id: 'mhlw-covid', name: 'MHLW COVID-19 Data', nameJa: '厚労省 COVID-19データ', type: 'api', category: 'statistics', url: 'https://www.mhlw.go.jp/stf/covid-19/', description: 'COVID-19 case and vaccination data', updateInterval: 3600, layer: 'health', free: true, status: 'offline' },

  // ── Economy Extended ────────────────────────────────────────────────
  { id: 'homes-co', name: 'Homes.co.jp Rentals', nameJa: 'HOME\'S 賃貸情報', type: 'scraped', category: 'economy', url: 'https://www.homes.co.jp/', description: 'Rental property listings and prices', updateInterval: 86400, layer: 'landprice', free: true, status: 'offline' },
  { id: 'athome-price', name: 'At Home Real Estate', nameJa: 'アットホーム 不動産', type: 'scraped', category: 'economy', url: 'https://www.athome.co.jp/', description: 'Real estate listing prices', updateInterval: 86400, layer: 'landprice', free: true, status: 'offline' },
  { id: 'mlit-transaction', name: 'MLIT Transactions', nameJa: '国交省 不動産取引', type: 'api', category: 'economy', url: 'https://www.reinfolib.mlit.go.jp/', description: 'Actual real estate transaction records', updateInterval: 86400, layer: 'landprice', free: true, status: 'offline' },
  { id: 'convenience-stores', name: 'Convenience Stores', nameJa: 'コンビニ店舗', type: 'scraped', category: 'economy', url: 'https://www.e-map.ne.jp/', description: '7-Eleven, FamilyMart, Lawson locations', updateInterval: 604800, layer: 'poi', free: true, status: 'offline' },
  { id: 'gas-stations', name: 'Gas Station Prices', nameJa: 'ガソリン価格', type: 'scraped', category: 'economy', url: 'https://gogo.gs/', description: 'Gas station locations and fuel prices', updateInterval: 3600, layer: 'poi', free: true, status: 'offline' },
  { id: 'tabelog-restaurants', name: 'Tabelog Restaurants', nameJa: '食べログ レストラン', type: 'scraped', category: 'economy', url: 'https://tabelog.com/', description: 'Restaurant ratings and locations', updateInterval: 86400, layer: 'poi', free: true, status: 'offline' },

  // ── Safety / Disaster Extended ──────────────────────────────────────
  { id: 'hazard-map-portal', name: 'Hazard Map Portal', nameJa: 'ハザードマップポータル', type: 'api', category: 'safety', url: 'https://disaportal.gsi.go.jp/', description: 'National hazard map portal for all disaster types', updateInterval: 604800, layer: 'hazard', free: true, status: 'offline' },
  { id: 'j-shis-seismic', name: 'J-SHIS Seismic Hazard', nameJa: 'J-SHIS 地震ハザード', type: 'api', category: 'safety', url: 'https://www.j-shis.bosai.go.jp/', description: 'Probabilistic seismic hazard maps', updateInterval: 604800, layer: 'hazard', free: true, status: 'offline' },
  { id: 'saigai-info', name: 'Cabinet Office Disaster', nameJa: '内閣府 災害情報', type: 'api', category: 'safety', url: 'https://www.bousai.go.jp/', description: 'Cabinet Office disaster information system', updateInterval: 300, layer: 'emergency', free: true, status: 'offline' },
  { id: 'dam-water-level', name: 'Dam Water Levels', nameJa: 'ダム貯水位', type: 'api', category: 'safety', url: 'https://www.river.go.jp/', description: 'Dam reservoir water level monitoring', updateInterval: 600, layer: 'river', free: true, status: 'offline' },
  { id: 'bosai-shelter', name: 'Emergency Shelters', nameJa: '指定緊急避難場所', type: 'dataset', category: 'safety', url: 'https://www.gsi.go.jp/bousaichiri/hinanbasho.html', description: 'Designated emergency evacuation shelter locations', updateInterval: 604800, layer: 'safety', free: true, status: 'offline' },
  { id: 'aed-map', name: 'AED Locations', nameJa: 'AED設置場所', type: 'dataset', category: 'safety', url: 'https://www.qqzaidanmap.jp/', description: 'Automated External Defibrillator locations', updateInterval: 604800, layer: 'safety', free: true, status: 'offline' },
  { id: 'koban-map', name: 'Police Box Locations', nameJa: '交番・駐在所', type: 'dataset', category: 'safety', url: 'https://www.npa.go.jp/', description: 'Koban (police box) and police station locations', updateInterval: 604800, layer: 'safety', free: true, status: 'offline' },
  { id: 'hospital-map', name: 'Hospital Locations', nameJa: '病院・医療機関', type: 'api', category: 'safety', url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/', description: 'Hospital and clinic location database', updateInterval: 86400, layer: 'safety', free: true, status: 'offline' },
  { id: 'fire-station-map', name: 'Fire Station Locations', nameJa: '消防署', type: 'dataset', category: 'safety', url: 'https://www.fdma.go.jp/', description: 'Fire station and fire department locations', updateInterval: 604800, layer: 'safety', free: true, status: 'offline' },

  // ── Infrastructure Extended ─────────────────────────────────────────
  { id: 'mlit-dam', name: 'MLIT Dam Data', nameJa: '国交省 ダム情報', type: 'api', category: 'infrastructure', url: 'https://www.river.go.jp/', description: 'Dam operational data and water storage', updateInterval: 600, layer: 'river', free: true, status: 'offline' },
  { id: 'tepco-power', name: 'TEPCO Power Usage', nameJa: '東京電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.tepco.co.jp/', description: 'Tokyo Electric Power usage and capacity', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'kepco-power', name: 'KEPCO Power Usage', nameJa: '関西電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.kepco.co.jp/', description: 'Kansai Electric Power usage data', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'chubu-power', name: 'Chubu Electric Power', nameJa: '中部電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.chuden.co.jp/', description: 'Chubu Electric Power usage', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'tohoku-power', name: 'Tohoku Electric Power', nameJa: '東北電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.tohoku-epco.co.jp/', description: 'Tohoku Electric Power usage', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'cell-tower-jp', name: 'Cell Tower Locations', nameJa: '携帯基地局', type: 'dataset', category: 'infrastructure', url: 'https://www.tele.soumu.go.jp/', description: 'Cell tower and base station locations', updateInterval: 604800, layer: 'telecom', free: true, status: 'offline' },
  { id: 'ev-charging', name: 'EV Charging Stations', nameJa: 'EV充電スタンド', type: 'api', category: 'infrastructure', url: 'https://ev.gogo.gs/', description: 'Electric vehicle charging station map', updateInterval: 86400, layer: 'poi', free: true, status: 'offline' },
  { id: 'wifi-hotspot', name: 'Free WiFi Hotspots', nameJa: 'フリーWiFiスポット', type: 'dataset', category: 'infrastructure', url: 'https://flets.com/freewifi/', description: 'Free WiFi hotspot locations across Japan', updateInterval: 604800, layer: 'telecom', free: true, status: 'offline' },

  // ── Cyber / IoT Extended ────────────────────────────────────────────
  { id: 'nicter-darknet', name: 'NICTER Darknet Monitor', nameJa: 'NICTER ダークネット観測', type: 'web_request', category: 'cyber', url: 'https://www.nicter.jp/', description: 'NICT darknet traffic monitoring', updateInterval: 3600, layer: 'cyber', free: true, status: 'offline' },
  { id: 'jpcert-alerts', name: 'JPCERT/CC Alerts', nameJa: 'JPCERT/CC 注意喚起', type: 'api', category: 'cyber', url: 'https://www.jpcert.or.jp/', description: 'JPCERT Coordination Center security alerts', updateInterval: 3600, layer: 'cyber', free: true, status: 'offline' },
  { id: 'ipa-vuln', name: 'IPA Vulnerability DB', nameJa: 'IPA 脆弱性対策情報', type: 'api', category: 'cyber', url: 'https://jvndb.jvn.jp/', description: 'IPA/JVN vulnerability database', updateInterval: 86400, layer: 'cyber', free: true, status: 'offline' },
  { id: 'atlas-jp', name: 'RIPE Atlas Japan Probes', nameJa: 'RIPE Atlas 日本プローブ', type: 'api', category: 'cyber', url: 'https://atlas.ripe.net/', description: 'RIPE Atlas internet measurement probes in Japan', updateInterval: 3600, layer: 'cyber', free: true, status: 'offline' },

  // ── Social / Culture Extended ───────────────────────────────────────
  { id: 'instagram-geo', name: 'Instagram Geotagged', nameJa: 'Instagram ジオタグ', type: 'scraped', category: 'social', url: 'https://www.instagram.com/', description: 'Geotagged Instagram posts from Japan', updateInterval: 600, layer: 'social', free: false, status: 'offline' },
  { id: 'tiktok-geo', name: 'TikTok Geotagged', nameJa: 'TikTok ジオタグ', type: 'scraped', category: 'social', url: 'https://www.tiktok.com/', description: 'Geotagged TikTok content from Japan', updateInterval: 600, layer: 'social', free: false, status: 'offline' },
  { id: 'google-trends-jp', name: 'Google Trends Japan', nameJa: 'Googleトレンド 日本', type: 'web_request', category: 'social', url: 'https://trends.google.co.jp/', description: 'Trending search topics by region in Japan', updateInterval: 3600, layer: 'social', free: true, status: 'offline' },
  { id: 'yahoo-realtime', name: 'Yahoo! Japan Realtime', nameJa: 'Yahoo!リアルタイム検索', type: 'scraped', category: 'social', url: 'https://search.yahoo.co.jp/realtime', description: 'Yahoo! Japan real-time trending topics', updateInterval: 300, layer: 'social', free: true, status: 'offline' },
  { id: '5ch-activity', name: '5ch Board Activity', nameJa: '5ちゃんねる 掲示板', type: 'scraped', category: 'social', url: 'https://5ch.net/', description: '5ch/2ch anonymous board activity metrics', updateInterval: 600, layer: 'social', free: true, status: 'offline' },
  { id: 'matsuri-events', name: 'Festival Calendar', nameJa: '祭り・イベント情報', type: 'scraped', category: 'social', url: 'https://www.walkerplus.com/festival/', description: 'Japanese festival and event calendar with locations', updateInterval: 86400, layer: 'events', free: true, status: 'offline' },
  { id: 'shrine-temple', name: 'Shrine & Temple Map', nameJa: '神社仏閣マップ', type: 'dataset', category: 'social', url: 'https://www.jinja.or.jp/', description: 'Shinto shrine and Buddhist temple locations', updateInterval: 604800, layer: 'poi', free: true, status: 'offline' },
  { id: 'onsen-map', name: 'Hot Spring Map', nameJa: '温泉マップ', type: 'dataset', category: 'social', url: 'https://www.onsen-r.co.jp/', description: 'Onsen (hot spring) locations across Japan', updateInterval: 604800, layer: 'poi', free: true, status: 'offline' },

  // ── Satellite Extended ──────────────────────────────────────────────
  { id: 'alos-palsar', name: 'ALOS/PALSAR SAR', nameJa: 'ALOS/PALSAR 合成開口レーダー', type: 'api', category: 'satellite', url: 'https://www.eorc.jaxa.jp/ALOS/', description: 'JAXA ALOS synthetic aperture radar data', updateInterval: 604800, layer: 'satellite', free: true, status: 'offline' },
  { id: 'himawari-realtime', name: 'Himawari-9 Realtime', nameJa: 'ひまわり9号 リアルタイム', type: 'api', category: 'satellite', url: 'https://www.data.jma.go.jp/mscweb/data/himawari/', description: 'Himawari-9 real-time satellite imagery', updateInterval: 600, layer: 'satellite', free: true, status: 'offline' },
  { id: 'jaxa-earth', name: 'JAXA Earth Observation', nameJa: 'JAXA 地球観測', type: 'api', category: 'satellite', url: 'https://earth.jaxa.jp/', description: 'JAXA Earth observation satellite data portal', updateInterval: 86400, layer: 'satellite', free: true, status: 'offline' },
  { id: 'landsat-jp', name: 'Landsat Japan Coverage', nameJa: 'Landsat 日本域', type: 'api', category: 'satellite', url: 'https://earthexplorer.usgs.gov/', description: 'Landsat satellite imagery covering Japan', updateInterval: 604800, layer: 'satellite', free: true, status: 'offline' },

  // ── Commercial Extended ─────────────────────────────────────────────
  { id: 'docomo-insight', name: 'Docomo Insight', nameJa: 'ドコモ・インサイト', type: 'api', category: 'commercial', url: 'https://mobaku.jp/', description: 'NTT Docomo population flow insights', updateInterval: 3600, layer: 'population', free: false, status: 'offline' },
  { id: 'softbank-crowd', name: 'SoftBank Crowd Analytics', nameJa: 'ソフトバンク 混雑統計', type: 'api', category: 'commercial', url: 'https://www.softbank.jp/', description: 'SoftBank crowd density analytics', updateInterval: 3600, layer: 'population', free: false, status: 'offline' },
  { id: 'zenrin-address', name: 'Zenrin Address Data', nameJa: 'ゼンリン 住所データ', type: 'api', category: 'commercial', url: 'https://www.zenrin.co.jp/', description: 'Zenrin address-level geocoding data', updateInterval: 86400, layer: 'basemap', free: false, status: 'offline' },
  { id: 'navitime-api', name: 'Navitime API', nameJa: 'ナビタイム API', type: 'api', category: 'commercial', url: 'https://api-sdk.navitime.co.jp/', description: 'Navitime routing and transit API', updateInterval: 300, layer: 'transport', free: false, status: 'offline' },
  { id: 'here-japan', name: 'HERE Maps Japan', nameJa: 'HERE Maps 日本', type: 'api', category: 'commercial', url: 'https://developer.here.com/', description: 'HERE location platform Japan', updateInterval: 86400, layer: 'basemap', free: false, status: 'offline' },
  { id: 'yahoo-map-api', name: 'Yahoo! Japan Map API', nameJa: 'Yahoo!地図 API', type: 'api', category: 'commercial', url: 'https://map.yahoo.co.jp/', description: 'Yahoo! Japan Map and geocoding API', updateInterval: 86400, layer: 'basemap', free: true, status: 'offline' },

  // ── Health / Medical ────────────────────────────────────────────────
  { id: 'ndb-open', name: 'NDB Open Data', nameJa: 'NDB オープンデータ', type: 'dataset', category: 'health', url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000177182.html', description: 'National Database of health insurance claims open data', updateInterval: 604800, layer: 'health', free: true, status: 'offline' },
  { id: 'pharmacy-map', name: 'Pharmacy Locations', nameJa: '薬局マップ', type: 'dataset', category: 'health', url: 'https://www.mhlw.go.jp/', description: 'Pharmacy location database across Japan', updateInterval: 604800, layer: 'safety', free: true, status: 'offline' },
  { id: 'influenza-surveillance', name: 'NIID Influenza Watch', nameJa: '国立感染研 インフルエンザ', type: 'api', category: 'health', url: 'https://www.niid.go.jp/niid/ja/flu-map.html', description: 'NIID influenza surveillance by prefecture', updateInterval: 604800, layer: 'health', free: true, status: 'offline' },
  { id: 'food-poisoning', name: 'Food Poisoning Reports', nameJa: '食中毒情報', type: 'api', category: 'health', url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/', description: 'MHLW food poisoning incident reports', updateInterval: 604800, layer: 'health', free: true, status: 'offline' },
  { id: 'cancer-registry', name: 'Cancer Registry Stats', nameJa: 'がん登録統計', type: 'dataset', category: 'health', url: 'https://ganjoho.jp/', description: 'National cancer registry incidence data', updateInterval: 604800, layer: 'health', free: true, status: 'offline' },

  // ── Additional Infrastructure / Energy ──────────────────────────────
  { id: 'kyushu-power', name: 'Kyushu Electric Power', nameJa: '九州電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.kyuden.co.jp/', description: 'Kyushu Electric Power usage', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'hokkaido-power', name: 'Hokkaido Electric Power', nameJa: '北海道電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.hepco.co.jp/', description: 'Hokkaido Electric Power grid usage', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'shikoku-power', name: 'Shikoku Electric Power', nameJa: '四国電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.yonden.co.jp/', description: 'Shikoku Electric Power usage', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'hokuriku-power', name: 'Hokuriku Electric Power', nameJa: '北陸電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.rikuden.co.jp/', description: 'Hokuriku Electric Power usage', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'chugoku-power', name: 'Chugoku Electric Power', nameJa: '中国電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.energia.co.jp/', description: 'Chugoku Electric Power usage', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'okinawa-power', name: 'Okinawa Electric Power', nameJa: '沖縄電力 電力使用状況', type: 'api', category: 'infrastructure', url: 'https://www.okiden.co.jp/', description: 'Okinawa Electric Power usage', updateInterval: 300, layer: 'energy', free: true, status: 'offline' },
  { id: 'ntt-fiber', name: 'NTT Fiber Coverage', nameJa: 'NTT光回線 エリア', type: 'web_request', category: 'infrastructure', url: 'https://flets.com/', description: 'NTT fiber optic coverage map', updateInterval: 604800, layer: 'telecom', free: true, status: 'offline' },
  { id: 'mlit-bridge', name: 'MLIT Bridge Inspection', nameJa: '国交省 橋梁点検', type: 'dataset', category: 'infrastructure', url: 'https://road-structures-map.mlit.go.jp/', description: 'Bridge condition inspection data', updateInterval: 604800, layer: 'infrastructure', free: true, status: 'offline' },

  // ── Additional Transport ────────────────────────────────────────────
  { id: 'vics-traffic', name: 'VICS Traffic Info', nameJa: 'VICS 道路交通情報', type: 'web_request', category: 'transport', url: 'https://www.vics.or.jp/', description: 'Vehicle Information Communication System traffic data', updateInterval: 300, layer: 'transport', free: true, status: 'offline' },
  { id: 'kansai-flights', name: 'Kansai Airport Flights', nameJa: '関西空港 フライト情報', type: 'web_request', category: 'transport', url: 'https://www.kansai-airport.or.jp/', description: 'Kansai International Airport flights', updateInterval: 300, layer: 'aviation', free: true, status: 'offline' },
  { id: 'ekitan-transfer', name: 'Ekitan Transfer Info', nameJa: '駅探 乗換情報', type: 'scraped', category: 'transport', url: 'https://ekitan.com/', description: 'Station transfer and route information', updateInterval: 3600, layer: 'transport', free: true, status: 'offline' },

  // ── Additional Statistics ───────────────────────────────────────────
  { id: 'estat-education', name: 'e-Stat Education Stats', nameJa: 'e-Stat 教育統計', type: 'api', category: 'statistics', url: 'https://api.e-stat.go.jp/', description: 'School enrollment and education data by region', updateInterval: 86400, layer: 'population', free: true, status: 'offline' },
  { id: 'resas-municipality', name: 'RESAS Municipal Comparison', nameJa: 'RESAS 自治体比較', type: 'api', category: 'statistics', url: 'https://opendata.resas-portal.go.jp/', description: 'Municipal-level economic/demographic comparison', updateInterval: 86400, layer: 'population', free: true, status: 'offline' },
  { id: 'covid19-japan', name: 'COVID-19 Japan Dashboard', nameJa: 'COVID-19 ダッシュボード', type: 'api', category: 'statistics', url: 'https://covid19.mhlw.go.jp/', description: 'COVID-19 Japan open data dashboard', updateInterval: 3600, layer: 'health', free: true, status: 'offline' },

  // ── Additional Economy ──────────────────────────────────────────────
  { id: 'lifull-homes', name: 'LIFULL HOME\'S', nameJa: 'LIFULL HOME\'S 物件', type: 'scraped', category: 'economy', url: 'https://www.homes.co.jp/', description: 'Real estate listings and price analysis', updateInterval: 86400, layer: 'landprice', free: true, status: 'offline' },
  { id: 'japan-reit', name: 'J-REIT Properties', nameJa: 'J-REIT 不動産', type: 'scraped', category: 'economy', url: 'https://www.japan-reit.com/', description: 'J-REIT investment property portfolio data', updateInterval: 86400, layer: 'landprice', free: true, status: 'offline' },
  { id: 'tochi-info', name: 'Tochi.info Land Use', nameJa: '土地情報 土地利用', type: 'api', category: 'economy', url: 'https://tochi.mlit.go.jp/', description: 'Land use and zoning information', updateInterval: 86400, layer: 'landprice', free: true, status: 'offline' },

  // ── Additional Social ───────────────────────────────────────────────
  { id: 'hatena-bookmark', name: 'Hatena Bookmark', nameJa: 'はてなブックマーク', type: 'scraped', category: 'social', url: 'https://b.hatena.ne.jp/', description: 'Hatena Bookmark trending topics', updateInterval: 3600, layer: 'social', free: true, status: 'offline' },

  // ── Additional Geospatial ───────────────────────────────────────────
  { id: 'chiriin-place', name: 'GSI Place Names', nameJa: '地理院 地名情報', type: 'api', category: 'geospatial', url: 'https://www.gsi.go.jp/', description: 'Official geographic place name database', updateInterval: 86400, layer: 'basemap', free: true, status: 'offline' },
  { id: 'gcom-w', name: 'GCOM-W Water Cycle', nameJa: 'GCOM-W 水循環', type: 'api', category: 'satellite', url: 'https://suzaku.eorc.jaxa.jp/GCOM_W/', description: 'GCOM-W satellite water cycle observation', updateInterval: 86400, layer: 'satellite', free: true, status: 'offline' },
  { id: 'bgp-japan', name: 'BGP Routing Japan', nameJa: 'BGPルーティング 日本', type: 'api', category: 'cyber', url: 'https://stat.ripe.net/', description: 'BGP routing data for Japanese ASNs', updateInterval: 86400, layer: 'cyber', free: true, status: 'offline' },
  { id: 'mapfan-api', name: 'MapFan API', nameJa: 'MapFan API', type: 'api', category: 'commercial', url: 'https://mapfan.com/', description: 'MapFan mapping and POI data', updateInterval: 86400, layer: 'basemap', free: false, status: 'offline' },

  // ── New: Social Media Geo (twitter/facebook/snapchat enhanced) ──────
  { id: 'twitter-geo', name: 'Twitter/X Geo Posts', nameJa: 'Twitter/X ジオ投稿', type: 'api', category: 'social', url: 'https://api.twitter.com/2/tweets/search/recent', description: 'Geocoded Twitter/X posts across Japan with engagement metrics', updateInterval: 600, layer: 'twitter-geo', free: false, status: 'live' },
  { id: 'facebook-geo', name: 'Facebook Check-ins', nameJa: 'Facebook チェックイン', type: 'api', category: 'social', url: 'https://graph.facebook.com/', description: 'Facebook check-ins and geotagged posts at landmarks across Japan', updateInterval: 1800, layer: 'facebook-geo', free: false, status: 'live' },
  { id: 'snapchat-heatmap', name: 'Snapchat Snap Map', nameJa: 'Snapchat スナップマップ', type: 'scraped', category: 'social', url: 'https://map.snapchat.com/', description: 'Snapchat Snap Map activity heatmap (youth activity zones)', updateInterval: 600, layer: 'snapchat-heatmap', free: false, status: 'live' },

  // ── New: Marketplace / Classifieds ──────────────────────────────────
  { id: 'classifieds', name: 'Jmty / Mercari / Yahoo Auctions', nameJa: 'ジモティー・メルカリ・ヤフオク', type: 'scraped', category: 'marketplace', url: 'https://jmty.jp/', description: 'Classifieds listings (free items, barter, jobs, trades) across Japan', updateInterval: 1800, layer: 'classifieds', free: true, status: 'live' },
  { id: 'real-estate', name: 'Suumo / Homes / AtHome', nameJa: 'スーモ・ホームズ・アットホーム', type: 'scraped', category: 'marketplace', url: 'https://suumo.jp/', description: 'Real estate listings (rent / sale) across Japan', updateInterval: 3600, layer: 'real-estate', free: true, status: 'live' },
  { id: 'job-boards', name: 'TownWork / Baitoru / Indeed', nameJa: 'タウンワーク・バイトル・Indeed', type: 'scraped', category: 'marketplace', url: 'https://townwork.net/', description: 'Job listings (part-time / full-time) across Japan', updateInterval: 3600, layer: 'job-boards', free: true, status: 'live' },

  // ── New: Cyber OSINT ────────────────────────────────────────────────
  { id: 'google-dorking', name: 'Google Dorking Results', nameJa: 'Google Dork 結果', type: 'web_request', category: 'cyber', url: 'https://www.google.com/search', description: 'Geo-coded Google dorking results (exposed admin panels, files, cameras, IoT)', updateInterval: 7200, layer: 'google-dorking', free: true, status: 'live' },
  { id: 'shodan-iot', name: 'Shodan IoT Devices', nameJa: 'Shodan IoT デバイス', type: 'api', category: 'cyber', url: 'https://api.shodan.io/', description: 'Internet-exposed IoT devices in Japan (cameras, routers, NAS, SCADA, PLCs)', updateInterval: 3600, layer: 'shodan-iot', free: false, status: 'live' },
  { id: 'insecam-webcams', name: 'Open Webcams', nameJa: '公開ウェブカメラ', type: 'web_request', category: 'cyber', url: 'http://www.insecam.org/en/bycountry/JP/', description: 'Open public webcams (insecam, municipal cams, ski/beach/port/volcano monitors)', updateInterval: 3600, layer: 'insecam-webcams', free: true, status: 'live' },
  { id: 'wifi-networks', name: 'WiGLE WiFi Networks', nameJa: 'WiGLE WiFi ネットワーク', type: 'api', category: 'cyber', url: 'https://api.wigle.net/', description: 'WiFi network database across Japan (SSID/BSSID/security)', updateInterval: 86400, layer: 'wifi-networks', free: false, status: 'live' },

  // ── New: Transport (nationwide expansion) ───────────────────────────
  { id: 'maritime-ais', name: 'AIS Ship Tracking', nameJa: 'AIS 船舶追跡', type: 'api', category: 'transport', url: 'https://www.marinetraffic.com/', description: 'AIS vessel positions around Japan ports and shipping lanes', updateInterval: 300, layer: 'maritime-ais', free: false, status: 'live' },
  { id: 'flight-adsb', name: 'ADS-B Flight Tracking', nameJa: 'ADS-B フライト追跡', type: 'api', category: 'transport', url: 'https://opensky-network.org/api/', description: 'ADS-B aircraft positions over Japan (airliners, GA, military)', updateInterval: 60, layer: 'flight-adsb', free: true, status: 'live' },
  { id: 'full-transport', name: 'Japan Rail Network', nameJa: '日本鉄道網', type: 'dataset', category: 'transport', url: 'https://www.jreast.co.jp/', description: 'Nationwide rail network: Shinkansen, JR lines, private railways, subways, monorails, trams', updateInterval: 86400, layer: 'full-transport', free: true, status: 'live' },
  { id: 'bus-routes', name: 'Bus Terminals', nameJa: 'バスターミナル', type: 'dataset', category: 'transport', url: 'https://www.bus.or.jp/', description: 'Highway bus terminals and city bus depots across Japan', updateInterval: 86400, layer: 'bus-routes', free: true, status: 'live' },
  { id: 'ferry-routes', name: 'Ferry Terminals', nameJa: 'フェリーターミナル', type: 'dataset', category: 'transport', url: 'https://www.jsanet.or.jp/', description: 'Ferry terminals (inter-island, Seto Inland, Okinawa, international)', updateInterval: 86400, layer: 'ferry-routes', free: true, status: 'live' },
  { id: 'highway-traffic', name: 'Expressway IC/JCT/SA/PA', nameJa: '高速道路 IC/JCT/SA/PA', type: 'web_request', category: 'transport', url: 'https://www.driveplaza.com/', description: 'NEXCO expressway interchanges, junctions, service areas, parking areas, congestion', updateInterval: 600, layer: 'highway-traffic', free: true, status: 'live' },

  // ── New: Infrastructure Networks ────────────────────────────────────
  { id: 'electrical-grid', name: 'Electrical Grid', nameJa: '電力網', type: 'dataset', category: 'infrastructure', url: 'https://www.fepc.or.jp/', description: 'Power plants (thermal/hydro/wind/solar/geothermal), substations, frequency converters', updateInterval: 86400, layer: 'electrical-grid', free: true, status: 'live' },
  { id: 'gas-network', name: 'Gas Network', nameJa: 'ガス網', type: 'dataset', category: 'infrastructure', url: 'https://www.gas.or.jp/', description: 'LNG terminals, distribution stations across Tokyo/Osaka/Toho/Saibu/Hokkaido Gas + JERA', updateInterval: 86400, layer: 'gas-network', free: true, status: 'live' },
  { id: 'water-infra', name: 'Water Infrastructure', nameJa: '水道インフラ', type: 'dataset', category: 'infrastructure', url: 'https://www.mlit.go.jp/river/', description: 'Major dams, water treatment plants, sewage treatment plants', updateInterval: 86400, layer: 'water-infra', free: true, status: 'live' },
  { id: 'cell-towers', name: 'Cell Towers', nameJa: '携帯基地局', type: 'api', category: 'infrastructure', url: 'https://opencellid.org/', description: 'Mobile network base stations (Docomo, au, SoftBank, Rakuten Mobile) - 4G/5G', updateInterval: 86400, layer: 'cell-towers', free: false, status: 'live' },
  { id: 'nuclear-facilities', name: 'Nuclear Facilities', nameJa: '原子力施設', type: 'dataset', category: 'infrastructure', url: 'https://www.nra.go.jp/', description: 'Nuclear power plants, fuel cycle facilities, research reactors, waste storage sites', updateInterval: 86400, layer: 'nuclear-facilities', free: true, status: 'live' },
];

export default sources;
