/* Originally GENERATED from server/src/utils/sourceRegistry.js. That generator
   is gone with the Node server, so THIS FILE IS NOW THE SOURCE OF TRUTH and is
   edited by hand.
   Deduplicated by id (registry had 427 rows, 7 duplicate
   ids removed → 420 unique; 5 breach-probe stubs since removed → 415).

   Camera rows reconciled with the C collectors (2026-07): the Node registry
   named the camera channels camscape-jp / insecam-japan / scs-com-ua /
   tabi-cam-jp / webcamendirect-net / windy-webcams, but the C port registers
   them as cam-camscape / cam-insecam-scrape / cam-scs_com_ua / cam-tabi_cam /
   cam-webcamendirect_list / cam-windy_api. The ids here now match the live
   source_defs (with update_interval aligned to the defs' 21600s), so the
   curated metadata actually attaches instead of describing sources that no
   longer exist. traffic-cameras, public-webcams and manual-ip-cams were
   dropped — no collector was ever ported for them, so they only inflated the
   cameras layer with rows that could never report a status.
   For each colliding id the LAST
   definition is kept (the canonical, more-specific one); single C
   backend, parity with the retired Node server no longer required.

   THIS TABLE IS AN OVERLAY, NOT THE REGISTRY. The registry is the set of
   `source_def`s that self-register at load time (native/source.h); every field
   here also exists inline on `source_def`, and source_registry_dyn.c layers
   this table on top of the live registry. A NEW SOURCE MUST NOT BE ADDED HERE
   — declare .category/.type/.url/.description/.license/.layer/.free_tier on
   its source_def and the catalog, /api/layers and /api/status pick it up with
   no generated file to edit. What still earns a row here is the ~320 curated
   Node-era rows whose rich JA names and descriptions were never transcribed
   back onto their defs.

   2026-08-09: 66 rows removed — every row whose collector was deleted in the
   66-source removal sweep (53 probe stubs + 8 key-gated + 5 scrapers). A row
   with no registered source_def cannot ever report a status, and 48 of these
   were the SOLE member of a layer, so /api/layers advertised 48 layers whose
   GeoJSON is permanently an empty FeatureCollection. Verified against the
   binary's own `--list-sources` (some ids are computed, not written as
   literals, so grep is not authoritative). 387 → 321 rows.
   `osint-search` deliberately stays: it has no source_def because it is the
   pipeline's synthetic source_id for entity-pivot results (core/pipeline.c
   binds intel rows to it), so real rows carry it and it must keep its name /
   description in /api/intel/sources. Its layer is NULL, so it adds nothing to
   /api/layers.

   Fields: id,name,name_ja,category,type,url,description,license,
           layer,free(0|1),update_interval(<0 == null/absent).

   `category` vocabulary: see the canonical list in native/source.h. */
#include "source_registry.h"
#include <string.h>
static const src_meta M[]={
{"osint-search","Interactive OSINT Search","対話型OSINT検索","investigation","api","internal://osint-search","Entity-pivot OSINT search results (ported OSINTsaas pipeline)",NULL,NULL,1,0},
{"jma-earthquake","JMA Earthquake API","気象庁 地震情報","environment","api","https://www.jma.go.jp/bosai/quake/data/list.json","Real-time earthquake data from the Japan Meteorological Agency",NULL,"earthquake",1,60},
{"gdelt-events","GDELT Global Events","GDELT グローバル・イベント","intelligence","api","https://api.gdeltproject.org/api/v2/geo/geo","Global geopolitical events (articles, protests, diplomacy) from GDELT 2.0, filtered to Japan",NULL,"gdelt",1,900},
{"jma-weather","JMA Weather Forecast","気象庁 天気予報","environment","api","https://www.jma.go.jp/bosai/forecast/","Weather forecast data for all prefectures",NULL,"weather",1,3600},
{"jma-tsunami","JMA Tsunami Warnings","気象庁 津波情報","environment","api","https://www.jma.go.jp/bosai/tsunami/","Tsunami warning and advisory data",NULL,"tsunami",1,60},
{"jma-volcano","JMA Volcanic Alerts","気象庁 火山情報","environment","api","https://www.jma.go.jp/bosai/volcano/","Volcanic activity alerts and warnings",NULL,"volcano",1,3600},
{"soramame","SORAMAME Air Quality","そらまめ君 大気汚染情報","environment","api","http://soramame.env.go.jp/","Hourly air quality monitoring station data (PM2.5, Ox, SO2, etc.)",NULL,"air-quality",1,3600},
{"nra-radiation","NRA Radiation Monitoring","原子力規制委員会 放射線モニタリング","environment","api","https://radioactivity.nra.go.jp/","Real-time radiation dose monitoring across Japan (10-min intervals)",NULL,"radiation",1,600},
{"odpt-train","ODPT Train Real-time","ODPT 鉄道リアルタイム","transport","api","https://api.odpt.org/api/v4/","Real-time train location and delay data in Tokyo metro area",NULL,"transport",1,30},
{"odpt-bus","ODPT Bus Real-time","ODPT バスリアルタイム","transport","api","https://api.odpt.org/api/v4/","Real-time bus location data",NULL,"transport",1,30},
{"odpt-station","ODPT Station Data","ODPT 駅データ","transport","api","https://api.odpt.org/api/v4/","Static station location and metadata",NULL,"transport",1,86400},
{"nlni-landuse","National Land Numerical Info","国土数値情報 土地利用","geospatial","dataset","https://nlftp.mlit.go.jp/ksj/","Land use mesh data from MLIT",NULL,"landuse",1,604800},
{"estat-population","e-Stat Population Mesh","e-Stat 人口メッシュ","statistics","api","https://api.e-stat.go.jp/","Grid-square population statistics",NULL,"population",1,86400},
{"mlit-landprice","MLIT Land Price Survey","国交省 地価公示","economy","api","https://www.land.mlit.go.jp/webland/api/","Official land price survey data",NULL,"landprice",1,86400},
{"reinfolib","Real Estate Transaction Prices","不動産取引価格情報","economy","api","https://www.reinfolib.mlit.go.jp/","Actual real estate transaction price data",NULL,"landprice",1,86400},
{"suumo","Suumo Rental Prices","SUUMO 賃料情報","economy","scraped","https://suumo.jp/","Scraped rental price listings",NULL,"landprice",1,86400},
{"police-incidents","Prefectural Police Crime Maps","都道府県警 犯罪発生マップ","safety","scraped","https://www.keishicho.metro.tokyo.lg.jp/jiken_jiko/hassei/index.html","Crime incident reports from prefectural police",NULL,"crime",1,86400},
{"fire-department","Fire Department Dispatches","消防庁 出動情報","safety","web_request","https://www.fdma.go.jp/","Fire department emergency dispatch data",NULL,"emergency",1,300},
{"jma-warnings","JMA Weather Warnings","気象庁 気象警報","safety","api","https://www.jma.go.jp/bosai/warning/","Weather warnings and advisories by region",NULL,"warnings",1,300},
{"mlit-river","MLIT River Water Levels","国交省 河川水位情報","infrastructure","api","https://www.river.go.jp/","Real-time river water level monitoring (10-min)",NULL,"river",1,600},
{"shodan-japan","Shodan Japan IoT Devices","Shodan 日本IoTデバイス","cyber","api","https://api.shodan.io/","Internet-connected devices in Japan via Shodan",NULL,"cyber",0,86400},
{"cam-insecam-scrape","Insecam Public Cameras","Insecam 公開カメラ","cyber","scraped","http://www.insecam.org/en/bycountry/JP/","Publicly accessible IP cameras in Japan",NULL,"cameras",1,21600},
{"flickr-geo","Flickr Geotagged Photos","Flickr ジオタグ写真","social","api","https://api.flickr.com/services/rest/","Geotagged photos from Flickr in Japan",NULL,"social",1,3600},
{"tellus-satellite","Tellus Satellite Imagery","Tellus 衛星画像","satellite","api","https://www.tellusxdp.com/","Japanese satellite imagery platform",NULL,"satellite",1,86400},
{"sentinel-japan","Sentinel Hub Japan","Sentinel Hub 日本","satellite","api","https://services.sentinel-hub.com/","Copernicus Sentinel satellite imagery over Japan",NULL,"satellite",1,86400},
{"docomo-population","NTT Docomo Population Stats","NTTドコモ モバイル空間統計","commercial","api","https://mobaku.jp/","Mobile spatial statistics from NTT Docomo (paid)",NULL,"population",0,3600},
{"agoop-flow","Agoop People Flow","Agoop 人流データ","commercial","api","https://www.agoop.co.jp/","People flow analytics data (paid)",NULL,"population",0,3600},
{"jma-himawari","JMA Himawari Satellite","ひまわり衛星","environment","api","https://www.jma.go.jp/bosai/map.html","Himawari-9 geostationary satellite imagery",NULL,"satellite",1,600},
{"pm25-japan","PM2.5 Distribution","PM2.5分布予測","environment","api","https://pm25.jp/","PM2.5 real-time distribution map",NULL,"air-quality",1,3600},
{"windy-japan","Windy Japan","Windy 日本","environment","web_request","https://www.windy.com/","Wind and weather visualization overlay",NULL,"weather",1,1800},
{"tenki-jp","tenki.jp Weather","tenki.jp 天気","environment","scraped","https://tenki.jp/","Detailed Japanese weather forecasts",NULL,"weather",1,1800},
{"jamstec-argo","JAMSTEC Argo Floats","JAMSTEC アルゴフロート","ocean","api","https://www.jamstec.go.jp/","Deep ocean profiling float data",NULL,"ocean",1,86400},
{"jma-ice","JMA Sea Ice Okhotsk","気象庁 オホーツク海氷","ocean","api","https://www.jma.go.jp/bosai/ice/","Sea ice extent in Sea of Okhotsk",NULL,"ocean",1,86400},
{"odpt-flight","ODPT Flight Data","ODPT 航空データ","transport","api","https://api.odpt.org/api/v4/","Flight arrival/departure data",NULL,"aviation",1,300},
{"flightradar-jp","FlightRadar24 Japan","FlightRadar24 日本","transport","scraped","https://www.flightradar24.com/","Live aircraft positions over Japan",NULL,"aviation",1,60},
{"marinetraffic-jp","MarineTraffic Japan","MarineTraffic 日本","transport","scraped","https://www.marinetraffic.com/","Live vessel positions around Japan",NULL,"maritime",1,300},
{"cycling-ports","Bike Share Ports","シェアサイクル ポート","transport","api","https://docomo-cycle.jp/","Docomo bike sharing port locations and availability",NULL,"transport",1,3600},
{"gsi-active-fault","GSI Active Fault Map","国土地理院 活断層図","geospatial","dataset","https://www.gsi.go.jp/bousaichiri/active_fault.html","Active fault line locations",NULL,"hazard",1,604800},
{"openstreetmap-jp","OpenStreetMap Japan","OpenStreetMap 日本","geospatial","dataset","https://download.geofabrik.de/asia/japan.html","OpenStreetMap Japan data extract",NULL,"basemap",1,604800},
{"parking-facilities","OSM Parking Facilities","OSM 駐車場","geospatial","api","https://overpass-api.de/","amenity=parking / parking_entrance via Overpass",NULL,"poi",1,86400},
{"water-towers","OSM Water Towers","OSM 給水塔","infrastructure","api","https://overpass-api.de/","man_made=water_tower / water_works via Overpass",NULL,"infrastructure",1,604800},
{"famous-places","OSM Famous Places","OSM 名所","tourism","api","https://overpass-api.de/","Famous places across Japan — tourism/historic/worship/leisure/natural nodes with Wikidata (rich metadata)",NULL,"famous-places",1,604800},
{"transmission-towers","OSM Transmission Towers","OSM 送電鉄塔","infrastructure","api","https://overpass-api.de/","power=tower / tower:type=transmission via Overpass",NULL,"energy",1,604800},
{"utility-poles","OSM Utility Poles","OSM 電柱","infrastructure","api","https://overpass-api.de/","man_made=utility_pole via Overpass",NULL,"telecom",1,604800},
{"admin-boundaries","OSM Administrative Boundaries","OSM 行政境界","geospatial","api","https://overpass-api.de/","boundary=administrative (prefecture/municipality) via Overpass",NULL,"basemap",1,604800},
{"estat-household","e-Stat Household Data","e-Stat 世帯データ","statistics","api","https://api.e-stat.go.jp/","Household composition statistics",NULL,"population",1,86400},
{"estat-employment","e-Stat Employment","e-Stat 雇用統計","statistics","api","https://api.e-stat.go.jp/","Employment and labor statistics",NULL,"economy",1,86400},
{"estat-industry","e-Stat Industry Data","e-Stat 産業統計","statistics","api","https://api.e-stat.go.jp/","Industrial production statistics by region",NULL,"economy",1,86400},
{"jstat-map","jSTAT MAP Grid Stats","jSTAT MAP 統計地図","statistics","api","https://jstatmap.e-stat.go.jp/","Grid-square based statistical mapping",NULL,"population",1,86400},
{"homes-co","Homes.co.jp Rentals","HOME'S 賃貸情報","economy","scraped","https://www.homes.co.jp/","Rental property listings and prices",NULL,"landprice",1,86400},
{"saigai-info","Cabinet Office Disaster","内閣府 災害情報","safety","api","https://www.bousai.go.jp/","Cabinet Office disaster information system",NULL,"emergency",1,300},
{"mlit-dam","MLIT Dam Data","国交省 ダム情報","infrastructure","api","https://www.river.go.jp/","Dam operational data and water storage",NULL,"river",1,600},
{"tepco-power","TEPCO Power Usage","東京電力 電力使用状況","infrastructure","api","https://www.tepco.co.jp/","Tokyo Electric Power usage and capacity",NULL,"energy",1,300},
{"kepco-power","KEPCO Power Usage","関西電力 電力使用状況","infrastructure","api","https://www.kepco.co.jp/","Kansai Electric Power usage data",NULL,"energy",1,300},
{"chubu-power","Chubu Electric Power","中部電力 電力使用状況","infrastructure","api","https://www.chuden.co.jp/","Chubu Electric Power usage",NULL,"energy",1,300},
{"tohoku-power","Tohoku Electric Power","東北電力 電力使用状況","infrastructure","api","https://www.tohoku-epco.co.jp/","Tohoku Electric Power usage",NULL,"energy",1,300},
{"ev-charging","EV Charging Stations","EV充電スタンド","infrastructure","api","https://ev.gogo.gs/","Electric vehicle charging station map",NULL,"poi",1,86400},
{"atlas-jp","RIPE Atlas Japan Probes","RIPE Atlas 日本プローブ","cyber","api","https://atlas.ripe.net/","RIPE Atlas internet measurement probes in Japan",NULL,"cyber",1,3600},
{"instagram-geo","Instagram Geotagged","Instagram ジオタグ","social","scraped","https://www.instagram.com/","Geotagged Instagram posts from Japan",NULL,"social",0,600},
{"tiktok-geo","TikTok Geotagged","TikTok ジオタグ","social","scraped","https://www.tiktok.com/","Geotagged TikTok content from Japan",NULL,"social",0,600},
{"alos-palsar","ALOS/PALSAR SAR","ALOS/PALSAR 合成開口レーダー","satellite","api","https://www.eorc.jaxa.jp/ALOS/","JAXA ALOS synthetic aperture radar data",NULL,"satellite",1,604800},
{"himawari-realtime","Himawari-9 Realtime","ひまわり9号 リアルタイム","satellite","api","https://www.data.jma.go.jp/mscweb/data/himawari/","Himawari-9 real-time satellite imagery",NULL,"satellite",1,600},
{"jaxa-earth","JAXA Earth Observation","JAXA 地球観測","satellite","api","https://earth.jaxa.jp/","JAXA Earth observation satellite data portal",NULL,"satellite",1,86400},
{"landsat-jp","Landsat Japan Coverage","Landsat 日本域","satellite","api","https://earthexplorer.usgs.gov/","Landsat satellite imagery covering Japan",NULL,"satellite",1,604800},
{"docomo-insight","Docomo Insight","ドコモ・インサイト","commercial","api","https://mobaku.jp/","NTT Docomo population flow insights",NULL,"population",0,3600},
{"softbank-crowd","SoftBank Crowd Analytics","ソフトバンク 混雑統計","commercial","api","https://www.softbank.jp/","SoftBank crowd density analytics",NULL,"population",0,3600},
{"navitime-api","Navitime API","ナビタイム API","commercial","api","https://api-sdk.navitime.co.jp/","Navitime routing and transit API",NULL,"transport",0,300},
{"here-japan","HERE Maps Japan","HERE Maps 日本","commercial","api","https://developer.here.com/","HERE location platform Japan",NULL,"basemap",0,86400},
{"yahoo-map-api","Yahoo! Japan Map API","Yahoo!地図 API","commercial","api","https://map.yahoo.co.jp/","Yahoo! Japan Map and geocoding API",NULL,"basemap",1,86400},
{"kyushu-power","Kyushu Electric Power","九州電力 電力使用状況","infrastructure","api","https://www.kyuden.co.jp/","Kyushu Electric Power usage",NULL,"energy",1,300},
{"hokkaido-power","Hokkaido Electric Power","北海道電力 電力使用状況","infrastructure","api","https://www.hepco.co.jp/","Hokkaido Electric Power grid usage",NULL,"energy",1,300},
{"shikoku-power","Shikoku Electric Power","四国電力 電力使用状況","infrastructure","api","https://www.yonden.co.jp/","Shikoku Electric Power usage",NULL,"energy",1,300},
{"hokuriku-power","Hokuriku Electric Power","北陸電力 電力使用状況","infrastructure","api","https://www.rikuden.co.jp/","Hokuriku Electric Power usage",NULL,"energy",1,300},
{"chugoku-power","Chugoku Electric Power","中国電力 電力使用状況","infrastructure","api","https://www.energia.co.jp/","Chugoku Electric Power usage",NULL,"energy",1,300},
{"okinawa-power","Okinawa Electric Power","沖縄電力 電力使用状況","infrastructure","api","https://www.okiden.co.jp/","Okinawa Electric Power usage",NULL,"energy",1,300},
{"mlit-bridge","MLIT Bridge Inspection","国交省 橋梁点検","infrastructure","dataset","https://road-structures-map.mlit.go.jp/","Bridge condition inspection data",NULL,"infrastructure",1,604800},
{"estat-education","e-Stat Education Stats","e-Stat 教育統計","statistics","api","https://api.e-stat.go.jp/","School enrollment and education data by region",NULL,"population",1,86400},
{"resas-municipality","RESAS Municipal Comparison","RESAS 自治体比較","statistics","api","https://opendata.resas-portal.go.jp/","Municipal-level economic/demographic comparison",NULL,"population",1,86400},
{"covid19-japan","COVID-19 Japan Dashboard","COVID-19 ダッシュボード","statistics","api","https://covid19.mhlw.go.jp/","COVID-19 Japan open data dashboard",NULL,"health",1,3600},
{"lifull-homes","LIFULL HOME'S","LIFULL HOME'S 物件","economy","scraped","https://www.homes.co.jp/","Real estate listings and price analysis",NULL,"landprice",1,86400},
{"japan-reit","J-REIT Properties","J-REIT 不動産","economy","scraped","https://www.japan-reit.com/","J-REIT investment property portfolio data",NULL,"landprice",1,86400},
{"tochi-info","Tochi.info Land Use","土地情報 土地利用","economy","api","https://tochi.mlit.go.jp/","Land use and zoning information",NULL,"landprice",1,86400},
{"chiriin-place","GSI Place Names","地理院 地名情報","geospatial","api","https://www.gsi.go.jp/","Official geographic place name database",NULL,"basemap",1,86400},
{"gcom-w","GCOM-W Water Cycle","GCOM-W 水循環","satellite","api","https://suzaku.eorc.jaxa.jp/GCOM_W/","GCOM-W satellite water cycle observation",NULL,"satellite",1,86400},
{"mapfan-api","MapFan API","MapFan API","commercial","api","https://mapfan.com/","MapFan mapping and POI data",NULL,"basemap",0,86400},
{"twitter-geo","Twitter/X Geo Posts","Twitter/X ジオ投稿","social","api","https://api.twitter.com/2/tweets/search/recent","Geocoded Twitter/X posts across Japan with engagement metrics",NULL,"twitter-geo",0,600},
{"facebook-geo","Facebook Check-ins","Facebook チェックイン","social","api","https://graph.facebook.com/","Facebook check-ins and geotagged posts at landmarks across Japan",NULL,"facebook-geo",0,1800},
{"classifieds","Jmty / Mercari / Yahoo Auctions","ジモティー・メルカリ・ヤフオク","marketplace","scraped","https://jmty.jp/","Classifieds listings (free items, barter, jobs, trades) across Japan",NULL,"classifieds",1,1800},
{"real-estate","Suumo / Homes / AtHome","スーモ・ホームズ・アットホーム","marketplace","scraped","https://suumo.jp/","Real estate listings (rent / sale) across Japan",NULL,"real-estate",1,3600},
{"job-boards","TownWork / Baitoru / Indeed","タウンワーク・バイトル・Indeed","marketplace","scraped","https://townwork.net/","Job listings (part-time / full-time) across Japan",NULL,"job-boards",1,3600},
{"google-dorking","Google Dorking Results","Google Dork 結果","cyber","web_request","https://www.google.com/search","Geo-coded Google dorking results (exposed admin panels, files, cameras, IoT)",NULL,"google-dorking",1,7200},
{"shodan-iot","Shodan IoT Devices","Shodan IoT デバイス","cyber","api","https://api.shodan.io/","Internet-exposed IoT devices in Japan (cameras, routers, NAS, SCADA, PLCs)",NULL,"shodan-iot",0,3600},
{"wifi-networks-wigle","WiGLE WiFi Networks","WiGLE WiFi ネットワーク","cyber","api","https://api.wigle.net/","WiGLE WiFi network search across Japan (SSID/BSSID/security)",NULL,"wifi-networks",0,86400},
{"wifi-networks-shodan","Shodan WiFi Devices","Shodan WiFi デバイス","cyber","api","https://api.shodan.io/","Shodan country:JP WiFi/wireless device hits",NULL,"wifi-networks",0,86400},
{"wifi-networks-mls","Mozilla Location Services WiFi","Mozilla ロケーションサービス WiFi","cyber","api","https://location.services.mozilla.com/api/v1/geolocate","MLS common-Japan WiFi BSSID anchors",NULL,"wifi-networks",0,86400},
{"wifi-hotspots-jcfw","Japan Connected Free WiFi Directory","Japan Connected Free WiFi 一覧","infrastructure","api","https://www.ntt-bp.net/jcfw/area.html","NTT-BP Japan Connected Free Wi-Fi venue directory (intel only — no coordinates)",NULL,"wifi-hotspots",1,86400},
{"wifi-hotspots-freespot","FREESPOT Directory","FREESPOT 一覧","infrastructure","api","https://www.freespot.com/users/map_e.html","FREESPOT venue directory (intel only — no coordinates)",NULL,"wifi-hotspots",1,86400},
{"maritime-ais","AIS Ship Tracking","AIS 船舶追跡","transport","api","https://www.marinetraffic.com/","AIS vessel positions around Japan ports and shipping lanes",NULL,"maritime-ais",0,300},
{"flight-adsb","ADS-B Flight Tracking","ADS-B フライト追跡","transport","api","https://opensky-network.org/api/states/all?lamin=24&lomin=122&lamax=46&lomax=154","ADS-B aircraft positions over Japan (airliners, GA, military)",NULL,"flight-adsb",1,60},
{"mlit-n02-stations","MLIT N02 Rail Stations","国土数値情報 鉄道駅 N02","transport","dataset","https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-N02-v3_0.html","MLIT KSJ N02 authoritative nationwide rail station dataset (~10,000 stations, yearly updates) — set MLIT_N02_GEOJSON_URL to enable",NULL,"mlit-n02-stations",1,2592000},
{"mlit-n05-rail-history","MLIT N05 Rail History","MLIT N05 Rail History","transport","dataset","https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-N05-v2_0.html","MLIT KSJ N05 long-term rail network history - active + abolished lines with opening/closure years",NULL,"mlit-n05-rail-history",1,2592000},
{"mlit-n07-bus-routes","MLIT N07 Bus Routes","MLIT N07 Bus Routes","transport","dataset","https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-N07-v1_1.html","MLIT KSJ N07 nationwide bus route geometry (LineStrings per operator)",NULL,"mlit-n07-bus-routes",1,2592000},
{"mlit-p02-airports","MLIT P02 Airports","MLIT P02 Airports","transport","dataset","https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-P02-v1_2.html","MLIT KSJ P02 all civil + joint-use airfields as polygons",NULL,"mlit-p02-airports",1,2592000},
{"mlit-p11-bus-stops","MLIT P11 Bus Stops","MLIT P11 Bus Stops","transport","dataset","https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-P11-v2_2.html","MLIT KSJ P11 authoritative nationwide bus stops (~200,000 points across all operators)",NULL,"mlit-p11-bus-stops",1,2592000},
{"mlit-c02-ports","MLIT C02 Ports","MLIT C02 Ports","transport","dataset","https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-C02-v2_2.html","MLIT KSJ C02 designated ports (International Strategic, Important, Local, Fishing)",NULL,"mlit-c02-ports",1,2592000},
{"gtfs-jp","GTFS-JP Nationwide Bus","GTFS-JP Nationwide Bus","transport","api","https://www.gtfs-data.jp/","GTFS Data Repository Japan - 400+ bus operator feeds aggregated in standardized GTFS-JP format",NULL,"gtfs-jp",1,86400},
{"osm-transport-trains","OSM Transport Trains","OSM Trains","transport","api","https://overpass-api.de/api/interpreter","OpenStreetMap transport layer - always-on nationwide mainline train stations",NULL,"osm-transport-trains",1,86400},
{"osm-transport-subways","OSM Transport Subways","OSM Subways","transport","api","https://overpass-api.de/api/interpreter","OpenStreetMap transport layer - always-on subway/metro/monorail/tram/light_rail stops",NULL,"osm-transport-subways",1,86400},
{"osm-transport-buses","OSM Transport Buses","OSM Buses","transport","api","https://overpass-api.de/api/interpreter","OpenStreetMap transport layer - always-on bus stops + terminals",NULL,"osm-transport-buses",1,86400},
{"osm-transport-ports","OSM Transport Ports","OSM Ports","transport","api","https://overpass-api.de/api/interpreter","OpenStreetMap transport layer - harbours, ferry terminals, marinas",NULL,"osm-transport-ports",1,86400},
{"unified-trains","Unified Trains (fused)","Unified Trains","transport","dataset","internal://unified-trains","Deduplicated nationwide train stations - merges MLIT N02 + ODPT + OSM transport layer",NULL,"unified-trains",1,86400},
{"unified-subways","Unified Subways (fused)","Unified Subways","transport","dataset","internal://unified-subways","Deduplicated subway / metro / monorail / tram stops - fused ODPT + OSM transport + MLIT N02",NULL,"unified-subways",1,86400},
{"unified-buses","Unified Buses (fused)","Unified Buses","transport","dataset","internal://unified-buses","Deduplicated nationwide bus stops + terminals - fused MLIT P11 + GTFS-JP + OSM transport + curated highway terminals",NULL,"unified-buses",1,86400},
{"unified-ais-ships","Unified AIS Ships (fused)","Unified AIS Ships","transport","dataset","internal://unified-ais-ships","Deduplicated AIS vessel positions - fuses MarineTraffic + VesselFinder + maritimeAis (dedup by MMSI/IMO, freshest position wins)",NULL,"unified-ais-ships",1,300},
{"unified-port-infra","Unified Port Infrastructure (fused)","Unified Port Infra","transport","dataset","internal://unified-port-infra","Deduplicated Japan port infrastructure - fuses curated PortInfra + OSM transport ports + MLIT C02 designated ports",NULL,"unified-port-infra",1,86400},
{"bus-routes","Bus Terminals","バスターミナル","transport","dataset","https://www.bus.or.jp/","Highway bus terminals and city bus depots across Japan",NULL,"bus-routes",1,86400},
{"ferry-routes","Ferry Terminals","フェリーターミナル","transport","dataset","https://www.jsanet.or.jp/","Ferry terminals (inter-island, Seto Inland, Okinawa, international)",NULL,"ferry-routes",1,86400},
{"highway-traffic","Expressway IC/JCT/SA/PA","高速道路 IC/JCT/SA/PA","transport","web_request","https://www.driveplaza.com/","NEXCO expressway interchanges, junctions, service areas, parking areas, congestion",NULL,"highway-traffic",1,600},
{"electrical-grid","Electrical Grid","電力網","infrastructure","dataset","https://www.fepc.or.jp/","Power plants (thermal/hydro/wind/solar/geothermal), substations, frequency converters",NULL,"electrical-grid",1,86400},
{"gas-network","Gas Network","ガス網","infrastructure","dataset","https://www.gas.or.jp/","LNG terminals, distribution stations across Tokyo/Osaka/Toho/Saibu/Hokkaido Gas + JERA",NULL,"gas-network",1,86400},
{"water-infra","Water Infrastructure","水道インフラ","infrastructure","dataset","https://www.mlit.go.jp/river/","Major dams, water treatment plants, sewage treatment plants",NULL,"water-infra",1,86400},
{"cell-towers","Cell Towers","携帯基地局","infrastructure","api","https://opencellid.org/","Mobile network base stations (Docomo, au, SoftBank, Rakuten Mobile) - 4G/5G",NULL,"cell-towers",0,86400},
{"nuclear-facilities","Nuclear Facilities","原子力施設","infrastructure","dataset","https://www.nra.go.jp/","Nuclear power plants, fuel cycle facilities, research reactors, waste storage sites",NULL,"nuclear-facilities",1,86400},
{"hospital-map","Hospital Map","病院マップ","health","api","https://overpass-api.de/api/interpreter","Hospitals across Japan via OSM Overpass + MHLW open data (university, general, specialized)",NULL,"hospital-map",1,86400},
{"aed-map","AED Map","AEDマップ","health","api","https://overpass-api.de/api/interpreter","AED (defibrillator) locations at stations, airports, public facilities",NULL,"aed-map",1,86400},
{"koban-map","Koban / Police Boxes","交番マップ","safety","api","https://overpass-api.de/api/interpreter","Japanese police boxes (koban), stations, prefectural HQs via OSM Overpass",NULL,"koban-map",1,86400},
{"fire-station-map","Fire Stations","消防署マップ","safety","api","https://overpass-api.de/api/interpreter","Fire stations and fire department HQs across Japan via OSM Overpass",NULL,"fire-station-map",1,86400},
{"bosai-shelter","Disaster Shelters","防災避難所","safety","api","https://overpass-api.de/api/interpreter","Designated emergency shelters, evacuation areas, tsunami towers across Japan",NULL,"bosai-shelter",1,86400},
{"hazard-map-portal","MLIT Hazard Map Portal","国土交通省 ハザードマップポータル","safety","dataset","https://disaportal.gsi.go.jp/","Hazard zones - tsunami inundation, volcanic eruption, landslide, flood, liquefaction",NULL,"hazard-map-portal",1,86400},
{"jshis-seismic","NIED J-SHIS Seismic Hazard","NIED J-SHIS 地震ハザード","safety","api","https://www.j-shis.bosai.go.jp/","Probability of seismic intensity 6-lower or higher within 30 years (mesh)",NULL,"jshis-seismic",1,86400},
{"hi-net","NIED Hi-net Stations","NIED Hi-net 観測点","environment","dataset","https://www.hinet.bosai.go.jp/","NIED Hi-net high-sensitivity seismograph stations across Japan",NULL,"hi-net",1,86400},
{"k-net","NIED K-NET Stations","NIED K-NET 観測点","environment","dataset","https://www.kyoshin.bosai.go.jp/","NIED K-NET strong motion seismograph stations across Japan",NULL,"k-net",1,86400},
{"jma-intensity","JMA Seismic Intensity","気象庁 震度情報","environment","api","https://www.jma.go.jp/bosai/quake/","JMA seismic intensity reports for recent significant earthquakes",NULL,"jma-intensity",1,60},
{"pharmacy-map","Pharmacy Map","薬局マップ","health","api","https://overpass-api.de/api/interpreter","Pharmacies across Japan (Matsumoto Kiyoshi, Welcia, Tsuruha, Sundrug, Sugi) via OSM Overpass",NULL,"pharmacy-map",1,604800},
{"convenience-stores","Convenience Stores","コンビニ店舗","marketplace","api","https://overpass-api.de/api/interpreter","Convenience stores (7-Eleven, FamilyMart, Lawson, MiniStop, NewDays) via OSM Overpass",NULL,"convenience-stores",1,604800},
{"gas-stations","Gas Stations","ガソリンスタンド","infrastructure","api","https://overpass-api.de/api/interpreter","Gas stations (ENEOS, Idemitsu, Cosmo, Shell, JA-SS) via OSM Overpass",NULL,"gas-stations",1,86400},
{"tabelog-restaurants","Tabelog / HotPepper Restaurants","食べログ・ホットペッパー グルメ","marketplace","api","https://webservice.recruit.co.jp/hotpepper/gourmet/v1/","Famous Japanese restaurants + HotPepper Gourmet API listings",NULL,"tabelog-restaurants",0,86400},
{"estat-census","e-Stat Census","e-Stat 国勢調査","statistics","api","https://api.e-stat.go.jp/rest/3.0/app/json/getStatsData","Prefecture-level census demographics from e-Stat (population, households, age structure)",NULL,"estat-census",1,86400},
{"resas-population","RESAS Population by City","RESAS 市町村別人口","statistics","api","https://opendata.resas-portal.go.jp/api/v1/","RESAS population by city with age composition (0-14, 15-64, 65+)",NULL,"resas-population",1,86400},
{"resas-tourism","RESAS Tourism","RESAS 観光統計","statistics","api","https://opendata.resas-portal.go.jp/api/v1/","RESAS tourism + major tourist sites with annual visitor counts and foreign visitor share",NULL,"resas-tourism",1,86400},
{"resas-industry","RESAS Industry","RESAS 産業構造","statistics","api","https://opendata.resas-portal.go.jp/api/v1/","RESAS industry composition by city - manufacturing, services, agriculture, fishery",NULL,"resas-industry",1,86400},
{"mlit-transaction","MLIT Land Transactions","国交省 不動産取引価格","economy","api","https://www.land.mlit.go.jp/webland/api/TradeListSearch","MLIT real estate transaction prices by district (free public API)",NULL,"mlit-transaction",1,86400},
{"dam-water-level","Dam Water Levels","ダム貯水位","infrastructure","api","https://www1.river.go.jp/","Major Japanese dams - storage capacity and current reservoir levels (Tokuyama, Kurobe, Sameura, etc.)",NULL,"dam-water-level",1,600},
{"jma-ocean-wave","JMA Ocean Wave","気象庁 波浪観測","environment","api","https://www.data.jma.go.jp/gmd/kaiyou/data/db/wave/","Significant wave heights from JMA coastal observation network",NULL,"jma-ocean-wave",1,3600},
{"jma-ocean-temp","JMA Sea Surface Temp","気象庁 海面水温","environment","api","https://www.data.jma.go.jp/gmd/kaiyou/data/db/kaikyo/","Sea surface temperature with anomaly grid - Pacific, Japan Sea, East China Sea",NULL,"jma-ocean-temp",1,86400},
{"jma-tide","JMA Tide Levels","気象庁 潮位情報","environment","api","https://www.data.jma.go.jp/kaiyou/data/db/tide/","JMA tide gauge observations across Japan with anomaly from astronomic tide",NULL,"jma-tide",1,600},
{"nowphas-wave","NOWPHAS Wave Network","NOWPHAS 波浪観測網","environment","api","https://nowphas.mlit.go.jp/","PARI NOWPHAS GPS-buoys + ultrasonic wave gauges around Japan",NULL,"nowphas-wave",1,1800},
{"lighthouse-map","Lighthouses","灯台マップ","transport","api","https://overpass-api.de/api/interpreter","JCG lighthouses across Japan via OSM Overpass + historic Meiji-era register",NULL,"lighthouse-map",1,604800},
{"jartic-traffic","JARTIC Traffic","JARTIC 道路交通情報","transport","api","https://www.jartic.or.jp/","JARTIC traffic congestion - urban expressways and national highway hotspots",NULL,"jartic-traffic",1,300},
{"drone-nofly","Drone No-Fly Zones","ドローン飛行禁止区域","safety","dataset","https://www.mlit.go.jp/koku/","MLIT/JCAB drone no-fly zones - airports, DID, nuclear, military, imperial",NULL,"drone-nofly",1,86400},
{"jcg-patrol","JCG Patrol Bases","海上保安庁 巡視船基地","safety","dataset","https://www.kaiho.mlit.go.jp/","Japan Coast Guard - 11 regional headquarters and patrol vessel bases",NULL,"jcg-patrol",1,604800},
{"government-buildings","Government Buildings","官公庁","government","api","https://overpass-api.de/api/interpreter","Cabinet, Diet, ministries, agencies and prefectural HQ via OSM Overpass",NULL,"government-buildings",1,604800},
{"city-halls","City Halls","市区町村役場","government","api","https://overpass-api.de/api/interpreter","Tokyo wards, designated cities, core cities and prefectural capital halls",NULL,"city-halls",1,604800},
{"courts-prisons","Courts & Prisons","裁判所・刑務所","government","api","https://overpass-api.de/api/interpreter","High/district courts and major correctional facilities (MOJ)",NULL,"courts-prisons",1,604800},
{"embassies","Embassies","大使館","government","api","https://overpass-api.de/api/interpreter","Foreign embassies in Japan via OSM Overpass diplomatic=embassy",NULL,"embassies",1,604800},
{"jsdf-bases","JSDF Bases","自衛隊基地","defense","dataset","https://www.mod.go.jp/","GSDF, MSDF, ASDF installations across Japan",NULL,"jsdf-bases",1,604800},
{"usfj-bases","USFJ Bases","在日米軍基地","defense","dataset","https://www.usfj.mil/","United States Forces Japan installations: USAF, USN, USMC, USA",NULL,"usfj-bases",1,604800},
{"radar-sites","Radar Sites","レーダーサイト","defense","dataset","https://www.mod.go.jp/asdf/","JADGE air-defense radar (FPS-3/FPS-7), BMD X-band (AN/TPY-2), JMA weather radar",NULL,"radar-sites",1,604800},
{"coast-guard-stations","Coast Guard Stations","海上保安部・署","defense","dataset","https://www.kaiho.mlit.go.jp/","JCG offices and signal stations across 11 regional headquarters",NULL,"coast-guard-stations",1,604800},
{"auto-plants","Automotive Plants","自動車工場","industry","api","https://overpass-api.de/api/interpreter","Toyota, Nissan, Honda, Mazda, Subaru, Mitsubishi, Suzuki, Daihatsu, Isuzu, Hino assembly + engine plants",NULL,"auto-plants",1,604800},
{"steel-mills","Steel Mills","製鉄所","industry","api","https://overpass-api.de/api/interpreter","Nippon Steel, JFE, Kobelco, Daido, Tokyo Steel: integrated mills + EAF",NULL,"steel-mills",1,604800},
{"petrochemical","Petrochemical","石油化学コンビナート","industry","api","https://overpass-api.de/api/interpreter","Major Japanese petrochemical complexes (Keiyou, Kashima, Yokkaichi, Mizushima, Tokuyama, Oita)",NULL,"petrochemical",1,604800},
{"refineries","Oil Refineries","製油所","industry","api","https://overpass-api.de/api/interpreter","METI registered active oil refineries: ENEOS, Idemitsu, Cosmo, Fuji, Taiyo, Kashima Oil",NULL,"refineries",1,604800},
{"semiconductor-fabs","Semiconductor Fabs","半導体工場","industry","dataset","https://www.meti.go.jp/","Kioxia, Sony, Renesas, Rohm, Mitsubishi, Fuji, TSMC JASM, Rapidus, Micron Japan",NULL,"semiconductor-fabs",1,604800},
{"shipyards","Shipyards","造船所","industry","api","https://overpass-api.de/api/interpreter","Imabari, JMU, MHI, KHI, Mitsui ES, Tsuneishi, Onomichi, Hakodate Dock",NULL,"shipyards",1,604800},
{"petroleum-stockpile","Petroleum Stockpile","国家石油備蓄基地","industry","dataset","https://www.jogmec.go.jp/about/domestic-offices/","JOGMEC strategic petroleum reserves (10 oil + 5 LPG, live-scraped: capacity, area, completion year, address) + 8 commercial depots + OSM tank tags",NULL,"petroleum-stockpile",1,2592000},
{"ccs-projects","CCS Projects","先進的CCS事業","industry","dataset","https://www.jogmec.go.jp/activities/ccs/support-projects/index.html","JOGMEC Advanced CCS Projects — 5 domestic + 4 overseas (Tomakomai, Tohoku, Niigata, Kanto, Kyushu, Malaysia, Sarawak, Oceania) targeting ~20 Mt CO₂/yr by 2030",NULL,"ccs-projects",1,2592000},
{"geothermal-springs","Geothermal Springs","温泉化学分析点","industry","dataset","https://gbank.gsj.jp/gres-db/","GSJ GRES-DB onsen / spring chemistry analysis points (~7,200) — name, prefecture, temperature, pH, TDS",NULL,"geothermal-springs",1,86400},
{"geothermal-projects","Geothermal Projects","地熱モデル地区","industry","dataset","https://geothermal-model.jogmec.go.jp/","JOGMEC geothermal model districts (3 designated: Mori, Hachimantai, Yuzawa) + 5 case-study regions (Teshikaga, Osaki, Fukushima City, Kokonoe, Oguni)",NULL,"geothermal-projects",1,2592000},
{"wind-turbines","Wind Turbines","風力発電所","industry","api","https://overpass-api.de/api/interpreter","Onshore + offshore wind farms across Japan including Goto floating array",NULL,"wind-turbines",1,604800},
{"data-centers","Data Centers","データセンター","telecom","api","https://overpass-api.de/api/interpreter","Equinix, NTT, KDDI/Telehouse, IDC Frontier, IIJ, SAKURA, AWS, Azure, Google, Colt, MC Digital Realty",NULL,"data-centers",1,604800},
{"internet-exchanges","Internet Exchanges","インターネットエクスチェンジ","telecom","api","https://www.peeringdb.com/api/ix?country=JP","JPNAP, JPIX, BBIX, Equinix IX, DIX-IE and regional IXPs (PeeringDB API)",NULL,"internet-exchanges",1,86400},
{"submarine-cables","Submarine Cable Landings","海底ケーブル陸揚局","telecom","dataset","https://www.telegeography.com/","Major Pacific (Chiba), Asia (Aichi), Russia (Niigata), Korea (Saga), Okinawa cable landing stations",NULL,"submarine-cables",1,2592000},
{"tor-exit-nodes","Tor Exit Nodes","Tor 出口ノード","telecom","api","https://onionoo.torproject.org/details?country=jp&flag=Exit","Live Tor exit relays in Japan via Tor Project onionoo API",NULL,"tor-exit-nodes",1,3600},
{"5g-coverage","5G Coverage","5G カバレッジ","telecom","dataset","https://www.soumu.go.jp/","Docomo, KDDI au, SoftBank, Rakuten Mobile 5G NSA/SA - n77/n78 sub-6 + n257 mmWave hotspots",NULL,"5g-coverage",1,86400},
{"satellite-ground-stations","Satellite Ground Stations","衛星地上局","telecom","dataset","https://global.jaxa.jp/","JAXA, NICT, KDDI, SKY Perfect JSAT, NAOJ ground stations and tracking facilities",NULL,"satellite-ground-stations",1,2592000},
{"satellite-imagery","Satellite Imagery (Multi-source)","衛星画像 (複数ソース)","satellite","api","https://gibs.earthdata.nasa.gov/","Aggregated satellite imagery over Japan: Himawari-9 (real-time), MODIS/VIIRS (NASA GIBS), Landsat 8/9 (Planetary Computer), GOES-18 (RAMMB), ALOS-2 (seed), CORONA + historical Landsat (USGS M2M), Sentinel-2 L2A (Sentinel Hub → Element84 AWS → Planetary Computer → CDSE fallback chain). Preview feed shown on popup click.",NULL,"satellite-imagery",1,1800},
{"satellite-tracking","Live Satellite Positions","人工衛星リアルタイム位置","satellite","api","https://celestrak.org/NORAD/elements/","Live positions of every tracked on-orbit object (active, debris, CubeSats, stations) currently over Japan. SGP4 propagation from CelesTrak TLEs; ground tracks computed client-side on popup click.",NULL,"satellite-tracking",1,60},
{"amateur-radio-repeaters","Amateur Radio Repeaters","アマチュア無線レピータ","telecom","dataset","https://www.jarl.org/","JARL VHF/UHF FM, D-STAR, C4FM digital, HF beacons across Japan",NULL,"amateur-radio-repeaters",1,2592000},
{"national-parks","National Parks","国立公園","tourism","api","https://overpass-api.de/api/interpreter","34 national parks + 56 quasi-national parks under Ministry of Environment via OSM",NULL,"national-parks",1,2592000},
{"unesco-heritage","UNESCO World Heritage","ユネスコ世界遺産","tourism","dataset","https://whc.unesco.org/","UNESCO World Heritage Sites in Japan (25 cultural + natural sites as of 2024)",NULL,"unesco-heritage",1,2592000},
{"castles","Japanese Castles","日本の城","tourism","api","https://overpass-api.de/api/interpreter","100 Famous Castles + 100 Continued Famous Castles across Japan via OSM historic=castle",NULL,"castles",1,2592000},
{"museums","Museums","博物館・美術館","tourism","api","https://overpass-api.de/api/interpreter","National and major museums across Japan (art, history, science, natural history)",NULL,"museums",1,604800},
{"stadiums","Stadiums","スタジアム","tourism","api","https://overpass-api.de/api/interpreter","NPB baseball, J-League football, sumo, rugby and multipurpose stadiums",NULL,"stadiums",1,604800},
{"racetracks","Racetracks","競馬・競輪・競艇・オート場","tourism","api","https://overpass-api.de/api/interpreter","JRA + NAR horse racing, keirin velodromes, kyotei boat race, auto race venues",NULL,"racetracks",1,604800},
{"shrine-temple","Shrines & Temples","神社・寺院","culture","api","https://overpass-api.de/api/interpreter","Shinto shrines and Buddhist temples - major historic sites via OSM Overpass",NULL,"shrine-temple",1,2592000},
{"onsen-map","Onsen (Hot Springs)","温泉","culture","api","https://overpass-api.de/api/interpreter","Japanese hot spring towns and public bath houses - 三名泉, 三古泉 and 100名湯",NULL,"onsen-map",1,604800},
{"ski-resorts","Ski Resorts","スキー場","tourism","api","https://overpass-api.de/api/interpreter","Ski and snowboard resorts across Hokkaido, Tohoku, Niigata, Nagano, Gifu",NULL,"ski-resorts",1,2592000},
{"anime-pilgrimage","Anime Pilgrimage Sites","アニメ聖地巡礼","culture","dataset","https://animetourism88.com/","Real-world locations featured in anime/manga - seichi junrei sites from Your Name, K-On!, Lucky Star, Love Live and more",NULL,"anime-pilgrimage",1,2592000},
{"red-light-zones","Red Light Districts","風俗営業地区","crime","api","https://overpass-api.de/api/interpreter","Tolerated entertainment districts - Kabukicho, Tobita Shinchi, Susukino, Nakasu, Gion, etc.",NULL,"red-light-zones",1,2592000},
{"pachinko-density","Pachinko Parlor Density","パチンコ店密度","crime","api","https://overpass-api.de/api/interpreter","Pachinko parlor density by city (NPA 遊技場営業許可) - adult gaming centers via OSM",NULL,"pachinko-density",1,604800},
{"bear-encounters","Bear Encounters","クマ出没情報","wildlife","api","https://www.pref.hokkaido.lg.jp/","Asiatic black bear and Hokkaido brown bear encounter hotspots - prefectural wildlife data",NULL,"bear-encounters",1,86400},
{"bird-flu-outbreaks","Bird Flu Outbreaks","高病原性鳥インフルエンザ","wildlife","api","https://www.maff.go.jp/j/syouan/douei/tori/","MAFF HPAI (H5N1) confirmed farm outbreaks across Japan with culled bird counts by prefecture",NULL,"bird-flu-outbreaks",1,86400},
{"sakura-front","Sakura Front","桜前線","wildlife","api","https://weathernews.jp/s/topics/sakura/","Cherry blossom progression front - JMA 標本木 observation network + hanami hotspots",NULL,"sakura-front",1,3600},
{"wanted-persons","NPA Wanted Persons","警察庁 指名手配","crime","dataset","https://www.npa.go.jp/sousa/shimeitehai/","NPA designated wanted persons (指名手配) by issuing prefectural police HQ",NULL,"wanted-persons",1,86400},
{"phone-scam-hotspots","Phone Scam Hotspots","特殊詐欺発生地点","crime","dataset","https://www.npa.go.jp/bureau/criminal/souni/tokushusagi/","NPA 特殊詐欺 (oreore-sagi / refund fraud) ward-level incident counts and damage totals",NULL,"phone-scam-hotspots",1,86400},
{"pref-police-crime","Prefectural Police Crime","都道府県警察 犯罪統計","crime","dataset","https://www.npa.go.jp/toukei/seianki/hanzaiopendatalink.html","Unified directory of all 47 prefectural police forces (homepages + per-prefecture monthly counts when CSV adapter env vars are set)",NULL,"pref-police-crime",1,86400},
{"npa-missing-persons","NPA Missing Persons","警察庁 行方不明者統計","safety","dataset","https://www.npa.go.jp/publications/statistics/safetylife/yukue.html","NPA annual missing-persons aggregates (sex / age / cause incl. dementia)",NULL,"npa-missing-persons",1,604800},
{"npa-traffic-accidents","NPA Traffic Accidents","警察庁 交通事故統計","safety","dataset","https://www.npa.go.jp/publications/statistics/koutsuu/opendata/","Per-incident lat/lon traffic accident open data (Shift_JIS CSV); aggregated to a 1.1km grid × month for heatmap rendering",NULL,"npa-traffic-accidents",1,86400},
{"npa-important-wanted","NPA Important Wanted","警察庁 重要指名手配","crime","dataset","https://www.npa.go.jp/bureau/criminal/wanted/","NPA-designated 重要指名手配 high-profile suspects with photos and handling-prefecture pins (sensitive layer; opt-in)",NULL,"npa-important-wanted",1,86400},
{"npa-special-fraud","NPA Special Fraud","警察庁 特殊詐欺統計","crime","dataset","https://www.npa.go.jp/publications/statistics/sousa/sagi.html","Monthly nationwide special-fraud (特殊詐欺) recognised cases, damage in JPY, arrests",NULL,"npa-special-fraud",1,86400},
{"npa-cyber-threat-obs","NPA Cyber Threat Observation","警察庁 サイバー観測","cyber","dataset","https://www.npa.go.jp/bureau/cyber/koho/observation.html","NPA Cyber Police Bureau live darknet/honeypot scan-traffic dashboard (links out — graphs are PNG-only)",NULL,"npa-cyber-threat-obs",1,3600},
{"estat-crime","e-Stat Crime Statistics","e-Stat 犯罪統計","crime","api","https://www.e-stat.go.jp/stat-search/database?toukei=00130001","Government Statistics portal canonical per-prefecture annual crime totals (NPA-fed). Requires free ESTAT_APP_ID env var.",NULL,"estatCrime",1,604800},
{"moj-crime-whitepaper","MOJ Crime White Paper","法務省 犯罪白書","crime","dataset","https://hakusyo1.moj.go.jp/","Ministry of Justice annual crime white paper — prosecution, sentencing, recidivism, juvenile justice",NULL,"mojCrimeWhitepaper",1,604800},
{"sake-breweries","Sake Breweries","日本酒蔵元","food","api","https://overpass-api.de/api/interpreter","Japan Sake Brewers Association registered breweries (~1,200 nationwide) - Hakutsuru, Dassai, Kubota, Juyondai",NULL,"sake-breweries",1,2592000},
{"wineries-craftbeer","Wineries & Craft Beer","ワイナリー・地ビール・蒸溜所","food","api","https://overpass-api.de/api/interpreter","NTA license registry - Katsunuma wineries, craft beer breweries, whisky distilleries (Yamazaki, Hakushu, Yoichi)",NULL,"wineries-craftbeer",1,2592000},
{"fish-markets","Fish Markets","魚市場・水産卸売","food","api","https://overpass-api.de/api/interpreter","MAFF wholesale fish markets (Toyosu, Osaka, Fukuoka) + regional port markets and morning markets",NULL,"fish-markets",1,604800},
{"wagyu-ranches","Wagyu Ranches","和牛産地","food","dataset","https://www.jlec.net/","Certified wagyu brand production regions - Matsusaka, Kobe, Omi, Hida, Yonezawa, Miyazaki, Kagoshima",NULL,"wagyu-ranches",1,2592000},
{"tea-zones","Tea Zones","茶産地","agriculture","api","https://overpass-api.de/api/interpreter","MAFF tea-growing regions - Shizuoka, Kagoshima, Uji, Yame, Sayama, Ise with cultivar and production volume",NULL,"tea-zones",1,2592000},
{"rice-paddies","Rice Paddies","稲作産地","agriculture","api","https://overpass-api.de/api/interpreter","MAFF premium rice-producing regions - Uonuma Koshihikari, Yumepirika, Akitakomachi and heritage tanada",NULL,"rice-paddies",1,2592000},
{"vending-machines","Vending Machines","自動販売機","culture","api","https://overpass-api.de/api/interpreter","Japanese vending machine density - ~2.3M units nationwide, world record per-capita (drinks, hot/cold, novelty)",NULL,"vending-machines",1,2592000},
{"karaoke-chains","Karaoke Chains","カラオケチェーン","culture","api","https://overpass-api.de/api/interpreter","Japanese karaoke box chains - Big Echo, Karaoke-kan, JOYSOUND, Manekineko, Jankara, Cote d'Azur",NULL,"karaoke-chains",1,2592000},
{"manga-net-cafes","Manga / Net Cafes","漫画喫茶・ネットカフェ","culture","api","https://overpass-api.de/api/interpreter","24-hour manga/internet cafes - Jiyu-kukan, Media Cafe Popeye, Gran Cyber Cafe Bagus, DiCE, Manboo!",NULL,"manga-net-cafes",1,2592000},
{"sento-public-baths","Sento Public Baths","銭湯","culture","api","https://www.1010.or.jp/","Traditional Japanese sento public bathhouses (~3,000 nationwide) - Tokyo Sento Association registered + OSM",NULL,"sento-public-baths",1,604800},
{"manhole-covers","Manhole Cards","マンホールカード","infrastructure","dataset","https://www.gk-p.jp/activity/mhcard/","GKP Manhole Card (マンホールカード) issuance sites - decorative civic manhole cover designs by municipality",NULL,"manhole-covers",1,2592000},
{"themed-cafes","Themed Cafes","コンセプトカフェ","culture","dataset","https://animetourism88.com/","Japanese themed cafes - maid (Maidreamin, @home), cat/owl/hedgehog, character (Pokemon, Kirby), robot, butler",NULL,"themed-cafes",1,2592000},
{"marine-traffic","MarineTraffic AIS","マリントラフィック AIS","transport","api","https://services.marinetraffic.com/api/exportvessels/v:8/","MarineTraffic Exportvessels REST API - live AIS positions in Japan bbox (needs MARINETRAFFIC_API_KEY, freemium)",NULL,"marine-traffic",0,300},
{"vessel-finder","VesselFinder AIS","ベッセルファインダー AIS","transport","api","https://api.vesselfinder.com/vesselslist","VesselFinder Master REST API - live AIS positions in Japan bbox (needs VESSELFINDER_API_KEY, freemium)",NULL,"vessel-finder",0,300},
{"google-my-maps","Google My Maps","グーグル マイマップ","tourism","api","https://www.google.com/maps/d/kml","Google My Maps public KML exports parsed to points (configure GOOGLE_MYMAPS_IDS env var with comma-separated mids)",NULL,"google-my-maps",1,3600},
{"p2pquake-jma","P2P Quake JMA mirror","P2P地震情報 (JMA)","environment","api","https://api.p2pquake.net/v2/history?codes=551&limit=50","Free community JMA earthquake mirror, JSON + WebSocket. 60 req/min anonymous. Also: wss://api.p2pquake.net/v2/ws",NULL,"earthquake",1,60},
{"wolfx-eew","Wolfx JMA Earthquake Early Warning","Wolfx 緊急地震速報","environment","api","https://api.wolfx.jp/jma_eew.json","JMA EEW (Earthquake Early Warning) JSON + WebSocket (wss://ws-api.wolfx.jp/jma_eew). No API key required",NULL,"earthquake",1,10},
{"wolfx-eqlist","Wolfx JMA Earthquake List","Wolfx 地震一覧","environment","api","https://api.wolfx.jp/jma_eqlist.json","Latest 50 JMA earthquake reports. JSON, anonymous",NULL,"earthquake",1,60},
{"jma-forecast-area","JMA Regional Forecast JSON","気象庁 地域別天気予報","environment","api","https://www.jma.go.jp/bosai/forecast/data/forecast/130000.json","JMA regional forecast JSON by 6-digit area code (iterate 47 prefecture codes). Anonymous",NULL,"weather",1,3600},
{"jma-typhoon-json","JMA Typhoon Track JSON","気象庁 台風経路","environment","api","https://www.jma.go.jp/bosai/typhoon/data/","JMA active typhoon track JSON endpoints",NULL,"weather",1,900},
{"openmeteo-jma","Open-Meteo JMA mirror","Open-Meteo JMA","environment","api","https://api.open-meteo.com/v1/jma","Open-Meteo free public JMA forecast API (no key, rate-limited for non-commercial use)",NULL,"weather",1,3600},
{"nerv-feed","NERV Disaster Alerts","特務機関NERV","environment","api","https://unii-api.nerv.app/v1/lib/alerts.json","NERV Disaster Prevention multi-hazard alert aggregator (earthquakes, tsunami, volcano, weather)",NULL,"earthquake",1,60},
{"msil-umishiru","MSIL Umishiru Public APIs","海しる 公開API","transport","api","https://portal.msil.go.jp/apis","Japan Coast Guard MDA \"Umishiru\" (海しる) public API catalog - maritime geo, weather, ports. Free key via portal; bbox JSON (≤1,000 rec)",NULL,"maritime-ais",1,900},
{"edinet-filings","FSA EDINET Corporate Filings","EDINET 有価証券報告書","government","api","https://api.edinet-fsa.go.jp/api/v2/documents.json","Japan FSA EDINET disclosures JSON API - every listed company, investment fund, REIT. Free Subscription-Key header; 3-5s throttle required",NULL,"edinet-filings",1,3600},
{"egov-laws","e-Gov Law Search API","e-Gov 法令検索 API","government","api","https://laws.e-gov.go.jp/api/1/lawlists/1","Japanese national laws, ordinances, ministerial regulations - full text XML/JSON. Anonymous",NULL,"edinet-filings",1,86400},
{"data-go-jp-ckan","data.go.jp CKAN catalog","data.go.jp CKAN","government","api","https://www.data.go.jp/data/api/action/package_search","Federated Japan government open-data CKAN catalog (action/package_search, action/package_show)",NULL,"edinet-filings",1,86400},
{"geospatial-jp-ckan","geospatial.jp CKAN catalog","地理空間情報 CKAN","geospatial","api","https://www.geospatial.jp/ckan/api/3/action/package_search","MLIT geospatial.jp open data catalog - PLATEAU, disaster hazard layers, transport GIS",NULL,"edinet-filings",1,86400},
{"nhk-news-rss","NHK News RSS","NHKニュース RSS","government","api","https://www3.nhk.or.jp/rss/news/cat0.xml","NHK public broadcaster news RSS feeds - cat0 (main) + cat1-cat7 (politics, economy, intl, society, science, culture, sport)",NULL,"news-feed",1,600},
{"nhk-world-rss","NHK World English RSS","NHK World EN RSS","government","api","https://www3.nhk.or.jp/nhkworld/en/news/feeds/","NHK World English news feed (Atom/RSS)",NULL,"news-feed",1,600},
{"kyodo-rss","Kyodo News English RSS","共同通信 英字 RSS","government","api","https://english.kyodonews.net/rss/news.xml","Kyodo News English RSS feed - domestic and international news wire",NULL,"news-feed",1,600},
{"jpcert-alerts-rss","JPCERT/CC Alerts RSS","JPCERT/CC 注意喚起 RSS","cyber","api","https://www.jpcert.or.jp/rss/jpcert.rdf","JPCERT Coordination Center security advisories and alerts (RDF/RSS). Anonymous",NULL,"jpcert-alerts",1,3600},
{"gsi-geocode","GSI Address Search","国土地理院 住所検索","geospatial","api","https://msearch.gsi.go.jp/address-search/AddressSearch","GSI (Geospatial Information Authority) address → lat/lon geocoder (JSON). Anonymous",NULL,"geocode",1,86400},
{"japan-api-prefectures","Japan Prefectures REST API","都道府県 REST API","geospatial","api","https://japanapi.curtisbarnard.com/api/v1/prefectures","Community REST API for Japan prefectures, regions, demographics. Anonymous JSON",NULL,"admin-boundaries",1,604800},
{"hatena-bookmark","Hatena Bookmark Trending","はてなブックマーク 人気エントリー","social","api","https://b.hatena.ne.jp/hotentry.rss","Japanese-language trending web articles (RDF/RSS). Anonymous",NULL,"hatena-bookmark",1,1800},
{"certstream-jp","CertStream .jp CT Monitor","CertStream .jp 証明書監視","cyber","api","wss://certstream.calidog.io/","Real-time Certificate Transparency log monitor filtered to .jp domains. Open WebSocket, MIT license",NULL,"certstream-jp",1,60},
{"japan-post-offices","Japan Post Offices","郵便局","infrastructure","api","https://www.post.japanpost.jp/","Nationwide post office locations (OSM amenity=post_office, ~20k records)",NULL,"japan-post-offices",1,86400},
{"wdcgg-co2","WDCGG GHG Stations","温室効果ガス観測所","environment","api","https://gaw.kishou.go.jp/","World Data Centre for Greenhouse Gases — CO2/CH4 monitoring stations (Japan + neighbours)",NULL,"wdcgg-co2",1,604800},
{"censys-japan","Censys (Japan hosts)","Censys 日本ホスト","cyber","api","https://search.censys.io/api/v2/hosts/search","Internet-exposed hosts with country_code: JP. Requires CENSYS_API_ID + CENSYS_API_SECRET (free signup)",NULL,"censys-japan",0,3600},
{"nicter-stats","NICTER Darknet Stats","NICTER ダークネット統計","cyber","api","https://www.nicter.jp/atlas/","NICT darknet observatory daily packet counts (HTML scrape, best-effort)",NULL,"nicter-stats",1,86400},
{"misskey-timeline","Misskey Global Timeline","Misskey グローバルタイムライン","social","api","https://misskey.io/api/notes/global-timeline","Public Fediverse notes from misskey.io. Optional MISSKEY_TOKEN raises rate limit",NULL,"misskey-timeline",1,600},
{"bird-makeup-jp","bird.makeup (JP bridge)","bird.makeup (X ブリッジ)","social","api","https://bird.makeup/","X accounts mirrored as ActivityPub via bird.makeup (JP-relevant handles). ToS caveat",NULL,"bird-makeup-jp",1,900},
{"suumo-rental-density","Suumo Rental Density","Suumo 賃貸物件数","classifieds","api","https://suumo.jp/chintai/","Per-prefecture count of Suumo rental listings (density proxy). Daily cadence max",NULL,"suumo-rental-density",1,86400},
{"note-com-trending","note.com Trending","note トレンド","social","api","https://note.com/","Trending hashtags/notes on note.com (unofficial endpoints)",NULL,"note-com-trending",1,1800},
{"mercari-trending","Mercari Trending","メルカリ トレンド","classifieds","api","https://jp.mercari.com/","Mercari trending search keywords (consumer demand signal). ToS caveat",NULL,"mercari-trending",1,86400},
{"greynoise-jp","GreyNoise (curated IPs)","GreyNoise (IPリスト)","cyber","api","https://api.greynoise.io/v3/community","GreyNoise classifier output for a curated IP list. Free community tier; GREYNOISE_API_KEY raises limits",NULL,"greynoise-jp",1,3600},
{"cam-camscape","Camscape (Japan search)","Camscape 日本検索","cyber","scraped","https://www.camscape.com/?s=japan","Camscape search results for Japan cameras (6 pages, YouTube-backed feeds)",NULL,"cameras",1,21600},
{"cam-webcamendirect_list","Webcamendirect (JP)","webcamendirect 日本","cyber","scraped","https://webcamendirect.net/japon","webcamendirect.net /japon listing + 5 curated detail URLs",NULL,"cameras",1,21600},
{"cam-tabi_cam","tabi.cam (Japan)","tabi.cam 日本","cyber","scraped","https://tabi.cam/japan/","tabi.cam Japan listing with JS \"show more\" expansion",NULL,"cameras",1,21600},
{"cam-scs_com_ua","SCS Asia/Japan webcams","SCS アジア日本 ウェブカメラ","cyber","scraped","https://webcam.scs.com.ua/en/asia/japan/","webcam.scs.com.ua /en/asia/japan paginated listing (5 pages)",NULL,"cameras",1,21600},
{"cam-windy_api","Windy Webcams API (JP)","Windy ウェブカメラ API","cyber","api","https://api.windy.com/webcams/api/v3/webcams","Windy.com webcams filtered to countries=JP, paged 50/req to offset 2000. Real lat/lon + player embed URLs. Requires WINDY_API_KEY (free signup)",NULL,"cameras",0,21600},
{"shodan-cameras-jp","Shodan Cameras (JP)","Shodan カメラ 日本","cyber","api","https://api.shodan.io/","Shodan country:JP camera search (Hikvision/Dahua/Axis/webcamXP/Panasonic etc.). Requires SHODAN_API_KEY",NULL,"cameras",0,86400},
{"unified-airports","Unified Airports (fused)","Unified Airports","transport","dataset","internal://unified-airports","Airport infrastructure - fuses MLIT P02 polygons + OSM aerodromes/runways/navaids/control towers",NULL,"unified-airports",1,86400},
{"unified-flights","Unified Flights (fused)","Unified Flights","transport","dataset","internal://unified-flights","Live flights - merges flight-adsb (OpenSky ADS-B) + Narita/Haneda/Kansai schedule APIs + ODPT flight data + FlightRadar24 JP",NULL,"unified-flights",1,60},
{"unified-highway","Expressways (fused)","高速道路 (統合)","transport","dataset","internal://unified-highway","Fused expressway IC/JCT/SA/PA inventory + JARTIC live congestion hotspots",NULL,"unified-highway",1,600},
{"fofa-jp","FOFA (Japan)","FOFA 日本","cyber","api","https://fofa.info/","FOFA internet-asset search filtered to country=\"JP\". Surfaces JP IoT/ICS that Shodan/Censys miss. Requires FOFA_API_KEY (+ FOFA_EMAIL for legacy v1)",NULL,"fofa-jp",0,3600},
{"quake360-jp","Quake (360 NetLab)","Quake 360 日本","cyber","api","https://quake.360.net/","Chinese internet-asset search engine — Japan-country hosts. Requires QUAKE_API_KEY (free signup)",NULL,"quake360-jp",0,3600},
{"urlscan-jp","URLscan.io (JP)","URLscan.io 日本","cyber","api","https://urlscan.io/","Recent public scans of *.jp / JP-brand impersonation URLs. Anonymous works; URLSCAN_API_KEY raises limits",NULL,"urlscan-jp",1,1800},
{"wayback-jp","Wayback CDX (JP gov)","Wayback Machine 日本政府","cyber","api","https://web.archive.org/cdx/search/cdx","Historical snapshots of JP gov / cyber-agency hosts. Free, no auth. Tune WAYBACK_TARGETS",NULL,"wayback-jp",1,86400},
{"github-leaks-jp","GitHub Code Search (JP leaks)","GitHub コード検索 (JP漏洩)","cyber","api","https://api.github.com/search/code","GitHub code search for JP-domain credential / config leaks. Defensive recon. Requires GITHUB_TOKEN",NULL,"github-leaks-jp",1,21600},
{"grayhat-buckets","GrayhatWarfare (JP buckets)","GrayhatWarfare (JPバケット)","cyber","api","https://buckets.grayhatwarfare.com/","Exposed S3/GCS/Azure buckets matching JP keywords. Requires GRAYHAT_API_KEY (paid)",NULL,"grayhat-buckets",0,21600},
{"strava-heatmap-bases","Strava Heatmap Probes (Bases)","Strava ヒートマップ (基地)","cyber","api","https://heatmap-external-a.strava.com/","Sample Strava heatmap tiles around USFJ + JSDF installations — activity heuristic indicates base-layout leakage",NULL,"strava-heatmap-bases",1,86400},
{"chan-5ch","5ch Threads","5ちゃんねる スレッド","social","api","https://5ch.net/","Trending threads from curated 5ch boards (subject.txt). Override CHAN5CH_BOARDS",NULL,"chan-5ch",1,1800},
{"houjin-bangou","Houjin Bangou (corp registry)","法人番号 (国税庁)","government","api","https://www.houjin-bangou.nta.go.jp/webapi/","JP National Tax Agency corporate-number diffs (new/changed/closed). Requires HOUJIN_BANGOU_KEY (free)",NULL,"houjin-bangou",1,86400},
{"my-jvn","JVN iPedia / MyJVN","JVN iPedia / MyJVN","cyber","api","https://jvndb.jvn.jp/myjvn","IPA/JPCERT Japan Vulnerability Notes — JP-canonical CVE/advisory database",NULL,"my-jvn",1,3600},
{"cisa-kev-jp","CISA KEV (JP vendors)","CISA KEV (日本ベンダー)","cyber","api","https://www.cisa.gov/known-exploited-vulnerabilities-catalog","CISA Known Exploited Vulnerabilities filtered to JP-vendor products",NULL,"cisa-kev-jp",1,21600},
{"osv-dev","OSV.dev (JP packages)","OSV.dev (日本パッケージ)","cyber","api","https://osv.dev/","Google OSV — open-source vulnerability DB queried for JP-popular packages",NULL,"osv-dev",1,21600},
{"ghsa-advisories","GitHub Security Advisories","GitHub セキュリティアドバイザリ","cyber","api","https://github.com/advisories","GHSA REST advisories — recent 100. Optional GITHUB_TOKEN for higher rate limit",NULL,"ghsa-advisories",1,3600},
{"poc-in-github","PoC-in-GitHub (nomi-sec)","PoC-in-GitHub","cyber","api","https://github.com/nomi-sec/PoC-in-GitHub","Daily-collected CVE → public PoC mapping. GITHUB_TOKEN recommended",NULL,"poc-in-github",1,21600},
{"trickest-cve","Trickest CVE","Trickest CVE","cyber","api","https://github.com/trickest/cve","Trickest CVE → PoC tracker (alt to nomi-sec)",NULL,"trickest-cve",1,21600},
{"shadowserver-jp","Shadowserver (JP stats)","Shadowserver (日本統計)","cyber","api","https://dashboard.shadowserver.org/","Shadowserver public time-series — daily JP compromised-host counts",NULL,"shadowserver-jp",1,21600},
{"urlhaus-jp","abuse.ch URLhaus (JP)","abuse.ch URLhaus 日本","cyber","api","https://urlhaus.abuse.ch/","abuse.ch URLhaus — JP-host malware URLs. Requires ABUSE_CH_AUTH_KEY (free)",NULL,"urlhaus-jp",1,3600},
{"threatfox-jp","abuse.ch ThreatFox (JP)","abuse.ch ThreatFox 日本","cyber","api","https://threatfox.abuse.ch/","abuse.ch ThreatFox — JP-relevant IOCs. Requires ABUSE_CH_AUTH_KEY (free)",NULL,"threatfox-jp",1,3600},
{"feodo-tracker-jp","abuse.ch Feodo Tracker (JP)","abuse.ch Feodo Tracker 日本","cyber","api","https://feodotracker.abuse.ch/","abuse.ch Feodo Tracker — active botnet C2 IPs hosted in Japan",NULL,"feodo-tracker-jp",1,3600},
{"sslbl-jp","abuse.ch SSLBL (JP)","abuse.ch SSLBL 日本","cyber","api","https://sslbl.abuse.ch/","abuse.ch SSLBL — malicious-cert IPs intersected with JP hosting set",NULL,"sslbl-jp",1,3600},
{"spamhaus-drop","Spamhaus DROP","Spamhaus DROP","cyber","api","https://www.spamhaus.org/drop/","Spamhaus DROP / ASN-DROP — hijacked & cybercrime networks (max 1×/hr)",NULL,"spamhaus-drop",1,3600},
{"abuseipdb-jp","AbuseIPDB blacklist (JP)","AbuseIPDB ブラックリスト 日本","cyber","api","https://www.abuseipdb.com/","AbuseIPDB blacklist — JP-IP entries (confidence ≥90). Requires ABUSEIPDB_API_KEY",NULL,"abuseipdb-jp",1,21600},
{"alienvault-otx-jp","AlienVault OTX (JP-targeted)","AlienVault OTX (日本標的)","cyber","api","https://otx.alienvault.com/","OTX threat-intel pulses matching \"japan\". Requires OTX_API_KEY (free)",NULL,"alienvault-otx-jp",1,7200},
{"phishing-feeds-jp","Phishing feeds (JP brands)","フィッシング (日本ブランド)","cyber","api","https://openphish.com/","OpenPhish + PhishTank URLs targeting JP brands & .jp hosts",NULL,"phishing-feeds-jp",1,3600},
{"sans-isc","SANS Internet Storm Center","SANS ISC","cyber","api","https://isc.sans.edu/","SANS ISC handler diary RSS + global infocon level",NULL,"sans-isc",1,3600},
{"leakix-jp","LeakIX (JP services)","LeakIX (日本サービス)","cyber","api","https://leakix.net/","LeakIX — exposed services geolocated in Japan. Requires LEAKIX_API_KEY (free)",NULL,"leakix-jp",1,7200},
{"netlas-jp","Netlas (JP responses)","Netlas 日本","cyber","api","https://netlas.io/","Netlas.io — JP-located internet responses. Requires NETLAS_API_KEY (free)",NULL,"netlas-jp",1,7200},
{"hudson-rock-jp","HudsonRock (JP corps)","HudsonRock 日本企業","cyber","api","https://cavalier.hudsonrock.com/","HudsonRock Cavalier — infostealer-infection summary per JP domain. Free /osint-tools/",NULL,"hudson-rock-jp",1,86400},
{"virustotal-jp","VirusTotal (JP corps)","VirusTotal 日本企業","cyber","api","https://www.virustotal.com/","VirusTotal v3 — JP-megacorp domain reputation snapshot. Requires VIRUSTOTAL_API_KEY (free 500/d)",NULL,"virustotal-jp",1,21600},
{"chaos-bugbounty-jp","Chaos (JP bug bounty)","Chaos (日本バグバウンティ)","cyber","api","https://chaos.projectdiscovery.io/","ProjectDiscovery Chaos — JP-headquartered bug-bounty program index",NULL,"chaos-bugbounty-jp",1,86400},
{"peeringdb-jp","PeeringDB (JP)","PeeringDB 日本","telecom","api","https://www.peeringdb.com/","PeeringDB — JP IXPs, facilities, networks (org metadata)",NULL,"peeringdb-jp",1,86400},
{"bgp-tools-jp","BGP.tools (JP ASNs)","BGP.tools (日本AS)","telecom","api","https://bgp.tools/","BGP.tools ASN list intersected with RIPEstat JP-country ASN set",NULL,"bgp-tools-jp",1,86400},
{"crtsh-historical","crt.sh historical (.jp)","crt.sh 履歴 (.jp)","cyber","api","https://crt.sh/","crt.sh historical certs for high-value JP targets (gov, banks, telecoms)",NULL,"crtsh-historical",1,21600},
{"cloudflare-radar-jp","Cloudflare Radar (JP)","Cloudflare Radar 日本","cyber","api","https://radar.cloudflare.com/","Cloudflare Radar — JP DDoS / BGP leaks / DNS / IQI summary. Requires CLOUDFLARE_API_TOKEN (free)",NULL,"cloudflare-radar-jp",1,3600},
{"ooni-jp","OONI Explorer (JP)","OONI Explorer 日本","cyber","api","https://explorer.ooni.org/country/JP","OONI Explorer — JP network-interference measurements (recent 200)",NULL,"ooni-jp",1,3600},
{"ioda-jp","IODA (JP outages)","IODA (日本ネット断)","cyber","api","https://ioda.inetintel.cc.gatech.edu/","IODA — JP internet-outage signals (BGP, active probing, telescope) + events",NULL,"ioda-jp",1,1800},
{"ripestat-jp","RIPEstat (JP)","RIPEstat 日本","telecom","api","https://stat.ripe.net/","RIPEstat — JP country-level routing resource totals (ASN / IPv4 / IPv6 prefix counts)",NULL,"ripestat-jp",1,86400},
{"yahoo-realtime","Yahoo! Realtime (buzz)","Yahoo!リアルタイム検索","social","api","https://search.yahoo.co.jp/realtime","Yahoo! JAPAN Realtime Search — buzz/trending JP X/Twitter keywords",NULL,"yahoo-realtime",1,600},
{"mastodon-jp-instances","Mastodon JP local timelines","Mastodon 日本サーバ","social","api","https://mstdn.jp/","Public local timelines from mstdn.jp / pawoo.net / fedibird.com / mastodon-japan.net",NULL,"mastodon-jp-instances",1,600},
{"bluesky-jetstream-jp","Bluesky Jetstream (JP)","Bluesky Jetstream 日本語","social","api","https://docs.bsky.app/blog/jetstream","Bluesky Jetstream — short JP-language post snapshot (langs:ja)",NULL,"bluesky-jetstream-jp",1,600},
{"niconico-ranking","Niconico ranking","ニコニコ ランキング","social","api","https://www.nicovideo.jp/","Niconico video + most-active live ranking (JP-IP geofenced)",NULL,"niconico-ranking",1,1800},
{"wikipedia-ja-recent","Wikipedia (ja) recent","ウィキペディア最新","social","api","https://ja.wikipedia.org/","Wikipedia (ja) recent mainspace edits — last 200",NULL,"wikipedia-ja-recent",1,600},
{"osm-changesets-jp","OSM changesets (JP)","OSM チェンジセット 日本","social","api","https://www.openstreetmap.org/","OSM changesets within JP bbox — recent 100",NULL,"osm-changesets-jp",1,1800},
{"yahoo-news-jp-rss","Yahoo! Japan News RSS","Yahoo!ニュース RSS","social","api","https://news.yahoo.co.jp/","Yahoo! JAPAN News topic feeds (top, domestic, world, business, IT)",NULL,"yahoo-news-jp-rss",1,1800},
{"jp-news-rss","JP news RSS bundle","日本ニュース RSS バンドル","social","api","https://asia.nikkei.com/rss/feed/nar","Aggregated JP news / government RSS (Nikkei, Japan Times, Reuters JP, NHK World, Kantei, NDL)",NULL,"jp-news-rss",1,1800},
{"nasa-firms-jp","NASA FIRMS active fires (JP)","NASA FIRMS 活火災 日本","environment","api","https://firms.modaps.eosdis.nasa.gov/","NASA FIRMS VIIRS/MODIS active-fire pixels over Japan. Requires NASA_FIRMS_MAP_KEY (free)",NULL,"nasa-firms-jp",1,1800},
{"tdnet-disclosure","TDnet Timely Disclosure","TDnet 適時開示","government","scraped","https://www.release.tdnet.info/inbs/","TSE Timely Disclosure Network — material filings minutes after decision (M&A, breach, recalls, leadership changes). Distinct from EDINET (statutory archive)",NULL,"tdnet-disclosure",1,1800},
{"mofa-travel-advisory","MOFA Travel Advisory","外務省 海外安全情報","government","api","https://www.anzen.mofa.go.jp/","JP MOFA travel advisories — JP govt risk read on every country (RSS spotinfo + dangerinfo + info)",NULL,"mofa-advisory",1,3600},
{"bike-share-gbfs","Bike-share GBFS (HelloCycling, DOCOMO Cycle)","シェアサイクル GBFS","transport","api","https://api-public.odpt.org/api/v4/gbfs/","GBFS feeds for HelloCycling + DOCOMO Cycle Tokyo — station positions, real-time bike/dock counts (last-mile demand leading indicator)",NULL,"bike-share",1,600},
{"grid-usage-realtime","10-grid 5-min supply/demand CSVs","10エリア 5分電力CSV","infrastructure","api","https://www.tepco.co.jp/forecast/html/images/juyo-d-j.csv","Per-grid 5-minute supply/demand CSV feeds — TEPCO, KEPCO, Chuden, Tohoku, Kyuden, HEPCO, Yonden, Rikuden, Chugoku, Okiden",NULL,"grid-usage",1,300},
{"telegeography-cables","TeleGeography Submarine Cables (JP-landing)","TeleGeography 海底ケーブル","infrastructure","api","https://www.submarinecablemap.com/api/v3/cable/cable-geo.json","TeleGeography canonical submarine cable + landing-point geojson, filtered to JP bbox. CC-BY",NULL,"submarine-cables",1,604800},
{"telegram-jp-channels","Telegram public channels (JP)","Telegram 日本パブリックチャネル","cyber","scraped","https://tgstat.com/","Public Telegram channels (~30 JP-relevant) — leaks / doxbins / OPSEC chatter. Requires TG_API_ID + TG_API_HASH for MTProto pulls",NULL,"telegram-jp-channels",0,1800},
{"discord-jp-servers","Discord public servers (JP)","Discord パブリックサーバー (日本)","cyber","scraped","https://disboard.org/","Disboard / top.gg JP-tagged servers — invite metadata, member counts. ToS-rate-limited",NULL,"discord-jp-servers",1,86400},
{"dnstwist-jp-targets","DNSTwist (JP-corp typosquats)","DNSTwist 類似ドメイン","cyber","dataset","internal://dnstwist","Local dnstwist library generating typosquats for mufg.jp / ntt.co.jp / mhlw.go.jp etc., then DNS-resolving live. Bundle as worker script",NULL,"dnstwist-jp-targets",1,86400},
{"instagram-locations","Instagram public location pages","Instagram 公開ロケーション","social","scraped","https://www.instagram.com/explore/locations/","Top posts/reels by JP location ID. Requires session cookie; ToS-rate-limited",NULL,"instagram-locations",1,86400},
{"eight-sansan","Eight / Sansan public cards","Eight / Sansan 名刺","social","scraped","https://8card.net/","Public business cards — name, title, company. ToS-rate-limited",NULL,"eight-sansan",1,86400},
{"linkedin-jp-search","LinkedIn JP search","LinkedIn 日本検索","social","scraped","https://www.linkedin.com/","Public-profile search by JP employer (gov, JSDF, METI…). Requires LI_COOKIE; ToS-heavy",NULL,"linkedin-jp-search",1,86400},
{"psn-xbox-jp","PSN / Xbox Live (JP gamertags)","PSN / Xbox Live (日本)","social","api","internal://psn-xbox","JP-located gamertags + online status. Requires PSN_API + XBOX_API third-party keys. Register-only",NULL,"psn-xbox-jp",0,86400},
{"reddit-jp-subs","Reddit r/japan + JP subs","Reddit 日本サブレディット","social","api","https://www.reddit.com/r/japan/new.json","r/japan / r/japanlife / r/Tokyo / r/newsokur / r/JapanFinance — keyless JSON listings",NULL,"reddit-jp-subs",1,1800},
{"note-com-profiles","note.com profile search","note.com プロフィール検索","social","api","https://note.com/api/v2/searches?context=user","note.com author search by tag/location (extension of note-com-trending)",NULL,"note-com-profiles",1,3600},
{"hatena-bookmark-extended","Hatena Bookmark (entry list)","はてなブックマーク エントリ","social","api","https://b.hatena.ne.jp/entrylist.rss","Full entry-list RSS — bookmarked URL buzz proxy (extension of hatena-bookmark)",NULL,"hatena-bookmark-extended",1,1800},
{"houmukyoku-commercial","Houmukyoku 商業登記 (officers)","法務局 商業登記","government","scraped","https://www1.touki.or.jp/","Officers / directors per company (extension of houjin-bangou). Paid record-fetch per pull",NULL,"houjin-bangou",0,604800},
{"luup-private","LUUP scooters / e-bikes (ports)","LUUP 電動キックボード/自転車","transport","api","https://api.luup.sc/v1/ports","LUUP e-scooter / e-bike share — per-port real-time vehicle counts across Tokyo / Osaka / Kyoto / Yokohama bboxes. Read-only. Requires LUUP_MOBILE_TOKEN (bearer from LUUP mobile sign-up)",NULL,"luup-private",0,600},
};
static const int N=sizeof(M)/sizeof(M[0]);
/* ids are unique post-dedupe → a plain forward scan is unambiguous.
 * These are the GENERATED-table accessors; the public src_meta_get/at/count
 * live in source_registry_dyn.c, which layers registry-synthesized metadata
 * (for sources absent from this curated table) on top of gen_meta_get(). */
const src_meta *gen_meta_get(const char *id){
  if(!id)return NULL;
  for(int i=0;i<N;i++) if(strcmp(M[i].id,id)==0) return &M[i];
  return NULL;
}
const src_meta *gen_meta_at(int i){ return (i>=0&&i<N)?&M[i]:NULL; }
int gen_meta_count(void){return N;}
